// Replays flutter/test/goldens/coach_goldens.json. The scenario fixtures were
// generated by executing the REAL RN coach.js, and every candidate kind,
// ranking, number, check-in choice, and win branch still derives from them.
// The message WORDING is Flutter-owned since 2026-07-23 (English-first copy
// for the global launch); after a deliberate copy change, regenerate with
// `dart run tool/regen_copy_goldens.dart`.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/coach.dart';

dynamic normalize(dynamic v) {
  if (v is num) return v.toDouble();
  if (v is Map) return v.map((k, x) => MapEntry(k.toString(), normalize(x)));
  if (v is List) return v.map(normalize).toList();
  return v;
}

void main() {
  final raw =
      jsonDecode(File('test/goldens/coach_goldens.json').readAsStringSync())
          as Map<String, dynamic>;
  final ref = DateTime(2026, 7, 16, 12);
  final nov = DateTime(2026, 11, 16, 12);

  test('weekKey matches', () {
    expect(weekKey(ref), raw['weekKey']);
  });

  // The payday-runway candidate is Flutter-only (not in RN), so it is tested
  // directly here rather than in the RN golden replay above.
  test('the payday-runway decision surfaces at risk and reaches Home', () {
    final atRisk = {
      'accounts': [
        {'id': 'c', 'kind': 'cash', 'balance': 2000},
      ],
      'debts': [],
      'recurring': [],
      'settings': {
        'paydaySchedule': {'mode': 'monthly', 'day': 30},
      },
      // Seven discretionary spend days = pace 250 a day, well over the ~143
      // a day the 2000 runway allows until the 30th.
      'transactions': [
        for (final day in [3, 5, 7, 9, 11, 13, 15])
          {
            'type': 'expense',
            'amount': 500,
            'date': '2026-07-${day.toString().padLeft(2, '0')}',
          },
      ],
    };
    final cands = decisionCandidates(atRisk, ref);
    final payday = cands.where((c) => c['kind'] == 'payday').toList();
    expect(payday, hasLength(1), reason: 'one payday candidate at risk');
    expect(payday.first['title'], contains('short before payday'));
    expect(payday.first['prio'], 63);
    expect((payday.first['message'] as String), contains('a day gets you'));
    // It is not a daily-habit nudge, so the Home check-in surfaces it.
    expect(weeklyCheckIn(atRisk, ref)['kind'], 'payday');

    // No spendable cash: crunch owns that state, the payday card stays away.
    final broke = {
      ...atRisk,
      'accounts': [
        {'id': 'c', 'kind': 'cash', 'balance': 0},
      ],
    };
    expect(
      decisionCandidates(broke, ref).where((c) => c['kind'] == 'payday'),
      isEmpty,
    );
  });

  for (final entry in (raw['scenarios'] as Map<String, dynamic>).entries) {
    test('coach golden: ${entry.key}', () {
      final s = entry.value as Map<String, dynamic>;
      final data = (s['data'] as Map).cast<String, dynamic>();
      final r = entry.key == 'kitchenSinkNov' ? nov : ref;
      expect(
        normalize(decisionCandidates(data, r)),
        normalize(s['candidates']),
        reason: '${entry.key} candidates',
      );
      expect(
        normalize(weeklyCheckIn(data, r)),
        normalize(s['checkIn']),
        reason: '${entry.key} checkIn',
      );
      expect(
        normalize(pickWin(data, r)),
        normalize(s['win']),
        reason: '${entry.key} win',
      );
    });
  }
}
