/// Sweldo Runway: what the balance does, day by day, between now and payday.
///
/// EVERY OTHER FIGURE IN SALAPIFY IS AN AMOUNT. This one produces a DATE, and
/// that is the whole point of it: "tightest day, Friday 12 Oct, short 1,840"
/// is something a person can act on today, where "safe to spend 6,083" is
/// something they can only obey.
///
/// IT IS NOT A SECOND OPINION ABOUT SAFE TO SPEND, and the two must never be
/// merged. `computeSafeToSpend` answers "how much may I spend between now and
/// payday", over a window, from reserves. This answers "on which DAY do I run
/// out", over a calendar, from dated events. Two engines over one ledger is
/// exactly the Home-versus-Plan disagreement this project has been bitten by,
/// so the journey test asserts that every bill one of them names appears in
/// the other on the same date for the same peso.
library;

import '../../models/models.dart';
import 'accounts.dart';
import 'payday_schedule.dart';
import 'money.dart';
import 'ph_calendar.dart';
import 'reminders.dart';

/// One thing that moves money on one day.
class ProjectedEvent {
  const ProjectedEvent({
    required this.label,
    required this.amount,
    required this.isIncome,
    this.movedFrom,
    this.movedReason = '',
    this.fromRule = false,
  });

  final String label;
  final Money amount;
  final bool isIncome;

  /// Generated by a RULE rather than written down as an entry.
  ///
  /// The five registers this engine reads are not peers. Three hold ENTRIES,
  /// a payment somebody wrote down: a bill, an upcoming item, an instalment.
  /// Two hold RULES, machinery that generates occurrences from a balance or a
  /// cycle: a debt's monthly minimum, and the payday schedule. The difference
  /// decides what a duplicate means. Two entries that look alike are usually
  /// two real payments, because people do have two plans with one provider. A
  /// rule and an entry describing one month are usually one obligation
  /// recorded twice.
  final bool fromRule;

  /// The date it was DUE, when that is not the date it actually moves.
  ///
  /// Banks do not move money on a weekend or a holiday, so a bill due on
  /// Sunday leaves on Monday. Keeping the original date means a screen can
  /// say "due Sunday, leaves Monday" rather than silently showing a date the
  /// person never wrote down.
  final DateTime? movedFrom;

  /// Why it moved, as a fragment that reads inside a sentence: "a Sunday",
  /// "Christmas Day".
  final String movedReason;

  bool get moved => movedFrom != null;
}

/// One day in the projection.
class ProjectedDay {
  const ProjectedDay({
    required this.date,
    required this.moneyIn,
    required this.moneyOut,
    required this.balanceAfter,
    required this.events,
  });

  final DateTime date;
  final Money moneyIn;
  final Money moneyOut;

  /// What is left at the END of this day.
  final Money balanceAfter;
  final List<ProjectedEvent> events;

  bool get isQuiet => events.isEmpty;
}

/// The whole answer.
class DailyProjection {
  const DailyProjection({
    required this.openingBalance,
    required this.days,
    required this.undatedOutflow,
    required this.undatedOutflowCount,
    this.undatedInflow = Money.zero,
    this.undatedInflowCount = 0,
    this.overdueOutflow = Money.zero,
    this.overdueOutflowCount = 0,
    this.overdueInflow = Money.zero,
    this.overdueInflowCount = 0,
    this.beyondHorizonOutflow = Money.zero,
    this.beyondHorizonOutflowCount = 0,
    this.beyondHorizonInflow = Money.zero,
    this.beyondHorizonInflowCount = 0,
    this.suppressedIncome = Money.zero,
    this.duplicateIncomeLabels = const <String>[],
  });

  /// Spendable cash at the start, NOT total cash.
  ///
  /// Money the person set aside is not available to cover Friday's bill,
  /// which is the whole of P2.3. Starting from total would make this engine
  /// disagree with Safe to Spend about the same money on the same screen.
  final Money openingBalance;

  final List<ProjectedDay> days;

  /// What could not be placed on a calendar, and how many items.
  ///
  /// RETURNED RATHER THAN DROPPED. Due dates are free text in this app, so
  /// some of them genuinely cannot be read. An app that silently leaves an
  /// undated bill out of a cash projection is worse than one that says it did,
  /// because the person reads a clean projection and believes it is complete.
  /// NAMED BY DIRECTION, and the rename is the fix rather than decoration.
  /// These were `undatedTotal`, `overdueTotal` and `beyondHorizonTotal`, and
  /// each one silently folded income in with money going out. See
  /// [overdueOutflow] for what that cost.
  final Money undatedOutflow;
  final int undatedOutflowCount;

  /// Income that could not be dated. Counted apart, never added to the above.
  final Money undatedInflow;
  final int undatedInflowCount;

  /// Unpaid, dated, and already in the past.
  ///
  /// Excluding these from the day grid is deliberate: an overdue bill is a
  /// problem but it is not a FUTURE movement, and putting it on today claims
  /// money leaves today that may have left weeks ago. The first version of
  /// this engine made that decision and then said nothing, which is the same
  /// silent drop the undated bucket exists to prevent. On the shipped sample
  /// ledger it was hiding 8,840.
  ///
  /// SPLIT BY DIRECTION, because the single figure was wrong on the shipped
  /// sample ledger by more than three quarters of itself. `placeOn` tested
  /// "is it in the past" before it ever tested "is it income", so an overdue
  /// SALARY landed in a bucket named "unpaid, dated, already in the past" and
  /// [accountedOutflow] then added it as money leaving. Measured on the seed
  /// at 18 September 2026: 42,987.80 across four items, of which the Sweldo
  /// Payday item was 32,500. The real overdue outflow is 10,487.80.
  ///
  /// This figure was about to go ON the runway card, as the one line that
  /// must stay on screen so a person does not draw a wrong conclusion from a
  /// comfortable balance beside it. A line placed there to prevent a wrong
  /// conclusion would have been causing one, and the person it misleads most
  /// is the one who is genuinely behind on bills.
  final Money overdueOutflow;
  final int overdueOutflowCount;

  /// Income that was due and has not been recorded as arriving.
  ///
  /// Kept rather than discarded, because it is a real thing to tell somebody:
  /// a sweldo the ledger still expects is either late or already in the
  /// account and never ticked off. It is never added to any outflow.
  final Money overdueInflow;
  final int overdueInflowCount;

  /// Dated, not overdue, and past the end of the window.
  ///
  /// Also a deliberate exclusion that used to be silent. Worse than the
  /// overdue case, because an item the person entered INSIDE the window could
  /// leave it: a bill due on the last day that lands on a Saturday is shifted
  /// to the Monday and fell off the end, counted nowhere. The horizon is now
  /// judged on the date the person wrote, not the date the bank moves it.
  final Money beyondHorizonOutflow;
  final int beyondHorizonOutflowCount;

  /// Income dated past the end of the window. Same split, same reason: an
  /// income item dated two months out produced a `beyondHorizonTotal` of
  /// 50,000 that [accountedOutflow] counted as money leaving.
  final Money beyondHorizonInflow;
  final int beyondHorizonInflowCount;

  /// Income left out because the payday rule already described it.
  ///
  /// Founder decision D27, 2026-10-04: one sweldo is counted once. A salary
  /// recorded as an upcoming item AND covered by the stored payday rule was
  /// placed twice, a measured 65,000 on one day for somebody who earns
  /// 32,500.
  ///
  /// RETURNED SO A SCREEN MUST SAY IT. Dropping income is the one suppression
  /// in this engine, and it is the one that can be wrong about real money:
  /// somebody genuinely paid the same amount twice in a month loses the
  /// second one here. The decision was "count it once AND say so", and these
  /// two fields are the second half of it. A card that reads them and prints
  /// nothing has implemented half a decision.
  final Money suppressedIncome;

  /// What the suppressed income was called, so the line can name it.
  final List<String> duplicateIncomeLabels;

  /// Every eligible peso, wherever it ended up.
  ///
  /// THE REAL FOOTING CHECK. The obvious one, opening plus every inflow less
  /// every outflow equals closing, is an identity: both sides are computed
  /// from the same accumulator loop, so it passes with every input list
  /// deleted. It restates the loop rather than testing it. This is the sum
  /// that can actually disagree with the ledger.
  Money get accountedOutflow {
    Money placed = Money.zero;
    for (final ProjectedDay d in days) {
      placed += d.moneyOut;
    }
    return placed + undatedOutflow + overdueOutflow + beyondHorizonOutflow;
  }

  /// The mirror of [accountedOutflow], and it exists so the income side can
  /// be checked at all.
  ///
  /// Nothing measured the inflow side before, which is how an overdue salary
  /// spent a day being counted as money leaving the account.
  Money get accountedInflow {
    Money placed = Money.zero;
    for (final ProjectedDay d in days) {
      placed += d.moneyIn;
    }
    return placed + undatedInflow + overdueInflow + beyondHorizonInflow;
  }

  Money get closingBalance =>
      days.isEmpty ? openingBalance : days.last.balanceAfter;

  /// The day the balance is at its lowest, or null when nothing is projected.
  ProjectedDay? get tightestDay {
    if (days.isEmpty) return null;
    ProjectedDay worst = days.first;
    for (final ProjectedDay d in days) {
      if (d.balanceAfter < worst.balanceAfter) worst = d;
    }
    return worst;
  }

  /// The FIRST day the balance goes below zero, which is the one that matters.
  ///
  /// Not the same as [tightestDay]: the lowest point may come later, and by
  /// then the person has already bounced a payment. The first crossing is the
  /// day they have to act before.
  ProjectedDay? get firstShortfall {
    for (final ProjectedDay d in days) {
      if (d.balanceAfter.isNegative) return d;
    }
    return null;
  }

  bool get runsShort => firstShortfall != null;
}

DateTime _midnight(DateTime d) => DateTime(d.year, d.month, d.day);

/// Project the balance forward, one day at a time.
///
/// [horizonDays] defaults to 45, which covers a full semi-monthly cycle and
/// the one after it with room to spare. It is a cap on work, not a claim
/// about the future.
DailyProjection projectDailyCash({
  required List<Account> accounts,
  required List<BillItem> bills,
  required List<UpcomingItem> upcoming,
  required List<InstallmentPlan> installments,
  required List<Debt> debts,
  required PaydayCycle payday,
  required DateTime now,
  int horizonDays = 45,
}) {
  final DateTime today = _midnight(now);

  // SPENDABLE, converted to pesos. Both halves matter: money set aside is not
  // available for Friday's bill, and a dollar account cannot be added to a
  // peso one. `accountsTotalPhp` is the one place that rule lives.
  final Money opening = Money.fromDouble(
    accountsTotalPhp(accounts.where((Account a) => a.isSpendable)),
  );

  final Map<int, List<ProjectedEvent>> byOffset = <int, List<ProjectedEvent>>{};
  // SIX BUCKETS, NOT THREE. Each exclusion is kept per direction, because
  // folding a salary in with money going out is what the single-figure
  // version did. See [DailyProjection.overdueOutflow].
  Money undatedOut = Money.zero;
  int undatedOutCount = 0;
  Money undatedIn = Money.zero;
  int undatedInCount = 0;
  Money overdueOut = Money.zero;
  int overdueOutCount = 0;
  Money overdueIn = Money.zero;
  int overdueInCount = 0;
  Money beyondOut = Money.zero;
  int beyondOutCount = 0;
  Money beyondIn = Money.zero;
  int beyondInCount = 0;

  // What D27 took out, so the card can say it took it. The founder's answer
  // was "count it once AND say so", and the saying is not polish: somebody
  // with a genuine second income of the same size in the same month has it
  // dropped here, and this list is the only thing between that and silence.
  Money suppressedIncome = Money.zero;
  final List<String> duplicateIncome = <String>[];

  /// File an amount the grid cannot take, on the correct side of the ledger.
  void excluded(Money amount, bool isIncome, String bucket) {
    switch (bucket) {
      case 'undated':
        if (isIncome) {
          undatedIn += amount;
          undatedInCount += 1;
        } else {
          undatedOut += amount;
          undatedOutCount += 1;
        }
      case 'overdue':
        if (isIncome) {
          overdueIn += amount;
          overdueInCount += 1;
        } else {
          overdueOut += amount;
          overdueOutCount += 1;
        }
      default:
        if (isIncome) {
          beyondIn += amount;
          beyondInCount += 1;
        } else {
          beyondOut += amount;
          beyondOutCount += 1;
        }
    }
  }

  /// Put one movement on one day, given how many days away it is.
  void placeOn(String label, Money amount, int days, bool isIncome) {
    if (!amount.isPositive) return;

    // Already gone. A bill due last week that is still unpaid is a problem,
    // but it is not a FUTURE movement and putting it on today would claim
    // money leaves today that may have left already. COUNTED, not dropped.
    if (days < 0) {
      excluded(amount, isIncome, 'overdue');
      return;
    }

    // JUDGED ON THE DATE THE PERSON WROTE, before any banking shift. A bill
    // due on the last day of the window that happens to fall on a Saturday
    // would otherwise be shifted past the end and vanish, counted nowhere, on
    // a window the person themselves chose.
    if (days > horizonDays) {
      excluded(amount, isIncome, 'beyond');
      return;
    }

    final DateTime due = today.add(Duration(days: days));

    // Income is not shifted. A salary credited on a Saturday is in the
    // account on Saturday; it is PAYMENTS that wait for a banking day.
    final BankingDay when = isIncome
        ? (date: due, moved: false, reason: '')
        : nextBankingDay(due);

    // The banking shift can push the last day or two of the window past its
    // end. That is kept rather than dropped: the person entered it inside the
    // window, so it belongs on the grid, and the grid runs to horizonDays.
    final int offset = when.date.difference(today).inDays.clamp(0, horizonDays);

    byOffset
        .putIfAbsent(offset, () => <ProjectedEvent>[])
        .add(
          ProjectedEvent(
            label: label,
            amount: amount,
            isIncome: isIncome,
            movedFrom: when.moved ? due : null,
            movedReason: when.reason,
          ),
        );
  }

  /// Put a dated obligation on the grid, EVERY TIME IT FALLS in the window.
  ///
  /// A forty-five day window is a month and a half, so a bill on the 15th
  /// falls twice in it and the payday rule that produced both falls three
  /// times. Until 2026-10-04 this placed each bill, each debt minimum and
  /// each instalment exactly ONCE while the payday walk looped, which made
  /// the projection optimistic by construction: roughly half a month of
  /// outgoings missing from the closing balance and from the shortfall date,
  /// every time, and always in the direction that tells somebody they are
  /// fine.
  ///
  /// THE RECURRENCE IS READ, NEVER ASSUMED. Only a day-of-month due date
  /// repeats, because only that shape says so: "15" and "10th of the month"
  /// name a day that comes round again, while "2026-10-15" and "Sep 25" name
  /// one day and are then over. [monthlyDayOf] is the single place that
  /// distinction lives, and it reads with the same pattern [daysUntil] does
  /// so the two can never disagree.
  void place(String label, Money amount, String? dueDate, bool isIncome) {
    if (!amount.isPositive) return;

    final int? days = daysUntil(dueDate, today);
    if (days == null) {
      // Could not be read as a date. Counted separately, never dropped.
      excluded(amount, isIncome, 'undated');
      return;
    }

    final int? repeatsOn = monthlyDayOf(dueDate);
    if (repeatsOn == null) {
      placeOn(label, amount, days, isIncome);
      return;
    }

    // Walk the month boundary rather than adding thirty days, so the 31st
    // lands on the last day of a short month exactly as `_onDayOf` does for
    // the first occurrence.
    DateTime when = today.add(Duration(days: days));
    // One more step than the window can hold, so the loop is bounded by
    // arithmetic rather than by a number somebody liked.
    for (int step = 0; step <= horizonDays ~/ 28 + 1; step++) {
      final int offset = when.difference(today).inDays;
      if (offset > horizonDays) break;
      placeOn(label, amount, offset, isIncome);
      final int lastDay = DateTime(when.year, when.month + 2, 0).day;
      when = DateTime(
        when.year,
        when.month + 1,
        repeatsOn < lastDay ? repeatsOn : lastDay,
      );
    }
  }

  for (final BillItem b in bills.where((BillItem b) => !b.isPaid)) {
    place(b.name, b.amount, b.dueDate, false);
  }

  for (final UpcomingItem u in upcoming.where((UpcomingItem u) => !u.isPaid)) {
    place(u.name, u.amount, u.dueDate, u.countsAsIncome);
  }

  // Payment plans ARE DATED, and this comment used to say the opposite.
  //
  // It read "instalments have no due date of their own in this model", which
  // was never true: `nextInstallmentDate` in reminders.dart derives one from
  // the start date, the instalments already paid and the frequency, and the
  // reminder engine has used it all along. So Salapify knew when the Home
  // Credit payment was due, told the person so in the tray, and the cash
  // projection over the same ledger called it undatable. That is exactly the
  // two-readings-of-one-ledger problem this file's own header warns about,
  // and it left the projected balance 2,000 too high for most of the window
  // on a plan the app could place to the day.
  //
  // Every instalment inside the window is placed, not just the next one, for
  // the reason written on `place` above. A plan whose start date cannot be
  // read is still counted as undated, which is the honest answer when the
  // app genuinely does not know.
  for (final InstallmentPlan i in installments.where(
    (InstallmentPlan i) => !i.isSettled,
  )) {
    Money left = i.runningBalance;
    bool placedAny = false;
    for (int skip = 0; left.isPositive; skip++) {
      final DateTime? due = nextInstallmentDate(i, skip: skip);
      if (due == null) break;
      final int offset = _midnight(due).difference(today).inDays;
      if (offset > horizonDays) break;
      final Money each = minMoney(i.installmentAmount, left);
      if (!each.isPositive) break;
      placeOn(i.name, each, offset, false);
      left -= each;
      placedAny = true;
    }
    if (!placedAny) {
      // Either the start date is unreadable or the next instalment falls
      // past the window. Counted, never dropped.
      final Money each = minMoney(i.installmentAmount, i.runningBalance);
      if (nextInstallmentDate(i) == null) {
        excluded(each, false, 'undated');
      } else {
        excluded(each, false, 'beyond');
      }
    }
  }

  // Debt minimums ride on their own due date where the debt carries one.
  // P2.4 made these real figures rather than eight percent of a balance.
  // `iOwe` ONLY, and the filter is not decoration.
  //
  // The first version of this loop iterated every Debt, so a scheduled debt
  // owed TO the person reduced THEIR runway: money somebody else has to find
  // came off this person's balance. `monthlyDebtMinimums` in debt.dart has
  // filtered on direction all along, so the two readings of one ledger
  // disagreed, which is exactly what this file's own header warns about.
  //
  // The seed hid it completely, because both of its receivables are
  // `flexible` and `monthlyMinimum` returns null for those. It would have
  // surfaced the first time somebody recorded "Kuya Mark owes me 12,000 over
  // six instalments". Found by the money review, not by the suite.
  //
  // A MONTHLY MINIMUM IS MONTHLY, whatever shape the due date is written in.
  // `place` above only repeats a day-of-month date, which is right for a bill
  // (a bill written "2026-10-15" is one bill) and wrong here: the field is
  // called monthlyMinimum, so the date says WHEN IN THE MONTH and the name
  // says how often. The seed's Home Credit phone plan carries an ISO date
  // and was therefore counted once in a forty-five day window, which is half
  // of what it really costs over that window.
  //
  // BOUNDED BY WHAT IS ACTUALLY OWED, so a plan with one instalment left is
  // placed once and not twice. Running past the balance would invent an
  // obligation, which is the same mistake as the eight percent rule P2.4
  // removed, just made with a calendar instead of a percentage.
  for (final Debt d in debts.where(
    (Debt d) => !d.isSettled && d.direction == DebtDirection.iOwe,
  )) {
    final Money? min = d.monthlyMinimum;
    if (min == null) continue;

    final int? firstIn = daysUntil(d.dueDate, today);
    if (firstIn == null) {
      excluded(min, false, 'undated');
      continue;
    }

    Money left = d.remaining;
    DateTime when = today.add(Duration(days: firstIn));
    for (int step = 0; left.isPositive; step++) {
      final int offset = when.difference(today).inDays;
      if (offset > horizonDays) {
        if (step == 0) {
          excluded(min, false, 'beyond');
        }
        break;
      }
      final Money each = min > left ? left : min;
      placeOn(d.person, each, offset, false);
      left -= each;
      final int lastDay = DateTime(when.year, when.month + 2, 0).day;
      when = DateTime(
        when.year,
        when.month + 1,
        when.day < lastDay ? when.day : lastDay,
      );
    }
  }

  // Payday, from the stored rule. NOTHING IS INVENTED: if the person has not
  // told Salapify when they are paid, no income appears, and the projection
  // simply runs down. A projection that invents a salary is the one mistake
  // that would make this feature dangerous.
  if (payday.isSet && payday.expectedIncome.isPositive) {
    void addPayday(int offset) {
      if (offset < 0 || offset > horizonDays) return;

      // ONE SWELDO IS COUNTED ONCE. Founder decision D27, 2026-10-04.
      //
      // A person who records their salary as an upcoming item AND stores a
      // payday rule has one salary described twice, and this engine placed
      // both: a measured 65,000 on one day for somebody who earns 32,500, and
      // a closing balance half as big again as their real one.
      //
      // THE ASYMMETRY IS THE WHOLE RULE. Counting a BILL twice is safe,
      // because the person is told they are tighter than they are and nobody
      // bounces a payment over an app being careful. Counting a SALARY twice
      // tells them they have cash that is not coming, which is the exact
      // failure a runway exists to prevent. So outflows are counted twice and
      // flagged, and income is counted once and flagged, for one stated
      // reason rather than two conventions.
      //
      // The RULE's occurrence is the one kept, and the entry is dropped. The
      // rule recurs properly across the window where a single entry does not,
      // and where the two dates differ the rule's is the later of the two
      // often enough that keeping it errs toward caution.
      final DateTime when = today.add(Duration(days: offset));
      for (final MapEntry<int, List<ProjectedEvent>> day in byOffset.entries) {
        final DateTime at = today.add(Duration(days: day.key));
        if (at.year != when.year || at.month != when.month) continue;
        final int i = day.value.indexWhere(
          (ProjectedEvent e) =>
              e.isIncome && !e.fromRule && e.amount == payday.expectedIncome,
        );
        if (i < 0) continue;
        // CALENDAR MONTH, not the same day. The seed's own duplicate is
        // THREE DAYS apart across two registers, and a same-day rule would
        // have reported nothing. A rolling window is worse, because it drifts
        // across the statement periods people actually think in.
        duplicateIncome.add(day.value[i].label);
        suppressedIncome += day.value[i].amount;
        day.value.removeAt(i);
        break;
      }

      byOffset
          .putIfAbsent(offset, () => <ProjectedEvent>[])
          .add(
            ProjectedEvent(
              label: 'Payday',
              amount: payday.expectedIncome,
              isIncome: true,
              fromRule: true,
            ),
          );
    }

    final PaydaySchedule schedule = PaydaySchedule(payday.paydayDays);
    if (schedule.isUsable) {
      // THE STORED RULE, WALKED FORWARD. An earlier draft of this stepped by
      // 15 days from the next payday, which quietly assumed everybody is paid
      // kinsenas and katapusan. That is the same sin as the eight percent
      // debt minimum P2.4 just removed: a plausible guess standing in for
      // something the app was actually told.
      DateTime cursor = today;
      // SIZED TO THE HORIZON, not to a number somebody liked. A bare 8
      // silently dropped a real payday: with a rule of the 5th, 10th, 15th,
      // 20th, 25th and 30th, which a commission earner genuinely has, the
      // walk stopped at offset 39 and never placed the one at 44. The loop
      // already has its true exit two lines down; this bound exists only so
      // a pathological rule cannot spin forever.
      for (int guard = 0; guard <= horizonDays + 2; guard++) {
        final PaydayPoints? points = schedule.pointsFrom(cursor);
        if (points == null) break;
        final int offset = points.next.difference(today).inDays;
        if (offset > horizonDays) break;
        addPayday(offset);
        cursor = points.next;
      }
    } else {
      // No day-of-month rule is stored, so only the ONE payday the cycle
      // knows about is projected. Anything past it would be invented.
      addPayday(payday.daysToPayday);
    }
  }

  final List<ProjectedDay> days = <ProjectedDay>[];
  Money running = opening;
  for (int offset = 0; offset <= horizonDays; offset++) {
    final List<ProjectedEvent> events =
        byOffset[offset] ?? const <ProjectedEvent>[];
    Money inToday = Money.zero;
    Money outToday = Money.zero;
    for (final ProjectedEvent e in events) {
      if (e.isIncome) {
        inToday += e.amount;
      } else {
        outToday += e.amount;
      }
    }
    running = running + inToday - outToday;
    days.add(
      ProjectedDay(
        date: today.add(Duration(days: offset)),
        moneyIn: inToday,
        moneyOut: outToday,
        balanceAfter: running,
        events: events,
      ),
    );
  }

  return DailyProjection(
    openingBalance: opening,
    days: days,
    undatedOutflow: undatedOut,
    undatedOutflowCount: undatedOutCount,
    undatedInflow: undatedIn,
    undatedInflowCount: undatedInCount,
    overdueOutflow: overdueOut,
    overdueOutflowCount: overdueOutCount,
    overdueInflow: overdueIn,
    overdueInflowCount: overdueInCount,
    beyondHorizonOutflow: beyondOut,
    beyondHorizonOutflowCount: beyondOutCount,
    beyondHorizonInflow: beyondIn,
    beyondHorizonInflowCount: beyondInCount,
    suppressedIncome: suppressedIncome,
    duplicateIncomeLabels: duplicateIncome,
  );
}
