/// The Smart Text Notes Calculator, from the prototype's
/// `parseNotesCalculator` in `src/components/PhilippineFeaturesModal.tsx`.
///
/// Somebody types their day as notes, one line each, and the app adds it up:
///
///     ate 50
///     kuya 600
///     mama 6*8
///     electricity 1250
///     groceries 1850 + 450
///
/// ## Why this is arithmetic and not a text field
///
/// The prototype evaluates each line's trailing expression with JavaScript's
/// own `Function` constructor, so `6*8` is 48 and `1850 + 450` is 2300. Dart
/// has no `eval`, and reaching for one would be the wrong instinct anyway: an
/// evaluator that runs arbitrary code to add up a grocery list is a large
/// amount of power for a small amount of convenience.
///
/// So the expression is parsed by the recursive descent parser below, which
/// understands exactly what the prototype's own sanitiser leaves behind:
/// digits, `+ - * /`, parentheses and a decimal point. Nothing else can be
/// expressed, so nothing else can be run.
///
/// EVERY NUMBER HERE IS LOCKED TO A VECTOR generated by running the
/// prototype's own function under node, not by reading its regex. The
/// behaviour that reading would have missed is in the tests: a label may
/// itself contain digits (`load 100 pesos 250` is the label "load 100 pesos"
/// and the value 250), a line whose expression ends in an operator is invalid
/// rather than zero, and a peso sign is stripped from the expression while
/// remaining part of the label.
library;

/// One line of the notepad, after parsing.
class NoteLine {
  const NoteLine({
    required this.label,
    required this.expr,
    required this.value,
    required this.isValid,
  });

  /// Everything before the trailing expression, or `Item` when the whole line
  /// was a number. The prototype's own fallback, kept verbatim.
  final String label;

  /// The expression as the person typed it, so the screen can echo `6*8`
  /// rather than only the 48 it came to.
  final String expr;

  final double value;

  /// False for a line that carries no readable number. It still appears, with
  /// a value of zero, because silently dropping somebody's line is how a
  /// total becomes inexplicable.
  final bool isValid;
}

class NotesResult {
  const NotesResult({required this.items, required this.grandTotal});

  final List<NoteLine> items;
  final double grandTotal;

  /// How many lines carried a number. The screen says this, because "5 lines"
  /// over a total that only counted four is the sort of quiet mismatch that
  /// makes somebody distrust the whole thing.
  int get countedLines => items.where((NoteLine i) => i.isValid).length;
}

/// The trailing arithmetic on a line: digits, spaces, operators, parentheses
/// and a dot. Lazy on the left so the LABEL takes as much as it can and the
/// expression takes only the tail, which is what makes `load 100 pesos 250`
/// come out as a label of "load 100 pesos".
final RegExp _lineShape = RegExp(r'^(.*?)([\d\s+\-*/().]+)$');

/// Everything the prototype's sanitiser keeps.
final RegExp _notAllowed = RegExp(r'[^0-9+\-*/().]');

NotesResult parseNotes(String text) {
  final List<NoteLine> items = <NoteLine>[];
  double grandTotal = 0;

  for (final String line in text.split('\n')) {
    final String trimmed = line.trim();
    if (trimmed.isEmpty) continue;

    final RegExpMatch? match = _lineShape.firstMatch(trimmed);
    if (match == null) {
      items.add(NoteLine(label: trimmed, expr: '', value: 0, isValid: false));
      continue;
    }

    final String label = match.group(1)!.trim().isEmpty
        ? 'Item'
        : match.group(1)!.trim();
    final String expr = match.group(2)!.trim();
    final double? value = evaluateExpression(expr.replaceAll(_notAllowed, ''));

    if (value == null || value.isNaN || value.isInfinite) {
      // The prototype's catch branch: the whole trimmed line becomes the
      // label and the value is zero. Note that it does NOT use the captured
      // label here, and neither does this.
      items.add(NoteLine(label: trimmed, expr: '', value: 0, isValid: false));
      continue;
    }

    grandTotal += value;
    items.add(NoteLine(label: label, expr: expr, value: value, isValid: true));
  }

  return NotesResult(items: items, grandTotal: grandTotal);
}

/// Works out `1850 + 450`, `6*8`, `(2+3)*4`, `-250`.
///
/// Returns null for anything it cannot read, which is the equivalent of the
/// prototype's `Function` constructor throwing. Null, never zero: a malformed
/// line has to be distinguishable from a line that genuinely adds nothing,
/// because one of them is a mistake the person wants to see.
double? evaluateExpression(String input) {
  final _Parser p = _Parser(input.replaceAll(' ', ''));
  final double? value = p.parseSum();
  // Trailing characters mean the expression was only partly understood, and
  // half an expression is not a number. `5+` fails here rather than quietly
  // coming back as 5.
  if (value == null || !p.atEnd) return null;
  return value;
}

/// Recursive descent, precedence lowest first: sum, then product, then unary,
/// then a number or a bracketed sum.
class _Parser {
  _Parser(this.src);

  final String src;
  int pos = 0;

  bool get atEnd => pos >= src.length;
  String get _peek => src[pos];

  double? parseSum() {
    double? left = _parseProduct();
    if (left == null) return null;
    while (!atEnd && (_peek == '+' || _peek == '-')) {
      final String op = src[pos++];
      final double? right = _parseProduct();
      if (right == null) return null;
      left = op == '+' ? left! + right : left! - right;
    }
    return left;
  }

  double? _parseProduct() {
    double? left = _parseUnary();
    if (left == null) return null;
    while (!atEnd && (_peek == '*' || _peek == '/')) {
      final String op = src[pos++];
      final double? right = _parseUnary();
      if (right == null) return null;
      // Division by zero is INFINITY, exactly as it is in JavaScript, and the
      // caller rejects a non-finite result. Guarding it here instead would
      // turn `1000/0` into a silent zero in the total.
      left = op == '*' ? left! * right : left! / right;
    }
    return left;
  }

  double? _parseUnary() {
    if (!atEnd && (_peek == '+' || _peek == '-')) {
      final String op = src[pos++];
      final double? v = _parseUnary();
      if (v == null) return null;
      return op == '-' ? -v : v;
    }
    return _parsePrimary();
  }

  double? _parsePrimary() {
    if (atEnd) return null;

    if (_peek == '(') {
      pos++;
      final double? inner = parseSum();
      if (inner == null) return null;
      if (atEnd || _peek != ')') return null;
      pos++;
      return inner;
    }

    final int start = pos;
    while (!atEnd && (_isDigit(_peek) || _peek == '.')) {
      pos++;
    }
    if (pos == start) return null;
    return double.tryParse(src.substring(start, pos));
  }

  static bool _isDigit(String c) => c.codeUnitAt(0) ^ 0x30 <= 9;
}
