/// Reminders, ported from the prototype's `evaluateReminders` in
/// `src/utils/notificationEngine.ts`.
///
/// Pure and deterministic: given the ledger, the settings, a clock and the set
/// of reminders already sent, it returns what is newly due. Nothing here
/// schedules anything or touches a platform channel, which is what lets every
/// rule below be locked to a vector generated by running the prototype's own
/// engine under bun.
///
/// ## Dedupe is a TAG, not a timestamp
///
/// Each reminder carries a tag built from what it is about and the day it is
/// about it: `bill-<id>-<due>-<today>`. Once that tag has been seen the
/// reminder does not fire again, so reopening the app fifty times in an
/// evening produces one reminder and not fifty. The tag includes today's date
/// so the same bill can remind again tomorrow.
///
/// ## One deliberate divergence, and it is the important one
///
/// The prototype tests `days >= 0`, so a bill or a debt that is ALREADY
/// OVERDUE produces no reminder at all. The most urgent case in the whole
/// feature is the one it is silent about: miss a due date and the app stops
/// mentioning it entirely. That is not ported. Salapify reminds on an overdue
/// item and says how late it is, and `remindersOverdueTest` pins the
/// difference so it stays deliberate.
library;

import '../../models/models.dart';
import 'format.dart';

/// [ReminderKind] lives in models.dart, with [AppNotification], because a
/// stored notification carries one and this file may not be what a reader of
/// the data model imports.
export '../../models/models.dart' show AppNotification, ReminderKind;

class ReminderSettings {
  const ReminderSettings({
    this.dailyExpenseEnabled = true,
    this.dailyExpenseHour = 20,
    this.dailyExpenseMinute = 0,
    this.paymentDueEnabled = true,
    this.paymentDueDaysBefore = 2,
    this.billEnabled = true,
    this.billDaysBefore = 2,
    this.subscriptionEnabled = true,
    this.subscriptionDaysBefore = 1,
  });

  /// The prototype's own defaults: 8pm for the daily nudge, two days before a
  /// payment or a bill.
  static const ReminderSettings defaults = ReminderSettings();

  final bool dailyExpenseEnabled;
  final int dailyExpenseHour;
  final int dailyExpenseMinute;
  final bool paymentDueEnabled;
  final int paymentDueDaysBefore;
  final bool billEnabled;
  final int billDaysBefore;
  final bool subscriptionEnabled;
  final int subscriptionDaysBefore;

  int get dailyExpenseMinuteOfDay => dailyExpenseHour * 60 + dailyExpenseMinute;

  ReminderSettings copyWith({
    bool? dailyExpenseEnabled,
    int? dailyExpenseHour,
    int? dailyExpenseMinute,
    bool? paymentDueEnabled,
    int? paymentDueDaysBefore,
    bool? billEnabled,
    int? billDaysBefore,
    bool? subscriptionEnabled,
    int? subscriptionDaysBefore,
  }) => ReminderSettings(
    dailyExpenseEnabled: dailyExpenseEnabled ?? this.dailyExpenseEnabled,
    dailyExpenseHour: dailyExpenseHour ?? this.dailyExpenseHour,
    dailyExpenseMinute: dailyExpenseMinute ?? this.dailyExpenseMinute,
    paymentDueEnabled: paymentDueEnabled ?? this.paymentDueEnabled,
    paymentDueDaysBefore: paymentDueDaysBefore ?? this.paymentDueDaysBefore,
    billEnabled: billEnabled ?? this.billEnabled,
    billDaysBefore: billDaysBefore ?? this.billDaysBefore,
    subscriptionEnabled: subscriptionEnabled ?? this.subscriptionEnabled,
    subscriptionDaysBefore:
        subscriptionDaysBefore ?? this.subscriptionDaysBefore,
  );
}

class Reminder {
  const Reminder({
    required this.tag,
    required this.kind,
    required this.title,
    required this.body,
  });

  /// What it is about and when, so the same thing cannot fire twice in a day.
  final String tag;
  final ReminderKind kind;
  final String title;
  final String body;
}

class ReminderResult {
  const ReminderResult({required this.fresh, required this.tags});

  final List<Reminder> fresh;

  /// Every tag now considered sent, the old ones included.
  final List<String> tags;
}

String _iso(DateTime d) =>
    '${d.year}-${d.month.toString().padLeft(2, '0')}-'
    '${d.day.toString().padLeft(2, '0')}';

/// Whole days from today to [dueDate], or null when it cannot be read.
///
/// Understands the four shapes the prototype does, because a due date in this
/// app comes from a free text field and people write all of them: `2026-09-21`,
/// `today`, `tomorrow`, and a bare day of the month like `15` or `15th`, which
/// means the NEXT such day rather than one in the past.
int? daysUntil(String? dueDate, DateTime now) {
  if (dueDate == null) return null;
  final String raw = dueDate.trim();
  if (raw.isEmpty) return null;

  final String lower = raw.toLowerCase();
  if (lower == 'today') return 0;
  if (lower == 'tomorrow') return 1;

  final DateTime today = DateTime(now.year, now.month, now.day);

  final RegExpMatch? isoMatch = RegExp(
    r'^(\d{4})-(\d{2})-(\d{2})$',
  ).firstMatch(raw);
  if (isoMatch != null) {
    final DateTime target = DateTime(
      int.parse(isoMatch.group(1)!),
      int.parse(isoMatch.group(2)!),
      int.parse(isoMatch.group(3)!),
    );
    return target.difference(today).inDays;
  }

  final RegExpMatch? dayMatch = RegExp(
    r'^(\d{1,2})(?:st|nd|rd|th)?$',
    caseSensitive: false,
  ).firstMatch(raw);
  if (dayMatch != null) {
    final int day = int.parse(dayMatch.group(1)!);
    DateTime target = DateTime(now.year, now.month, day);
    if (target.isBefore(today)) {
      target = DateTime(now.year, now.month + 1, day);
    }
    return target.difference(today).inDays;
  }

  // "Sep 18" and friends. Parsed against the current year, which is what the
  // prototype does and is right far more often than it is wrong.
  final RegExpMatch? named = RegExp(
    r'^([A-Za-z]{3,9})\s+(\d{1,2})$',
  ).firstMatch(raw);
  if (named != null) {
    const List<String> months = <String>[
      'jan',
      'feb',
      'mar',
      'apr',
      'may',
      'jun',
      'jul',
      'aug',
      'sep',
      'oct',
      'nov',
      'dec',
    ];
    final int m = months.indexOf(named.group(1)!.toLowerCase().substring(0, 3));
    if (m < 0) return null;
    final DateTime target = DateTime(
      now.year,
      m + 1,
      int.parse(named.group(2)!),
    );
    return target.difference(today).inDays;
  }

  return null;
}

/// How a due date reads in a sentence.
String _whenPhrase(int days, String dueDate) {
  if (days < 0) {
    final int late = -days;
    return late == 1 ? 'was due yesterday' : 'was due $late days ago';
  }
  if (days == 0) return 'is due today';
  if (days == 1) return 'is due tomorrow';
  return 'is due in $days days ($dueDate)';
}

/// What is newly worth telling somebody about.
ReminderResult evaluateReminders({
  required ReminderSettings settings,
  required List<Transaction> transactions,
  required List<Debt> debts,
  required List<BillItem> bills,
  required Set<String> sentTags,
  required DateTime now,
  List<Account> accounts = const <Account>[],
  List<InstallmentPlan> installments = const <InstallmentPlan>[],
  List<UpcomingItem> upcoming = const <UpcomingItem>[],
}) {
  final List<Reminder> fresh = <Reminder>[];
  final Set<String> tags = <String>{...sentTags};
  final String today = _iso(now);

  void add(String tag, ReminderKind kind, String title, String body) {
    if (tags.contains(tag)) return;
    tags.add(tag);
    fresh.add(Reminder(tag: tag, kind: kind, title: title, body: body));
  }

  // 1. The daily nudge, once the configured time has passed and nothing has
  //    been logged today.
  if (settings.dailyExpenseEnabled &&
      now.hour * 60 + now.minute >= settings.dailyExpenseMinuteOfDay) {
    final bool loggedToday = transactions.any(
      (Transaction t) =>
          t.type == TransactionType.expense && t.date.split('T').first == today,
    );
    if (!loggedToday) {
      final String h = settings.dailyExpenseHour > 12
          ? '${settings.dailyExpenseHour - 12}'
          : '${settings.dailyExpenseHour == 0 ? 12 : settings.dailyExpenseHour}';
      final String suffix = settings.dailyExpenseHour >= 12 ? 'PM' : 'AM';
      final String mm = settings.dailyExpenseMinute.toString().padLeft(2, '0');
      add(
        'daily-expense-$today',
        ReminderKind.dailyExpense,
        'Nothing logged today',
        'It is past $h:$mm $suffix and nothing has gone into Salapify today. '
            'A minute now beats an evening of guessing later.',
      );
    }
  }

  // 2. Debts YOU owe. Money owed TO you is deliberately silent: it is not
  //    your payment to make, and nagging somebody about their own receivable
  //    is how a reminder tray stops being read.
  if (settings.paymentDueEnabled) {
    for (final Debt d in debts) {
      if (d.direction != DebtDirection.iOwe || d.isSettled) continue;
      final int? days = daysUntil(d.dueDate, now);
      if (days == null || days > settings.paymentDueDaysBefore) continue;

      final double remaining = d.totalAmount - d.paidAmount;
      if (remaining <= 0) continue;

      add(
        'debt-due-${d.id}-${d.dueDate}-$today',
        ReminderKind.paymentDue,
        'Payment due: ${d.person}',
        'Your payment of ${formatPeso(remaining)} to ${d.person} '
            '${_whenPhrase(days, d.dueDate ?? '')}.',
      );
    }

    // 2b. Credit cards carrying a balance with a statement date.
    //
    // `balance < 0` is the prototype's own test and is not a style choice: a
    // credit account stores what is OWED as a negative number, so a card at
    // zero or in credit has nothing to pay and must stay quiet.
    for (final Account a in accounts) {
      if (a.kind != AccountKind.credit || a.balance >= 0) continue;
      final int? days = daysUntil(a.dueDate, now);
      if (days == null || days > settings.paymentDueDaysBefore) continue;

      add(
        'card-due-${a.id}-${a.dueDate}-$today',
        ReminderKind.paymentDue,
        'Credit card due: ${a.name}',
        '${formatPeso(a.balance.abs())} on ${a.name} '
            '${_whenPhrase(days, a.dueDate ?? '')}. Paying before the cutoff '
            'is what keeps the interest off it.',
      );
    }

    // 2c. Payment plans.
    //
    // A DIVERGENCE, and a load bearing one. The prototype measures days until
    // `startDate`, so a plan reminds during the first days of its life and
    // then never again for the rest of its term, which for a 24 month plan is
    // 23 payments it says nothing about. The next date is worked out from the
    // start plus however many payments have been made, which is what the
    // screen already shows a person.
    for (final InstallmentPlan p in installments) {
      if (p.isSettled) continue;
      final DateTime? next = nextInstallmentDate(p);
      if (next == null) continue;
      final int? days = daysUntil(_iso(next), now);
      if (days == null || days > settings.paymentDueDaysBefore) continue;

      add(
        'installment-due-${p.id}-${_iso(next)}-$today',
        ReminderKind.paymentDue,
        'Payment plan: ${p.name}',
        '${formatPeso(p.installmentAmount)} to ${p.provider} '
            '${_whenPhrase(days, _iso(next))}.',
      );
    }
  }

  // 3. Bills, from the bills collection and from anything on the Coming up
  //    list that is a bill.
  if (settings.billEnabled) {
    for (final BillItem b in bills) {
      if (b.isPaid) continue;
      final int? days = daysUntil(b.dueDate, now);
      if (days == null || days > settings.billDaysBefore) continue;

      add(
        'bill-${b.id}-${b.dueDate}-$today',
        ReminderKind.billDue,
        'Bill due: ${b.name}',
        '${formatPeso(b.amount)} for ${b.name} '
            '${_whenPhrase(days, b.dueDate)}.',
      );
    }

    for (final UpcomingItem u in upcoming) {
      if (u.type != UpcomingItemType.bill || u.isPaid || u.isIncome) continue;
      final int? days = daysUntil(u.dueDate, now);
      if (days == null || days > settings.billDaysBefore) continue;

      add(
        'upcoming-bill-${u.id}-${u.dueDate}-$today',
        ReminderKind.billDue,
        'Bill due: ${u.name}',
        '${formatPeso(u.amount)} for ${u.name} '
            '${_whenPhrase(days, u.dueDate)}.',
      );
    }
  }

  // 4. Subscriptions. A day's notice by default rather than two: the thing
  //    worth catching is the renewal you had forgotten you were paying for,
  //    and a week of warnings about Netflix teaches somebody to swipe the
  //    whole tray away.
  if (settings.subscriptionEnabled) {
    for (final UpcomingItem u in upcoming) {
      if (u.type != UpcomingItemType.subscription || u.isPaid) continue;
      final int? days = daysUntil(u.dueDate, now);
      if (days == null || days > settings.subscriptionDaysBefore) continue;

      add(
        'subscription-${u.id}-${u.dueDate}-$today',
        ReminderKind.subscription,
        'Renews: ${u.name}',
        '${formatPeso(u.amount)} for ${u.name} '
            '${_whenPhrase(days, u.dueDate).replaceFirst('due', 'charged')}. '
            'Cancel before it renews if you are not using it.',
      );
    }
  }

  return ReminderResult(fresh: fresh, tags: tags.toList());
}

/// The date of the next unpaid instalment, or null when there is none left.
///
/// Stepping from the start by whole periods is a calendar derivation and
/// changes no money: the amount, the balance and the term all come from the
/// plan exactly as stored.
DateTime? nextInstallmentDate(InstallmentPlan p) {
  final DateTime? start = DateTime.tryParse(p.startDate);
  if (start == null) return null;
  if (p.paidInstallments >= p.totalInstallments) return null;

  final int n = p.paidInstallments;
  switch (p.paymentFrequency) {
    case PaymentFrequency.monthly:
      return DateTime(start.year, start.month + n, start.day);
    case PaymentFrequency.semimonthly:
      // Two a month, so every other step lands mid month.
      return DateTime(
        start.year,
        start.month + (n ~/ 2),
        start.day + (n.isOdd ? 15 : 0),
      );
    case PaymentFrequency.biweekly:
      return start.add(Duration(days: 14 * n));
    case PaymentFrequency.weekly:
      return start.add(Duration(days: 7 * n));
  }
}
