import 'duplicate_balances.dart';
import 'money.dart';
import '../../models/models.dart';

/// The Reports engine, ported from archive/prototype-google-ai-studio/src/components/ReportsScreen.tsx.
///
/// The prototype computes all of this inline inside the component, in about
/// two hundred lines of `useMemo`. Pulling it out is not tidiness: it is the
/// only way to lock it to vectors generated by RUNNING the TypeScript, which
/// is how every other engine in app/ was ported and the reason the numbers
/// match to the centavo.
///
/// Four questions, and the prototype's own four tabs answer one each:
///   POSITION       what you own and what you owe, right now
///   PERFORMANCE    what came in and went out over a period
///   CASH FLOW      the same money sorted into operating, investing, financing
///   RECONCILIATION does the app agree with your actual bank balance
///
/// Reconciliation is NOT here. It is the only one of the four that WRITES
/// (it creates an adjustment transaction and changes a transaction's status),
/// so it is its own batch with its own journey tests, rather than a fourth
/// tab bolted onto three read-only ones.

/// The periods the prototype offers, from archive/prototype-google-ai-studio/src/types.ts.
///
/// `custom` is in the prototype's type and is never selectable in its UI, so
/// it is not here. Adding an enum value nothing can produce is how a switch
/// gets a branch nobody has ever run.
enum ReportPeriod { daily, weekly, monthly, quarterly, semiAnnually, annually }

extension ReportPeriodLabel on ReportPeriod {
  String get label => switch (this) {
    ReportPeriod.daily => 'Today',
    ReportPeriod.weekly => 'This week',
    ReportPeriod.monthly => 'This month',
    ReportPeriod.quarterly => 'This quarter',
    ReportPeriod.semiAnnually => 'This half',
    ReportPeriod.annually => 'This year',
  };
}

/// Which accounts count as things you OWN, from the prototype's own list.
const List<AccountKind> assetKinds = <AccountKind>[
  AccountKind.cash,
  AccountKind.bank,
  AccountKind.gcash,
  AccountKind.maya,
  AccountKind.debit,
  AccountKind.investment,
  AccountKind.receivable,
  // Things you own outright. An asset like any other for the balance sheet,
  // and never a cash equivalent: the list below is what you could spend, and
  // a house is not.
  AccountKind.property,
];

/// Assets money can actually LEAVE FROM, stated once.
///
/// WHY IT IS NOT `assetKinds`. Three pickers each typed out their own version
/// of "an asset, but not a receivable", and the comment on one of them
/// already said why that is dangerous: a typed list is a second copy of a
/// decision and the two drift. Adding `property` to `assetKinds` proved it
/// instantly, because all three silently started offering a house as
/// somewhere to pay a bill from. `signedDelta` would have taken the 1,500 out
/// of it quite happily and the estimate would have become 398,500, which
/// nobody could trace and nobody could dispute.
///
/// WHY IT IS NOT `cashEquivalentKinds` EITHER. That list excludes
/// `investment`, and the existing policy deliberately lets somebody pay from
/// an investment account: pulling money out of MP2 to cover a bill is a real
/// thing people do. A fourth set earns its place rather than reusing one that
/// answers a different question.
///
/// Receivables are out because money owed TO you is not somewhere you can
/// send money from, and recording a repayment is the Debt screen's job.
const List<AccountKind> settlementKinds = <AccountKind>[
  AccountKind.cash,
  AccountKind.bank,
  AccountKind.gcash,
  AccountKind.maya,
  AccountKind.debit,
  AccountKind.investment,
];

/// Which count as things you OWE.
const List<AccountKind> liabilityKinds = <AccountKind>[
  AccountKind.credit,
  AccountKind.loan,
  AccountKind.mortgage,
];

/// The subset of assets that is money you could spend today.
const List<AccountKind> cashEquivalentKinds = <AccountKind>[
  AccountKind.cash,
  AccountKind.bank,
  AccountKind.gcash,
  AccountKind.maya,
  AccountKind.debit,
];

/// Converts an account balance to pesos.
///
/// This used to be the identity function, a named seam left for the day the
/// model carried a currency. That day is 2026-09-18: `Account.currency`
/// exists now, so the seam does the real conversion. Every account in the
/// fixture is still PHP, so no figure on any screen moved, and the reports
/// vector tests are what proves that rather than my saying so.
///
/// It stays a function rather than being inlined because the prototype calls
/// convertToPhp at every one of these sums, and a MISSING call site is
/// invisible while a wrapper is greppable.
Money toPhp(Account account) => account.balanceInPhp;

/// What you own and what you owe, at this instant. No period applies: a
/// balance sheet is a photograph, not a film.
class FinancialPosition {
  const FinancialPosition({
    required this.totalAssets,
    required this.totalLiabilities,
    required this.netWorth,
    required this.cashEquivalents,
    required this.investments,
    required this.receivables,
    required this.creditCards,
    required this.loans,
    required this.assetAccounts,
    required this.liabilityAccounts,
    required this.assetSourceCount,
    required this.liabilitySourceCount,
  });

  final Money totalAssets;
  final Money totalLiabilities;

  /// Assets minus liabilities. The one number on the screen that answers
  /// "am I actually getting anywhere".
  ///
  /// IN CENTAVOS SINCE 2026-10-05, with the rest of this class, and it had to
  /// move before debts could join the sheet. Every figure here was a `double`
  /// while `computePosition` summed in `Money` and threw the exactness away
  /// on the last line. That is survivable while nothing checks the identity
  /// and fatal the moment something does: with debts included, the sample
  /// ledger's assets less liabilities came to -36.65000000002328 against a
  /// stored -36.65, so `totalAssets - totalLiabilities == netWorth` was FALSE
  /// by 2.3e-11. A control asserted with a tolerance is a control that does
  /// not check, and a control asserted exactly on floats reddens on a crumb.
  final Money netWorth;

  final Money cashEquivalents;
  final Money investments;
  final Money receivables;
  final Money creditCards;
  final Money loans;

  final List<Account> assetAccounts;
  final List<Account> liabilityAccounts;

  /// How many SEPARATE THINGS each total is made of, which stopped being the
  /// account count on 2026-10-05.
  ///
  /// The screen captioned both totals "N accounts" by reading the two lists
  /// above, and that was true for exactly as long as the totals contained
  /// only accounts. The moment debts and instalment plans joined, the caption
  /// under 463,936.65 still read "3 accounts" while the figure was made of
  /// three accounts, two debts and three plans. A count that does not count
  /// the thing above it is worse than no count, because it invites somebody
  /// to divide one by the other.
  final int assetSourceCount;
  final int liabilitySourceCount;
}

/// What came in and what went out, over a period.
class FinancialPerformance {
  const FinancialPerformance({
    required this.totalIncome,
    required this.totalExpenses,
    required this.netSurplus,
    required this.businessRevenue,
    required this.businessExpenses,
    required this.businessNetProfit,
    required this.investedOutflows,
    required this.repaymentInflows,
    required this.earnedIncome,
    required this.keptRate,
    required this.savingsRate,
    required this.debtServicingExpenses,
    required this.debtServiceRatio,
    required this.projectedIncome,
    required this.projectedExpenses,
    required this.projectedSurplus,
  });

  final double totalIncome;
  final double totalExpenses;
  final double netSurplus;

  final double businessRevenue;
  final double businessExpenses;
  final double businessNetProfit;

  /// Money that left as an expense but went INTO something, not out of your
  /// life: Pag-IBIG MP2 and anything else filed as an investment.
  final double investedOutflows;

  /// Money that came back from somebody who owed you.
  ///
  /// It arrives as income in the ledger, which is right for the ledger. It is
  /// not income in any ordinary sense: it is an asset turning back into cash,
  /// and the balance sheet already treats it that way.
  final double repaymentInflows;

  /// What actually came in as EARNINGS: [totalIncome] less [repaymentInflows].
  ///
  /// This is the denominator of both published ratios, and it is a field
  /// rather than a local for two reasons that both cost something once.
  ///
  /// The screen has to be able to ASK whether there is anything to take a
  /// ratio of. `_ratioText` prints a dash when there is not, and it used to
  /// ask `totalIncome > 0`, which is a different question: a period whose
  /// only inflow was a repayment has income above zero and nothing earned, so
  /// the dash never appeared and a 0 that meant "no measurement" was printed
  /// as "0.0%".
  ///
  /// And a percentage whose denominator is nowhere on the screen cannot be
  /// checked. With a repayment in the period, dividing the visible
  /// `Debt payments` row by the visible "Money in" gives a different answer
  /// from the printed one, which reads as a wrong number rather than as a
  /// different base.
  final double earnedIncome;

  /// What was KEPT AS CASH, as a percent of everything that came in.
  ///
  /// This is the prototype's old `savingsRate` under an honest name, and it is
  /// what the "You kept" card means.
  final double keptRate;

  /// What was SAVED, as a percent of what was earned.
  ///
  /// Percent, 0 to 100, not a fraction. The prototype multiplies by 100 here
  /// and the screen appends a % sign, so keeping the same unit avoids the
  /// classic hundredfold error at the one place it would be least noticed.
  ///
  /// DIFFERS FROM THE PROTOTYPE, deliberately and with founder approval. Money
  /// moved into an investment counts as saved rather than spent, and money
  /// repaid to you is out of the denominator. See [computePerformance].
  final double savingsRate;

  final double debtServicingExpenses;

  /// Debt payments as a percent of what was EARNED, repayments excluded.
  final double debtServiceRatio;

  /// A straight-line run rate: what this month ends at if the rest of it
  /// looks like the part so far. See [computePerformance] for why this is
  /// worth distrusting.
  final double projectedIncome;
  final double projectedExpenses;
  final double projectedSurplus;
}

/// The same money as [FinancialPerformance], sorted the way a statement of
/// cash flows sorts it.
class CashFlow {
  const CashFlow({
    required this.operatingInflows,
    required this.operatingOutflows,
    required this.netOperating,
    required this.investingInflows,
    required this.investingOutflows,
    required this.netInvesting,
    required this.financingInflows,
    required this.financingOutflows,
    required this.netFinancing,
    required this.transfersCount,
    required this.transfersVolume,
    required this.netCashChange,
  });

  final double operatingInflows;
  final double operatingOutflows;
  final double netOperating;

  final double investingInflows;
  final double investingOutflows;
  final double netInvesting;

  final double financingInflows;
  final double financingOutflows;
  final double netFinancing;

  /// Transfers are reported and then EXCLUDED from netCashChange, because
  /// moving your own money between your own accounts is not cash flowing in
  /// or out of anything. Showing the count and volume anyway is deliberate:
  /// somebody who moved 50,000 around wants to see that the report noticed,
  /// rather than wondering whether it was dropped.
  final int transfersCount;
  final double transfersVolume;

  final double netCashChange;
}

/// One category's share of the spending (or the income) in a period.
class CategoryBreakdown {
  const CategoryBreakdown({
    required this.category,
    required this.total,
    required this.count,
    required this.percentage,
    required this.subcategories,
  });

  final String category;
  final double total;
  final int count;

  /// Percent of the period's total, 0 to 100.
  final double percentage;
  final List<SubcategoryBreakdown> subcategories;
}

class SubcategoryBreakdown {
  const SubcategoryBreakdown({
    required this.name,
    required this.total,
    required this.count,
    required this.percentageOfCategory,
  });

  final String name;
  final double total;
  final int count;
  final double percentageOfCategory;
}

/// Everything Reports shows, computed once from one set of inputs.
///
/// One object rather than four calls, so the four tabs cannot disagree about
/// which transactions they were looking at. Three false alarms in this
/// repository came from two screens seeming to disagree about money, and none
/// could be settled because nothing had ever put them in front of one source.
class ReportSet {
  const ReportSet({
    required this.position,
    required this.performance,
    required this.cashFlow,
    required this.expenseByCategory,
    required this.incomeByCategory,
    required this.transactions,
    this.duplicateBalances = const <SuspectedDuplicateBalance>[],
  });

  final FinancialPosition position;

  /// Balances that look like they are on the sheet twice.
  ///
  /// NOT SUBTRACTED FROM ANYTHING. Every total above is whole, and this list
  /// only tells the person where to look. Dropping a side would mean the app
  /// choosing which record they meant, and both are reasonable: an account is
  /// the right home for a loan you watch a balance on, a debt row is the
  /// right home for one you make payments against.
  final List<SuspectedDuplicateBalance> duplicateBalances;
  final FinancialPerformance performance;
  final CashFlow cashFlow;
  final List<CategoryBreakdown> expenseByCategory;
  final List<CategoryBreakdown> incomeByCategory;

  /// The transactions every figure above was computed from, after the profile,
  /// status and period filters. Exposed so a screen can say "from N entries"
  /// truthfully, and so a test can check the filter rather than infer it.
  final List<Transaction> transactions;
}

/// Keeps only the entries belonging to one entity, or all of them when
/// [profile] is null ("All" in the picker).
///
/// An entry with no profile counts as personal, which is the prototype's
/// `t.profile || 'personal'`.
List<Transaction> filterByProfile(
  List<Transaction> transactions,
  ProfileEntity? profile,
) {
  if (profile == null) return transactions;
  return transactions
      .where(
        (Transaction t) => (t.profile ?? ProfileEntity.personal) == profile,
      )
      .toList();
}

/// Accounts belonging to one entity, or all of them when [profile] is null.
///
/// Note the asymmetry with transactions above, which is the prototype's and
/// is deliberate here: an account with NO profile passes every filter, where a
/// transaction with no profile is treated as personal. An unclassified wallet
/// should not vanish from a report; an unclassified expense has to land
/// somewhere, and personal is the prototype's answer.
List<Account> filterAccountsByProfile(
  List<Account> accounts,
  ProfileEntity? profile,
) {
  if (profile == null) return accounts;
  return accounts
      .where((Account a) => a.profile == null || a.profile == profile)
      .toList();
}

/// Keeps only entries that belong in a ledger at all.
///
/// Excluded and duplicate entries are shown in Activity, struck through, so a
/// person can see what was discounted and why. They must never reach a total.
List<Transaction> validLedgerEntries(List<Transaction> transactions) {
  // READS THE MODEL'S OWN RULE rather than restating it. This function used to
  // carry its own copy of the list, so "does this count" had two definitions
  // that had to be kept in step by hand. They were, until a third state was
  // added; then one of them would have been right and the other wrong, and the
  // same entry would have counted on some screens and not on others.
  return transactions.where((Transaction t) => t.countsTowardTotals).toList();
}

/// Keeps only the entries inside [period], relative to [now].
///
/// An UNPARSEABLE date is KEPT, not dropped, which is the prototype's
/// `if (isNaN(txDate.getTime())) return true`. That looks like a bug and is
/// the safer of the two behaviours: a corrupt date should make a total look
/// wrong and get investigated, not quietly shrink it.
List<Transaction> filterByPeriod(
  List<Transaction> transactions,
  ReportPeriod period,
  DateTime now,
) {
  return transactions.where((Transaction t) {
    final DateTime? d = DateTime.tryParse(t.date);
    if (d == null) return true;

    switch (period) {
      case ReportPeriod.daily:
        return t.date == _iso(now);

      case ReportPeriod.weekly:
        // The prototype builds `oneWeekAgo` by subtracting 7 from the DAY OF
        // MONTH of a Date that still carries the current time of day, then
        // compares full timestamps. A transaction date parses to midnight, so
        // an entry dated exactly seven days ago is already before the cutoff
        // and falls outside the window. Reproduced rather than corrected: the
        // number on the phone has to match the number the prototype prints.
        final DateTime cutoff = now.subtract(const Duration(days: 7));
        return !d.isBefore(cutoff) && !d.isAfter(now);

      case ReportPeriod.monthly:
        return d.year == now.year && d.month == now.month;

      case ReportPeriod.quarterly:
        return d.year == now.year &&
            _quarterOf(d.month) == _quarterOf(now.month);

      case ReportPeriod.semiAnnually:
        return d.year == now.year && (d.month <= 6) == (now.month <= 6);

      case ReportPeriod.annually:
        return d.year == now.year;
    }
  }).toList();
}

/// 0 for Jan to Mar, 1 for Apr to Jun, and so on. Takes a 1-based Dart month
/// and matches the prototype's 0-based `Math.floor(getMonth() / 3)`.
int _quarterOf(int month) => (month - 1) ~/ 3;

String _iso(DateTime d) =>
    '${d.year}-${d.month.toString().padLeft(2, '0')}-'
    '${d.day.toString().padLeft(2, '0')}';

/// Case-insensitive substring test, the shape the prototype uses everywhere in
/// this screen to decide what a category means.
///
/// This is a WEAK test and naming it once makes that visible. "Investment &
/// Passive Income" contains "investment", which is the intent, but so would a
/// category somebody named "Investment club snacks". The prototype classifies
/// cash flow this way and the port matches it; a stronger scheme is a product
/// decision, not a porting one.
bool _has(String? haystack, String needle) =>
    haystack != null && haystack.toLowerCase().contains(needle);

double _sumOf(Iterable<Transaction> txs) =>
    txs.fold<double>(0, (double sum, Transaction t) => sum + t.amount.pesos);

/// What you owe that was never entered as an account.
///
/// READS `Debt.remaining`, NEVER `totalAmount - paidAmount`. That subtraction
/// is already written, once, in `models.dart`, where it is CLAMPED at zero.
/// An overpaid debt re-derived here would contribute a negative liability and
/// quietly raise net worth, which is a defect that has already shipped in
/// this codebase once and was measured at 2,000.
Money debtLiabilities(List<Debt> debts) => sumMoney(
  debts
      .where(
        (Debt d) =>
            d.direction == DebtDirection.iOwe && !d.isSettled && !d.isArchived,
      )
      .map((Debt d) => d.remaining),
);

/// Money owed TO you that was never entered as a receivable account.
///
/// Included for symmetry and not as a kindness. Counting what you owe while
/// ignoring what you are owed would bias the balance sheet pessimistic by
/// construction, which is a lie with a better bedside manner.
Money debtAssets(List<Debt> debts) => sumMoney(
  debts
      .where(
        (Debt d) =>
            d.direction == DebtDirection.owedToMe &&
            !d.isSettled &&
            !d.isArchived,
      )
      .map((Debt d) => d.remaining),
);

/// What instalment plans still owe, counting PRINCIPAL ONLY.
///
/// NOT `runningBalance`, and this is the one place the obvious choice is
/// wrong. `runningBalance` is principal plus the interest still to come, and
/// on the sample ledger those are 47,386.65 and 3,563.70, footing exactly to
/// the 50,950.35 that screen shows.
///
/// Use the total and the balance sheet capitalises interest nobody has
/// incurred yet. Net worth would then fall by the whole contractual interest
/// on the day a plan is opened and RISE with every interest payment made,
/// because the liability would drop faster than the cash does. Somebody who
/// keeps books would trace that and conclude the app rewards them for paying
/// interest. Interest belongs on the income statement as it accrues.
///
/// `runningBalance` is still the right figure to SHOW as "total still
/// payable". It is a memo line, never a total.
Money planLiabilities(List<InstallmentPlan> plans) => sumMoney(
  plans
      .where((InstallmentPlan p) => !p.isSettled && !p.isArchived)
      .map((InstallmentPlan p) => p.principalRemaining),
);

/// The balance sheet.
///
/// DEBTS AND PLANS JOINED IT ON 2026-10-05, on founder decision, and until
/// then this function read accounts and nothing else while a comment in
/// `accounts.dart` stated in writing that it read debts too. Measured on the
/// sample ledger before the change: 399,200 of liabilities reported, against
/// a Debt register holding 17,350 and instalment plans holding 50,950.35 that
/// it never saw. A balance sheet that changes depending on WHICH SCREEN you
/// entered a debt on is not a balance sheet.
///
/// NEITHER `Debt` NOR `InstallmentPlan` HAS A PROFILE, so both are treated as
/// profile-free and appear in every profile view, which is exactly what
/// `filterAccountsByProfile` already does with a null-profile account. No new
/// field, no new rule. The consequence is pre-existing and worth stating
/// rather than discovering: the four profile views are NOT a partition and
/// must never be summed, because a profile-free row appears in all of them.
FinancialPosition computePosition(
  List<Account> accounts,
  ProfileEntity? profile, {
  List<Debt> debts = const <Debt>[],
  List<InstallmentPlan> plans = const <InstallmentPlan>[],
}) {
  final List<Account> scoped = filterAccountsByProfile(accounts, profile);

  final List<Account> assets = scoped
      .where((Account a) => assetKinds.contains(a.kind))
      .toList();
  final List<Account> liabilities = scoped
      .where((Account a) => liabilityKinds.contains(a.kind))
      .toList();

  Money sum(Iterable<Account> list) => sumMoney(list.map(toPhp));

  // Filtered ONCE and reused, so the totals and the counts beside them can
  // never be built from two different readings of the same lists.
  final List<Debt> liveOwedToMe = debts
      .where(
        (Debt d) =>
            d.direction == DebtDirection.owedToMe &&
            !d.isSettled &&
            !d.isArchived,
      )
      .toList();
  final List<Debt> liveIOwe = debts
      .where(
        (Debt d) =>
            d.direction == DebtDirection.iOwe && !d.isSettled && !d.isArchived,
      )
      .toList();
  final List<InstallmentPlan> livePlans = plans
      .where((InstallmentPlan p) => !p.isSettled && !p.isArchived)
      .toList();

  final Money owedToMe = debtAssets(debts);
  final Money owedByMe = debtLiabilities(debts) + planLiabilities(plans);
  final Money totalAssets = sum(assets) + owedToMe;
  final Money totalLiabilities = sum(liabilities) + owedByMe;

  return FinancialPosition(
    totalAssets: totalAssets,
    totalLiabilities: totalLiabilities,
    netWorth: totalAssets - totalLiabilities,
    cashEquivalents: sum(
      assets.where((Account a) => cashEquivalentKinds.contains(a.kind)),
    ),
    investments: sum(
      assets.where((Account a) => a.kind == AccountKind.investment),
    ),
    // Receivable ACCOUNTS plus money lent out on the Debt screen, because a
    // person who recorded a loan to a cousin either way means the same thing
    // by it and should see one figure.
    receivables:
        sum(assets.where((Account a) => a.kind == AccountKind.receivable)) +
        owedToMe,
    creditCards: sum(
      liabilities.where((Account a) => a.kind == AccountKind.credit),
    ),
    loans:
        sum(
          liabilities.where(
            (Account a) =>
                a.kind == AccountKind.loan || a.kind == AccountKind.mortgage,
          ),
        ) +
        owedByMe,
    assetAccounts: assets,
    liabilityAccounts: liabilities,
    assetSourceCount: assets.length + liveOwedToMe.length,
    liabilitySourceCount:
        liabilities.length + liveIOwe.length + livePlans.length,
  );
}

/// The income statement, plus the two ratios and the run rate.
FinancialPerformance computePerformance(
  List<Transaction> scoped,
  DateTime now,
) {
  final double totalIncome = _sumOf(
    scoped.where((Transaction t) => t.type == TransactionType.income),
  );
  final double totalExpenses = _sumOf(
    scoped.where((Transaction t) => t.type == TransactionType.expense),
  );
  final double netSurplus = totalIncome - totalExpenses;

  final double businessRevenue = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.income &&
          t.profile == ProfileEntity.business,
    ),
  );
  final double businessExpenses = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.expense &&
          t.profile == ProfileEntity.business,
    ),
  );

  final double debtServicing = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.expense &&
          (_has(t.category, 'debt') ||
              _has(t.category, 'loan') ||
              _has(t.subcategory, 'loan')),
    ),
  );

  // The run rate divides by the day of the month REGARDLESS of the period
  // selected, which is the prototype's behaviour and is worth knowing about
  // before trusting the figure: choose "This year" on the 2nd of January and
  // it projects the year's income onto a month. The screen only shows it on
  // the monthly view for that reason.
  final int daysInMonth = DateTime(now.year, now.month + 1, 0).day;
  final int currentDay = now.day < 1 ? 1 : now.day;
  final double projectedIncome = (totalIncome / currentDay) * daysInMonth;
  final double projectedExpenses = (totalExpenses / currentDay) * daysInMonth;

  // MONEY MOVED INTO INVESTMENTS, which is spending by the ledger's reckoning
  // and saving by any ordinary reading of the word.
  //
  // The same filter computeCashFlow already uses for `investingOutflows`, so
  // the two cannot drift apart and disagree about the same peso.
  final double investedOutflows = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.expense &&
          (_has(t.category, 'investment') || _has(t.subcategory, 'mp2')),
    ),
  );

  // MONEY COMING BACK FROM SOMEBODY WHO OWED YOU. `applyDebtPayment` writes a
  // collected repayment as income under 'Receivables & Repayments'
  // (core/money/debt.dart), which is right for the ledger and wrong for a
  // ratio: it is an asset turning back into cash, not money earned.
  final double repaymentInflows = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.income && _has(t.category, 'receivable'),
    ),
  );

  // The denominator both published ratios divide by. Repayments are taken out
  // because including them makes the ratios flatter in exactly the month a
  // cousin pays you back, which is the month they describe least well.
  final double earnedIncome = totalIncome - repaymentInflows;

  return FinancialPerformance(
    totalIncome: totalIncome,
    totalExpenses: totalExpenses,
    netSurplus: netSurplus,
    businessRevenue: businessRevenue,
    businessExpenses: businessExpenses,
    businessNetProfit: businessRevenue - businessExpenses,
    investedOutflows: investedOutflows,
    repaymentInflows: repaymentInflows,
    earnedIncome: earnedIncome,
    // WHAT WAS KEPT AS CASH, which is what the "You kept" card means and what
    // the prototype called the savings rate. Unchanged arithmetic, renamed so
    // the two readings below cannot be confused for one another.
    keptRate: totalIncome > 0 ? (netSurplus / totalIncome) * 100 : 0,
    // DELIBERATELY NOT THE PROTOTYPE'S FORMULA. Founder approved, 2026-10-06.
    //
    // The prototype computes (income - allExpenses) / income, and
    // `totalExpenses` counts every expense transaction including money moved
    // into Pag-IBIG MP2 or any other investment. So a person who put 10,000
    // into MP2 had their savings rate REDUCED BY THE ACT OF SAVING, while the
    // Cash flow tab pulled that same 10,000 out of spending and into
    // investing. Two tabs, one ledger, opposite verdicts, and the one read
    // first was the discouraging one.
    //
    // For an app that actively teaches people toward MP2, that was the most
    // harmful reading on the screen.
    //
    // THE REPAYMENT COMES OFF THE TOP AS WELL AS THE BOTTOM, and leaving it on
    // the top was a real defect that printed 180%.
    //
    // `netSurplus` is `totalIncome - totalExpenses`, and totalIncome still
    // counts a collected repayment, correctly, because the money really did
    // arrive. Taking the repayment out of the denominator alone therefore
    // subtracted the same peso from the bottom while leaving it on the top:
    // 50,000 earned, a 50,000 repayment collected and 10,000 of loan payments
    // gave (90,000 + 0) / 50,000 = 180.0%, printed as a plain percentage on a
    // field whose own contract says 0 to 100.
    //
    // It is what was SAVED OUT OF WHAT WAS EARNED, so both ends have to be on
    // the same base.
    savingsRate: earnedIncome > 0
        ? ((netSurplus - repaymentInflows + investedOutflows) / earnedIncome) *
              100
        : 0,
    debtServicingExpenses: debtServicing,
    debtServiceRatio: earnedIncome > 0
        ? (debtServicing / earnedIncome) * 100
        : 0,
    projectedIncome: projectedIncome,
    projectedExpenses: projectedExpenses,
    projectedSurplus: projectedIncome - projectedExpenses,
  );
}

/// The statement of cash flows.
CashFlow computeCashFlow(List<Transaction> scoped) {
  final double operatingInflows = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.income &&
          !_has(t.category, 'investment') &&
          !_has(t.category, 'dividend'),
    ),
  );
  final double operatingOutflows = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.expense &&
          !_has(t.category, 'debt') &&
          !_has(t.category, 'investment'),
    ),
  );

  final double investingInflows = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.income &&
          (_has(t.category, 'investment') ||
              _has(t.category, 'dividend') ||
              _has(t.category, 'interest')),
    ),
  );
  final double investingOutflows = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.expense &&
          (_has(t.category, 'investment') || _has(t.subcategory, 'mp2')),
    ),
  );

  // Financing INFLOWS are hardcoded to zero in the prototype, with the comment
  // "External loans taken in". Nothing in the app records taking a loan out as
  // income, so there is no figure to put here; a plausible-looking number
  // would be worse than a zero the screen can explain.
  const double financingInflows = 0;
  final double financingOutflows = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.expense &&
          (_has(t.category, 'debt') ||
              _has(t.category, 'loan') ||
              _has(t.subcategory, 'loan')),
    ),
  );

  final Iterable<Transaction> transfers = scoped.where(
    (Transaction t) => t.type == TransactionType.transfer,
  );

  final double netOperating = operatingInflows - operatingOutflows;
  final double netInvesting = investingInflows - investingOutflows;
  final double netFinancing = financingInflows - financingOutflows;

  return CashFlow(
    operatingInflows: operatingInflows,
    operatingOutflows: operatingOutflows,
    netOperating: netOperating,
    investingInflows: investingInflows,
    investingOutflows: investingOutflows,
    netInvesting: netInvesting,
    financingInflows: financingInflows,
    financingOutflows: financingOutflows,
    netFinancing: netFinancing,
    transfersCount: transfers.length,
    transfersVolume: _sumOf(transfers),
    netCashChange: netOperating + netInvesting + netFinancing,
  );
}

/// Groups one side of the ledger by category and then by sub-category,
/// biggest first.
List<CategoryBreakdown> computeCategoryBreakdown(
  List<Transaction> scoped,
  TransactionType type,
) {
  final List<Transaction> txs = scoped
      .where((Transaction t) => t.type == type)
      .toList();
  final double grand = _sumOf(txs);

  // Insertion-ordered, so two categories with identical totals keep the order
  // they were first seen in rather than swapping between rebuilds. Dart's sort
  // is not stable for lists over 32 elements, but the ties here are settled
  // before the sort by the order this map was built in, which is the
  // prototype's Object.values order.
  final Map<String, _CategoryAccumulator> byCategory =
      <String, _CategoryAccumulator>{};

  for (final Transaction t in txs) {
    final String category = t.category.isEmpty
        ? (type == TransactionType.income ? 'Income' : 'Uncategorized')
        : t.category;
    final String sub = (t.subcategory == null || t.subcategory!.isEmpty)
        ? (type == TransactionType.income ? 'Regular' : 'General')
        : t.subcategory!;

    final _CategoryAccumulator acc = byCategory.putIfAbsent(
      category,
      () => _CategoryAccumulator(category),
    );
    acc.total += t.amount.pesos;
    acc.count += 1;

    final _SubAccumulator subAcc = acc.subcategories.putIfAbsent(
      sub,
      () => _SubAccumulator(),
    );
    subAcc.total += t.amount.pesos;
    subAcc.count += 1;
  }

  final List<CategoryBreakdown> out = byCategory.values.map((
    _CategoryAccumulator a,
  ) {
    return CategoryBreakdown(
      category: a.category,
      total: a.total,
      count: a.count,
      percentage: grand > 0 ? (a.total / grand) * 100 : 0,
      subcategories: a.subcategories.entries.map((
        MapEntry<String, _SubAccumulator> e,
      ) {
        return SubcategoryBreakdown(
          name: e.key,
          total: e.value.total,
          count: e.value.count,
          percentageOfCategory: a.total > 0
              ? (e.value.total / a.total) * 100
              : 0,
        );
      }).toList(),
    );
  }).toList();

  out.sort((CategoryBreakdown a, CategoryBreakdown b) {
    return b.total.compareTo(a.total);
  });
  return out;
}

class _CategoryAccumulator {
  _CategoryAccumulator(this.category);
  final String category;
  double total = 0;
  int count = 0;
  final Map<String, _SubAccumulator> subcategories =
      <String, _SubAccumulator>{};
}

class _SubAccumulator {
  double total = 0;
  int count = 0;
}

/// Everything Reports shows, from one set of inputs and one filter pass.
ReportSet buildReports({
  required List<Transaction> transactions,
  required List<Account> accounts,
  required ReportPeriod period,
  required DateTime now,
  ProfileEntity? profile,
  // DEFAULTED EMPTY so every existing caller and fixture keeps compiling and
  // keeps its old answer. That is deliberate rather than lazy: making these
  // required would have moved a figure in every report fixture at once and
  // buried the real change among the noise. The app passes both, a test that
  // cares passes them too, and everything else is provably untouched.
  List<Debt> debts = const <Debt>[],
  List<InstallmentPlan> plans = const <InstallmentPlan>[],
}) {
  // The order matters and is the prototype's: entity, then validity, then
  // date. Filtering by date first would be equivalent here and is not
  // guaranteed to stay equivalent, so the order is preserved rather than
  // optimised.
  final List<Transaction> scoped = filterByPeriod(
    validLedgerEntries(filterByProfile(transactions, profile)),
    period,
    now,
  );

  return ReportSet(
    // Position deliberately takes NO period. A balance sheet is what you own
    // now; "my net worth last March" is a different feature and needs history
    // the app does not keep.
    position: computePosition(accounts, profile, debts: debts, plans: plans),
    duplicateBalances: findDuplicateBalances(accounts: accounts, debts: debts),
    performance: computePerformance(scoped, now),
    cashFlow: computeCashFlow(scoped),
    expenseByCategory: computeCategoryBreakdown(
      scoped,
      TransactionType.expense,
    ),
    incomeByCategory: computeCategoryBreakdown(scoped, TransactionType.income),
    transactions: scoped,
  );
}
