import '../../models/models.dart';

/// The Reports engine, ported from src/components/ReportsScreen.tsx.
///
/// The prototype computes all of this inline inside the component, in about
/// two hundred lines of `useMemo`. Pulling it out is not tidiness: it is the
/// only way to lock it to vectors generated by RUNNING the TypeScript, which
/// is how every other engine in app/ was ported and the reason the numbers
/// match to the centavo.
///
/// Four questions, and the prototype's own four tabs answer one each:
///   POSITION       what you own and what you owe, right now
///   PERFORMANCE    what came in and went out over a period
///   CASH FLOW      the same money sorted into operating, investing, financing
///   RECONCILIATION does the app agree with your actual bank balance
///
/// Reconciliation is NOT here. It is the only one of the four that WRITES
/// (it creates an adjustment transaction and changes a transaction's status),
/// so it is its own batch with its own journey tests, rather than a fourth
/// tab bolted onto three read-only ones.

/// The periods the prototype offers, from src/types.ts.
///
/// `custom` is in the prototype's type and is never selectable in its UI, so
/// it is not here. Adding an enum value nothing can produce is how a switch
/// gets a branch nobody has ever run.
enum ReportPeriod { daily, weekly, monthly, quarterly, semiAnnually, annually }

extension ReportPeriodLabel on ReportPeriod {
  String get label => switch (this) {
    ReportPeriod.daily => 'Today',
    ReportPeriod.weekly => 'This week',
    ReportPeriod.monthly => 'This month',
    ReportPeriod.quarterly => 'This quarter',
    ReportPeriod.semiAnnually => 'This half',
    ReportPeriod.annually => 'This year',
  };
}

/// Which accounts count as things you OWN, from the prototype's own list.
const List<AccountKind> assetKinds = <AccountKind>[
  AccountKind.cash,
  AccountKind.bank,
  AccountKind.gcash,
  AccountKind.maya,
  AccountKind.debit,
  AccountKind.investment,
  AccountKind.receivable,
];

/// Which count as things you OWE.
const List<AccountKind> liabilityKinds = <AccountKind>[
  AccountKind.credit,
  AccountKind.loan,
  AccountKind.mortgage,
];

/// The subset of assets that is money you could spend today.
const List<AccountKind> cashEquivalentKinds = <AccountKind>[
  AccountKind.cash,
  AccountKind.bank,
  AccountKind.gcash,
  AccountKind.maya,
  AccountKind.debit,
];

/// Converts an account balance to pesos.
///
/// Every account in the fixture is PHP and the Dart model carries no currency
/// field yet, so this is the identity function. It exists as a NAMED SEAM
/// rather than being left out: the prototype calls convertToPhp on every one
/// of these sums, and when multi-currency lands it has to land in exactly
/// these places. A missing call site is invisible; a function that does
/// nothing yet is greppable.
double toPhp(double amount) => amount;

/// What you own and what you owe, at this instant. No period applies: a
/// balance sheet is a photograph, not a film.
class FinancialPosition {
  const FinancialPosition({
    required this.totalAssets,
    required this.totalLiabilities,
    required this.netWorth,
    required this.cashEquivalents,
    required this.investments,
    required this.receivables,
    required this.creditCards,
    required this.loans,
    required this.assetAccounts,
    required this.liabilityAccounts,
  });

  final double totalAssets;
  final double totalLiabilities;

  /// Assets minus liabilities. The one number on the screen that answers
  /// "am I actually getting anywhere".
  final double netWorth;

  final double cashEquivalents;
  final double investments;
  final double receivables;
  final double creditCards;
  final double loans;

  final List<Account> assetAccounts;
  final List<Account> liabilityAccounts;
}

/// What came in and what went out, over a period.
class FinancialPerformance {
  const FinancialPerformance({
    required this.totalIncome,
    required this.totalExpenses,
    required this.netSurplus,
    required this.businessRevenue,
    required this.businessExpenses,
    required this.businessNetProfit,
    required this.savingsRate,
    required this.debtServicingExpenses,
    required this.debtServiceRatio,
    required this.projectedIncome,
    required this.projectedExpenses,
    required this.projectedSurplus,
  });

  final double totalIncome;
  final double totalExpenses;
  final double netSurplus;

  final double businessRevenue;
  final double businessExpenses;
  final double businessNetProfit;

  /// Percent, 0 to 100, not a fraction. The prototype multiplies by 100 here
  /// and the screen appends a % sign, so keeping the same unit avoids the
  /// classic hundredfold error at the one place it would be least noticed.
  final double savingsRate;

  final double debtServicingExpenses;
  final double debtServiceRatio;

  /// A straight-line run rate: what this month ends at if the rest of it
  /// looks like the part so far. See [computePerformance] for why this is
  /// worth distrusting.
  final double projectedIncome;
  final double projectedExpenses;
  final double projectedSurplus;
}

/// The same money as [FinancialPerformance], sorted the way a statement of
/// cash flows sorts it.
class CashFlow {
  const CashFlow({
    required this.operatingInflows,
    required this.operatingOutflows,
    required this.netOperating,
    required this.investingInflows,
    required this.investingOutflows,
    required this.netInvesting,
    required this.financingInflows,
    required this.financingOutflows,
    required this.netFinancing,
    required this.transfersCount,
    required this.transfersVolume,
    required this.netCashChange,
  });

  final double operatingInflows;
  final double operatingOutflows;
  final double netOperating;

  final double investingInflows;
  final double investingOutflows;
  final double netInvesting;

  final double financingInflows;
  final double financingOutflows;
  final double netFinancing;

  /// Transfers are reported and then EXCLUDED from netCashChange, because
  /// moving your own money between your own accounts is not cash flowing in
  /// or out of anything. Showing the count and volume anyway is deliberate:
  /// somebody who moved 50,000 around wants to see that the report noticed,
  /// rather than wondering whether it was dropped.
  final int transfersCount;
  final double transfersVolume;

  final double netCashChange;
}

/// One category's share of the spending (or the income) in a period.
class CategoryBreakdown {
  const CategoryBreakdown({
    required this.category,
    required this.total,
    required this.count,
    required this.percentage,
    required this.subcategories,
  });

  final String category;
  final double total;
  final int count;

  /// Percent of the period's total, 0 to 100.
  final double percentage;
  final List<SubcategoryBreakdown> subcategories;
}

class SubcategoryBreakdown {
  const SubcategoryBreakdown({
    required this.name,
    required this.total,
    required this.count,
    required this.percentageOfCategory,
  });

  final String name;
  final double total;
  final int count;
  final double percentageOfCategory;
}

/// Everything Reports shows, computed once from one set of inputs.
///
/// One object rather than four calls, so the four tabs cannot disagree about
/// which transactions they were looking at. Three false alarms in this
/// repository came from two screens seeming to disagree about money, and none
/// could be settled because nothing had ever put them in front of one source.
class ReportSet {
  const ReportSet({
    required this.position,
    required this.performance,
    required this.cashFlow,
    required this.expenseByCategory,
    required this.incomeByCategory,
    required this.transactions,
  });

  final FinancialPosition position;
  final FinancialPerformance performance;
  final CashFlow cashFlow;
  final List<CategoryBreakdown> expenseByCategory;
  final List<CategoryBreakdown> incomeByCategory;

  /// The transactions every figure above was computed from, after the profile,
  /// status and period filters. Exposed so a screen can say "from N entries"
  /// truthfully, and so a test can check the filter rather than infer it.
  final List<Transaction> transactions;
}

/// Keeps only the entries belonging to one entity, or all of them when
/// [profile] is null ("All" in the picker).
///
/// An entry with no profile counts as personal, which is the prototype's
/// `t.profile || 'personal'`.
List<Transaction> filterByProfile(
  List<Transaction> transactions,
  ProfileEntity? profile,
) {
  if (profile == null) return transactions;
  return transactions
      .where(
        (Transaction t) => (t.profile ?? ProfileEntity.personal) == profile,
      )
      .toList();
}

/// Accounts belonging to one entity, or all of them when [profile] is null.
///
/// Note the asymmetry with transactions above, which is the prototype's and
/// is deliberate here: an account with NO profile passes every filter, where a
/// transaction with no profile is treated as personal. An unclassified wallet
/// should not vanish from a report; an unclassified expense has to land
/// somewhere, and personal is the prototype's answer.
List<Account> filterAccountsByProfile(
  List<Account> accounts,
  ProfileEntity? profile,
) {
  if (profile == null) return accounts;
  return accounts
      .where((Account a) => a.profile == null || a.profile == profile)
      .toList();
}

/// Keeps only entries that belong in a ledger at all.
///
/// Excluded and duplicate entries are shown in Activity, struck through, so a
/// person can see what was discounted and why. They must never reach a total.
List<Transaction> validLedgerEntries(List<Transaction> transactions) {
  return transactions
      .where(
        (Transaction t) =>
            t.status != TransactionStatus.excluded &&
            t.status != TransactionStatus.duplicate,
      )
      .toList();
}

/// Keeps only the entries inside [period], relative to [now].
///
/// An UNPARSEABLE date is KEPT, not dropped, which is the prototype's
/// `if (isNaN(txDate.getTime())) return true`. That looks like a bug and is
/// the safer of the two behaviours: a corrupt date should make a total look
/// wrong and get investigated, not quietly shrink it.
List<Transaction> filterByPeriod(
  List<Transaction> transactions,
  ReportPeriod period,
  DateTime now,
) {
  return transactions.where((Transaction t) {
    final DateTime? d = DateTime.tryParse(t.date);
    if (d == null) return true;

    switch (period) {
      case ReportPeriod.daily:
        return t.date == _iso(now);

      case ReportPeriod.weekly:
        // The prototype builds `oneWeekAgo` by subtracting 7 from the DAY OF
        // MONTH of a Date that still carries the current time of day, then
        // compares full timestamps. A transaction date parses to midnight, so
        // an entry dated exactly seven days ago is already before the cutoff
        // and falls outside the window. Reproduced rather than corrected: the
        // number on the phone has to match the number the prototype prints.
        final DateTime cutoff = now.subtract(const Duration(days: 7));
        return !d.isBefore(cutoff) && !d.isAfter(now);

      case ReportPeriod.monthly:
        return d.year == now.year && d.month == now.month;

      case ReportPeriod.quarterly:
        return d.year == now.year &&
            _quarterOf(d.month) == _quarterOf(now.month);

      case ReportPeriod.semiAnnually:
        return d.year == now.year && (d.month <= 6) == (now.month <= 6);

      case ReportPeriod.annually:
        return d.year == now.year;
    }
  }).toList();
}

/// 0 for Jan to Mar, 1 for Apr to Jun, and so on. Takes a 1-based Dart month
/// and matches the prototype's 0-based `Math.floor(getMonth() / 3)`.
int _quarterOf(int month) => (month - 1) ~/ 3;

String _iso(DateTime d) =>
    '${d.year}-${d.month.toString().padLeft(2, '0')}-'
    '${d.day.toString().padLeft(2, '0')}';

/// Case-insensitive substring test, the shape the prototype uses everywhere in
/// this screen to decide what a category means.
///
/// This is a WEAK test and naming it once makes that visible. "Investment &
/// Passive Income" contains "investment", which is the intent, but so would a
/// category somebody named "Investment club snacks". The prototype classifies
/// cash flow this way and the port matches it; a stronger scheme is a product
/// decision, not a porting one.
bool _has(String? haystack, String needle) =>
    haystack != null && haystack.toLowerCase().contains(needle);

double _sumOf(Iterable<Transaction> txs) =>
    txs.fold<double>(0, (double sum, Transaction t) => sum + t.amount);

/// The balance sheet.
FinancialPosition computePosition(
  List<Account> accounts,
  ProfileEntity? profile,
) {
  final List<Account> scoped = filterAccountsByProfile(accounts, profile);

  final List<Account> assets = scoped
      .where((Account a) => assetKinds.contains(a.kind))
      .toList();
  final List<Account> liabilities = scoped
      .where((Account a) => liabilityKinds.contains(a.kind))
      .toList();

  double sum(Iterable<Account> list) =>
      list.fold<double>(0, (double s, Account a) => s + toPhp(a.balance));

  final double totalAssets = sum(assets);
  final double totalLiabilities = sum(liabilities);

  return FinancialPosition(
    totalAssets: totalAssets,
    totalLiabilities: totalLiabilities,
    netWorth: totalAssets - totalLiabilities,
    cashEquivalents: sum(
      assets.where((Account a) => cashEquivalentKinds.contains(a.kind)),
    ),
    investments: sum(
      assets.where((Account a) => a.kind == AccountKind.investment),
    ),
    receivables: sum(
      assets.where((Account a) => a.kind == AccountKind.receivable),
    ),
    creditCards: sum(
      liabilities.where((Account a) => a.kind == AccountKind.credit),
    ),
    loans: sum(
      liabilities.where(
        (Account a) =>
            a.kind == AccountKind.loan || a.kind == AccountKind.mortgage,
      ),
    ),
    assetAccounts: assets,
    liabilityAccounts: liabilities,
  );
}

/// The income statement, plus the two ratios and the run rate.
FinancialPerformance computePerformance(
  List<Transaction> scoped,
  DateTime now,
) {
  final double totalIncome = _sumOf(
    scoped.where((Transaction t) => t.type == TransactionType.income),
  );
  final double totalExpenses = _sumOf(
    scoped.where((Transaction t) => t.type == TransactionType.expense),
  );
  final double netSurplus = totalIncome - totalExpenses;

  final double businessRevenue = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.income &&
          t.profile == ProfileEntity.business,
    ),
  );
  final double businessExpenses = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.expense &&
          t.profile == ProfileEntity.business,
    ),
  );

  final double debtServicing = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.expense &&
          (_has(t.category, 'debt') ||
              _has(t.category, 'loan') ||
              _has(t.subcategory, 'loan')),
    ),
  );

  // The run rate divides by the day of the month REGARDLESS of the period
  // selected, which is the prototype's behaviour and is worth knowing about
  // before trusting the figure: choose "This year" on the 2nd of January and
  // it projects the year's income onto a month. The screen only shows it on
  // the monthly view for that reason.
  final int daysInMonth = DateTime(now.year, now.month + 1, 0).day;
  final int currentDay = now.day < 1 ? 1 : now.day;
  final double projectedIncome = (totalIncome / currentDay) * daysInMonth;
  final double projectedExpenses = (totalExpenses / currentDay) * daysInMonth;

  return FinancialPerformance(
    totalIncome: totalIncome,
    totalExpenses: totalExpenses,
    netSurplus: netSurplus,
    businessRevenue: businessRevenue,
    businessExpenses: businessExpenses,
    businessNetProfit: businessRevenue - businessExpenses,
    savingsRate: totalIncome > 0 ? (netSurplus / totalIncome) * 100 : 0,
    debtServicingExpenses: debtServicing,
    debtServiceRatio: totalIncome > 0 ? (debtServicing / totalIncome) * 100 : 0,
    projectedIncome: projectedIncome,
    projectedExpenses: projectedExpenses,
    projectedSurplus: projectedIncome - projectedExpenses,
  );
}

/// The statement of cash flows.
CashFlow computeCashFlow(List<Transaction> scoped) {
  final double operatingInflows = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.income &&
          !_has(t.category, 'investment') &&
          !_has(t.category, 'dividend'),
    ),
  );
  final double operatingOutflows = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.expense &&
          !_has(t.category, 'debt') &&
          !_has(t.category, 'investment'),
    ),
  );

  final double investingInflows = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.income &&
          (_has(t.category, 'investment') ||
              _has(t.category, 'dividend') ||
              _has(t.category, 'interest')),
    ),
  );
  final double investingOutflows = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.expense &&
          (_has(t.category, 'investment') || _has(t.subcategory, 'mp2')),
    ),
  );

  // Financing INFLOWS are hardcoded to zero in the prototype, with the comment
  // "External loans taken in". Nothing in the app records taking a loan out as
  // income, so there is no figure to put here; a plausible-looking number
  // would be worse than a zero the screen can explain.
  const double financingInflows = 0;
  final double financingOutflows = _sumOf(
    scoped.where(
      (Transaction t) =>
          t.type == TransactionType.expense &&
          (_has(t.category, 'debt') ||
              _has(t.category, 'loan') ||
              _has(t.subcategory, 'loan')),
    ),
  );

  final Iterable<Transaction> transfers = scoped.where(
    (Transaction t) => t.type == TransactionType.transfer,
  );

  final double netOperating = operatingInflows - operatingOutflows;
  final double netInvesting = investingInflows - investingOutflows;
  final double netFinancing = financingInflows - financingOutflows;

  return CashFlow(
    operatingInflows: operatingInflows,
    operatingOutflows: operatingOutflows,
    netOperating: netOperating,
    investingInflows: investingInflows,
    investingOutflows: investingOutflows,
    netInvesting: netInvesting,
    financingInflows: financingInflows,
    financingOutflows: financingOutflows,
    netFinancing: netFinancing,
    transfersCount: transfers.length,
    transfersVolume: _sumOf(transfers),
    netCashChange: netOperating + netInvesting + netFinancing,
  );
}

/// Groups one side of the ledger by category and then by sub-category,
/// biggest first.
List<CategoryBreakdown> computeCategoryBreakdown(
  List<Transaction> scoped,
  TransactionType type,
) {
  final List<Transaction> txs = scoped
      .where((Transaction t) => t.type == type)
      .toList();
  final double grand = _sumOf(txs);

  // Insertion-ordered, so two categories with identical totals keep the order
  // they were first seen in rather than swapping between rebuilds. Dart's sort
  // is not stable for lists over 32 elements, but the ties here are settled
  // before the sort by the order this map was built in, which is the
  // prototype's Object.values order.
  final Map<String, _CategoryAccumulator> byCategory =
      <String, _CategoryAccumulator>{};

  for (final Transaction t in txs) {
    final String category = t.category.isEmpty
        ? (type == TransactionType.income ? 'Income' : 'Uncategorized')
        : t.category;
    final String sub = (t.subcategory == null || t.subcategory!.isEmpty)
        ? (type == TransactionType.income ? 'Regular' : 'General')
        : t.subcategory!;

    final _CategoryAccumulator acc = byCategory.putIfAbsent(
      category,
      () => _CategoryAccumulator(category),
    );
    acc.total += t.amount;
    acc.count += 1;

    final _SubAccumulator subAcc = acc.subcategories.putIfAbsent(
      sub,
      () => _SubAccumulator(),
    );
    subAcc.total += t.amount;
    subAcc.count += 1;
  }

  final List<CategoryBreakdown> out = byCategory.values.map((
    _CategoryAccumulator a,
  ) {
    return CategoryBreakdown(
      category: a.category,
      total: a.total,
      count: a.count,
      percentage: grand > 0 ? (a.total / grand) * 100 : 0,
      subcategories: a.subcategories.entries.map((
        MapEntry<String, _SubAccumulator> e,
      ) {
        return SubcategoryBreakdown(
          name: e.key,
          total: e.value.total,
          count: e.value.count,
          percentageOfCategory: a.total > 0
              ? (e.value.total / a.total) * 100
              : 0,
        );
      }).toList(),
    );
  }).toList();

  out.sort((CategoryBreakdown a, CategoryBreakdown b) {
    return b.total.compareTo(a.total);
  });
  return out;
}

class _CategoryAccumulator {
  _CategoryAccumulator(this.category);
  final String category;
  double total = 0;
  int count = 0;
  final Map<String, _SubAccumulator> subcategories =
      <String, _SubAccumulator>{};
}

class _SubAccumulator {
  double total = 0;
  int count = 0;
}

/// Everything Reports shows, from one set of inputs and one filter pass.
ReportSet buildReports({
  required List<Transaction> transactions,
  required List<Account> accounts,
  required ReportPeriod period,
  required DateTime now,
  ProfileEntity? profile,
}) {
  // The order matters and is the prototype's: entity, then validity, then
  // date. Filtering by date first would be equivalent here and is not
  // guaranteed to stay equivalent, so the order is preserved rather than
  // optimised.
  final List<Transaction> scoped = filterByPeriod(
    validLedgerEntries(filterByProfile(transactions, profile)),
    period,
    now,
  );

  return ReportSet(
    // Position deliberately takes NO period. A balance sheet is what you own
    // now; "my net worth last March" is a different feature and needs history
    // the app does not keep.
    position: computePosition(accounts, profile),
    performance: computePerformance(scoped, now),
    cashFlow: computeCashFlow(scoped),
    expenseByCategory: computeCategoryBreakdown(
      scoped,
      TransactionType.expense,
    ),
    incomeByCategory: computeCategoryBreakdown(scoped, TransactionType.income),
    transactions: scoped,
  );
}
