// Personal financial statements, ported 1:1 from mobile/lib/statements.js
// plus the two helpers it leans on (netWorthParts and trackedRemaining from
// mobile/lib/analytics.js, isThisMonth from mobile/lib/format.js). Pure
// functions over the same data shape the backup file carries, so the Reports
// numbers here can never disagree with the RN app. Golden-verified against
// outputs generated by executing the real RN modules.

import 'base_currency_scope.dart' show baseCurrencyOf, inBaseCurrency;
import 'fx_totals.dart' show FxOutcome, FxTable, convertAll;
import 'ledger.dart' show amountOf;

double _num(dynamic x) => amountOf(x);

bool _truthy(dynamic v) =>
    v == true || (v is num && v != 0) || (v is String && v.isNotEmpty);

bool _eq(double a, double b) => (a - b).abs() < 0.005;

String todayISO(DateTime d) {
  final m = d.month.toString().padLeft(2, '0');
  final day = d.day.toString().padLeft(2, '0');
  return '${d.year}-$m-$day';
}

bool isThisMonth(dynamic dateStr, DateTime ref) {
  if (!_truthy(dateStr)) return false;
  final s = dateStr.toString();
  final prefix = s.length >= 7 ? s.substring(0, 7) : s;
  return prefix == todayISO(ref).substring(0, 7);
}

bool _inMonth(dynamic dateStr, DateTime ref) =>
    _truthy(dateStr) && isThisMonth(dateStr, ref);

List<Map<String, dynamic>> _list(dynamic v) => (v as List? ?? [])
    .whereType<Map>()
    .map((m) => m.cast<String, dynamic>())
    .toList();

/// Tracked (cash leg) utang still outstanding: amount minus recorded
/// payments, unpaid entries only, never negative.
double trackedRemaining(dynamic list) {
  var total = 0.0;
  for (final r in _list(list)) {
    if (!_truthy(r['cashLeg']) || _truthy(r['paid'])) continue;
    var paid = 0.0;
    for (final p in _list(r['payments'])) {
      paid += _num(p['amount']);
    }
    final left = _num(r['amount']) - paid;
    total += left > 0 ? left : 0;
  }
  return total;
}

/// The ONE net worth breakdown, same formula as the RN app on every screen.
///
/// [fx] converts foreign rows instead of dropping them.
///
/// Optional, and null by default, which is EXACTLY what this function did
/// before delivery E: every foreign row excluded, every golden vector byte
/// identical. A caller that wants a converted total has to ask for one AND
/// hand over the table it was converted with, because a total that depends on
/// hidden state set somewhere else is how a money app gets "it was right
/// yesterday".
///
/// The result then gains `fxAssets` and `fxDebts`, carrying what the
/// conversion actually did, so the screen showing the number can say what
/// produced it. There is no state in which a converted total is available
/// without that.
Map<String, dynamic> netWorthParts(Map<String, dynamic>? data, {FxTable? fx}) {
  final d = data ?? {};
  // A row in another currency is never ADDED as if it were base currency.
  //
  // A DELIBERATE divergence from analytics.js, recorded rather than slipped
  // in. The React Native app has no per-account currency, so no golden vector
  // carries one and every vector still matches byte for byte. What it stops is
  // a $1,000 balance landing in a peso net worth as ₱1,000 and understating
  // the truth by about ₱55,000 with nothing on screen to hint at it.
  //
  // Foreign rows are collected as they are skipped, so the conversion pass
  // below works from the same list the exclusion used and the two can never
  // disagree about which rows are foreign.
  final base = baseCurrencyOf(d);
  final foreign = <(double, String)>[];
  final foreignDebts = <(double, String)>[];
  String codeOf(Map<String, dynamic> r) =>
      (r['currencyCode'] as String).toUpperCase();

  var accounts = 0.0;
  for (final a in _list(d['accounts'])) {
    if (!inBaseCurrency(a, base)) {
      foreign.add((_num(a['balance']), codeOf(a)));
      continue;
    }
    accounts += _num(a['balance']);
  }
  var holdings = 0.0;
  for (final a in _list(d['assets'])) {
    if (!inBaseCurrency(a, base)) {
      foreign.add((_num(a['value']), codeOf(a)));
      continue;
    }
    holdings += _num(a['value']);
  }
  final receivables = trackedRemaining(d['receivables']);
  final payables = trackedRemaining(d['payables']);
  var debts = 0.0;
  for (final x in _list(d['debts'])) {
    // Same rule on the liability side, and this is the more dangerous
    // direction: a dollar debt left in a peso total UNDERSTATES what is owed,
    // which makes net worth look better than it is.
    if (!inBaseCurrency(x, base)) {
      foreignDebts.add((_num(x['remaining']), codeOf(x)));
      continue;
    }
    debts += _num(x['remaining']);
  }
  // Assets and liabilities converted SEPARATELY, so a dollar debt lands on the
  // liability side rather than netting invisibly against a dollar account.
  // Netting would leave net worth right by luck and both halves of the summary
  // card wrong.
  final fxAssets = fx == null
      ? const FxOutcome(0, {}, {})
      : convertAll(fx, foreign);
  final fxDebts = fx == null
      ? const FxOutcome(0, {}, {})
      : convertAll(fx, foreignDebts);
  final assets = accounts + holdings + receivables + fxAssets.converted;
  final liabilities = debts + payables + fxDebts.converted;
  return {
    'accounts': accounts,
    'holdings': holdings,
    'receivables': receivables,
    'payables': payables,
    'debts': debts,
    'assets': assets,
    'liabilities': liabilities,
    'netWorth': assets - liabilities,
    // CONDITIONAL, like every other new key in this feature. Absent when no
    // table was passed, so a caller that did not ask for conversion gets a map
    // shaped exactly as it always was.
    if (fx != null) 'fxAssets': fxAssets,
    if (fx != null) 'fxDebts': fxDebts,
  };
}

const List<String> _shortTermDebtTypes = [
  'credit card',
  'bnpl',
  'short term',
  'insurance',
];

/// Balance sheet as of now. Assets = Liabilities + Equity by construction;
/// the balances flag guards the identity against future edits.
Map<String, dynamic> balanceSheet(Map<String, dynamic>? data) {
  final d = data ?? {};
  final parts = netWorthParts(d);

  var cash = 0.0;
  for (final a in _list(d['accounts'])) {
    if (a['kind'] == 'cash') cash += _num(a['balance']);
  }
  final bank = (parts['accounts'] as double) - cash;

  var shortDebts = 0.0;
  for (final x in _list(d['debts'])) {
    if (_shortTermDebtTypes.contains(x['type'])) {
      shortDebts += _num(x['remaining']);
    }
  }
  final longDebts = (parts['debts'] as double) - shortDebts;

  final currentAssets = cash + bank + (parts['receivables'] as double);
  final totalAssets = parts['assets'] as double;
  final currentLiabilities = shortDebts + (parts['payables'] as double);
  final totalLiabilities = parts['liabilities'] as double;
  final equity = parts['netWorth'] as double;

  return {
    'cash': cash,
    'bank': bank,
    'receivables': parts['receivables'],
    'investments': parts['holdings'],
    'currentAssets': currentAssets,
    'longTermAssets': parts['holdings'],
    'totalAssets': totalAssets,
    'shortDebts': shortDebts,
    'longDebts': longDebts,
    'payables': parts['payables'],
    'currentLiabilities': currentLiabilities,
    'longTermLiabilities': longDebts,
    'totalLiabilities': totalLiabilities,
    'equity': equity,
    'balances': _eq(totalAssets, totalLiabilities + equity),
  };
}

/// Income statement for one month: honest earnings, not cash movement.
Map<String, dynamic> incomeStatement(Map<String, dynamic>? data, DateTime ref) {
  final tx = _list(
    (data ?? {})['transactions'],
  ).where((t) => _inMonth(t['date'], ref)).toList();
  var income = 0.0;
  var expenses = 0.0;
  var interestExpense = 0.0;
  for (final t in tx) {
    if (t['type'] == 'income' && t['source'] != 'receivable') {
      income += _num(t['amount']);
    }
    if (t['type'] == 'expense') {
      expenses += _num(t['amount']);
      if (t['source'] == 'interest') interestExpense += _num(t['amount']);
    }
  }
  return {
    'income': income,
    'expenses': expenses,
    'interestExpense': interestExpense,
    'spendingExpense': expenses - interestExpense,
    'netIncome': income - expenses,
  };
}

/// Cash flow for one month: every peso that moved through an account, sorted
/// into operating, investing, and financing, with the reconcile proof.
Map<String, dynamic> cashFlowStatement(
  Map<String, dynamic>? data,
  DateTime ref,
) {
  final d = data ?? {};
  final accountIds = _list(
    d['accounts'],
  ).map((a) => a['id']).where((id) => id != null).toSet();
  final tx = _list(
    d['transactions'],
  ).where((t) => _inMonth(t['date'], ref)).toList();
  final linked = tx
      .where(
        (t) =>
            _truthy(t['accountId']) &&
            accountIds.contains(t['accountId']) &&
            t['type'] != 'adjustment',
      )
      .toList();

  int sign(Map<String, dynamic> t) {
    if (t['flow'] == 'in') return 1;
    if (t['flow'] == 'out') return -1;
    return t['type'] == 'income' ? 1 : -1;
  }

  final op = {'in': 0.0, 'out': 0.0};
  final inv = {'in': 0.0, 'out': 0.0};
  final fin = {'in': 0.0, 'out': 0.0};
  void add(Map<String, double> bucket, double signed) {
    if (signed >= 0) {
      bucket['in'] = bucket['in']! + signed;
    } else {
      bucket['out'] = bucket['out']! - signed;
    }
  }

  for (final t in linked) {
    final signed = sign(t) * _num(t['amount']);
    if (t['type'] == 'income') {
      add(t['source'] == 'receivable' ? fin : op, signed);
    } else if (t['type'] == 'expense') {
      add(op, signed);
    } else {
      add(fin, signed);
    }
  }

  final payments = _list(
    d['payments'],
  ).where((p) => _inMonth(p['date'], ref)).toList();
  var principalPaid = 0.0;
  var interestPaid = 0.0;
  for (final p in payments) {
    final paidFromAccount =
        _truthy(p['account']) && accountIds.contains(p['account']);
    if (!paidFromAccount) continue;
    final amount = _num(p['amount']);
    var interest = p['interest'] != null ? _num(p['interest']) : 0.0;
    if (interest < 0) interest = 0;
    if (interest > amount) interest = amount;
    final principal = amount - interest;
    interestPaid += interest;
    principalPaid += principal;
    op['out'] = op['out']! + interest;
    fin['out'] = fin['out']! + principal;
  }

  final operating = op['in']! - op['out']!;
  final investing = inv['in']! - inv['out']!;
  final financing = fin['in']! - fin['out']!;
  final netChange = operating + investing + financing;

  var recorded = 0.0;
  for (final t in linked) {
    recorded += sign(t) * _num(t['amount']);
  }
  for (final p in payments) {
    if (_truthy(p['account']) && accountIds.contains(p['account'])) {
      recorded -= _num(p['amount']);
    }
  }

  return {
    'operating': {'in': op['in'], 'out': op['out'], 'net': operating},
    'investing': {'in': inv['in'], 'out': inv['out'], 'net': investing},
    'financing': {'in': fin['in'], 'out': fin['out'], 'net': financing},
    'interestPaid': interestPaid,
    'principalPaid': principalPaid,
    'netChange': netChange,
    'reconciles': _eq(netChange, recorded),
    'recorded': recorded,
  };
}
