// Replays flutter/test/goldens/analytics_goldens.json, generated by
// executing the REAL RN analytics.js and chartgeom.js. The Dart engine must
// match every number: series, categories, weekday averages, savings rate,
// forecast, runway, health score, goal pace, and chart geometry.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/analytics.dart';
import 'package:salapify/money/chartgeom.dart';

dynamic normalize(dynamic v) {
  if (v is num) return v.toDouble();
  if (v is Map) return v.map((k, x) => MapEntry(k.toString(), normalize(x)));
  if (v is List) return v.map(normalize).toList();
  return v;
}

void main() {
  final raw = jsonDecode(
      File('test/goldens/analytics_goldens.json').readAsStringSync())
      as Map<String, dynamic>;
  // Noon, matching the generator's ref so date comparisons never straddle.
  final ref = DateTime(2026, 7, 16, 12);
  final fixtures = raw['fixtures'] as Map<String, dynamic>;
  final rich = (fixtures['rich'] as Map).cast<String, dynamic>();
  final sparse = (fixtures['sparse'] as Map).cast<String, dynamic>();
  final empty = (fixtures['empty'] as Map).cast<String, dynamic>();

  void check(String name, dynamic actual, dynamic expected) {
    expect(normalize(actual), normalize(expected), reason: name);
  }

  test('monthlySeries matches the RN engine', () {
    final g = raw['monthlySeries'];
    check('rich6', monthlySeries(rich['transactions'], 6, ref), g['rich6']);
    check('rich8', monthlySeries(rich['transactions'], 8, ref), g['rich8']);
    check('empty', monthlySeries([], 6, ref), g['empty']);
  });

  test('categoryMovers matches the RN engine', () {
    final g = raw['categoryMovers'];
    check('rich', categoryMovers(rich['transactions'], ref, 5), g['rich']);
    check('limit3', categoryMovers(rich['transactions'], ref, 3),
        g['richLimit3']);
    check('empty', categoryMovers([], ref, 5), g['empty']);
  });

  test('categoryVsAverage matches the RN engine', () {
    final g = raw['categoryVsAverage'];
    check('rich', categoryVsAverage(rich['transactions'], ref, 6, 5),
        g['rich']);
    check('sparse', categoryVsAverage(sparse['transactions'], ref, 6, 5),
        g['sparse']);
    check('empty', categoryVsAverage([], ref, 6, 5), g['empty']);
  });

  test('weekdayPattern matches the RN engine', () {
    final g = raw['weekdayPattern'];
    check('rich', weekdayPattern(rich['transactions'], ref), g['rich']);
    check('empty', weekdayPattern([], ref), g['empty']);
  });

  test('savingsRate matches the RN engine, null included', () {
    final g = raw['savingsRate'];
    check('rich', savingsRate(rich['transactions'], rich['payments'], ref),
        g['rich']);
    expect(savingsRate(sparse['transactions'], [], ref), isNull);
    expect(g['noIncome'], isNull);
    expect(savingsRate([], [], ref), isNull);
  });

  test('forecastMonthEnd matches the RN engine', () {
    final g = raw['forecastMonthEnd'];
    check('rich', forecastMonthEnd(rich['transactions'], ref), g['rich']);
    check('empty', forecastMonthEnd([], ref), g['empty']);
  });

  test('emergencyRunway matches the RN engine, cap and null included', () {
    final g = raw['emergencyRunway'];
    check('rich', emergencyRunway(rich, ref), g['rich']);
    check('sparse', emergencyRunway(sparse, ref), g['sparse']);
    check('empty', emergencyRunway(empty, ref), g['empty']);
    check(
        'hugeBuffer',
        emergencyRunway({
          ...rich,
          'accounts': [
            {'id': 'c', 'kind': 'cash', 'balance': 9999999},
          ],
        }, ref),
        g['hugeBuffer']);
  });

  test('healthScore matches the RN engine', () {
    final g = raw['healthScore'];
    check('rich', healthScore(rich, ref), g['rich']);
    check('sparse', healthScore(sparse, ref), g['sparse']);
    check('empty', healthScore(empty, ref), g['empty']);
    check('noLimit', healthScore({...rich, 'settings': {}}, ref),
        g['noLimit']);
  });

  test('previousMonthLeftover matches the RN engine', () {
    final g = raw['previousMonthLeftover'];
    check('rich', previousMonthLeftover(rich['transactions'], 15000, ref),
        g['rich']);
    check('overspent',
        previousMonthLeftover(rich['transactions'], 5000, ref),
        g['overspent']);
    check('noLimit', previousMonthLeftover(rich['transactions'], 0, ref),
        g['noLimit']);
    check('quiet', previousMonthLeftover([], 15000, ref), g['quietMonth']);
  });

  test('goalPace matches the RN engine on every goal fixture', () {
    for (final entry in (raw['goalPace'] as List)) {
      final goal = (entry['goal'] as Map).cast<String, dynamic>();
      check('goal ${goal['name']}', goalPace(goal, ref), entry['result']);
    }
  });

  test('chart geometry matches the RN engine', () {
    final g = raw['chartgeom'];
    final sm = g['sharedMax'];
    check('sharedMax two', sharedMax([[1, 5, 3], [2, 9, 4]]), sm['two']);
    check('sharedMax junk', sharedMax([[1, 'x', null], 'nope', [-5]]),
        sm['junk']);
    check('sharedMax empty', sharedMax([]), sm['empty']);
    final lps = g['linePointsScaled'];
    check('lps normal', linePointsScaled([0, 50, 100, 25], 100, 300, 120, 8),
        lps['normal']);
    check('lps single', linePointsScaled([42], 42, 300, 120, 8),
        lps['single']);
    check('lps allZero', linePointsScaled([0, 0, 0], 0, 300, 120, 8),
        lps['allZero']);
    check('lps tiny', linePointsScaled([5, 10], 10, 4, 4, 8), lps['tiny']);
    check('lps junk', linePointsScaled([3, 'x', null], 3, 200, 100, 8),
        lps['junk']);
    final lp = g['linePoints'];
    check('lp normal', linePoints([10, 40, 20], 300, 120, 8), lp['normal']);
    check('lp empty', linePoints([], 300, 120, 8), lp['empty']);
  });
}
