// Replays flutter/test/goldens/budget_goldens.json, generated by executing
// the verbatim RN budget-tab money logic wired to the real lib functions.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/budget.dart';

dynamic normalize(dynamic v) {
  // JSON.stringify writes Infinity and NaN as null, so the golden holds
  // null where the live JS value was non-finite; mirror that here.
  if (v is num) return v.toDouble().isFinite ? v.toDouble() : null;
  if (v is Map) return v.map((k, x) => MapEntry(k.toString(), normalize(x)));
  if (v is List) return v.map(normalize).toList();
  return v;
}

void main() {
  final raw = jsonDecode(
      File('test/goldens/budget_goldens.json').readAsStringSync())
      as Map<String, dynamic>;
  final ref = DateTime(2026, 7, 16, 12);

  for (final entry in (raw['scenarios'] as Map<String, dynamic>).entries) {
    test('budget golden: ${entry.key}', () {
      final s = entry.value as Map<String, dynamic>;
      final data = (s['data'] as Map).cast<String, dynamic>();
      expect(normalize(budgetSummary(data, ref)), normalize(s['summary']),
          reason: '${entry.key} summary');
      expect(normalize(whereItWent(data, ref)), normalize(s['whereItWent']),
          reason: '${entry.key} whereItWent');
    });
  }
}
