// Replays flutter/test/goldens/categories_goldens.json, generated by executing
// the real mobile/lib/categories.js. Locks the data SHAPE around a category
// delete: who keeps their tag, who loses it, which children get promoted, and
// what order the tree renders in.
//
// The founder's rule lives in the recategorize block: deleting a category
// MOVES its entries to a chosen category, and only an explicit clear untags
// them. A port that silently orphaned rows would pass every money test in the
// suite, because no peso changes.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/data/backup.dart' show normalizeCategoryTree;
import 'package:salapify/money/categories.dart';

List<Map<String, dynamic>> _rows(dynamic v) =>
    (v as List).map((e) => (e as Map).cast<String, dynamic>()).toList();

void main() {
  final g =
      jsonDecode(
            File('test/goldens/categories_goldens.json').readAsStringSync(),
          )
          as Map<String, dynamic>;

  test('normalizeCategoryTree matches the RN tree cleaner', () {
    for (final c in (g['normalize'] as List).cast<Map<String, dynamic>>()) {
      final input = c['in'] as Map<String, dynamic>;
      final name = input['name'];
      // The junk fixture carries a null row, which the RN function returns
      // as-is; the Dart signature takes maps only, so that one row is dropped
      // before the call and the comparison skips it. Said out loud rather
      // than quietly filtering the whole case away.
      final given = (input['list'] as List).whereType<Map>().toList();
      final want = (c['out'] as List).whereType<Map>().toList();
      final got = normalizeCategoryTree(
        given.map((e) => e.cast<String, dynamic>()).toList(),
      );
      expect(got.length, want.length, reason: 'tree $name row count');
      for (var i = 0; i < want.length; i++) {
        expect(got[i]['id'], want[i]['id'], reason: 'tree $name row $i id');
        expect(
          got[i]['parentId'],
          want[i]['parentId'],
          reason: 'tree $name row $i parentId',
        );
      }
    }
  });

  test('promoteChildren matches RN', () {
    for (final c in (g['promote'] as List).cast<Map<String, dynamic>>()) {
      final input = c['in'] as Map<String, dynamic>;
      final treeName = input['name'];
      final source = (g['normalize'] as List)
          .cast<Map<String, dynamic>>()
          .firstWhere(
            (n) => (n['in'] as Map<String, dynamic>)['name'] == treeName,
          );
      final list = ((source['in'] as Map<String, dynamic>)['list'] as List)
          .whereType<Map>()
          .map((e) => e.cast<String, dynamic>())
          .toList();
      final got = promoteChildren(list, input['parentId']);
      final want = (c['out'] as List).whereType<Map>().toList();
      expect(
        got.length,
        want.length,
        reason: 'promote $treeName under ${input['parentId']}',
      );
      for (var i = 0; i < want.length; i++) {
        expect(
          got[i]['parentId'],
          want[i]['parentId'],
          reason: 'promote $treeName row $i parentId',
        );
      }
    }
  });

  test('categoryTree renders in the RN order, at the RN depths', () {
    for (final c in (g['tree'] as List).cast<Map<String, dynamic>>()) {
      final input = c['in'] as Map<String, dynamic>;
      final list = (input['list'] as List)
          .whereType<Map>()
          .map((e) => e.cast<String, dynamic>())
          .toList();
      final got = categoryTree(list);
      // Compared whole, INCLUDING the row RN emits for an id-less category.
      // The first version filtered those out and hid a real difference: with
      // a category that has no id, RN's own childrenOf matches undefined
      // against undefined, so every other top level category is rendered
      // once as its child and once again at top level. That duplicate is
      // faithful RN behaviour on corrupt data, and the port reproduces it
      // rather than quietly being tidier than the app it must match.
      final want = _rows(c['out']);
      expect(got.length, want.length, reason: 'tree ${input['name']} length');
      for (var i = 0; i < want.length; i++) {
        expect(
          got[i].cat['id'],
          want[i]['id'],
          reason: 'tree ${input['name']} row $i id',
        );
        expect(got[i].depth, want[i]['depth'], reason: 'row $i depth');
      }
    }
  });

  test('recategorizeTransactions moves tags exactly as RN does', () {
    final txns = _rows(g['transactions']);
    for (final c in (g['recategorize'] as List).cast<Map<String, dynamic>>()) {
      final input = c['in'] as Map<String, dynamic>;
      final rawTo = input['toId'];
      // The generator writes undefined as a sentinel, because JSON has no
      // undefined and RN treats it the same as null here.
      final toId = rawTo == '__undefined__' ? null : rawTo;
      final got = recategorizeTransactions(txns, input['fromId'], toId);
      final want = _rows(c['out']);
      final label = 'from=${input['fromId']} to=$rawTo';
      expect(got.length, want.length, reason: label);
      for (var i = 0; i < want.length; i++) {
        expect(
          got[i]['categoryId'],
          want[i]['categoryId'],
          reason: '$label row $i categoryId',
        );
        expect(
          got[i].containsKey('categoryId'),
          want[i].containsKey('categoryId'),
          reason: '$label row $i tag presence',
        );
        // Nothing but the tag may move. This is the assertion that would
        // catch a "helpful" edit that also touched an amount or a date.
        expect(got[i]['amount'], want[i]['amount'], reason: '$label amount');
        expect(got[i]['type'], want[i]['type'], reason: '$label type');
      }
    }
  });

  test('taggedCount counts what the delete sheet promises', () {
    final txns = _rows(g['transactions']);
    expect(taggedCount(txns, 'food'), 2);
    expect(taggedCount(txns, 'groceries'), 1);
    expect(taggedCount(txns, 'missing'), 0);
    expect(taggedCount(txns, null), 0);
    expect(taggedCount(null, 'food'), 0);
  });
}
