// Replays flutter/test/goldens/debtmath_goldens.json, generated by
// executing the REAL RN splitDebtPayment, debtFreeProjection, cardForecast,
// buildSOA, and dueDateFor. Interest splits, payoff simulations, card
// forecasts, and the SOA text must all match the live app, byte for byte
// where text is involved.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/debtmath.dart';

dynamic normalize(dynamic v) {
  if (v is num) return v.toDouble().isFinite ? v.toDouble() : null;
  if (v is Map) return v.map((k, x) => MapEntry(k.toString(), normalize(x)));
  if (v is List) return v.map(normalize).toList();
  return v;
}

void main() {
  final raw = jsonDecode(
      File('test/goldens/debtmath_goldens.json').readAsStringSync())
      as Map<String, dynamic>;
  final ref = DateTime(2026, 7, 16, 12);

  test('monthlyInterest matches the RN arrow on every vector', () {
    final mi = jsonDecode(
        File('test/goldens/monthly_interest_goldens.json').readAsStringSync())
        as Map<String, dynamic>;
    for (final c in (mi['cases'] as List).cast<Map<String, dynamic>>()) {
      final debt = (c['debt'] as Map).cast<String, dynamic>();
      expect(monthlyInterest(debt), (c['result'] as num).toDouble(),
          reason: c['name'] as String);
    }
  });

  test('splitDebtPayment matches the RN engine on every vector', () {
    for (final v in (raw['splits'] as List)) {
      final a = (v['args'] as Map).cast<String, dynamic>();
      final result = splitDebtPayment(a['remaining'], a['monthlyRate'],
          a['interestThroughISO'], a['amount'], a['todayStr'] as String);
      expect(normalize(result), normalize(v['result']),
          reason: v['name'] as String);
    }
  });

  test('debtFreeProjection matches the RN engine, null and junk included',
      () {
    final g = raw['projections'];
    final debts = raw['projDebts'] as List;
    final hopeless = raw['hopeless'] as List;
    expect(normalize(debtFreeProjection(debts, 'avalanche', 0, ref)),
        normalize(g['avalanche']));
    expect(normalize(debtFreeProjection(debts, 'snowball', 0, ref)),
        normalize(g['snowball']));
    expect(normalize(debtFreeProjection(debts, 'avalanche', 2000, ref)),
        normalize(g['avalancheExtra']));
    expect(normalize(debtFreeProjection(debts, 'snowball', 2000, ref)),
        normalize(g['snowballExtra']));
    expect(debtFreeProjection(hopeless, 'avalanche', 0, ref), isNull);
    expect(g['hopeless'], isNull);
    expect(normalize(debtFreeProjection([], 'avalanche', 0, ref)),
        normalize(g['empty']));
    expect(
        normalize(debtFreeProjection([
          null,
          {'remaining': 'abc'},
          {'id': 'x', 'remaining': 300, 'monthlyRate': 2, 'minPayment': 50},
        ], 'snowball', 0, ref)),
        normalize(g['junk']));
  });

  test('cardForecast and dueDateFor match the RN engine per card', () {
    final cards = (raw['cards'] as Map).cast<String, dynamic>();
    final payments = raw['payments'] as List;
    for (final name in cards.keys) {
      final card = (cards[name] as Map).cast<String, dynamic>();
      expect(normalize(cardForecast(card, payments, ref)),
          normalize((raw['forecasts'] as Map)[name]),
          reason: 'forecast $name');
      expect(dueDateFor(card, ref), (raw['dueDates'] as Map)[name],
          reason: 'dueDate $name');
    }
  });

  test('an overflowing utilization caps at 999% instead of crashing', () {
    // remaining / creditLimit overflows to Infinity; RN prints 999%, Dart
    // used to throw on toInt(). Reachable from an imported backup.
    final soa = buildSOA({
      'id': 'huge',
      'name': 'Huge Card',
      'remaining': 1.7e308,
      'creditLimit': 0.5,
      'monthlyRate': 0,
      'minPayment': 0,
    }, [], ref);
    // The real RN engine prints exactly this line for these inputs.
    expect(soa, contains('Credit used: 999% of ₱1'));
  });

  test('a date stamp JS rejects accrues zero interest here too', () {
    // new Date('2026-01-32') is Invalid Date in JS (day outside 01-31),
    // so RN accrues nothing; Dart tryParse would normalize it to Feb 1
    // and accrue 42 days. Same for month 13 and day 00.
    for (final stamp in ['2026-01-32', '2026-13-05', '2026-01-00']) {
      final r = splitDebtPayment(10000, 3, stamp, 0, '2026-03-15');
      expect(r['accrued'], 0.0, reason: stamp);
      expect(r['balance'], 10000.0, reason: stamp);
    }
    // Inside the grammar, an overflowing day normalizes in BOTH engines:
    // the real RN engine accrues 130 on this input, so must we.
    final feb30 = splitDebtPayment(10000, 3, '2026-02-30', 0, '2026-03-15');
    expect(feb30['accrued'], 130.0, reason: '2026-02-30');
  });

  test('buildSOA matches the RN text byte for byte', () {
    final cards = (raw['cards'] as Map).cast<String, dynamic>();
    final payments = raw['payments'] as List;
    for (final name in cards.keys) {
      final card = (cards[name] as Map).cast<String, dynamic>();
      expect(buildSOA(card, payments, ref), (raw['soas'] as Map)[name],
          reason: 'SOA $name');
    }
  });
}
