// Replays flutter/test/goldens/debts_goldens.json, generated by executing
// the REAL RN debts screen money logic (save, del, applyPayment, logPayment,
// markPaid) against pure-state replicas of the AppData reducers. Every step
// replays the same op with the same args and deterministic ids, then the
// whole data map and the returned message must match byte for byte.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/debts.dart';

dynamic normalize(dynamic v) {
  if (v is num) return v.toDouble().isFinite ? v.toDouble() : null;
  if (v is Map) return v.map((k, x) => MapEntry(k.toString(), normalize(x)));
  if (v is List) return v.map(normalize).toList();
  return v;
}

void main() {
  final raw = jsonDecode(
      File('test/goldens/debts_goldens.json').readAsStringSync())
      as Map<String, dynamic>;
  final today = raw['today'] as String;

  for (final s in (raw['scenarios'] as List).cast<Map<String, dynamic>>()) {
    test('debts scenario ${s['name']} matches the RN engine step by step',
        () {
      var counter = 0;
      String genId(String prefix) => '${prefix}_g${counter++}';
      var data =
          jsonDecode(jsonEncode(raw['base'])) as Map<String, dynamic>;
      for (final step in (s['steps'] as List).cast<Map<String, dynamic>>()) {
        final label = '${s['name']}: ${step['label']}';
        final args = (step['args'] as Map).cast<String, dynamic>();
        final form = (args['form'] as Map).cast<String, dynamic>();
        final payFrom = args['payFrom'] as String?;
        final out = step['out'];
        switch (step['op'] as String) {
          case 'save':
            final r = saveDebt(data, form, today: today, genId: genId);
            data = r.data;
            expect(r.error, out, reason: label);
          case 'apply':
          case 'log':
            final r = step['op'] == 'apply'
                ? applyDebtPayment(data, form, payFrom,
                    (args['amt'] as num).toDouble(),
                    today: today, genId: genId)
                : logDebtPayment(data, form, payFrom, args['payAmount'],
                    today: today, genId: genId);
            data = r.data;
            final expected = (out as Map).cast<String, dynamic>();
            expect(r.msg, expected['msg'], reason: label);
            expect(r.celebrated, expected['celebrated'], reason: label);
            expect(normalize(r.newRemaining), normalize(expected['newRem']),
                reason: label);
          case 'markpaid':
            final r = markDebtPaid(data, form, payFrom,
                today: today, genId: genId);
            data = r.data;
            final expected = (out as Map).cast<String, dynamic>();
            expect(r.msg, expected['msg'], reason: label);
            expect(r.celebrated, expected['celebrated'], reason: label);
          case 'del':
            data = deleteDebt(data, form['id']);
        }
        expect(normalize(data), normalize(step['data']), reason: label);
      }
    });
  }
}
