// Golden contract for the ledger cluster. The statements section replays
// fixtures through outputs generated by EXECUTING the real RN modules
// (lib/statements.js, lib/analytics.js). The engine section replays the
// scenario sequence mirrored verbatim from context/AppData.js reducers.
// Goldens are never hand-edited; regenerate from the RN engine if it changes.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/ledger.dart';
import 'package:salapify/money/statements.dart';

void expectMatches(dynamic actual, dynamic golden, String path) {
  if (golden is num) {
    expect(actual, isA<num>(), reason: '$path should be a number');
    expect((actual as num).toDouble(), closeTo(golden.toDouble(), 1e-9),
        reason: path);
  } else if (golden is bool || golden is String) {
    expect(actual, equals(golden), reason: path);
  } else if (golden == null) {
    expect(actual, isNull, reason: path);
  } else if (golden is List) {
    expect(actual, isA<List>(), reason: '$path should be a list');
    expect((actual as List).length, golden.length, reason: '$path length');
    for (var i = 0; i < golden.length; i++) {
      expectMatches(actual[i], golden[i], '$path[$i]');
    }
  } else if (golden is Map) {
    expect(actual, isA<Map>(), reason: '$path should be a map');
    for (final key in golden.keys) {
      expectMatches((actual as Map)[key], golden[key], '$path.$key');
    }
  } else {
    fail('$path: unhandled golden type ${golden.runtimeType}');
  }
}

Map<String, dynamic> asMap(dynamic v) => (v as Map).cast<String, dynamic>();

void main() {
  final goldens = jsonDecode(
          File('test/goldens/ledger_goldens.json').readAsStringSync())
      as Map<String, dynamic>;
  final ref = DateTime(2026, 7, 15);

  test('statements match the RN engine on every fixture', () {
    final fixtures = asMap(goldens['fixtures']);
    final expected = asMap(goldens['statements']);
    for (final name in fixtures.keys) {
      final data = asMap(fixtures[name]);
      final want = asMap(expected[name]);
      expectMatches(netWorthParts(data), want['netWorthParts'],
          '$name.netWorthParts');
      expectMatches(balanceSheet(data), want['balanceSheet'],
          '$name.balanceSheet');
      expectMatches(incomeStatement(data, ref), want['incomeStatement'],
          '$name.incomeStatement');
      expectMatches(cashFlowStatement(data, ref), want['cashFlowStatement'],
          '$name.cashFlowStatement');
    }
  });

  test('the transaction engine replays the AppData scenario exactly', () {
    var state = <String, dynamic>{
      'accounts': [
        {'id': 'cash', 'balance': 1000},
        {'id': 'bank', 'balance': 5000},
      ],
      'transactions': <Map<String, dynamic>>[],
    };
    for (final raw in goldens['engine'] as List) {
      final entry = asMap(raw);
      final step = entry['step'] as List;
      final action = step[0] as String;
      if (action == 'add') {
        state = addTransaction(state, asMap(step[1]));
      } else if (action == 'update') {
        state = updateTransaction(state, step[1] as String, asMap(step[2]));
      } else if (action == 'remove') {
        state = removeTransaction(state, step[1] as String);
      }
      expectMatches(state['accounts'], entry['accounts'], 'accounts after $step');
      final ids =
          (state['transactions'] as List).map((t) => (t as Map)['id']).toList();
      expectMatches(ids, entry['txIds'], 'txIds after $step');
    }
  });

  test('balanceSign follows flow first, then type', () {
    expect(balanceSign({'type': 'expense', 'flow': 'in'}), 1);
    expect(balanceSign({'type': 'income', 'flow': 'out'}), -1);
    expect(balanceSign({'type': 'income'}), 1);
    expect(balanceSign({'type': 'expense'}), -1);
    expect(balanceSign({'type': 'transfer'}), -1);
    expect(balanceSign(null), -1);
  });
}
