// Replays flutter/test/goldens/loan_goldens.json, generated by executing
// the REAL mobile/lib/loan.js. Every payment, schedule row, and effective
// rate must match the live app to the centavo and the fourth decimal.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/loan.dart';

dynamic normalize(dynamic v) {
  if (v is num) return v.toDouble().isFinite ? v.toDouble() : null;
  if (v is Map) return v.map((k, x) => MapEntry(k.toString(), normalize(x)));
  if (v is List) return v.map(normalize).toList();
  return v;
}

void main() {
  final raw = jsonDecode(
      File('test/goldens/loan_goldens.json').readAsStringSync())
      as Map<String, dynamic>;

  test('loanSummary matches the RN engine on every vector', () {
    for (final c in (raw['summaries'] as List).cast<Map<String, dynamic>>()) {
      final args = c['args'] as List;
      final opts = (args[3] as Map).cast<String, dynamic>();
      final result = loanSummary(args[0], args[1], args[2],
          method: (opts['method'] ?? 'diminishing') as String,
          rateBasis: (opts['rateBasis'] ?? 'monthly') as String);
      expect(normalize(result), normalize(c['result']),
          reason: c['name'] as String);
    }
  });

  test('payoffSaving matches the RN engine', () {
    for (final c in (raw['payoffs'] as List).cast<Map<String, dynamic>>()) {
      final args = c['args'] as List;
      expect(normalize(payoffSaving(args[0], args[1], args[2], args[3])),
          normalize(c['result']),
          reason: c['name'] as String);
    }
  });

  test('effectiveMonthlyRate matches the RN bisection', () {
    for (final c in (raw['rates'] as List).cast<Map<String, dynamic>>()) {
      final args = c['args'] as List;
      expect(normalize(effectiveMonthlyRate(args[0], args[1], args[2])),
          normalize(c['result']),
          reason: c['name'] as String);
    }
    expect(maxMonths, raw['maxMonths']);
  });
}
