// Replays flutter/test/goldens/notecalc_goldens.json, generated by
// executing the REAL RN notes.js engine. Every expression, line analysis,
// and whole-note calculation must match the live app.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/notecalc.dart';

dynamic normalize(dynamic v) {
  if (v is num) return v.toDouble();
  if (v is Map) return v.map((k, x) => MapEntry(k.toString(), normalize(x)));
  if (v is List) return v.map(normalize).toList();
  return v;
}

void main() {
  final raw = jsonDecode(
      File('test/goldens/notecalc_goldens.json').readAsStringSync())
      as Map<String, dynamic>;

  test('evaluateMath matches the RN engine on every expression', () {
    for (final v in (raw['evaluateMath'] as List)) {
      final expected = v['value'];
      final actual = evaluateMath(v['text'] as String);
      expect(normalize(actual), normalize(expected),
          reason: 'expression "${v['text']}"');
    }
  });

  test('analyzeLine matches the RN engine on every line', () {
    for (final v in (raw['analyzeLine'] as List)) {
      final expected = (v['result'] as Map).cast<String, dynamic>();
      final actual = analyzeLine(v['text'] as String);
      expect(normalize(actual.value), normalize(expected['value']),
          reason: 'value of "${v['text']}"');
      expect(actual.bare, expected['bare'],
          reason: 'bare of "${v['text']}"');
    }
  });

  test('computeCalc matches the RN engine on every note', () {
    for (final entry in (raw['computeCalc'] as Map<String, dynamic>).entries) {
      final s = entry.value as Map<String, dynamic>;
      expect(normalize(computeCalc(s['text'])), normalize(s['calc']),
          reason: 'note ${entry.key}');
    }
  });
}
