// Replays flutter/test/goldens/pan_goldens.json, generated by executing the
// REAL RN Pan brain (normalize, intents, resolvers over the real engines,
// respond) plus monthRecap/recapText and daysUntilPayday/scheduleLabel.
// Every normalized string, detected intent, and whole reply must match the
// live app word for word and number for number.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/debtmath.dart' show formatMoneyText;
import 'package:salapify/money/pan/ask.dart';
import 'package:salapify/money/pan/intents.dart' show detectIntent;
import 'package:salapify/money/pan/normalize.dart';
import 'package:salapify/money/recap.dart';
import 'package:salapify/money/schedule.dart'
    show daysUntilPayday, scheduleLabel;

dynamic normalizeJson(dynamic v) {
  if (v is num) return v.toDouble().isFinite ? v.toDouble() : null;
  if (v is Map) {
    return v.map((k, x) => MapEntry(k.toString(), normalizeJson(x)));
  }
  if (v is List) return v.map(normalizeJson).toList();
  return v;
}

/// Replies carry no undefined-vs-missing distinction across JSON, so drop
/// null-valued optional keys on both sides before comparing.
Map<String, dynamic> tidyReply(Map<String, dynamic> reply) {
  final out = <String, dynamic>{};
  reply.forEach((k, v) {
    if (v != null) out[k] = normalizeJson(v);
  });
  return out;
}

void main() {
  final raw = jsonDecode(
      File('test/goldens/pan_goldens.json').readAsStringSync())
      as Map<String, dynamic>;
  final now = DateTime.parse(raw['nowISO'] as String);
  final fixtures = (raw['fixtures'] as Map).cast<String, dynamic>();

  test('every Pan case matches the RN brain end to end', () {
    for (final c in (raw['cases'] as List).cast<Map<String, dynamic>>()) {
      final message = c['message'] as String;
      final label = '${c['fixture']} | $message';
      expect(normalize(message), c['norm'], reason: 'norm: $label');
      expect(normalizeJson(extractAmount(message)),
          normalizeJson(c['amount']),
          reason: 'amount: $label');
      final det = detectIntent(normalize(message));
      final expectedDet = (c['detect'] as Map).cast<String, dynamic>();
      expect(det['id'], expectedDet['id'], reason: 'intent: $label');
      expect(normalizeJson(det['score']), normalizeJson(expectedDet['score']),
          reason: 'score: $label');
      expect(det['alternatives'], expectedDet['alternatives'],
          reason: 'alternatives: $label');
      final data =
          (fixtures[c['fixture']] as Map).cast<String, dynamic>();
      final reply = ask(data, message, now: now);
      expect(tidyReply(reply),
          tidyReply((c['reply'] as Map).cast<String, dynamic>()),
          reason: 'reply: $label');
    }
  });

  test('helpReply and the starter chips match the registry', () {
    expect(tidyReply(helpReply()),
        tidyReply((raw['help'] as Map).cast<String, dynamic>()));
    expect(tidyReply(helpReply(['balances', 'payday'])),
        tidyReply((raw['helpAlt'] as Map).cast<String, dynamic>()));
    expect(normalizeJson(suggestions(6)), normalizeJson(raw['chips']));
  });

  test('monthRecap and recapText match the RN module', () {
    final recaps = (raw['recaps'] as Map).cast<String, dynamic>();
    expect(
        normalizeJson(monthRecap(
            (fixtures['main'] as Map).cast<String, dynamic>(), now)),
        normalizeJson(recaps['main']));
    expect(normalizeJson(monthRecap(const {}, now)),
        normalizeJson(recaps['empty']));
    expect(
        normalizeJson(monthRecap({
          'transactions': [
            {'type': 'income', 'label': 'Sweldo', 'amount': 1000, 'date': '2026-07-02'},
            {'type': 'expense', 'label': 'Food', 'amount': 3000, 'date': '2026-07-03'},
          ],
        }, now)),
        normalizeJson(recaps['overspent']));
    final texts = (recaps['texts'] as Map).cast<String, dynamic>();
    final mainRecap =
        monthRecap((fixtures['main'] as Map).cast<String, dynamic>(), now);
    expect(recapText(mainRecap, formatMoneyText), texts['main']);
    expect(recapText(mainRecap, formatMoneyText, true), texts['mainHidden']);
    expect(recapText(monthRecap(const {}, now), formatMoneyText),
        texts['empty']);
  });

  test('daysUntilPayday and scheduleLabel match the RN module', () {
    for (final s in (raw['schedules'] as List).cast<Map<String, dynamic>>()) {
      expect(daysUntilPayday(now, s['schedule']), s['days'],
          reason: 'days: ${s['schedule']}');
      expect(scheduleLabel(s['schedule']), s['label'],
          reason: 'label: ${s['schedule']}');
    }
  });
}
