// Replays flutter/test/goldens/period_goldens.json, generated by executing the
// real mobile/lib/format.js.
//
// This is not money math, and it is locked as hard as money math is, because it
// decides WHICH money every total on a screen adds up. A period that quietly
// drops an entry makes the number wrong while it still looks right, which is
// the one failure mode nobody catches by looking.
//
// 360 membership checks: every period shape crossed with every date that sits
// on a boundary, plus the dateless and malformed ones a hand edited backup can
// carry.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/period.dart';

Period? _period(dynamic raw) {
  if (raw == null) return null;
  final m = (raw as Map).cast<String, dynamic>();
  return Period(
    mode: '${m['mode']}',
    ym: m['ym'] as String?,
    y: m['y'] as String?,
    from: m['from'] as String?,
    to: m['to'] as String?,
  );
}

/// The generator writes undefined as a sentinel, because JSON has no undefined
/// and the cases that produce one are exactly the cases worth pinning.
dynamic _value(dynamic v) => v == '__undefined__' ? null : v;

void main() {
  final g =
      jsonDecode(File('test/goldens/period_goldens.json').readAsStringSync())
          as Map<String, dynamic>;
  final refParts = (g['ref'] as String).split('-').map(int.parse).toList();
  final ref = DateTime(refParts[0], refParts[1], refParts[2]);

  test('every period is titled exactly as RN titles it', () {
    final cases = (g['labels'] as List).cast<Map<String, dynamic>>();
    expect(cases, isNotEmpty);
    for (final c in cases) {
      // RN returns undefined for a year period with no year, which renders as
      // nothing. Dart has no undefined, so the port returns '', which renders
      // as the same nothing. Said out loud rather than quietly compared away.
      final want = c['label'] == '__undefined__' ? '' : c['label'];
      expect(
        periodLabel(_period(c['period'])),
        want,
        reason: 'label for ${c['name']}',
      );
    }
  });

  test('every entry falls on the same side of every period as in RN', () {
    final cases = (g['membership'] as List).cast<Map<String, dynamic>>();
    expect(cases, isNotEmpty);
    var checks = 0;
    for (final c in cases) {
      final p = _period(c['period']);
      for (final row in (c['rows'] as List).cast<Map<String, dynamic>>()) {
        final date = _value(row['date']);
        expect(
          inPeriod(date, p),
          row['inside'],
          reason: 'date ${jsonEncode(row['date'])} against ${c['name']}',
        );
        checks++;
      }
    }
    expect(checks, greaterThan(300), reason: 'the fixture set shrank');
  });

  test('stepping a period lands where RN lands', () {
    final cases = (g['shifts'] as List).cast<Map<String, dynamic>>();
    expect(cases, isNotEmpty);
    for (final c in cases) {
      final got = shiftPeriod(_period(c['period']), c['delta'] as int);
      final want = _period(c['out']);
      expect(got?.mode, want?.mode, reason: '${c['name']} mode');
      expect(got?.ym, want?.ym, reason: '${c['name']} ym');
      expect(got?.y, want?.y, reason: '${c['name']} y');
    }
  });

  test('the forward stop is where RN puts it', () {
    final cases = (g['future'] as List).cast<Map<String, dynamic>>();
    expect(cases, isNotEmpty);
    for (final c in cases) {
      expect(
        periodIsFuture(_period(c['period']), ref),
        c['isFuture'],
        reason: 'future check for ${c['name']}',
      );
    }
  });

  test('a month boundary belongs to exactly one month', () {
    // Named separately so a regression says WHICH rule broke. The last day of
    // June and the first of July are the two entries a person actually
    // notices moving, because they are the ones that decide whether a payday
    // landed in the month they think it did.
    const june = Period.month('2026-06');
    const july = Period.month('2026-07');
    expect(inPeriod('2026-06-30', june), isTrue);
    expect(inPeriod('2026-06-30', july), isFalse);
    expect(inPeriod('2026-07-01', july), isTrue);
    expect(inPeriod('2026-07-01', june), isFalse);
  });

  test('a custom range includes both of its own end days', () {
    // An inclusive range is what a person means by "the 1st to the 15th", and
    // an off by one here silently drops a whole day of spending out of a
    // total the screen still presents as complete.
    const range = Period.custom(from: '2026-06-01', to: '2026-06-15');
    expect(inPeriod('2026-06-01', range), isTrue);
    expect(inPeriod('2026-06-15', range), isTrue);
    expect(inPeriod('2026-05-31', range), isFalse);
    expect(inPeriod('2026-06-16', range), isFalse);
  });

  test('an entry with no date is only ever in All time', () {
    for (final blank in [null, '', 0, false]) {
      expect(inPeriod(blank, const Period.all()), isTrue);
      expect(inPeriod(blank, const Period.month('2026-07')), isFalse);
      expect(inPeriod(blank, const Period.year('2026')), isFalse);
      expect(inPeriod(blank, const Period.custom()), isFalse);
    }
  });
}
