// The port contract test. test/goldens/phtax_goldens.json was generated by
// EXECUTING the RN engine (mobile/lib/phtax.js and thirteenth.js), so these
// assertions mean: the Dart money engine reproduces the shipping app's
// numbers to the centavo on 85 cases covering every bracket edge,
// contribution cap, both self-employed regimes, year-end annualization, and
// the 13th month. If a golden ever needs to change, the RN engine changed
// first and the vectors must be regenerated from it, never hand-edited.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/phtax.dart';
import 'package:salapify/money/thirteenth.dart';

void expectMatches(dynamic actual, dynamic golden, String path) {
  if (golden is num) {
    expect(actual, isA<num>(), reason: '$path should be a number');
    expect((actual as num).toDouble(), closeTo(golden.toDouble(), 1e-9),
        reason: path);
  } else if (golden is bool || golden is String) {
    expect(actual, equals(golden), reason: path);
  } else if (golden is Map) {
    expect(actual, isA<Map>(), reason: '$path should be a map');
    for (final key in golden.keys) {
      expectMatches((actual as Map)[key], golden[key], '$path.$key');
    }
    expect((actual as Map).keys.toSet(), equals(golden.keys.toSet().cast()),
        reason: '$path keys');
  } else {
    fail('$path: unhandled golden type ${golden.runtimeType}');
  }
}

void main() {
  final goldens = jsonDecode(
          File('test/goldens/phtax_goldens.json').readAsStringSync())
      as Map<String, dynamic>;

  test('annualIncomeTax matches the RN engine on every vector', () {
    for (final c in goldens['annualIncomeTax'] as List) {
      expectMatches(annualIncomeTax(c['input'] as num), c['out'],
          'annualIncomeTax(${c['input']})');
    }
  });

  test('marginalRate matches the RN engine on every vector', () {
    for (final c in goldens['marginalRate'] as List) {
      expectMatches(marginalRate(c['input'] as num), c['out'],
          'marginalRate(${c['input']})');
    }
  });

  test('contributionBreakdown matches the RN engine on every vector', () {
    for (final c in goldens['contributions'] as List) {
      expectMatches(contributionBreakdown(c['input'] as num), c['out'],
          'contributions(${c['input']})');
    }
  });

  test('takeHomePay matches the RN engine on every vector', () {
    for (final c in goldens['takeHomePay'] as List) {
      final opts = c['opts'] as Map<String, dynamic>;
      final out = takeHomePay(c['basic'] as num,
          taxableAllowance: (opts['taxableAllowance'] as num?) ?? 0,
          nonTaxableAllowance: (opts['nonTaxableAllowance'] as num?) ?? 0);
      expectMatches(out, c['out'], 'takeHomePay(${c['basic']}, $opts)');
    }
  });

  test('selfEmployedTax matches the RN engine on every vector', () {
    for (final c in goldens['selfEmployed'] as List) {
      final opts = c['opts'] as Map<String, dynamic>;
      final out = selfEmployedTax(c['gross'] as num,
          mixedIncome: (opts['mixedIncome'] as bool?) ?? false,
          useOSD: (opts['useOSD'] as bool?) ?? true,
          expenses: (opts['expenses'] as num?) ?? 0,
          salaryTaxable: (opts['salaryTaxable'] as num?) ?? 0);
      expectMatches(out, c['out'], 'selfEmployedTax(${c['gross']}, $opts)');
    }
  });

  test('annualizeCompensation matches the RN engine on every vector', () {
    for (final c in goldens['annualize'] as List) {
      final opts = c['opts'] as Map<String, dynamic>;
      final out = annualizeCompensation(c['basic'] as num,
          taxableAllowance: (opts['taxableAllowance'] as num?) ?? 0,
          monthsWorked: opts['monthsWorked'] as num?,
          bonuses: (opts['bonuses'] as num?) ?? 0,
          taxWithheld: (opts['taxWithheld'] as num?) ?? 0);
      expectMatches(out, c['out'], 'annualize(${c['basic']}, $opts)');
    }
  });

  test('thirteenthMonth matches the RN engine on every vector', () {
    for (final c in goldens['thirteenth'] as List) {
      final opts = c['opts'] as Map<String, dynamic>;
      final out = thirteenthMonth(c['basic'] as num,
          monthsWorked: opts['monthsWorked'] as num?,
          otherBenefits: (opts['otherBenefits'] as num?) ?? 0);
      expectMatches(out, c['out'], 'thirteenth(${c['basic']}, $opts)');
    }
  });

  test('the constants match the published values', () {
    expect(ratesYear, 2026);
    expect(bonusTaxFreeCeiling, 90000);
    expect(thirteenthTaxFreeCeiling, bonusTaxFreeCeiling);
    expect(percentageTaxRate, 0.03);
    expect(vatThreshold, 3000000);
    expect(selfEmployedExempt, 250000);
  });
}
