// Replays flutter/test/goldens/receivables_goldens.json, generated by
// scratchpad/gen-receivables-goldens.js executing the REAL RN receivables
// money logic (verbatim copies of the screen's postIncome, logPartial,
// markPaid, removePayment, save, and del wired to the AppData reducer
// semantics). The Dart engine must land on the exact same state: balances,
// transactions, payments, ids, everything.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/receivables.dart';

/// JSON numbers arrive as int where JS wrote a whole double; unify so 250
/// and 250.0 compare equal, exactly like the other golden suites.
dynamic normalize(dynamic v) {
  if (v is num) return v.toDouble();
  if (v is Map) return v.map((k, x) => MapEntry(k.toString(), normalize(x)));
  if (v is List) return v.map(normalize).toList();
  return v;
}

void main() {
  final raw = jsonDecode(
      File('test/goldens/receivables_goldens.json').readAsStringSync());
  final today = raw['today'] as String;
  final scenarios = (raw['scenarios'] as List).cast<Map<String, dynamic>>();

  for (final s in scenarios) {
    test('golden: ${s['name']}', () {
      var counter = 0;
      String genId(String prefix) => '${prefix}_g${counter++}';
      final initial = (s['initial'] as Map).cast<String, dynamic>();
      final name = s['name'] as String;

      Map<String, dynamic> after;
      dynamic result;
      if (name.startsWith('logPartial')) {
        final args = _argsFor(name);
        after = logPartial(initial, args.$1, args.$2,
            today: today, genId: genId);
      } else if (name.startsWith('markPaid')) {
        after = markPaid(initial, _targetFor(name),
            today: today, genId: genId);
      } else if (name.startsWith('removePayment')) {
        final t = name.contains('reopens')
            ? ('r4', 'old3')
            : ('r1', 'old1');
        after = removePayment(initial, t.$1, t.$2);
      } else if (name.startsWith('save')) {
        final form = _formFor(name);
        final r = saveReceivable(
          initial,
          id: form['id'] as String,
          person: form['person'] as String,
          amountText: form['amount'] as String,
          dueDate: form['dueDate'] as String,
          phone: form['phone'] as String,
          note: form['note'] as String,
          fromAccount: form['fromAccount'] as String,
          paid: form['paid'] as bool,
          today: today,
          genId: genId,
        );
        after = r.data;
        result = r.error != null ? {'error': r.error} : {'id': r.id};
      } else if (name.startsWith('delete')) {
        after = deleteReceivable(
            initial, name.contains('lend leg') ? 'r2' : 'r4');
      } else {
        fail('Unknown scenario: $name');
      }

      expect(normalize(after), normalize(s['after']),
          reason: 'state mismatch in "$name"');
      if (result != null) {
        expect(normalize(result), normalize(s['result']),
            reason: 'result mismatch in "$name"');
      }
    });
  }
}

// The generator passes fixed arguments per scenario; mirror them by name so
// the goldens file stays pure data.
(String, String) _argsFor(String name) {
  if (name.contains('default account')) return ('r1', '250');
  if (name.contains('clamps')) return ('r1', '9,999');
  if (name.contains('cashLeg')) return ('r2', '400');
  if (name.contains('zero remaining')) return ('r3', '50');
  return ('r1', 'abc');
}

String _targetFor(String name) {
  if (name.contains('nothing left')) return 'r3';
  if (name.contains('cashLeg')) return 'r2';
  return 'r1';
}

Map<String, dynamic> _formFor(String name) {
  final base = {
    'id': '',
    'person': '',
    'amount': '',
    'dueDate': '',
    'phone': '',
    'note': '',
    'fromAccount': '',
    'paid': false,
  };
  if (name.contains('creates utang and person')) {
    return {
      ...base,
      'person': '  Juan Cruz ',
      'amount': '750',
      'dueDate': '2026-08-01',
      'phone': '0999',
      'note': 'sa jeep',
    };
  }
  if (name.contains('case-insensitively')) {
    return {...base, 'person': 'ana', 'amount': '150', 'phone': '0918'};
  }
  if (name.contains('lending cash leg')) {
    return {...base, 'person': 'Migs', 'amount': '600', 'fromAccount': 'cash'};
  }
  if (name.contains('impossible date')) {
    return {
      ...base,
      'person': 'Lita',
      'amount': '100',
      'dueDate': '2026-02-30',
    };
  }
  if (name.contains('below what is paid')) {
    return {...base, 'id': 'r1', 'person': 'Migs', 'amount': '400'};
  }
  if (name.contains('paid toggle on')) {
    return {
      ...base,
      'id': 'r1',
      'person': 'Migs',
      'amount': '2000',
      'dueDate': '2026-07-04',
      'paid': true,
    };
  }
  // save reopen reverses only settled-tagged payments
  return {...base, 'id': 'r4', 'person': 'Migs', 'amount': '400'};
}
