// Replays flutter/test/goldens/statement_goldens.json, generated by executing
// the real mobile/lib/statement.js. Every case compares the WHOLE text, byte
// for byte, because this document goes to another person and every line of it
// is a claim about their money.
//
// The comparison is deliberately not "the totals match". A statement whose
// numbers are right but whose payment lines are in a different order, or
// which drops the reconciling "Marked paid" line, still reads as a different
// document to the friend holding it, and would still tie out.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/receivables.dart' show personPaymentHistory;
import 'package:salapify/money/statement.dart';

StatementLang _lang(String s) =>
    s == 'tl' ? StatementLang.tl : StatementLang.en;

void main() {
  final g =
      jsonDecode(File('test/goldens/statement_goldens.json').readAsStringSync())
          as Map<String, dynamic>;
  final asOfParts = (g['asOf'] as String).split('-').map(int.parse).toList();
  final asOf = DateTime(asOfParts[0], asOfParts[1], asOfParts[2]);

  test('every statement matches the RN text byte for byte', () {
    final cases = (g['statements'] as List).cast<Map<String, dynamic>>();
    expect(cases, isNotEmpty);
    for (final c in cases) {
      final got = buildPersonStatement(
        (c['person'] as Map?)?.cast<String, dynamic>(),
        c['receivables'],
        lang: _lang(c['lang'] as String),
        asOf: asOf,
      );
      expect(got, c['text'], reason: 'statement: ${c['name']}');
    }
  });

  test('every reminder matches the RN text byte for byte', () {
    final cases = (g['reminders'] as List).cast<Map<String, dynamic>>();
    expect(cases, isNotEmpty);
    for (final c in cases) {
      final got = buildPersonReminder(
        (c['person'] as Map?)?.cast<String, dynamic>(),
        c['owed'],
        lang: _lang(c['lang'] as String),
      );
      expect(got, c['text'], reason: 'reminder: ${c['name']}');
    }
  });

  test('the statement can never bill for money the app calls settled', () {
    // Named separately from the byte comparison so a regression says WHICH
    // rule broke. A paid utang with no logged payment is the case that
    // matters: the ledger shows nothing owed, and a statement that showed
    // ₱2,000 STILL OPEN would be the app accusing someone of not paying.
    final text = buildPersonStatement(
      {'name': 'Ben'},
      [
        {'id': 'r1', 'amount': 2000, 'paid': true},
      ],
      asOf: asOf,
    );
    expect(text, contains('FULLY PAID'));
    expect(text, contains('Marked paid   Utang   ₱2,000'));
    expect(text, isNot(contains('STILL OPEN')));
  });

  test(
    'total lent minus total paid is what the statement calls still open',
    () {
      // The promise the document makes to two people reading it together.
      final text = buildPersonStatement(
        {'name': 'Ana'},
        [
          {
            'id': 'r1',
            'amount': 5000,
            'payments': [
              {'id': 'p1', 'amount': 1200, 'date': '2026-07-01'},
            ],
          },
          {'id': 'r2', 'amount': 750},
        ],
        asOf: asOf,
      );
      expect(text, contains('Total lent: ₱5,750'));
      expect(text, contains('Total paid: ₱1,200'));
      expect(text, contains('STILL OPEN: ₱4,550'));
    },
  );

  test('the payment history matches the RN screen block, row for row', () {
    final cases = (g['history'] as List).cast<Map<String, dynamic>>();
    expect(cases, isNotEmpty);
    for (final c in cases) {
      final got = personPaymentHistory(c['receivables']);
      final want = (c['rows'] as List).cast<Map<String, dynamic>>();
      final label = 'history: ${c['name']}';
      expect(got.length, want.length, reason: '$label row count');
      for (var i = 0; i < want.length; i++) {
        expect(got[i].id, '${want[i]['id']}', reason: '$label row $i id');
        expect(got[i].rid, '${want[i]['rid']}', reason: '$label row $i rid');
        expect(got[i].date, want[i]['date'], reason: '$label row $i date');
        expect(got[i].from, want[i]['from'], reason: '$label row $i from');
        expect(
          got[i].amount,
          (want[i]['amount'] as num).toDouble(),
          reason: '$label row $i amount',
        );
        expect(
          got[i].running,
          (want[i]['running'] as num).toDouble(),
          reason: '$label row $i running total',
        );
      }
    }
  });

  test('a person with nothing recorded still gets a readable document', () {
    final text = buildPersonStatement({'name': 'Iris'}, const [], asOf: asOf);
    expect(text, contains('For: Iris'));
    expect(text, contains('Total lent: ₱0'));
    // Not FULLY PAID: nothing was ever lent, and telling someone they are
    // fully paid on a debt that never existed is a different sentence.
    expect(text, isNot(contains('FULLY PAID')));
  });
}
