// Replays flutter/test/goldens/surplus_goldens.json. The vectors were
// generated by executing the REAL RN analytics.js (safeToSpend,
// emergencyRunway, goalPace) inside the reference reconciliation, so
// nextPesoPlan's order of operations and every peso must match the live
// engines exactly. See scratchpad/gen-surplus-goldens.js.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/surplus.dart';

dynamic normalize(dynamic v) {
  if (v is num) return v.toDouble();
  if (v is Map) return v.map((k, x) => MapEntry(k.toString(), normalize(x)));
  if (v is List) return v.map(normalize).toList();
  return v;
}

void main() {
  final raw = jsonDecode(
          File('test/goldens/surplus_goldens.json').readAsStringSync())
      as Map<String, dynamic>;
  final ref = DateTime(2026, 7, 16, 12);
  final fixtures = raw['fixtures'] as Map<String, dynamic>;
  final cases = raw['cases'] as Map<String, dynamic>;

  for (final name in cases.keys) {
    test('nextPesoPlan matches the RN engines: $name', () {
      final data = (fixtures[name] as Map).cast<String, dynamic>();
      final got = nextPesoPlan(data, ref);
      expect(normalize(got), normalize(cases[name]), reason: name);
    });
  }
}
