// Replays flutter/test/goldens/taxdeadlines_goldens.json, generated by
// executing the real mobile/lib/taxdeadlines.js.
//
// The cases that earn their keep are the boundaries: a deadline dated TODAY
// reads as 0 days left rather than as missed, the list wraps across the year
// end, the 8% option drops the percentage tax rows, a count of 0 or 99 is
// clamped, and a junk date returns nothing rather than a wrong date. Getting
// any of those wrong tells someone their filing is past when it is not.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/taxdeadlines.dart';

String _iso(DateTime d) =>
    '${d.year.toString().padLeft(4, '0')}-'
    '${d.month.toString().padLeft(2, '0')}-'
    '${d.day.toString().padLeft(2, '0')}';

void main() {
  final g =
      jsonDecode(
            File('test/goldens/taxdeadlines_goldens.json').readAsStringSync(),
          )
          as Map<String, dynamic>;

  test('every RN deadline case matches, row for row', () {
    final cases = (g['cases'] as List).cast<Map<String, dynamic>>();
    expect(cases, isNotEmpty);
    for (final c in cases) {
      final input = c['in'] as Map<String, dynamic>;
      final want = (c['out'] as List).cast<Map<String, dynamic>>();
      final todayRaw = input['today'] as String;
      final label =
          'today=$todayRaw eight=${input['onEightPercent']} '
          'count=${input['count']}';

      // The null sentinel is the one place this port deliberately differs
      // from RN, so it is asserted here rather than skipped. JS coerces
      // new Date(null) to the epoch, so the golden for this row carries four
      // deadlines dated 1970. Reproducing that would put "Annual income tax,
      // April 15 1970" on a tax screen. Junk strings already return empty in
      // RN; null now behaves like the junk it is.
      if (todayRaw == '__null__') {
        expect(
          want.first['year'],
          1970,
          reason: 'the golden must still record what RN really does',
        );
        expect(
          taxDeadlines(null),
          isEmpty,
          reason: 'and Salapify must refuse to print a 1970 filing date',
        );
        continue;
      }
      final today = DateTime.tryParse(todayRaw);
      final got = taxDeadlines(
        today,
        onEightPercent: input['onEightPercent'] as bool,
        count: input['count'] as int,
      );

      expect(got.length, want.length, reason: 'row count for $label');
      for (var i = 0; i < want.length; i++) {
        expect(got[i].form, want[i]['form'], reason: '$label row $i form');
        expect(got[i].title, want[i]['title'], reason: '$label row $i title');
        expect(got[i].what, want[i]['what'], reason: '$label row $i what');
        expect(got[i].year, want[i]['year'], reason: '$label row $i year');
        expect(
          _iso(got[i].date),
          want[i]['date'],
          reason: '$label row $i date',
        );
        expect(
          got[i].daysLeft,
          want[i]['daysLeft'],
          reason: '$label row $i daysLeft',
        );
      }
    }
  });

  test('a deadline due today is upcoming, not missed', () {
    // Pulled out of the sweep so this names itself if it ever breaks. April 15
    // is the annual return; on the morning of the 15th it is due TODAY.
    final rows = taxDeadlines(DateTime(2026, 4, 15, 9, 30));
    expect(rows.first.daysLeft, 0);
    expect(rows.first.form, '1701 / 1701A');
    expect(deadlineDaysLabel(rows.first.daysLeft), 'Due today');
  });

  test('the 8 percent option drops the percentage tax rows', () {
    final rows = taxDeadlines(DateTime(2026, 1, 1), onEightPercent: true);
    expect(rows.any((r) => r.form == '2551Q'), isFalse);
    expect(rows.any((r) => r.form.startsWith('1701')), isTrue);
  });

  test('the labels read like a person talking', () {
    expect(deadlineDaysLabel(0), 'Due today');
    expect(deadlineDaysLabel(-3), 'Due today');
    expect(deadlineDaysLabel(1), 'Tomorrow');
    expect(deadlineDaysLabel(9), 'In 9 days');
    expect(deadlineDaysLabel(30), 'In 30 days');
    expect(deadlineDaysLabel(31), 'In about 1 month');
    expect(deadlineDaysLabel(95), 'In about 3 months');
  });
}
