// Replays flutter/test/goldens/transfer_goldens.json, generated by EXECUTING
// the real RN saveTransfer body out of mobile/app/accounts.js. Every centavo,
// every refusal message and every field of the record row is compared against
// what the live app actually produced, not against what the port intended.
//
// The cases that earn their keep are the coercion edges: JS Number() accepts
// "0x10", "+7" and ".5", turns "" and "   " into 0, and treats "1,2,3" as 123
// once the commas are stripped. A Dart port written from understanding gets
// at least three of those wrong, silently, in a direction that moves money.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/money/ledger.dart' show amountOf;
import 'package:salapify/money/transfers.dart';

/// num to double, non-finite to null, so a golden NaN and a Dart NaN compare
/// equal instead of NaN != NaN.
dynamic normalize(dynamic v) {
  if (v is num) {
    final d = v.toDouble();
    return d.isFinite ? d : null;
  }
  return v;
}

void main() {
  final g =
      jsonDecode(File('test/goldens/transfer_goldens.json').readAsStringSync())
          as Map<String, dynamic>;
  final today = g['today'] as String;
  final seedAccounts = (g['accounts'] as List).cast<Map<String, dynamic>>();

  Map<String, dynamic> freshData() => {
    'accounts': [for (final a in seedAccounts) Map<String, dynamic>.from(a)],
    'transactions': <Map<String, dynamic>>[],
  };

  test('every RN transfer case matches to the centavo', () {
    final cases = (g['cases'] as List).cast<Map<String, dynamic>>();
    expect(cases, isNotEmpty);
    for (final c in cases) {
      final input = c['in'] as Map<String, dynamic>;
      final expected = c['out'] as Map<String, dynamic>;
      final label =
          'amount=${jsonEncode(input['amount'])} '
          'from=${input['fromId']} to=${input['toId']}';

      final outcome = applyTransfer(
        freshData(),
        fromId: input['fromId'],
        toId: input['toId'],
        amountText: input['amount'],
        today: today,
        genId: () => 'txn_fixed',
      );

      final expectedError = expected['error'] as String;
      if (expectedError.isNotEmpty) {
        expect(outcome.ok, isFalse, reason: 'RN refused this one: $label');
        expect(outcome.error, expectedError, reason: label);
        continue;
      }

      expect(outcome.ok, isTrue, reason: 'RN accepted this one: $label');
      final data = outcome.data!;

      // The two balance writes, compared as the balances RN would have left.
      final writes = (expected['writes'] as List).cast<Map<String, dynamic>>();
      expect(writes, hasLength(2), reason: label);
      for (final w in writes) {
        final id = w['id'];
        final want = normalize((w['patch'] as Map<String, dynamic>)['balance']);
        final got = (data['accounts'] as List)
            .cast<Map<String, dynamic>>()
            .firstWhere((a) => a['id'] == id)['balance'];
        expect(normalize(got), want, reason: 'balance of $id after $label');
      }
      // Untouched accounts stay exactly as they were, including the junk and
      // negative balances: a transfer must never quietly clean up a row it
      // was not asked to touch.
      for (final a in seedAccounts) {
        if (writes.any((w) => w['id'] == a['id'])) continue;
        final got = (data['accounts'] as List)
            .cast<Map<String, dynamic>>()
            .firstWhere((x) => x['id'] == a['id'])['balance'];
        expect(got, a['balance'], reason: 'untouched ${a['id']} after $label');
      }

      // The one record row, field by field.
      final added = (expected['added'] as List).cast<Map<String, dynamic>>();
      expect(added, hasLength(1), reason: label);
      final wantRow = added.single;
      final gotRows = (data['transactions'] as List)
          .cast<Map<String, dynamic>>();
      expect(gotRows, hasLength(1), reason: label);
      final gotRow = gotRows.single;
      for (final key in wantRow.keys) {
        expect(
          normalize(gotRow[key]),
          normalize(wantRow[key]),
          reason: '$key of the record row after $label',
        );
      }
      // Never an accountId: the balances already moved, so a linked row would
      // move them a second time the day someone deletes it from History.
      expect(
        gotRow.containsKey('accountId'),
        isFalse,
        reason: 'the record row must not link an account: $label',
      );
    }
  });

  test('a signed radix literal is not a number, the way JS says', () {
    // QA found this one, and the goldens could not: they carry "0x10" but no
    // signed body, and int.tryParse accepts a sign INSIDE the digits. So
    // "0x+10" parsed as 16 and moved 16 pesos where the live app refuses.
    for (final bad in ['0x+10', '0x-10', '-0x10', '+0x10', '0x', '0b12']) {
      expect(
        transferAmount(bad).isNaN,
        isTrue,
        reason: 'JS Number("$bad") is NaN, so this must refuse',
      );
    }
    // And the wide ones JS answers with a double rather than giving up.
    expect(transferAmount('0xFFFFFFFFFFFFFFFF'), 1.8446744073709552e19);
  });

  test('a transfer never creates or destroys more than a rounding crumb', () {
    // The engine rounds each side independently, exactly as RN does, so a
    // balance carrying sub-centavo residue can shift the total by up to half
    // a centavo. That is faithful, not a bug, and it is worth an assertion so
    // a future edit cannot widen it into real money without saying so.
    final seedAccounts = (g['accounts'] as List).cast<Map<String, dynamic>>();
    // amountOf, not a cast: the fixture set deliberately carries a string
    // balance and an unreadable one, which is the whole reason those rows
    // exist. A cast here would fail on the fixtures rather than on the money.
    double totalOf(List rows) => rows.cast<Map<String, dynamic>>().fold(
      0.0,
      (t, a) => t + amountOf(a['balance']),
    );
    final before = totalOf(seedAccounts);
    for (final c in (g['cases'] as List).cast<Map<String, dynamic>>()) {
      if ((c['out'] as Map<String, dynamic>)['error'] != '') continue;
      final input = c['in'] as Map<String, dynamic>;
      final out = applyTransfer(
        {
          'accounts': [
            for (final a in seedAccounts) Map<String, dynamic>.from(a),
          ],
          'transactions': <Map<String, dynamic>>[],
        },
        fromId: input['fromId'],
        toId: input['toId'],
        amountText: input['amount'],
        today: today,
        genId: () => 'txn_fixed',
      );
      final after = totalOf(out.data!['accounts'] as List);
      expect(
        (after - before).abs(),
        lessThanOrEqualTo(0.005001),
        reason: 'total moved by more than a rounding crumb: $input',
      );
    }
  });

  test('the amount parse matches JS Number() on its own', () {
    // Pulled out of the case list so a parse divergence names itself rather
    // than showing up as a wrong balance three assertions later.
    for (final c in (g['cases'] as List).cast<Map<String, dynamic>>()) {
      final raw = (c['in'] as Map<String, dynamic>)['amount'];
      final out = c['out'] as Map<String, dynamic>;
      final added = (out['added'] as List).cast<Map<String, dynamic>>();
      if (added.isEmpty) continue;
      expect(
        transferAmount(raw),
        (added.single['amount'] as num).toDouble(),
        reason: 'transferAmount(${jsonEncode(raw)})',
      );
    }
  });
}
