#!/usr/bin/env bash
# The shipped manifest is not the source manifest.
#
# The source AndroidManifest.xml declares four permissions. The app actually
# ships more, because every plugin merges its own permissions, receivers, and
# providers into the final manifest at build time. Nobody sees that merged file
# unless they go looking, so a dependency bump can add a permission or export a
# component and no human would ever know.
#
# This reads the MERGED manifest out of a real build and holds it to an
# allowlist: the exact permissions we intend, the exact components we export,
# backup switched off with both rule files wired, and no cleartext. Anything
# unexpected fails the build and PRINTS what it was, so a new permission is a
# decision somebody makes on purpose, not a thing that arrives silently.
#
# The allowlists are typed sets on purpose (a promise, not a guess): a new
# permission reddens CI until a human adds it here, having decided it belongs.
#
# The extraction of the merged manifest happens in CI (only a real build has
# one). The LOGIC below is driven on the branch by
# flutter/test/merged_manifest_guard_test.dart, through every failure shape,
# because a workflow step can otherwise only be tested by shipping.
#
# Usage: check-merged-manifest.sh <merged-AndroidManifest.xml>
# Exit 0: the manifest matches the allowlists.  Exit 1: it does not, loudly.

set -u

MANIFEST="${1:-}"
if [ -z "$MANIFEST" ] || [ ! -f "$MANIFEST" ]; then
  echo "MANIFEST CHECK FAILED: no merged manifest at '${MANIFEST:-}'."
  echo "Nothing was verified, which must never read as a pass."
  exit 1
fi

# Every permission the app is allowed to ship. Update this ONLY when a new
# permission is a reviewed decision. INTERNET (updates + rate lookups),
# USE_BIOMETRIC + USE_FINGERPRINT (App Lock; local_auth_android merges the
# legacy pre-API-28 USE_FINGERPRINT alongside USE_BIOMETRIC, same biometric
# trust, no data leaves the phone), POST_NOTIFICATIONS + RECEIVE_BOOT_COMPLETED
# (reminders), VIBRATE (haptics), WAKE_LOCK + ACCESS_NETWORK_STATE +
# FOREGROUND_SERVICE (home-widget plumbing, unused by us but merged in).
ALLOWED_PERMS=(
  "android.permission.INTERNET"
  "android.permission.USE_BIOMETRIC"
  "android.permission.USE_FINGERPRINT"
  "android.permission.POST_NOTIFICATIONS"
  "android.permission.RECEIVE_BOOT_COMPLETED"
  "android.permission.VIBRATE"
  "android.permission.WAKE_LOCK"
  "android.permission.ACCESS_NETWORK_STATE"
  "android.permission.FOREGROUND_SERVICE"
  # App-scoped, signature-level, auto-generated by AndroidX Core to protect its
  # own dynamically-registered non-exported receivers. Not a capability the app
  # requests from the user and it never leaves the app's own signature; benign.
  "dev.icedamericano.salapify.DYNAMIC_RECEIVER_NOT_EXPORTED_PERMISSION"
)

# The only components allowed to be exported, by their short (last-segment)
# name. MainActivity is the launcher; YourNumberWidget is the home-screen tile
# receiver, exported so OEM launchers honor it. Everything else must be
# exported="false".
ALLOWED_EXPORTED=(
  "MainActivity"
  "YourNumberWidget"
)

# Collapse to one line so a pretty-printed or minified manifest reads the same.
FLAT=$(tr '\n' ' ' < "$MANIFEST" | tr -s ' ')

fail() {
  echo "MANIFEST CHECK FAILED: $1"
  exit 1
}

# Guard against being handed the wrong file. Every plugin emits its own merged
# LIBRARY manifest with no <application> element; checking one of those for
# app-level attributes (allowBackup, exported activities) would fail with a
# confusing message about the app when the real problem is the file selection.
case "$FLAT" in
  *'<application'*) ;;
  *) fail "this manifest has no <application> element, so it is a library manifest, not the app's merged manifest. The caller selected the wrong file (search flutter/build/app only)." ;;
esac

in_list() {
  local needle="$1"; shift
  local x
  for x in "$@"; do [ "$x" = "$needle" ] && return 0; done
  return 1
}

# 1. Permissions: every declared permission must be on the allowlist. Compare
# the FULL android:name value, not just the android.permission.* namespace: an
# OEM or custom permission (com.sec.android...badge, a ${applicationId}.permission
# .*, a C2DM permission) is exactly the kind a dependency merges in silently,
# and pre-filtering to one namespace would drop it before the allowlist saw it.
#
# Collect ALL unexpected permissions and report them together, so tuning the
# allowlist to a real merged build takes one round trip rather than one per
# permission.
unexpected_perms=""
while IFS= read -r perm; do
  [ -z "$perm" ] && continue
  in_list "$perm" "${ALLOWED_PERMS[@]}" || unexpected_perms="$unexpected_perms $perm"
done < <(grep -oE 'uses-permission[^>]*android:name="[^"]+"' <<<"$FLAT" \
  | sed -E 's/.*android:name="([^"]+)".*/\1/' | sort -u)
if [ -n "$unexpected_perms" ]; then
  fail "unexpected permission(s):$unexpected_perms . Add each to ALLOWED_PERMS with a reason, or remove the dependency that pulled it in."
fi

# 2. Exported components: every component tag carrying exported="true" must be
# on the allowlist, matched by its last name segment. Collect all, report once.
unexpected_exported=""
while IFS= read -r tag; do
  case "$tag" in
    *'android:exported="true"'*) ;;
    *) continue ;;
  esac
  name=$(grep -oE 'android:name="[^"]+"' <<<"$tag" | head -1 | sed -E 's/.*="([^"]+)".*/\1/')
  short="${name##*.}"
  in_list "$short" "${ALLOWED_EXPORTED[@]}" || unexpected_exported="$unexpected_exported $name"
done < <(grep -oE '<(activity|service|receiver|provider)[^>]*>' <<<"$FLAT")
if [ -n "$unexpected_exported" ]; then
  fail "exported component(s) not on the allowlist:$unexpected_exported . An exported component is reachable by other apps; add it to ALLOWED_EXPORTED only if that is intended."
fi

# 3. Backup posture, checked here too so the merged artifact itself proves it
# (backup_posture_test.dart checks the source; this checks the shipped file).
case "$FLAT" in
  *'android:allowBackup="false"'*) ;;
  *) fail "allowBackup is not false in the merged manifest; the ledger would be eligible for cloud backup." ;;
esac
case "$FLAT" in
  *'android:fullBackupContent="@xml/backup_rules"'*) ;;
  *) fail "fullBackupContent is not wired in the merged manifest (Android 11 backup rules)." ;;
esac
case "$FLAT" in
  *'android:dataExtractionRules="@xml/data_extraction_rules"'*) ;;
  *) fail "dataExtractionRules is not wired in the merged manifest (Android 12+ backup and transfer rules)." ;;
esac

# 4. Cleartext: an offline app that only talks HTTPS must never allow cleartext.
case "$FLAT" in
  *'android:usesCleartextTraffic="true"'*)
    fail "usesCleartextTraffic is true; the app must talk HTTPS only." ;;
esac

echo "MANIFEST CHECK PASSED: permissions, exported components, backup, and cleartext all match the allowlist."
exit 0
