import 'package:flutter/material.dart';

import '../../core/money/format.dart';
import '../../core/money/plan.dart';
import '../../design/tokens.dart';
import '../../design/type.dart';
import '../../features/debt/add_debt_sheet.dart';
import '../../features/info/info_dot.dart';
import '../../features/info/info_sheet.dart';
import '../../features/safe_to_spend/safe_to_spend_sheet.dart';
import '../../features/tax/business_tax_sheet.dart';
import '../../features/tax/tax_calculator_sheet.dart';
import '../../state/financial_state.dart';
import 'plan_segments.dart';

/// Plan, the prototype's fourth tab, from src/components/PlanScreen.tsx.
///
/// A HUB rather than a screen: eight segments reached from a grid of tiles.
/// The prototype uses the same shape, and it is the right one, because the
/// eight have almost nothing to do with each other beyond all being about the
/// future rather than the past.
///
/// Every figure comes out of core/money/plan.dart, which is locked to vectors
/// generated by running the prototype's own arithmetic.
class PlanScreen extends StatefulWidget {
  const PlanScreen({super.key, required this.state});

  final FinancialState state;

  @override
  State<PlanScreen> createState() => _PlanScreenState();
}

class _PlanScreenState extends State<PlanScreen> {
  PlanSegment _segment = PlanSegment.overview;

  void _open(PlanSegment s) => setState(() => _segment = s);
  void _back() => setState(() => _segment = PlanSegment.overview);

  @override
  Widget build(BuildContext context) {
    final Palette p = Palette.of(widget.state.theme);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        _Header(palette: p, segment: _segment, onBack: _back),
        Expanded(
          child: ListView(
            padding: const EdgeInsets.fromLTRB(
              Spacing.lg,
              Spacing.md,
              Spacing.lg,
              Spacing.xl,
            ),
            children: <Widget>[
              switch (_segment) {
                PlanSegment.overview => _Overview(
                  palette: p,
                  state: widget.state,
                  onOpen: _open,
                ),
                PlanSegment.budgets => BudgetsSegment(
                  palette: p,
                  state: widget.state,
                ),
                PlanSegment.bills => BillsSegment(
                  palette: p,
                  state: widget.state,
                ),
                PlanSegment.goals => GoalsSegment(
                  palette: p,
                  state: widget.state,
                ),
                PlanSegment.decisions => DecisionsSegment(
                  palette: p,
                  state: widget.state,
                  onOpenSafeToSpend: () =>
                      SafeToSpendSheet.show(context, widget.state),
                ),
                PlanSegment.trackers => TrackersSegment(
                  palette: p,
                  state: widget.state,
                ),
                PlanSegment.calculators => CalculatorsSegment(
                  palette: p,
                  onOpenTax: () => TaxCalculatorSheet.show(context, p),
                  onOpenBusiness: () => BusinessTaxSheet.show(context, p),
                  onOpenDebt: () => AddDebtSheet.show(context, p),
                  onOpenSafeToSpend: () =>
                      SafeToSpendSheet.show(context, widget.state),
                ),
                PlanSegment.academy => AcademySegment(palette: p),
              },
            ],
          ),
        ),
      ],
    );
  }
}

class _Header extends StatelessWidget {
  const _Header({
    required this.palette,
    required this.segment,
    required this.onBack,
  });

  final Palette palette;
  final PlanSegment segment;
  final VoidCallback onBack;

  @override
  Widget build(BuildContext context) {
    final bool isRoot = segment == PlanSegment.overview;

    return Padding(
      padding: const EdgeInsets.fromLTRB(
        Spacing.lg,
        Spacing.md,
        Spacing.lg,
        Spacing.sm,
      ),
      child: Row(
        children: <Widget>[
          // A BACK control rather than a row of eight tabs across the top.
          // Eight labels do not fit a phone, and the prototype's own answer is
          // the same: a grid you go into and come out of.
          if (!isRoot)
            Semantics(
              button: true,
              label: 'Back to Plan',
              child: InkWell(
                onTap: onBack,
                customBorder: const CircleBorder(),
                child: SizedBox(
                  width: 44,
                  height: 44,
                  child: Icon(
                    Icons.arrow_back,
                    size: 20,
                    color: palette.textSecondary,
                  ),
                ),
              ),
            ),
          Expanded(
            child: Column(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: <Widget>[
                Text(segment.title, style: AppType.title(palette)),
                const SizedBox(height: 2),
                Text(segment.kicker, style: AppType.caption(palette)),
              ],
            ),
          ),
        ],
      ),
    );
  }
}

/// The hub. Eight tiles, and every one of them goes somewhere.
class _Overview extends StatelessWidget {
  const _Overview({
    required this.palette,
    required this.state,
    required this.onOpen,
  });

  final Palette palette;
  final FinancialState state;
  final ValueChanged<PlanSegment> onOpen;

  @override
  Widget build(BuildContext context) {
    final List<BudgetStatus> budgets = computeBudgets(
      budgets: state.budgets,
      transactions: state.transactions,
      now: state.now,
    );
    final BudgetTotals totals = computeBudgetTotals(budgets);
    final UpcomingTotals bills = computeUpcomingTotals(state.upcoming);
    final List<GoalStatus> goals = computeGoals(state.goals);

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        // The headline answers the one question somebody opens Plan to ask.
        // A grid of eight doors with no number on it makes them open three
        // before finding out whether anything is wrong.
        _SummaryCard(
          palette: palette,
          totals: totals,
          onTap: () => onOpen(PlanSegment.budgets),
        ),
        const SizedBox(height: Spacing.md),

        // Two per row. Three is too narrow for these labels on a 320dp phone,
        // and one per row turns eight tiles into a scroll.
        for (int i = 0; i < PlanSegment.tiles.length; i += 2) ...<Widget>[
          // IntrinsicHeight, and it is load-bearing rather than tidy. A Row
          // with CrossAxisAlignment.stretch inside a scroll view has no
          // height to stretch TO, so the constraint goes infinite and the
          // whole screen throws. This repository has hit it before, in four
          // sheets at once. IntrinsicHeight measures the taller tile first,
          // which is what makes a pair of tiles match.
          IntrinsicHeight(
            child: Row(
              crossAxisAlignment: CrossAxisAlignment.stretch,
              children: <Widget>[
                Expanded(
                  child: _Tile(
                    palette: palette,
                    segment: PlanSegment.tiles[i],
                    badge: _badgeFor(
                      PlanSegment.tiles[i],
                      totals,
                      bills,
                      goals,
                    ),
                    onTap: () => onOpen(PlanSegment.tiles[i]),
                  ),
                ),
                const SizedBox(width: Spacing.sm),
                Expanded(
                  child: i + 1 < PlanSegment.tiles.length
                      ? _Tile(
                          palette: palette,
                          segment: PlanSegment.tiles[i + 1],
                          badge: _badgeFor(
                            PlanSegment.tiles[i + 1],
                            totals,
                            bills,
                            goals,
                          ),
                          onTap: () => onOpen(PlanSegment.tiles[i + 1]),
                        )
                      : const SizedBox.shrink(),
                ),
              ],
            ),
          ),
          const SizedBox(height: Spacing.sm),
        ],
      ],
    );
  }

  /// A live figure on the tile, so the hub says something rather than being
  /// eight identical doors.
  String? _badgeFor(
    PlanSegment s,
    BudgetTotals totals,
    UpcomingTotals bills,
    List<GoalStatus> goals,
  ) {
    switch (s) {
      case PlanSegment.budgets:
        if (totals.overCount > 0) {
          return totals.overCount == 1 ? '1 over' : '${totals.overCount} over';
        }
        if (totals.nearCount > 0) return '${totals.nearCount} to watch';
        return 'On track';
      case PlanSegment.bills:
        return formatPeso(bills.totalOut, showDecimals: false);
      case PlanSegment.goals:
        final int done = goals.where((GoalStatus g) => g.isComplete).length;
        return '$done of ${goals.length} done';
      case PlanSegment.overview:
      case PlanSegment.decisions:
      case PlanSegment.trackers:
      case PlanSegment.calculators:
      case PlanSegment.academy:
        return null;
    }
  }
}

class _SummaryCard extends StatelessWidget {
  const _SummaryCard({
    required this.palette,
    required this.totals,
    required this.onTap,
  });

  final Palette palette;
  final BudgetTotals totals;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(Radii.card),
      child: Container(
        width: double.infinity,
        padding: const EdgeInsets.all(Spacing.md),
        decoration: BoxDecoration(
          color: palette.surface,
          borderRadius: BorderRadius.circular(Radii.card),
          border: Border.all(color: palette.border),
        ),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: <Widget>[
            Row(
              children: <Widget>[
                Expanded(
                  child: Text(
                    'LEFT TO SPEND THIS MONTH',
                    style: AppType.kicker(palette),
                  ),
                ),
                InfoDot(
                  color: palette.textMuted,
                  semanticLabel: 'How budgets are counted',
                  onTap: () =>
                      InfoSheet.show(context, palette, InfoTopic.budgets),
                ),
              ],
            ),
            FittedBox(
              fit: BoxFit.scaleDown,
              alignment: Alignment.centerLeft,
              child: Text(
                formatPeso(totals.leftToSpend),
                style: AppType.hero(palette).copyWith(
                  color: totals.overCount > 0
                      ? palette.warning
                      : palette.positive,
                ),
              ),
            ),
            const SizedBox(height: 2),
            Text(
              '${formatPeso(totals.totalSpent)} of '
              '${formatPeso(totals.totalLimit)} used',
              style: AppType.caption(palette),
            ),
          ],
        ),
      ),
    );
  }
}

class _Tile extends StatelessWidget {
  const _Tile({
    required this.palette,
    required this.segment,
    required this.onTap,
    this.badge,
  });

  final Palette palette;
  final PlanSegment segment;
  final VoidCallback onTap;
  final String? badge;

  @override
  Widget build(BuildContext context) {
    return Semantics(
      button: true,
      label: segment.title,
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(Radii.card),
        child: Container(
          constraints: const BoxConstraints(minHeight: 44),
          padding: const EdgeInsets.all(Spacing.md),
          decoration: BoxDecoration(
            color: palette.surface,
            borderRadius: BorderRadius.circular(Radii.card),
            border: Border.all(color: palette.border),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: <Widget>[
              Container(
                width: 32,
                height: 32,
                decoration: BoxDecoration(
                  color: palette.iconTile,
                  borderRadius: BorderRadius.circular(Radii.control),
                ),
                child: Icon(segment.icon, size: 16, color: palette.accent),
              ),
              const SizedBox(height: Spacing.sm),
              Text(
                segment.title,
                maxLines: 2,
                overflow: TextOverflow.ellipsis,
                style: AppType.rowTitle(palette),
              ),
              const SizedBox(height: 2),
              Text(
                badge ?? segment.kicker,
                maxLines: 2,
                overflow: TextOverflow.ellipsis,
                style: AppType.caption(palette).copyWith(
                  color: badge == null ? palette.textMuted : palette.accent,
                  fontWeight: badge == null ? FontWeight.w500 : FontWeight.w700,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
