import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import '../../core/money/format.dart';
import '../../core/money/reports.dart' show assetKinds, liabilityKinds;
import '../../design/tokens.dart';
import '../../design/type.dart';
import '../../models/models.dart';
import '../../state/financial_state.dart';
import '../shared/sheet_scaffold.dart';
import 'package:salapify/core/money/money.dart';

/// Moving money between your own accounts.
///
/// Ported from `src/components/TransferModal.tsx` on founder direction,
/// 2026-10-01 ("Migrate bills and move quick actions"), which replaces the
/// "Move is not migrated yet" placeholder on Home's shortcut row.
///
/// THERE IS NO NEW ARITHMETIC HERE, and that is worth saying plainly because
/// a screen that moves money usually means a money port. The transfer rule
/// (the source falls, the destination rises, net worth does not change) was
/// ported and vector-locked long ago in `core/money/ledger.dart`'s
/// `applyToBalances`, against vectors generated by running the prototype's
/// own `addTransaction`. This sheet decides WHICH accounts and HOW MUCH and
/// then hands a Transaction to the store. It must never compute a balance.
///
/// ## The one thing this screen exists to make impossible
///
/// `applyToBalances` carries a preserved quirk, named in its own comment: a
/// transfer whose destination id matches no account debits the source and
/// credits nobody, so the money leaves net worth and arrives nowhere. The
/// vectors lock that because it is what the prototype does, and the comment
/// says the defence has to live in the UI: "a destination is picked from the
/// account list and cannot be the source. If a caller ever manages to produce
/// it, that is a bug in the caller."
///
/// This is that caller. Both ends are dropdowns over the real account list,
/// the save is refused when they are equal, and `move_money_journey_test.dart`
/// asserts the money arrives rather than merely that net worth held, because
/// net worth holds perfectly when nothing happens at all.
class MoveMoneySheet extends StatefulWidget {
  const MoveMoneySheet({super.key, required this.palette, required this.state});

  final Palette palette;
  final FinancialState state;

  static Future<bool?> show(
    BuildContext context, {
    required Palette palette,
    required FinancialState state,
  }) {
    return SheetScaffold.show<bool>(
      context: context,
      palette: palette,
      builder: (BuildContext context) =>
          MoveMoneySheet(palette: palette, state: state),
    );
  }

  @override
  State<MoveMoneySheet> createState() => _MoveMoneySheetState();
}

class _MoveMoneySheetState extends State<MoveMoneySheet> {
  final TextEditingController _amount = TextEditingController();
  final TextEditingController _note = TextEditingController();

  String? _fromId;
  String? _toId;
  late DateTime _date;

  /// Accounts somebody can actually move money between.
  ///
  /// EVERY LIABILITY IS EXCLUDED FROM BOTH ENDS, and this is a divergence
  /// from the prototype, which offers every account in both dropdowns.
  ///
  /// THE ARITHMETIC REASON FOR THIS IS GONE, and the rest of this comment
  /// used to be it. It said that "move 5,000 from GCash to the credit card"
  /// and "pay 5,000 off the credit card" were opposite instructions to
  /// `applyToBalances`, which "would ADD 5,000 to what is owed and call it an
  /// arrival". That was true and is now false: `signedDelta` reads the
  /// account's kind on both legs, so a transfer INTO a liability subtracts
  /// from what is owed, which is exactly what the person meant. The engine
  /// pays a card down correctly today and every one of the hundred
  /// source-to-destination pairs is asserted in
  /// `test/core/money/balance_direction_test.dart`.
  ///
  /// WHAT KEEPS THE FILTER IS NOW A PRODUCT DECISION, not a defence against
  /// the engine. Opening this dropdown to liabilities is how a credit card
  /// finally becomes payable, and it needs its own copy, an overpayment
  /// warning, and an answer to what a card payment does to the Financing
  /// section of Cash flow, which reads `type == expense` and would show zero.
  /// Until that is designed the door stays shut, and this paragraph exists so
  /// nobody reopens it believing the sums are still wrong.
  ///
  /// This started as `kind != credit`, which left the loan and the mortgage
  /// in. The journey test found it by accident: `find.textContaining('BPI')`
  /// matched four seed accounts, and the one it picked was BPI Gadget Loan.
  /// A test looking for something else is how that was caught, so the rule is
  /// now derived from `assetKinds` rather than typed out, because a typed
  /// list is a second copy of a decision and the two drift.
  ///
  /// Receivables come out as well. Money owed TO you is not somewhere you can
  /// send money, and recording a repayment is the Debt screen's job too.
  /// WHERE MONEY CAN LEAVE FROM. Unchanged: things you own, minus
  /// receivables.
  List<Account> get _sources => widget.state.accounts
      .where(
        (Account a) =>
            assetKinds.contains(a.kind) && a.kind != AccountKind.receivable,
      )
      .toList();

  /// WHERE MONEY CAN ARRIVE. The sources, plus everything you OWE.
  ///
  /// This is how a credit card finally gets paid, and it opened on 2026-10-05
  /// rather than earlier because until then the engine would have got it
  /// backwards. `signedDelta` now reads the account's kind on both legs, so a
  /// transfer into a liability subtracts from what is owed, which is what the
  /// person meant all along. All one hundred source-to-destination pairs are
  /// asserted in `test/core/money/balance_direction_test.dart`.
  ///
  /// RECEIVABLES STAY OUT OF BOTH ENDS, and that half of the old rule is
  /// still true: money owed TO you is not somewhere you can send money, and
  /// recording a repayment is the Debt screen's job.
  ///
  /// Derived from `liabilityKinds` rather than typed out, for the reason the
  /// source list already gives: a typed list is a second copy of a decision
  /// and the two drift.
  List<Account> get _destinations => widget.state.accounts
      .where(
        (Account a) =>
            (assetKinds.contains(a.kind) && a.kind != AccountKind.receivable) ||
            liabilityKinds.contains(a.kind),
      )
      .toList();

  Account? get _from =>
      _sources.where((Account a) => a.id == _fromId).firstOrNull;
  Account? get _to =>
      _destinations.where((Account a) => a.id == _toId).firstOrNull;

  /// True when this move is a payment against something owed rather than a
  /// move between two pockets. It changes the words, never the arithmetic.
  bool get _paysDebt {
    final Account? to = _to;
    return to != null && liabilityKinds.contains(to.kind);
  }

  @override
  void initState() {
    super.initState();
    // The store's clock, not DateTime.now(), so a test can pin today and so
    // the date shown here agrees with every other date in the app.
    _date = widget.state.now;
    // The default DESTINATION comes from the sources, not from every
    // possible destination: opening the sheet already pointing at a credit
    // card would make paying one the default move, which it is not.
    final List<Account> accounts = _sources;
    _fromId = accounts.isNotEmpty ? accounts.first.id : null;
    _toId = accounts.length > 1 ? accounts[1].id : null;
  }

  @override
  void dispose() {
    _amount.dispose();
    _note.dispose();
    super.dispose();
  }

  /// The chosen day as the app stores one, which is also what every date
  /// helper in core/money/format.dart takes.
  String get _iso =>
      '${_date.year}-${_date.month.toString().padLeft(2, '0')}-'
      '${_date.day.toString().padLeft(2, '0')}';

  double get _value {
    // The prototype strips commas before parseFloat, because its own preset
    // buttons write a plain number but a person types "1,000".
    final double? v = double.tryParse(_amount.text.replaceAll(',', '').trim());
    return v == null || !v.isFinite ? 0 : v;
  }

  /// Why the move cannot be saved, and whether that is the person's MISTAKE
  /// or simply a form they have not finished.
  ///
  /// The split matters, and it exists because the first version of this sheet
  /// got it wrong in a way a test caught. There was one `_refusal` getter, the
  /// button was disabled whenever it returned anything, and the message was
  /// only written onto the screen inside `_save`. `_save` can never run while
  /// the button is disabled, so every reason was unreachable: picking the same
  /// account at both ends greyed the button out and said NOTHING about why.
  ///
  /// So the reason is now always on the screen when there is one, and the two
  /// kinds are told apart because they deserve different volumes. "You have
  /// not typed an amount" is not an error and must not be shouted on a sheet
  /// somebody just opened. "These are the same account" is a real mistake and
  /// gets the panel.
  ({String message, bool isMistake})? get _blocker {
    if (_fromId == null || _toId == null) {
      return (
        message: 'Pick the account the money leaves and the one it arrives in.',
        isMistake: false,
      );
    }
    if (_fromId == _toId) {
      return (
        message:
            'Pick two different accounts. Money cannot move to where it '
            'already is.',
        isMistake: true,
      );
    }
    if (_value <= 0) {
      return (message: 'Enter how much to move.', isMistake: false);
    }
    final Account? from = _from;
    if (from != null &&
        from.kind == AccountKind.cash &&
        from.balance < Money.fromDouble(_value)) {
      return (
        message:
            'There is only ${formatPeso(from.balance.pesos)} in ${from.name}.',
        isMistake: true,
      );
    }
    return null;
  }

  /// A warning, NOT a refusal, and the difference is deliberate.
  ///
  /// The prototype blocks an overdraft on a `cash` account only, so a bank or
  /// e-wallet can be sent below zero with nothing said. Blocking those too
  /// would be the safer-looking change and the wrong one: a person who knows
  /// their balance is stale, or who is recording a move that already happened
  /// in the real world, has every right to record it. So the app says what
  /// will happen and still lets them do it.
  ///
  /// Cash keeps the hard block because physical cash cannot go negative. You
  /// cannot hand somebody money you are not holding.
  String? get _warning {
    final Account? from = _from;
    if (from == null || _value <= 0) return null;

    // PAYING MORE THAN IS OWED, which became reachable the day this sheet
    // started offering liabilities. A warning and never a refusal, for the
    // reason the paragraph above gives: somebody whose stored balance is
    // stale, or who is recording a payment that already left their bank, has
    // every right to record it.
    //
    // The extra is not an error to round away. A card in credit is real
    // money the bank is holding, and `Money` keeps the sign, so the figure
    // stays correct even though it is unusual.
    final Account? to = _to;
    if (to != null &&
        liabilityKinds.contains(to.kind) &&
        Money.fromDouble(_value) > to.balance) {
      return 'That is '
          '${formatPeso((Money.fromDouble(_value) - to.balance).pesos)} more '
          'than you owe on ${to.name}. The extra stays on the card as money '
          'the bank is holding for you.';
    }

    if (from.kind == AccountKind.cash) return null;
    if (from.balance >= Money.fromDouble(_value)) return null;
    return 'This takes ${from.name} below zero, to '
        '${formatPeso((from.balance - Money.fromDouble(_value)).pesos)}.';
  }

  void _swap() {
    setState(() {
      final String? old = _fromId;
      _fromId = _toId;
      _toId = old;
    });
  }

  void _save() {
    // Belt and braces. The button is already disabled while [_blocker] has
    // anything to say, so this is unreachable from the UI, and it stays
    // because the alternative to an unreachable guard is a reachable write
    // that moves money it should not.
    if (_blocker != null) return;

    final Account from = _from!;
    final Account to = _to!;
    final String note = _note.text.trim();

    widget.state.logTransaction(
      Transaction(
        id: 'tx_move_${DateTime.now().microsecondsSinceEpoch}',
        type: TransactionType.transfer,
        amount: Money.fromDouble(_value),
        // The prototype's own category string. The ledger's totals skip
        // transfers entirely, so this never lands in a spending summary; it
        // is what the Activity row and the category filter read.
        category: 'Transfer',
        accountId: from.id,
        toAccountId: to.id,
        merchant: 'Transfer: ${from.name} to ${to.name}',
        note: note.isEmpty ? null : note,
        date: _iso,
        createdAt: DateTime.now().millisecondsSinceEpoch,
      ),
    );

    Navigator.of(context).pop(true);
  }

  Future<void> _pickDate() async {
    final DateTime today = widget.state.now;
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: _date,
      firstDate: DateTime(today.year - 5),
      // Not the future, matching the Log sheet. The balance moves the moment
      // this is saved, so a move dated next week would be a balance that
      // already changed and a row claiming it has not happened yet.
      lastDate: today,
    );
    if (picked != null) setState(() => _date = picked);
  }

  @override
  Widget build(BuildContext context) {
    final Palette p = widget.palette;
    // THE EMPTY STATE IS JUDGED ON DESTINATIONS, which is wider than sources
    // now. Somebody holding one bank account and one credit card can pay the
    // card, so this sheet has work to do for them, where before it would have
    // told them to go and add a second account.
    final List<Account> accounts = _destinations;

    if (accounts.length < 2 || _sources.isEmpty) {
      return SheetScaffold(
        palette: p,
        icon: Icons.swap_horiz,
        title: 'Move money',
        subtitle: 'Between your own accounts',
        child: Padding(
          padding: const EdgeInsets.only(top: Spacing.lg),
          child: Text(
            accounts.isEmpty
                ? 'There are no accounts to move money between yet. Add one '
                      'on the Accounts tab first.'
                : 'Moving money needs somewhere for it to go. Add a second '
                      'account on the Accounts tab first.',
            style: AppType.body(p),
          ),
        ),
      );
    }

    final String? warning = _warning;
    final ({String message, bool isMistake})? blocker = _blocker;

    return SheetScaffold(
      palette: p,
      icon: Icons.swap_horiz,
      title: 'Move money',
      subtitle: 'Between your own accounts',
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          if (blocker != null && blocker.isMistake) ...<Widget>[
            _Notice(
              palette: p,
              text: blocker.message,
              tone: _NoticeTone.refusal,
            ),
            const SizedBox(height: Spacing.md),
          ],

          _AccountPicker(
            palette: p,
            label: 'Money leaves',
            accounts: _sources,
            selected: _fromId,
            onChanged: (String v) => setState(() {
              _fromId = v;
            }),
          ),
          const SizedBox(height: Spacing.xs),
          // THE SWAP DISAPPEARS WHEN THE DESTINATION IS SOMETHING YOU OWE,
          // because the reverse of paying a card is taking a cash advance on
          // it, and Salapify does not record one. A cash advance carries its
          // own fee and its own interest clock, usually from the day it is
          // taken rather than from the statement date, and an app that let
          // somebody log one as a plain transfer would be quietly
          // understating what it costs. A control that produces a wrong entry
          // is worse than no control.
          if (!_paysDebt) ...<Widget>[
            Align(
              alignment: Alignment.centerRight,
              child: Semantics(
                button: true,
                label: 'Swap the two accounts',
                child: InkWell(
                  onTap: _swap,
                  borderRadius: BorderRadius.circular(Radii.control),
                  child: Container(
                    constraints: const BoxConstraints(
                      minWidth: 44,
                      minHeight: 44,
                    ),
                    alignment: Alignment.center,
                    child: Icon(Icons.swap_vert, size: 20, color: p.accent),
                  ),
                ),
              ),
            ),
            const SizedBox(height: Spacing.xs),
          ] else
            const SizedBox(height: Spacing.sm),
          _AccountPicker(
            palette: p,
            // The label carries the whole difference. "Money arrives" is
            // wrong for a card: nothing arrives anywhere, a debt gets smaller.
            label: _paysDebt ? 'Pays down' : 'Money arrives',
            accounts: _destinations,
            selected: _toId,
            onChanged: (String v) => setState(() {
              _toId = v;
            }),
          ),
          const SizedBox(height: Spacing.lg),

          SheetField(
            palette: p,
            label: 'How much',
            controller: _amount,
            prefix: '₱ ',
            hint: '0.00',
            keyboardType: const TextInputType.numberWithOptions(decimal: true),
            inputFormatters: <TextInputFormatter>[
              FilteringTextInputFormatter.allow(RegExp(r'[0-9.,]')),
            ],
            onChanged: (_) => setState(() {}),
          ),
          const SizedBox(height: Spacing.sm),
          _Presets(
            palette: p,
            // The prototype's own four, plus its Max, which it shows only
            // when the source actually holds something.
            amounts: const <double>[500, 1000, 2000, 5000],
            maxAmount: (_from?.balance ?? Money.zero).isPositive
                ? _from!.balance.pesos
                : null,
            onPick: (double v) => setState(() {
              _amount.text = v.toStringAsFixed(2);
            }),
          ),

          if (warning != null) ...<Widget>[
            const SizedBox(height: Spacing.md),
            _Notice(palette: p, text: warning, tone: _NoticeTone.warning),
          ],

          const SizedBox(height: Spacing.lg),
          Text('When', style: AppType.label(p)),
          const SizedBox(height: Spacing.xs),
          Semantics(
            button: true,
            label: 'Change the date, currently ${formatDateLabel(_iso)}',
            child: InkWell(
              onTap: _pickDate,
              borderRadius: BorderRadius.circular(Radii.control),
              child: Container(
                width: double.infinity,
                constraints: const BoxConstraints(minHeight: 48),
                padding: const EdgeInsets.symmetric(
                  horizontal: Spacing.md,
                  vertical: Spacing.sm,
                ),
                decoration: BoxDecoration(
                  color: p.card,
                  borderRadius: BorderRadius.circular(Radii.control),
                  border: Border.all(color: p.border),
                ),
                child: Row(
                  children: <Widget>[
                    Expanded(
                      child: Text(
                        formatDateLabel(_iso, now: widget.state.now),
                        style: AppType.body(p),
                      ),
                    ),
                    Text(
                      'Change',
                      style: AppType.body(p).copyWith(color: p.accent),
                    ),
                  ],
                ),
              ),
            ),
          ),
          const SizedBox(height: Spacing.lg),

          SheetField(
            palette: p,
            label: 'Note (optional)',
            controller: _note,
            hint: 'Cash in for dinner',
            keyboardType: TextInputType.text,
          ),

          const SizedBox(height: Spacing.lg),
          PrimaryButton(
            palette: p,
            // "Pay it", never "Pay it off", which promises the balance
            // reaches zero and is wrong for every partial payment.
            label: _paysDebt ? 'Pay it' : 'Move it',
            icon: _paysDebt ? Icons.credit_score : Icons.swap_horiz,
            onTap: blocker == null ? _save : null,
          ),
          const SizedBox(height: Spacing.sm),
          Text(
            // A disabled button always says why it is disabled. The unfinished
            // reasons live here rather than in the panel above, because a
            // sheet that opens shouting "enter an amount" at somebody who has
            // been looking at it for half a second is nagging, not helping.
            //
            // When nothing is blocking, this is the sentence that stops the
            // support question: a transfer is in neither the money-in nor the
            // money-out total by design, and somebody who has just moved 5,000
            // and sees their spending unchanged needs telling on purpose
            // rather than left to wonder whether it saved.
            blocker != null && !blocker.isMistake
                ? blocker.message
                : _paysDebt
                // BOTH HALVES STOP A WRONG CONCLUSION, so both stay on the
                // screen rather than going behind a dot. The first answers
                // "am I poorer now", which somebody sending 5,000 away
                // reasonably wonders. The second answers "why did my spending
                // not go up", which they will check next. Paying a debt is
                // the one money movement that feels like spending and is not:
                // less cash and less owed, by exactly the same amount.
                ? 'Your net worth does not change. Less cash, and less owed '
                      'by exactly the same amount. This is not spending, so '
                      'it will not appear in what you spent this month.'
                : 'Your net worth does not change. This is not spending, so '
                      'it will not appear in what you spent this month.',
            style: AppType.caption(p),
          ),
        ],
      ),
    );
  }
}

/// One end of the move.
class _AccountPicker extends StatelessWidget {
  const _AccountPicker({
    required this.palette,
    required this.label,
    required this.accounts,
    required this.selected,
    required this.onChanged,
  });

  final Palette palette;
  final String label;
  final List<Account> accounts;
  final String? selected;
  final ValueChanged<String> onChanged;

  @override
  Widget build(BuildContext context) {
    return DropdownButtonFormField<String>(
      initialValue: accounts.any((Account a) => a.id == selected)
          ? selected
          : null,
      isExpanded: true,
      decoration: InputDecoration(
        labelText: label,
        labelStyle: AppType.label(palette),
        border: OutlineInputBorder(
          borderRadius: BorderRadius.circular(Radii.control),
        ),
      ),
      items: <DropdownMenuItem<String>>[
        for (final Account a in accounts)
          DropdownMenuItem<String>(
            value: a.id,
            // The balance sits beside the name on purpose: picking the
            // account money leaves is the moment somebody needs to know
            // whether there is enough in it.
            child: Text(
              '${a.name}  ${formatPeso(a.balance.pesos)}',
              style: AppType.body(palette),
              overflow: TextOverflow.ellipsis,
            ),
          ),
      ],
      onChanged: (String? v) {
        if (v != null) onChanged(v);
      },
    );
  }
}

class _Presets extends StatelessWidget {
  const _Presets({
    required this.palette,
    required this.amounts,
    required this.maxAmount,
    required this.onPick,
  });

  final Palette palette;
  final List<double> amounts;
  final double? maxAmount;
  final ValueChanged<double> onPick;

  @override
  Widget build(BuildContext context) {
    // Wrap, not Row. Five chips do not fit across a 320dp phone, and a Row
    // would overflow rather than fold.
    return Wrap(
      spacing: Spacing.sm,
      runSpacing: Spacing.sm,
      children: <Widget>[
        for (final double a in amounts)
          _Chip(palette: palette, label: formatPeso(a), onTap: () => onPick(a)),
        if (maxAmount != null)
          _Chip(
            palette: palette,
            label: 'All of it',
            onTap: () => onPick(maxAmount!),
          ),
      ],
    );
  }
}

class _Chip extends StatelessWidget {
  const _Chip({
    required this.palette,
    required this.label,
    required this.onTap,
  });

  final Palette palette;
  final String label;
  final VoidCallback onTap;

  @override
  Widget build(BuildContext context) {
    return Semantics(
      button: true,
      child: InkWell(
        onTap: onTap,
        borderRadius: BorderRadius.circular(Radii.control),
        child: Container(
          // NO `alignment` HERE, and that is the whole comment.
          //
          // A Container given an alignment and no width expands to fill
          // everything it is offered. Inside a Wrap that is the Wrap's full
          // width, so every chip became its own full-width row and the four
          // presets drew as a stack of bars. This repository has documented
          // that trap seven times; the first version of this widget carried a
          // comment naming it and did it anyway, and only the render showed
          // it. Height comes from the padding instead, which is what keeps
          // the 44dp touch target without claiming any width.
          padding: const EdgeInsets.symmetric(
            horizontal: Spacing.md,
            vertical: Spacing.sm + 2,
          ),
          decoration: BoxDecoration(
            color: palette.surface,
            borderRadius: BorderRadius.circular(Radii.control),
            border: Border.all(color: palette.border),
          ),
          child: Text(
            label,
            style: AppType.body(palette).copyWith(fontSize: 13),
          ),
        ),
      ),
    );
  }
}

enum _NoticeTone { refusal, warning }

class _Notice extends StatelessWidget {
  const _Notice({
    required this.palette,
    required this.text,
    required this.tone,
  });

  final Palette palette;
  final String text;
  final _NoticeTone tone;

  @override
  Widget build(BuildContext context) {
    final Color tint = tone == _NoticeTone.refusal
        ? palette.negativeSoft
        : palette.warningSoft;

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(Spacing.md),
      decoration: BoxDecoration(
        color: tint,
        borderRadius: BorderRadius.circular(Radii.control),
        border: Border.all(color: palette.border),
      ),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Icon(
            tone == _NoticeTone.refusal
                ? Icons.error_outline
                : Icons.warning_amber_outlined,
            size: 18,
            color: palette.textPrimary,
          ),
          const SizedBox(width: Spacing.sm),
          Expanded(
            // The PRIMARY ink, not the caption colour. Caption on a tinted
            // panel measured 4.29 to 1 in Gabi against the 4.5 floor when the
            // business guide did this, and the contrast sweep cannot catch it
            // because the sweep only lists pairs the app already draws.
            child: Text(text, style: AppType.body(palette)),
          ),
        ],
      ),
    );
  }
}
