import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/core/money/notes_calculator.dart';

/// Locked to vectors generated by running the PROTOTYPE'S OWN
/// `parseNotesCalculator` under node, not by reading its regex.
///
/// Three of the cases below are behaviours a careful reading would have got
/// wrong, which is the whole argument for generating rather than deriving:
/// a label may itself contain digits, a trailing operator makes a line
/// INVALID rather than zero, and a peso sign is stripped from the expression
/// while staying in the label.
void main() {
  group('the prototype vectors', () {
    test('the default notepad comes to 4,248', () {
      final NotesResult r = parseNotes('''
ate 50
kuya 600
mama 6*8
electricity 1250
groceries 1850 + 450''');

      expect(r.grandTotal, 4248);
      expect(r.items.map((NoteLine i) => i.label), <String>[
        'ate',
        'kuya',
        'mama',
        'electricity',
        'groceries',
      ]);
      expect(r.items.map((NoteLine i) => i.value), <double>[
        50,
        600,
        48,
        1250,
        2300,
      ]);
      expect(r.items.every((NoteLine i) => i.isValid), isTrue);
    });

    test('blank lines are skipped entirely', () {
      final NotesResult r = parseNotes('ate 50\n\n\nkuya 600');
      expect(r.grandTotal, 650);
      expect(r.items.length, 2);
    });

    test('a bare number is labelled Item', () {
      final NotesResult r = parseNotes('500');
      expect(r.items.single.label, 'Item');
      expect(r.grandTotal, 500);
    });

    test('a line with no number is kept, invalid, and counts nothing', () {
      final NotesResult r = parseNotes('just a note');
      expect(r.grandTotal, 0);
      expect(r.items.single.isValid, isFalse);
      expect(
        r.items.single.label,
        'just a note',
        reason:
            'dropping the line silently is how a total becomes impossible to '
            'account for',
      );
    });

    test('decimals', () {
      expect(parseNotes('load 99.75\nfare 12.50').grandTotal, 112.25);
    });

    test('division keeps its full precision', () {
      expect(
        parseNotes('split 1000/3').grandTotal,
        closeTo(333.3333333333333, 1e-10),
      );
    });

    test('multiplication binds tighter than addition', () {
      expect(parseNotes('mix 2+3*4').grandTotal, 14);
    });

    test('parentheses', () {
      expect(parseNotes('paren (2+3)*4').grandTotal, 20);
    });

    test('a negative is a negative, not a parse failure', () {
      final NotesResult r = parseNotes('refund -250');
      expect(r.grandTotal, -250);
      expect(r.items.single.isValid, isTrue);
    });

    test('a trailing operator makes the line INVALID, not zero', () {
      // The prototype's Function() throws on `5+`, so the line lands in the
      // catch branch: whole line as the label, value zero, isValid false.
      // An evaluator that returned 5 here would be adding money nobody typed.
      final NotesResult r = parseNotes('broken 5+');
      expect(r.grandTotal, 0);
      expect(r.items.single.isValid, isFalse);
      expect(r.items.single.label, 'broken 5+');
    });

    test('a label may contain digits of its own', () {
      // The one a careful reading gets wrong. The regex is lazy on the left,
      // so the label takes as much as it can and only the TAIL is arithmetic.
      final NotesResult r = parseNotes('load 100 pesos 250');
      expect(r.items.single.label, 'load 100 pesos');
      expect(r.grandTotal, 250);
    });

    test('spaces inside an expression do not break it', () {
      expect(parseNotes('sum 10 + 20 + 30').grandTotal, 60);
    });

    test('empty input is an empty result, not a crash', () {
      final NotesResult r = parseNotes('');
      expect(r.items, isEmpty);
      expect(r.grandTotal, 0);
    });

    test('a peso sign is stripped from the maths and kept in the label', () {
      final NotesResult r = parseNotes('rent ₱5000');
      expect(r.grandTotal, 5000);
      expect(r.items.single.label, 'rent ₱');
    });
  });

  group('the evaluator on its own', () {
    test('it refuses what it cannot fully read', () {
      // Null rather than a partial answer. A half understood expression is
      // not a number, and returning the part it managed would put money in
      // the total that nobody typed.
      expect(evaluateExpression('5+'), isNull);
      expect(evaluateExpression('(2+3'), isNull);
      expect(evaluateExpression('2+3)'), isNull);
      expect(evaluateExpression(''), isNull);
      expect(evaluateExpression('*5'), isNull);
    });

    test('division by zero does not become a silent zero', () {
      // JavaScript gives Infinity here and the prototype's isNaN check lets
      // it through as a number. Salapify rejects the LINE instead, because
      // an infinite peso total is not a figure anybody can act on, and a
      // zero would be a wrong number that looks reasonable.
      expect(parseNotes('oops 1000/0').items.single.isValid, isFalse);
      expect(parseNotes('oops 1000/0').grandTotal, 0);
    });

    test('it counts how many lines actually carried a number', () {
      final NotesResult r = parseNotes('ate 50\njust a note\nkuya 600');
      expect(r.items.length, 3);
      expect(
        r.countedLines,
        2,
        reason:
            '"3 lines" over a total that counted two is the quiet mismatch '
            'that makes somebody distrust the whole thing',
      );
    });
  });
}
