import 'package:flutter_test/flutter_test.dart';
import 'package:salapify/core/money/reminders.dart';
import 'package:salapify/models/models.dart';

/// Locked to vectors generated by running the PROTOTYPE'S OWN
/// `evaluateReminders` under bun, plus one deliberate divergence that is
/// pinned rather than assumed.
void main() {
  planningTests();
  dateReadingTests();
  // Midday on purpose. The daily nudge fires from 8pm, so a default clock in
  // the evening would add a second reminder to every bill and debt test and
  // turn each of them into a test of two features at once.
  final DateTime now = DateTime(2026, 9, 19, 12, 0);

  // When the nudge itself is the subject.
  final DateTime evening = DateTime(2026, 9, 19, 21, 0);
  String iso(int plusDays) {
    final DateTime d = DateTime(2026, 9, 19).add(Duration(days: plusDays));
    return '${d.year}-${d.month.toString().padLeft(2, '0')}-'
        '${d.day.toString().padLeft(2, '0')}';
  }

  BillItem bill({String? due, bool paid = false}) => BillItem(
    id: 'b1',
    name: 'Meralco',
    amount: 2840,
    dueDate: due ?? iso(2),
    isPaid: paid,
  );

  ReminderResult run({
    ReminderSettings? settings,
    List<Transaction>? txs,
    List<Debt>? debts,
    List<BillItem>? bills,
    List<Account>? accounts,
    List<InstallmentPlan>? installments,
    List<UpcomingItem>? upcoming,
    Set<String>? sent,
    DateTime? at,
  }) => evaluateReminders(
    settings: settings ?? ReminderSettings.defaults,
    transactions: txs ?? const <Transaction>[],
    debts: debts ?? const <Debt>[],
    bills: bills ?? const <BillItem>[],
    accounts: accounts ?? const <Account>[],
    installments: installments ?? const <InstallmentPlan>[],
    upcoming: upcoming ?? const <UpcomingItem>[],
    sentTags: sent ?? <String>{},
    now: at ?? now,
  );

  group('bills, against the prototype vectors', () {
    test('a bill due in two days reminds', () {
      final ReminderResult r = run(bills: <BillItem>[bill()]);
      expect(r.fresh.single.kind, ReminderKind.billDue);
      expect(r.fresh.single.title, 'Bill due: Meralco');
      expect(r.fresh.single.body, contains('is due in 2 days'));
    });

    test('five days away is outside the window and stays quiet', () {
      expect(run(bills: <BillItem>[bill(due: iso(5))]).fresh, isEmpty);
    });

    test('due today says today', () {
      final ReminderResult r = run(bills: <BillItem>[bill(due: iso(0))]);
      expect(r.fresh.single.body, contains('is due today'));
    });

    test('a paid bill is silent', () {
      expect(run(bills: <BillItem>[bill(paid: true)]).fresh, isEmpty);
    });

    test('bills switched off is silent', () {
      expect(
        run(
          settings: ReminderSettings.defaults.copyWith(billEnabled: false),
          bills: <BillItem>[bill()],
        ).fresh,
        isEmpty,
      );
    });
  });

  group('the deliberate divergence', () {
    test('an OVERDUE bill reminds, where the prototype says nothing', () {
      // The prototype tests days >= 0, so a bill three days late produces no
      // reminder at all: miss a due date and the app stops mentioning it.
      // The most urgent case in the feature is the one it is silent about.
      final ReminderResult r = run(bills: <BillItem>[bill(due: iso(-3))]);
      expect(
        r.fresh,
        hasLength(1),
        reason:
            'an overdue bill went silent, which is the prototype behaviour '
            'and is the opposite of what a reminder is for',
      );
      expect(r.fresh.single.body, contains('was due 3 days ago'));
    });

    test('one day late reads as yesterday, not "was due 1 days ago"', () {
      final ReminderResult r = run(bills: <BillItem>[bill(due: iso(-1))]);
      expect(r.fresh.single.body, contains('was due yesterday'));
    });
  });

  group('debts', () {
    Debt owed({bool settled = false, double paid = 0, String? due}) => Debt(
      id: 'd1',
      person: 'Ana',
      direction: DebtDirection.iOwe,
      totalAmount: 5000,
      paidAmount: paid,
      isSettled: settled,
      dueDate: due ?? iso(2),
    );

    test('a debt you owe, due in two days, reminds', () {
      final ReminderResult r = run(debts: <Debt>[owed()]);
      expect(r.fresh.single.kind, ReminderKind.paymentDue);
      expect(r.fresh.single.title, 'Payment due: Ana');
    });

    test('a settled debt is silent', () {
      expect(run(debts: <Debt>[owed(settled: true)]).fresh, isEmpty);
    });

    test('a fully paid debt is silent even when not marked settled', () {
      expect(run(debts: <Debt>[owed(paid: 5000)]).fresh, isEmpty);
    });

    test('money owed TO you never reminds', () {
      // It is not your payment to make. Nagging somebody about their own
      // receivable is how a reminder tray stops being read.
      final ReminderResult r = run(
        debts: <Debt>[
          Debt(
            id: 'd2',
            person: 'Mark',
            direction: DebtDirection.owedToMe,
            totalAmount: 900,
            paidAmount: 0,
            isSettled: false,
            dueDate: iso(2),
          ),
        ],
      );
      expect(r.fresh, isEmpty);
    });
  });

  group('credit cards', () {
    Account card({double balance = -18400, String? due}) => Account(
      id: 'c1',
      name: 'BPI Gold',
      kind: AccountKind.credit,
      institution: 'BPI',
      balance: balance,
      monogram: 'BP',
      dueDate: due ?? iso(1),
    );

    test('a card carrying a balance reminds before the cutoff', () {
      final ReminderResult r = run(accounts: <Account>[card()]);
      expect(r.fresh.single.kind, ReminderKind.paymentDue);
      expect(r.fresh.single.title, 'Credit card due: BPI Gold');
      expect(r.fresh.single.body, contains('18,400'));
    });

    test('a card at zero is silent, and one in credit too', () {
      // Money you do not owe is not a payment due. The prototype's own test
      // is balance < 0, and getting the sign wrong here would nag somebody
      // every month about a card they had already cleared.
      expect(run(accounts: <Account>[card(balance: 0)]).fresh, isEmpty);
      expect(run(accounts: <Account>[card(balance: 2500)]).fresh, isEmpty);
    });

    test('a card with no statement date cannot remind', () {
      expect(run(accounts: <Account>[card(due: '')]).fresh, isEmpty);
    });

    test('a plain bank account is never a payment due', () {
      final ReminderResult r = run(
        accounts: <Account>[
          Account(
            id: 'b1',
            name: 'BPI Savings',
            kind: AccountKind.bank,
            institution: 'BPI',
            balance: -400,
            monogram: 'BP',
            dueDate: iso(1),
          ),
        ],
      );
      expect(r.fresh, isEmpty);
    });
  });

  group('payment plans', () {
    InstallmentPlan plan({
      int paid = 0,
      int total = 12,
      String start = '2026-01-20',
      PaymentFrequency every = PaymentFrequency.monthly,
      bool settled = false,
    }) => InstallmentPlan(
      id: 'p1',
      name: 'Laptop',
      provider: 'Home Credit',
      principal: 48000,
      interestRate: 0,
      interestRateType: InterestRateType.fixed,
      totalInterest: 0,
      totalPayable: 48000,
      termMonths: total,
      installmentAmount: 4000,
      paidInstallments: paid,
      totalInstallments: total,
      runningBalance: 48000,
      principalRemaining: 48000,
      interestRemaining: 0,
      startDate: start,
      maturityDate: '2027-01-20',
      paymentFrequency: every,
      isSettled: settled,
    );

    test('the next payment is the start plus the payments already made', () {
      expect(nextInstallmentDate(plan(paid: 0)), DateTime(2026, 1, 20));
      expect(nextInstallmentDate(plan(paid: 8)), DateTime(2026, 9, 20));
      expect(
        nextInstallmentDate(plan(paid: 12, total: 12)),
        isNull,
        reason: 'a finished plan has no next payment',
      );
    });

    test('a plan mid-term reminds, where the prototype went silent', () {
      // THE divergence on this branch. The prototype measures days until
      // startDate, so this plan, eight payments in and due in two days, would
      // produce nothing at all: it reminded once in January 2026 and then
      // never again for the remaining 23 months of a two year plan.
      final ReminderResult r = run(
        installments: <InstallmentPlan>[plan(paid: 8, start: '2026-01-21')],
      );
      expect(
        r.fresh,
        hasLength(1),
        reason:
            'a payment plan in the middle of its term said nothing, which is '
            'every payment after the first',
      );
      expect(r.fresh.single.title, 'Payment plan: Laptop');
      expect(r.fresh.single.body, contains('Home Credit'));
    });

    test('a settled plan is silent', () {
      expect(
        run(
          installments: <InstallmentPlan>[
            plan(paid: 8, start: '2026-01-21', settled: true),
          ],
        ).fresh,
        isEmpty,
      );
    });

    test('weekly and biweekly plans step by days, not months', () {
      expect(
        nextInstallmentDate(
          plan(paid: 3, start: '2026-09-01', every: PaymentFrequency.weekly),
        ),
        DateTime(2026, 9, 22),
      );
      expect(
        nextInstallmentDate(
          plan(paid: 2, start: '2026-09-01', every: PaymentFrequency.biweekly),
        ),
        DateTime(2026, 9, 29),
      );
    });
  });

  group('the Coming up list', () {
    UpcomingItem item(
      UpcomingItemType type, {
      String? due,
      bool paid = false,
    }) => UpcomingItem(
      id: 'u1',
      name: type == UpcomingItemType.subscription ? 'Spotify' : 'Globe',
      amount: type == UpcomingItemType.subscription ? 194 : 1699,
      dueDate: due ?? iso(1),
      type: type,
      isPaid: paid,
    );

    test('a bill on it reminds like any other bill', () {
      final ReminderResult r = run(
        upcoming: <UpcomingItem>[item(UpcomingItemType.bill)],
      );
      expect(r.fresh.single.kind, ReminderKind.billDue);
      expect(r.fresh.single.title, 'Bill due: Globe');
    });

    test('a subscription renewal reminds the day before', () {
      final ReminderResult r = run(
        upcoming: <UpcomingItem>[item(UpcomingItemType.subscription)],
      );
      expect(r.fresh.single.kind, ReminderKind.subscription);
      expect(r.fresh.single.title, 'Renews: Spotify');
      expect(
        r.fresh.single.body,
        contains('is charged tomorrow'),
        reason: 'a renewal is charged, not "due", and the wording says so',
      );
    });

    test('two days out is outside the subscription window', () {
      // One day by default, unlike bills. A week of warnings about Netflix is
      // how the whole tray gets swiped away.
      expect(
        run(
          upcoming: <UpcomingItem>[
            item(UpcomingItemType.subscription, due: iso(2)),
          ],
        ).fresh,
        isEmpty,
      );
    });

    test('a paid item is silent, and payday is never a bill', () {
      expect(
        run(
          upcoming: <UpcomingItem>[item(UpcomingItemType.bill, paid: true)],
        ).fresh,
        isEmpty,
      );
      expect(
        run(upcoming: <UpcomingItem>[item(UpcomingItemType.payday)]).fresh,
        isEmpty,
        reason: 'money arriving is not a payment to make',
      );
    });

    test('subscriptions switched off is silent', () {
      expect(
        run(
          settings: ReminderSettings.defaults.copyWith(
            subscriptionEnabled: false,
          ),
          upcoming: <UpcomingItem>[item(UpcomingItemType.subscription)],
        ).fresh,
        isEmpty,
      );
    });
  });

  group('the daily nudge', () {
    test('it fires after the configured time when nothing is logged', () {
      final ReminderResult r = run(at: DateTime(2026, 9, 19, 21));
      expect(r.fresh.single.kind, ReminderKind.dailyExpense);
      expect(r.fresh.single.body, contains('8:00 PM'));
    });

    test('before the time, nothing', () {
      expect(run(at: DateTime(2026, 9, 19, 19, 59)).fresh, isEmpty);
    });

    test('an expense logged today silences it', () {
      final ReminderResult r = run(
        at: evening,
        txs: <Transaction>[
          Transaction(
            id: 't1',
            type: TransactionType.expense,
            amount: 50,
            category: 'Food & Dining',
            accountId: 'a1',
            date: '2026-09-19',
            createdAt: now.millisecondsSinceEpoch,
          ),
        ],
      );
      expect(r.fresh, isEmpty);
    });

    test('an INCOME entry does not count as logging your day', () {
      final ReminderResult r = run(
        at: evening,
        txs: <Transaction>[
          Transaction(
            id: 't1',
            type: TransactionType.income,
            amount: 32500,
            category: 'Salary & Compensation',
            accountId: 'a1',
            date: '2026-09-19',
            createdAt: now.millisecondsSinceEpoch,
          ),
        ],
      );
      expect(r.fresh, hasLength(1));
    });
  });

  group('not saying the same thing twice', () {
    test('a tag already sent does not fire again', () {
      final ReminderResult first = run(bills: <BillItem>[bill()]);
      final ReminderResult second = run(
        bills: <BillItem>[bill()],
        sent: first.tags.toSet(),
      );
      expect(
        second.fresh,
        isEmpty,
        reason:
            'reopening the app in an evening would produce a reminder every '
            'time, which is how somebody learns to ignore the tray',
      );
    });

    test('but it fires again the NEXT day', () {
      final ReminderResult first = run(bills: <BillItem>[bill(due: iso(3))]);
      expect(first.fresh, isEmpty, reason: 'three days is outside the window');

      final ReminderResult tomorrow = run(
        bills: <BillItem>[bill(due: iso(3))],
        sent: first.tags.toSet(),
        at: DateTime(2026, 9, 20, 21),
      );
      expect(
        tomorrow.fresh.where((Reminder r) => r.kind == ReminderKind.billDue),
        hasLength(1),
        reason: 'the tag carries today, so a bill can remind on each day',
      );
    });
  });

  group('reading a due date somebody typed', () {
    test('the four shapes the prototype understands', () {
      final DateTime at = DateTime(2026, 9, 19, 12);
      expect(daysUntil('2026-09-21', at), 2);
      expect(daysUntil('today', at), 0);
      expect(daysUntil('Tomorrow', at), 1);
      expect(daysUntil('Sep 25', at), 6);
    });

    test('a bare day of the month means the NEXT one, never a past one', () {
      final DateTime at = DateTime(2026, 9, 19, 12);
      expect(daysUntil('25', at), 6);
      expect(
        daysUntil('15th', at),
        26,
        reason:
            'the 15th has passed, so it means next month. Reading it as the '
            'past would make every old bill overdue forever.',
      );
    });

    test('nonsense reads as no date rather than as today', () {
      expect(daysUntil('whenever', DateTime(2026, 9, 19)), isNull);
      expect(daysUntil('', DateTime(2026, 9, 19)), isNull);
      expect(daysUntil(null, DateTime(2026, 9, 19)), isNull);
    });
  });
}

/// Scheduling AHEAD, which is what makes a phone buzz when Salapify is closed.
void planningTests() {
  final DateTime from = DateTime(2026, 9, 19, 12);

  List<PlannedReminder> plan({
    ReminderSettings? settings,
    List<BillItem>? bills,
    List<Transaction>? txs,
    Set<String>? sent,
    int days = 14,
    DateTime? at,
  }) => planReminders(
    settings: settings ?? ReminderSettings.defaults,
    transactions: txs ?? const <Transaction>[],
    debts: const <Debt>[],
    bills: bills ?? const <BillItem>[],
    sentTags: sent ?? <String>{},
    from: at ?? from,
    days: days,
  );

  group('planning ahead', () {
    test('a bill five days out is scheduled, on the right morning', () {
      // Two days of warning, so a bill on the 24th is spoken about on the
      // 22nd. The whole point of scheduling: on the 19th, nothing is due, and
      // the phone still has to be told now.
      final List<PlannedReminder> p = plan(
        bills: <BillItem>[
          BillItem(
            id: 'b1',
            name: 'Meralco',
            amount: 2840,
            dueDate: '2026-09-24',
          ),
        ],
      );
      final List<PlannedReminder> bill = p
          .where((PlannedReminder x) => x.reminder.kind == ReminderKind.billDue)
          .toList();

      expect(
        bill,
        isNotEmpty,
        reason:
            'nothing was scheduled, so the phone stays silent about a bill it '
            'already knows is coming',
      );
      expect(bill.first.at, DateTime(2026, 9, 22, 9));
      expect(bill.first.reminder.body, contains('is due in 2 days'));
    });

    test('the same bill is scheduled once, not once a day until it is due', () {
      final List<PlannedReminder> p = plan(
        bills: <BillItem>[
          BillItem(
            id: 'b1',
            name: 'Meralco',
            amount: 2840,
            dueDate: '2026-09-24',
          ),
        ],
      );
      final Set<String> days = p
          .where((PlannedReminder x) => x.reminder.kind == ReminderKind.billDue)
          .map((PlannedReminder x) => '${x.at.month}-${x.at.day}')
          .toSet();
      expect(
        days,
        <String>{'9-22', '9-23', '9-24', '10-1'},
        reason:
            'a bill speaks once a day inside its window, on the 22nd, 23rd '
            'and 24th, and then ONCE A WEEK while it stays unpaid. Every '
            'morning for a fortnight is how an alarm gets its battery taken '
            'out.',
      );
    });

    test('an overdue bill is weekly on the phone, daily on the screen', () {
      // The two rules are different on purpose, and this pins the difference.
      // On screen, somebody is already looking and an unpaid bill should be
      // in front of them every visit. On a phone it would be a buzz every
      // morning until they pay, which teaches them to swipe.
      final BillItem late = BillItem(
        id: 'b1',
        name: 'Meralco',
        amount: 2840,
        dueDate: '2026-09-12',
      );

      final ReminderResult onScreen = evaluateReminders(
        settings: ReminderSettings.defaults,
        transactions: const <Transaction>[],
        debts: const <Debt>[],
        bills: <BillItem>[late],
        sentTags: <String>{},
        now: from,
      );
      expect(
        onScreen.fresh,
        hasLength(1),
        reason: 'the screen went quiet about a bill a week overdue',
      );

      final List<PlannedReminder> p = plan(bills: <BillItem>[late], days: 10);
      final List<DateTime> when = p
          .where((PlannedReminder x) => x.reminder.kind == ReminderKind.billDue)
          .map((PlannedReminder x) => x.at)
          .toList();
      expect(
        when.map((DateTime d) => d.day),
        <int>[26],
        reason:
            'the phone was scheduled to say it more than once a week, or was '
            'scheduled not to say it at all',
      );
    });

    test('nothing is ever scheduled into the past', () {
      // The plugin fires a past time immediately, so a first launch would
      // produce a burst of notifications about yesterday.
      final List<PlannedReminder> p = plan(
        bills: <BillItem>[
          BillItem(
            id: 'b1',
            name: 'Meralco',
            amount: 2840,
            dueDate: '2026-09-10',
          ),
        ],
        at: DateTime(2026, 9, 19, 23, 30),
      );
      for (final PlannedReminder x in p) {
        expect(x.at.isAfter(DateTime(2026, 9, 19, 23, 30)), isTrue);
      }
    });

    test('the nudge lands at the hour chosen, not the morning hour', () {
      final List<PlannedReminder> p = plan(
        settings: ReminderSettings.defaults.copyWith(dailyExpenseHour: 21),
        days: 2,
      );
      final PlannedReminder nudge = p.firstWhere(
        (PlannedReminder x) => x.reminder.kind == ReminderKind.dailyExpense,
      );
      expect(nudge.at.hour, 21);
    });

    test('a nudge is planned for tomorrow, which is not a guess', () {
      // Whether tomorrow gets logged is unknowable today. Planning it anyway
      // is right: if they never open Salapify tomorrow they have not logged,
      // and if they do, the app replans and this one is cancelled first.
      final List<PlannedReminder> p = plan(days: 3);
      final Set<int> nudgeDays = p
          .where(
            (PlannedReminder x) => x.reminder.kind == ReminderKind.dailyExpense,
          )
          .map((PlannedReminder x) => x.at.day)
          .toSet();
      expect(nudgeDays, containsAll(<int>[20, 21]));
    });

    test('an expense logged today takes TODAY off the plan, not the week', () {
      // The directional half. A planner that dropped every nudge would pass
      // an assertion about today on its own.
      final List<PlannedReminder> p = plan(
        days: 3,
        at: DateTime(2026, 9, 19, 12),
        txs: <Transaction>[
          Transaction(
            id: 't1',
            type: TransactionType.expense,
            amount: 50,
            category: 'Food & Dining',
            accountId: 'a1',
            date: '2026-09-19',
            createdAt: 0,
          ),
        ],
      );
      final Set<int> nudgeDays = p
          .where(
            (PlannedReminder x) => x.reminder.kind == ReminderKind.dailyExpense,
          )
          .map((PlannedReminder x) => x.at.day)
          .toSet();

      expect(nudgeDays, isNot(contains(19)));
      expect(
        nudgeDays,
        containsAll(<int>[20, 21]),
        reason:
            'logging once silenced the rest of the week, so the nudge stops '
            'working the day somebody uses the app',
      );
    });

    test('what is already in the tray is not also scheduled', () {
      final List<PlannedReminder> first = plan(
        bills: <BillItem>[
          BillItem(
            id: 'b1',
            name: 'Meralco',
            amount: 2840,
            dueDate: '2026-09-20',
          ),
        ],
      );
      expect(first, isNotEmpty);

      final List<PlannedReminder> second = plan(
        bills: <BillItem>[
          BillItem(
            id: 'b1',
            name: 'Meralco',
            amount: 2840,
            dueDate: '2026-09-20',
          ),
        ],
        sent: first.map((PlannedReminder x) => x.reminder.tag).toSet(),
      );
      expect(
        second,
        isEmpty,
        reason:
            'a reminder already read on screen would buzz the phone about the '
            'same bill on the same day',
      );
    });

    test('everything switched off plans nothing at all', () {
      expect(
        plan(
          settings: const ReminderSettings(
            dailyExpenseEnabled: false,
            paymentDueEnabled: false,
            billEnabled: false,
            subscriptionEnabled: false,
          ),
          bills: <BillItem>[
            BillItem(
              id: 'b1',
              name: 'Meralco',
              amount: 2840,
              dueDate: '2026-09-20',
            ),
          ],
        ),
        isEmpty,
      );
    });
  });
}

/// Dates people actually type, and dates no person ever meant.
///
/// Every case here is from an adversarial QA pass. The due date field is free
/// text with the hint "Oct 3, or the 15th", so the app invites all of these.
void dateReadingTests() {
  final DateTime at = DateTime(2026, 9, 19, 12);

  group('dates the app invites but used to ignore', () {
    test('a single digit month is read, not silently dropped', () {
      // The ISO pattern demanded two digits, so `2026-9-21` returned null,
      // which means NO REMINDER EVER. The account screen accepts the date,
      // shows it back, and the payment reminder simply never happens with
      // nothing anywhere saying why.
      expect(daysUntil('2026-9-21', at), 2);
      expect(daysUntil('2026-09-21', at), 2);
    });

    test('an ordinal and a written year are both read', () {
      expect(daysUntil('Oct 3rd', at), 14);
      expect(daysUntil('Oct 3, 2026', at), 14);
      expect(
        daysUntil('Sep 5, 2027', at),
        351,
        reason: 'a year somebody typed must win over the roll-forward',
      );
    });
  });

  group('dates that used to nag forever', () {
    test('a month name LONG past rolls to next year rather than nagging', () {
      // "Jun 5" was 106 days overdue and stayed overdue forever, growing by a
      // day every morning, because the year and month were both pinned. It
      // could never self-correct.
      expect(
        daysUntil('Jun 5', at),
        greaterThan(250),
        reason:
            'a due date months in the past keeps being announced as overdue '
            'and the lateness grows every day, with no way back',
      );
    });

    test('but a date only just past still reads as overdue', () {
      // The other half of the alarm, and the more important one. Rolling
      // EVERYTHING forward would silence a genuinely missed payment, which is
      // the exact prototype defect this engine exists to avoid.
      expect(daysUntil('Sep 12', at), -7);
      expect(daysUntil('Sep 5', at), -14);
      expect(daysUntil('Aug 25', at), -25);
    });
  });

  group('dates no person meant', () {
    test('a garbage stored date is ignored rather than shouted', () {
      // DateTime accepts these and normalises them silently, so the tray said
      // "was due 740275 days ago" with a peso figure in front of it.
      expect(daysUntil('0000-00-00', at), isNull);
      expect(daysUntil('9999-12-31', at), isNull);
    });

    test('and a real date near today is still fine', () {
      // The guard must not eat ordinary dates.
      expect(daysUntil('2026-09-21', at), 2);
      expect(daysUntil('2027-09-21', at), 367);
    });

    test('nothing throws, whatever is typed', () {
      for (final String s in <String>[
        '',
        '   ',
        'next friday',
        '0',
        '99',
        '2026-13-45',
        'Feb 30',
        'Oct',
        '10/3',
        'tomorrow',
      ]) {
        expect(
          () => daysUntil(s, at),
          returnsNormally,
          reason: 'threw on "$s"',
        );
      }
    });
  });

  group('payment plan dates land in the right month', () {
    InstallmentPlan onThe(String start, int paid) => InstallmentPlan(
      id: 'p1',
      name: 'Laptop',
      provider: 'Provider',
      principal: 48000,
      interestRate: 0,
      interestRateType: InterestRateType.fixed,
      totalInterest: 0,
      totalPayable: 48000,
      termMonths: 12,
      installmentAmount: 4000,
      paidInstallments: paid,
      totalInstallments: 12,
      runningBalance: 48000,
      principalRemaining: 48000,
      interestRemaining: 0,
      startDate: start,
      maturityDate: '2027-01-20',
    );

    test('a plan starting on the 31st does not skip February', () {
      // DateTime(y, m + n, 31) overflows silently. A monthly plan starting
      // 31 January gave 31 Jan, then 3 MARCH, then 31 Mar, then 1 MAY: the
      // February payment is never mentioned at all, and the person is told a
      // payment is due days after the lender expected it.
      expect(
        nextInstallmentDate(onThe('2026-01-31', 0)),
        DateTime(2026, 1, 31),
      );
      expect(
        nextInstallmentDate(onThe('2026-01-31', 1)),
        DateTime(2026, 2, 28),
        reason: 'the February payment landed in March',
      );
      expect(
        nextInstallmentDate(onThe('2026-01-31', 2)),
        DateTime(2026, 3, 31),
      );
      expect(
        nextInstallmentDate(onThe('2026-01-31', 3)),
        DateTime(2026, 4, 30),
        reason: 'April has thirty days',
      );
    });

    test('an ordinary day of the month is untouched', () {
      expect(
        nextInstallmentDate(onThe('2026-01-20', 1)),
        DateTime(2026, 2, 20),
      );
      expect(
        nextInstallmentDate(onThe('2026-01-20', 11)),
        DateTime(2026, 12, 20),
      );
    });

    test('it rolls into the next year correctly', () {
      expect(
        nextInstallmentDate(onThe('2026-12-29', 2)),
        DateTime(2027, 2, 28),
      );
    });
  });
}
