// Moving money between two accounts, ported from the RN saveTransfer that
// lives inline in mobile/app/accounts.js, and golden-locked against that exact
// source (test/goldens/transfer_goldens.json is generated by executing the
// real function body, not by reading it).
//
// A transfer is deliberately NOT income and NOT spending. It moves two
// balances and leaves one record row so History can explain why both changed.
// That row carries no accountId on purpose: the balances moved here, and
// deleting the row later must never move them a second time. Every income,
// expense and budget calculation already skips type 'transfer'.
//
// The whole engine is pure. The screen collects three fields and shows
// whatever comes back; it does no arithmetic of its own, which is the rule
// that put monthlyInterest and whatIfLadder in the money layer too.

import 'base_currency_scope.dart' show baseCurrencyOf;
import 'debtmath.dart' show formatMoneyText;
import 'ledger.dart' as ledger;

double _jsRound(double x) => (x + 0.5).floorToDouble();

/// Round to the centavo the RN way, so repeated transfers never leave float
/// residue like 0.30000000000000004 in a balance.
double _round2(double x) => _jsRound(x * 100) / 100;

/// JS `Number(str)`, which is stricter than double.tryParse in one direction
/// and looser in three others. The goldens found all four: an empty or
/// whitespace-only string is 0 rather than a failure, a leading + is fine,
/// and 0x, 0o and 0b literals parse as numbers. Anything else JS rejects
/// comes back NaN, and the caller turns that into the "greater than 0"
/// message rather than a wrong balance.
double jsNumber(String raw) {
  final s = raw.trim();
  if (s.isEmpty) return 0;
  final signed = s.startsWith('-') || s.startsWith('+');
  final body = signed ? s.substring(1) : s;
  if (body.length > 2 && body[0] == '0') {
    final radix = switch (body[1]) {
      'x' || 'X' => 16,
      'o' || 'O' => 8,
      'b' || 'B' => 2,
      _ => 0,
    };
    if (radix != 0) {
      // A signed radix literal is NaN in JS: "-0x10" and "0x+10" are both
      // not numbers. The second one is the subtle half, because int.tryParse
      // accepts a sign INSIDE the body, so "0x+10" parsed as 16 and moved
      // ₱16 where the live app refuses. QA found it; the goldens could not,
      // because they only carried the unsigned form.
      if (signed) return double.nan;
      final digits = body.substring(2);
      if (digits.isEmpty || digits.startsWith('-') || digits.startsWith('+')) {
        return double.nan;
      }
      // BigInt, not int: JS has no 64-bit ceiling, so 0xFFFFFFFFFFFFFFFF is
      // 1.8446744073709552e19 there and null from int.tryParse here. Parsing
      // wide and converting keeps the same answer, and keeps it the same on
      // web, where a Dart int IS a double and the ceiling moves.
      final v = BigInt.tryParse(digits, radix: radix);
      return v == null ? double.nan : v.toDouble();
    }
  }
  return double.tryParse(s) ?? double.nan;
}

/// The typed amount, comma and space stripped, coerced and rounded to the
/// centavo exactly as RN does. NaN when the text is not a number at all.
double transferAmount(dynamic raw) {
  final text = (raw ?? '').toString().replaceAll(RegExp(r'[, ]'), '');
  final n = jsNumber(text);
  if (!n.isFinite) return double.nan;
  return _round2(n);
}

/// A balance to show beside a "you can move this much" control.
///
/// TRUNCATED, never rounded, and that is the whole point. formatMoneyText
/// rounds to whole pesos, so an account holding 48,500.55 read as "₱48,501"
/// and moving 48,501 out of it is refused: the screen printed a number the
/// next tap contradicted. The first fix rounded the centavos instead, which
/// only moved the lie two decimal places (0.999 read as "₱1", and moving 1
/// was still refused). Rounding UP a balance can always overstate it.
/// Truncating never can, so this is the shape the problem actually has.
///
/// A balance too large for exact centavo arithmetic falls back to the whole
/// peso formatter rather than inventing decimals: past 2^53 centavos the
/// hundredths are noise, and a restored backup carrying 1e307 used to
/// overflow to Infinity here and take the whole sheet down with it.
String balanceLabel(num value) {
  final v = value.toDouble();
  if (!v.isFinite) return formatMoneyText(v);
  final scaled = v.abs() * 100;
  if (!scaled.isFinite || scaled >= 9007199254740992.0) {
    return formatMoneyText(v);
  }
  final centavos = scaled.floorToDouble() % 100;
  if (centavos == 0) return formatMoneyText(v.truncateToDouble());
  final whole = formatMoneyText(v.abs().floorToDouble());
  final cents = centavos.toInt().toString().padLeft(2, '0');
  return '${v < 0 ? '-' : ''}$whole.$cents';
}

/// Why a transfer was refused, so a screen can say the honest thing without
/// the engine having to change the message it is golden-locked to. `currency`
/// has no RN counterpart: the RN app has no per-account currency, so it could
/// never hit this. It exists because a Flutter account CAN carry its own
/// currencyCode, and moving 1:1 between two currencies would silently dent net
/// worth (see the guard in applyTransfer).
enum TransferRefusal { amount, accounts, overdraft, currency }

/// An account's effective currency: its own currencyCode when it carries a
/// valid one, otherwise the base currency (an account with no code has always
/// meant "the app's one currency", the same rule base_currency_scope uses).
String _effectiveCurrency(Map<String, dynamic> account, String base) {
  final code = account['currencyCode'];
  if (code is String && RegExp(r'^[A-Za-z]{3}$').hasMatch(code)) {
    return code.toUpperCase();
  }
  return base;
}

/// What a transfer attempt produced: either a message to show, or the new
/// store data. Never both, and never neither.
class TransferOutcome {
  /// The refusal, worded exactly as the live RN app words it. Golden locked.
  final String? error;

  /// Which refusal it was, so a screen can compose an honest sentence of its
  /// own. The RN message rounds the balance ("only has ₱3,201" for an account
  /// holding 3,200.995), and a rounded-up figure in a refusal is a number the
  /// app will not honour. The engine keeps RN's string so the two apps stay
  /// comparable; the screen uses [available] and says the truthful thing.
  final TransferRefusal? refusal;

  /// What the source account actually holds, on an overdraft refusal.
  final double? available;

  final Map<String, dynamic>? data;
  const TransferOutcome.failed(
    String this.error,
    this.refusal, {
    this.available,
  }) : data = null;
  const TransferOutcome.applied(Map<String, dynamic> this.data)
    : error = null,
      refusal = null,
      available = null;
  bool get ok => error == null;
}

List<Map<String, dynamic>> _accounts(Map<String, dynamic> data) {
  final list = data['accounts'];
  return list is List ? list.whereType<Map<String, dynamic>>().toList() : [];
}

Map<String, dynamic>? _find(List<Map<String, dynamic>> accounts, dynamic id) {
  for (final a in accounts) {
    if (a['id'] == id) return a;
  }
  return null;
}

/// Move [amountText] from one account to another, or say why not.
///
/// The three refusals and their wording are the RN ones to the character, and
/// the order they are checked in matters: an amount of zero is reported as an
/// amount problem even when the accounts are also wrong, because that is the
/// first thing the person can fix.
///
/// No overdrafts. A transfer can only move money that is really there, which
/// is also why a negative or unreadable stored balance simply refuses rather
/// than being treated as zero and quietly inventing money.
TransferOutcome applyTransfer(
  Map<String, dynamic> data, {
  required dynamic fromId,
  required dynamic toId,
  required dynamic amountText,
  required String today,
  required String Function() genId,
}) {
  final amount = transferAmount(amountText);
  if (!amount.isFinite || amount <= 0) {
    return const TransferOutcome.failed(
      'Enter an amount greater than 0.',
      TransferRefusal.amount,
    );
  }
  if (fromId == null ||
      toId == null ||
      '$fromId'.isEmpty ||
      '$toId'.isEmpty ||
      fromId == toId) {
    return const TransferOutcome.failed(
      'Pick two different accounts.',
      TransferRefusal.accounts,
    );
  }
  final accounts = _accounts(data);
  final from = _find(accounts, fromId);
  final to = _find(accounts, toId);
  if (from == null || to == null) {
    return const TransferOutcome.failed(
      'Pick two different accounts.',
      TransferRefusal.accounts,
    );
  }
  // A cross-currency move is refused, not converted. The engine moves the same
  // number out of one balance and into the other, so moving 50 from a dollar
  // account to a peso account would take $50 and add P50, and net worth (which
  // converts each balance) would drop by the difference. The app never stores a
  // conversion rate on purpose (an offline rate goes stale silently), so the
  // honest move is to refuse and let the person log the exchange at the real
  // rate they got. A same-currency move, which is every move the golden vectors
  // cover, is unaffected.
  final base = baseCurrencyOf(data);
  if (_effectiveCurrency(from, base) != _effectiveCurrency(to, base)) {
    return const TransferOutcome.failed(
      'Move money only works between accounts in the same currency.',
      TransferRefusal.currency,
    );
  }
  final fromBal = ledger.amountOf(from['balance']);
  if (amount > fromBal) {
    return TransferOutcome.failed(
      '${from['name']} only has ${formatMoneyText(fromBal)}.',
      TransferRefusal.overdraft,
      available: fromBal,
    );
  }
  final nextAccounts = [
    for (final a in accounts)
      if (a['id'] == from['id'])
        {...a, 'balance': _round2(fromBal - amount)}
      else if (a['id'] == to['id'])
        {...a, 'balance': _round2(ledger.amountOf(to['balance']) + amount)}
      else
        a,
  ];
  final txs = data['transactions'];
  return TransferOutcome.applied({
    ...data,
    'accounts': nextAccounts,
    'transactions': [
      if (txs is List) ...txs,
      {
        'id': genId(),
        'type': 'transfer',
        'label': 'Transfer: ${from['name']} to ${to['name']}',
        'amount': amount,
        'date': today,
        'transferFromId': from['id'],
        'transferToId': to['id'],
      },
    ],
  });
}
