// Philippine payroll and tax math, ported 1:1 from mobile/lib/phtax.js.
// Pure functions, no platform code. The port contract: every function must
// reproduce the RN engine's output to the centavo. That is enforced by
// test/phtax_golden_test.dart, which replays golden vectors generated by
// EXECUTING the RN engine, so the two apps can never quietly disagree.
//
// Returns use Map<String, dynamic> with the exact JS key names on purpose:
// golden vectors diff structurally, and the backup import will speak the
// same shape. Typed wrappers can come later; fidelity comes first.
//
// Sources (2025 rates, confirmed unchanged for 2026): TRAIN graduated table,
// SSS RA 11199 (15 percent, MSC 5,000 to 35,000), PhilHealth 5 percent with
// the 10,000 floor and 100,000 ceiling, Pag-IBIG 2 percent capped at a
// 10,000 fund salary. Estimates, not filings, same as the RN app.

const int ratesYear = 2026;

/// The TRAIN 90,000 tax-free ceiling for 13th month pay and other bonuses
/// combined for the year. Single source of truth, mirrored by thirteenth.dart.
const double bonusTaxFreeCeiling = 90000;

const double percentageTaxRate = 0.03;
const double vatThreshold = 3000000;
const double selfEmployedExempt = 250000;

double _num(num? x) => (x == null || !x.isFinite) ? 0 : x.toDouble();

/// JS Math.round semantics: half rounds toward positive infinity, so the
/// port matches the RN engine on every edge (Dart's round() differs on
/// negative halves).
double _jsRound(double v) {
  final f = v.floorToDouble();
  return (v - f >= 0.5) ? f + 1 : f;
}

double _round2(num x) => _jsRound(_num(x) * 100) / 100;

class _Bracket {
  final double upTo;
  final double base;
  final double rate;
  final double over;
  const _Bracket(this.upTo, this.base, this.rate, this.over);
}

const List<_Bracket> _brackets = [
  _Bracket(250000, 0, 0, 0),
  _Bracket(400000, 0, 0.15, 250000),
  _Bracket(800000, 22500, 0.2, 400000),
  _Bracket(2000000, 102500, 0.25, 800000),
  _Bracket(8000000, 402500, 0.3, 2000000),
  _Bracket(double.infinity, 2202500, 0.35, 8000000),
];

/// Annual graduated income tax (TRAIN, 2023 onward) on the taxable amount.
double annualIncomeTax(num annualTaxable) {
  final t = _num(annualTaxable) < 0 ? 0.0 : _num(annualTaxable);
  for (final b in _brackets) {
    if (t <= b.upTo) return _round2(b.base + (t - b.over) * b.rate);
  }
  return 0;
}

/// The bracket rate the income's top peso falls in; an exact boundary
/// resolves to the lower bracket, matching annualIncomeTax.
double marginalRate(num annualTaxable) {
  final t = _num(annualTaxable) < 0 ? 0.0 : _num(annualTaxable);
  for (final b in _brackets) {
    if (t <= b.upTo) return b.rate;
  }
  return 0;
}

/// SSS Monthly Salary Credit: pay rounded to the nearest 500, held between
/// 5,000 and 35,000. Zero for a non-positive salary.
double sssMSC(num monthly) {
  final m = _num(monthly);
  if (m <= 0) return 0;
  final rounded = _jsRound(m / 500) * 500;
  return rounded.clamp(5000, 35000).toDouble();
}

double sssEmployee(num monthly) => _round2(sssMSC(monthly) * 0.05);

double sssEmployer(num monthly) {
  final msc = sssMSC(monthly);
  if (msc <= 0) return 0;
  final ec = msc >= 15000 ? 30 : 10;
  return _round2(msc * 0.1 + ec);
}

double philhealthEmployee(num monthly) {
  final m = _num(monthly);
  if (m <= 0) return 0;
  final base = m.clamp(10000, 100000);
  return _round2((base * 0.05) / 2);
}

double philhealthEmployer(num monthly) => philhealthEmployee(monthly);

double pagibigEmployee(num monthly) {
  final m = _num(monthly);
  if (m <= 0) return 0;
  final fund = m > 10000 ? 10000 : m;
  final rate = m <= 1500 ? 0.01 : 0.02;
  return _round2(fund * rate);
}

double pagibigEmployer(num monthly) {
  final m = _num(monthly);
  if (m <= 0) return 0;
  final fund = m > 10000 ? 10000 : m;
  return _round2(fund * 0.02);
}

/// Employee, employer, and total for each mandatory contribution, plus the
/// grand totals and the MSC the figures rest on.
Map<String, dynamic> contributionBreakdown(num monthly) {
  final sss = <String, dynamic>{
    'employee': sssEmployee(monthly),
    'employer': sssEmployer(monthly),
  };
  sss['total'] = _round2((sss['employee'] as double) + (sss['employer'] as double));
  final philhealth = <String, dynamic>{
    'employee': philhealthEmployee(monthly),
    'employer': philhealthEmployer(monthly),
  };
  philhealth['total'] =
      _round2((philhealth['employee'] as double) + (philhealth['employer'] as double));
  final pagibig = <String, dynamic>{
    'employee': pagibigEmployee(monthly),
    'employer': pagibigEmployer(monthly),
  };
  pagibig['total'] =
      _round2((pagibig['employee'] as double) + (pagibig['employer'] as double));

  final employeeTotal = _round2((sss['employee'] as double) +
      (philhealth['employee'] as double) +
      (pagibig['employee'] as double));
  final employerTotal = _round2((sss['employer'] as double) +
      (philhealth['employer'] as double) +
      (pagibig['employer'] as double));

  return {
    'msc': sssMSC(monthly),
    'sss': sss,
    'philhealth': philhealth,
    'pagibig': pagibig,
    'employeeTotal': employeeTotal,
    'employerTotal': employerTotal,
    'grandTotal': _round2(employeeTotal + employerTotal),
    'ratesYear': ratesYear,
  };
}

/// Full monthly payslip estimate. Contributions are computed on the BASIC
/// salary; taxable allowances are taxed with pay; non-taxable allowances
/// pass straight to take-home. The annual graduated tax spreads across 12
/// months for the withholding estimate.
Map<String, dynamic> takeHomePay(num basic,
    {num taxableAllowance = 0, num nonTaxableAllowance = 0}) {
  final basicPay = _num(basic) < 0 ? 0.0 : _num(basic);
  final taxAllow = _num(taxableAllowance) < 0 ? 0.0 : _num(taxableAllowance);
  final nonTaxAllow =
      _num(nonTaxableAllowance) < 0 ? 0.0 : _num(nonTaxableAllowance);

  final sss = sssEmployee(basicPay);
  final philhealth = philhealthEmployee(basicPay);
  final pagibig = pagibigEmployee(basicPay);
  final contributions = _round2(sss + philhealth + pagibig);

  var monthlyTaxable = _round2(basicPay + taxAllow - contributions);
  if (monthlyTaxable < 0) monthlyTaxable = 0;
  final annualTax = annualIncomeTax(monthlyTaxable * 12);
  final monthlyTax = _round2(annualTax / 12);

  final gross = _round2(basicPay + taxAllow + nonTaxAllow);
  final net = _round2(gross - contributions - monthlyTax);

  return {
    'basic': basicPay,
    'taxableAllowance': taxAllow,
    'nonTaxableAllowance': nonTaxAllow,
    'gross': gross,
    'sss': sss,
    'philhealth': philhealth,
    'pagibig': pagibig,
    'contributions': contributions,
    'monthlyTaxable': monthlyTaxable,
    'monthlyTax': monthlyTax,
    'annualTax': _round2(annualTax),
    'net': net,
    'ratesYear': ratesYear,
  };
}

/// 3 percent percentage tax on annual gross (non-VAT self-employed).
double percentageTax(num annualGross) {
  final g = _num(annualGross) < 0 ? 0.0 : _num(annualGross);
  return _round2(g * percentageTaxRate);
}

/// The flat 8 percent option. Purely self-employed: first 250,000 exempt.
/// Mixed income: the whole gross is taxed.
double eightPercentTax(num annualGross, {bool mixedIncome = false}) {
  final g = _num(annualGross) < 0 ? 0.0 : _num(annualGross);
  final taxBase =
      mixedIncome ? g : (g - selfEmployedExempt < 0 ? 0.0 : g - selfEmployedExempt);
  return _round2(taxBase * 0.08);
}

/// The graduated option for a self-employed taxpayer: graduated income tax
/// on net (after the 40 percent OSD or itemized expenses), plus the 3
/// percent percentage tax where it applies. For a mixed earner the business
/// net stacks on top of the salary at the marginal rungs.
Map<String, dynamic> graduatedSelfEmployedTax(num annualGross,
    {bool useOSD = true,
    num expenses = 0,
    num salaryTaxable = 0,
    bool vatRegistered = false}) {
  final g = _num(annualGross) < 0 ? 0.0 : _num(annualGross);
  final exp = _num(expenses) < 0 ? 0.0 : _num(expenses);
  final salary = _num(salaryTaxable) < 0 ? 0.0 : _num(salaryTaxable);
  final deduction = useOSD ? _round2(g * 0.4) : (exp > g ? g : exp);
  var net = _round2(g - deduction);
  if (net < 0) net = 0;
  var incomeTax = _round2(annualIncomeTax(salary + net) - annualIncomeTax(salary));
  final pct = vatRegistered ? 0.0 : percentageTax(g);
  if (incomeTax < 0) incomeTax = 0;
  return {
    'deduction': _round2(deduction),
    'net': net,
    'incomeTax': incomeTax,
    'percentageTax': pct,
    'total': _round2(incomeTax + pct),
  };
}

/// Both self-employed regimes compared, with a recommendation. Mirrors the
/// RN engine exactly, including the mixed-earner-without-salary guard and
/// the VAT-threshold gate on the 8 percent option.
Map<String, dynamic> selfEmployedTax(num annualGross,
    {bool mixedIncome = false,
    bool useOSD = true,
    num expenses = 0,
    num salaryTaxable = 0}) {
  final gross = _num(annualGross) < 0 ? 0.0 : _num(annualGross);
  final salary = _num(salaryTaxable) < 0 ? 0.0 : _num(salaryTaxable);
  final eligible8 = gross <= vatThreshold;
  final canCompareGraduated = !mixedIncome || salary > 0;

  final eightTotal = eightPercentTax(gross, mixedIncome: mixedIncome);
  final graduated = graduatedSelfEmployedTax(gross,
      useOSD: useOSD,
      expenses: expenses,
      salaryTaxable: salary,
      vatRegistered: !eligible8);

  final eightPercent = <String, dynamic>{
    'exempt': mixedIncome ? 0.0 : selfEmployedExempt,
    'total': eightTotal,
  };

  String recommended;
  double savings;
  if (!eligible8) {
    recommended = 'graduated';
    savings = 0;
  } else if (!canCompareGraduated) {
    recommended = 'eight';
    savings = 0;
  } else {
    recommended = eightTotal <= (graduated['total'] as double) ? 'eight' : 'graduated';
    savings = _round2(((graduated['total'] as double) - eightTotal).abs());
  }

  final chosenTotal =
      recommended == 'eight' ? eightTotal : graduated['total'] as double;
  final effectiveRate = gross > 0 ? _round2((chosenTotal / gross) * 100) : 0.0;

  return {
    'gross': gross,
    'mixedIncome': mixedIncome,
    'eligible8': eligible8,
    'canCompareGraduated': canCompareGraduated,
    'eightPercent': eightPercent,
    'graduated': graduated,
    'recommended': recommended,
    'savings': savings,
    'effectiveRate': effectiveRate,
    'ratesYear': ratesYear,
  };
}

/// Employee year-end annualization: the year's tax due versus what was
/// withheld, and the refund (positive) or shortfall (negative).
Map<String, dynamic> annualizeCompensation(num basic,
    {num taxableAllowance = 0,
    num? monthsWorked,
    num bonuses = 0,
    num taxWithheld = 0}) {
  final basicPay = _num(basic) < 0 ? 0.0 : _num(basic);
  final taxAllow = _num(taxableAllowance) < 0 ? 0.0 : _num(taxableAllowance);
  final months = monthsWorked == null
      ? 12
      : _jsRound(_num(monthsWorked)).clamp(1, 12).toInt();
  final bon = _num(bonuses) < 0 ? 0.0 : _num(bonuses);
  final withheld = _num(taxWithheld) < 0 ? 0.0 : _num(taxWithheld);

  final monthlyTaxable =
      takeHomePay(basicPay, taxableAllowance: taxAllow)['monthlyTaxable'] as double;
  final regularTaxable = _round2(monthlyTaxable * months);

  var bonusTaxable = _round2(bon - bonusTaxFreeCeiling);
  if (bonusTaxable < 0) bonusTaxable = 0;

  final annualTaxable = _round2(regularTaxable + bonusTaxable);
  final annualTaxDue = annualIncomeTax(annualTaxable);
  final difference = _round2(withheld - annualTaxDue);

  final grossForYear = _round2((basicPay + taxAllow) * months + bon);
  final effectiveRate =
      grossForYear > 0 ? _round2((annualTaxDue / grossForYear) * 100) : 0.0;

  return {
    'regularTaxable': regularTaxable,
    'bonusTaxable': bonusTaxable,
    'annualTaxable': annualTaxable,
    'annualTaxDue': annualTaxDue,
    'taxWithheld': withheld,
    'difference': difference,
    'isRefund': difference > 0,
    'effectiveRate': effectiveRate,
    'monthsWorked': months,
    'ratesYear': ratesYear,
  };
}
