// Moving money between two accounts, ported from the RN saveTransfer that
// lives inline in mobile/app/accounts.js, and golden-locked against that exact
// source (test/goldens/transfer_goldens.json is generated by executing the
// real function body, not by reading it).
//
// A transfer is deliberately NOT income and NOT spending. It moves two
// balances and leaves one record row so History can explain why both changed.
// That row carries no accountId on purpose: the balances moved here, and
// deleting the row later must never move them a second time. Every income,
// expense and budget calculation already skips type 'transfer'.
//
// The whole engine is pure. The screen collects three fields and shows
// whatever comes back; it does no arithmetic of its own, which is the rule
// that put monthlyInterest and whatIfLadder in the money layer too.

import 'debtmath.dart' show formatMoneyText;
import 'ledger.dart' as ledger;

double _jsRound(double x) => (x + 0.5).floorToDouble();

/// Round to the centavo the RN way, so repeated transfers never leave float
/// residue like 0.30000000000000004 in a balance.
double _round2(double x) => _jsRound(x * 100) / 100;

/// JS `Number(str)`, which is stricter than double.tryParse in one direction
/// and looser in three others. The goldens found all four: an empty or
/// whitespace-only string is 0 rather than a failure, a leading + is fine,
/// and 0x, 0o and 0b literals parse as numbers. Anything else JS rejects
/// comes back NaN, and the caller turns that into the "greater than 0"
/// message rather than a wrong balance.
double jsNumber(String raw) {
  final s = raw.trim();
  if (s.isEmpty) return 0;
  final neg = s.startsWith('-');
  final body = (neg || s.startsWith('+')) ? s.substring(1) : s;
  if (body.length > 2 && body[0] == '0') {
    final radix = switch (body[1]) {
      'x' || 'X' => 16,
      'o' || 'O' => 8,
      'b' || 'B' => 2,
      _ => 0,
    };
    if (radix != 0) {
      // A signed radix literal is NaN in JS ("-0x10" is not a number), so
      // only the unsigned form parses.
      if (neg || s.startsWith('+')) return double.nan;
      final v = int.tryParse(body.substring(2), radix: radix);
      return v == null ? double.nan : v.toDouble();
    }
  }
  return double.tryParse(s) ?? double.nan;
}

/// The typed amount, comma and space stripped, coerced and rounded to the
/// centavo exactly as RN does. NaN when the text is not a number at all.
double transferAmount(dynamic raw) {
  final text = (raw ?? '').toString().replaceAll(RegExp(r'[, ]'), '');
  final n = jsNumber(text);
  if (!n.isFinite) return double.nan;
  return _round2(n);
}

/// A balance for the account picker: whole pesos when it is whole, centavos
/// when it has them.
///
/// formatMoneyText rounds to whole pesos, which is right nearly everywhere in
/// the app and wrong here. The render showed why: an account holding 48,500.55
/// displayed as "₱48,501", and moving 48,501 out of it is refused. A screen
/// must not print a number the next tap contradicts.
///
/// The refusal MESSAGE keeps the rounded RN wording on purpose. It is locked
/// to the live app by goldens, and changing an engine string to fix a display
/// problem is how the two apps start disagreeing about more than spelling.
String balanceLabel(num value) {
  final v = value.toDouble();
  if (!v.isFinite) return formatMoneyText(v);
  final centavos = _jsRound(v.abs() * 100) % 100;
  if (centavos == 0) return formatMoneyText(v);
  final whole = formatMoneyText(v.abs().floorToDouble());
  final cents = centavos.toInt().toString().padLeft(2, '0');
  return '${v < 0 ? '-' : ''}$whole.$cents';
}

/// What a transfer attempt produced: either a message to show, or the new
/// store data. Never both, and never neither.
class TransferOutcome {
  final String? error;
  final Map<String, dynamic>? data;
  const TransferOutcome.failed(String this.error) : data = null;
  const TransferOutcome.applied(Map<String, dynamic> this.data) : error = null;
  bool get ok => error == null;
}

List<Map<String, dynamic>> _accounts(Map<String, dynamic> data) {
  final list = data['accounts'];
  return list is List ? list.whereType<Map<String, dynamic>>().toList() : [];
}

Map<String, dynamic>? _find(List<Map<String, dynamic>> accounts, dynamic id) {
  for (final a in accounts) {
    if (a['id'] == id) return a;
  }
  return null;
}

/// Move [amountText] from one account to another, or say why not.
///
/// The three refusals and their wording are the RN ones to the character, and
/// the order they are checked in matters: an amount of zero is reported as an
/// amount problem even when the accounts are also wrong, because that is the
/// first thing the person can fix.
///
/// No overdrafts. A transfer can only move money that is really there, which
/// is also why a negative or unreadable stored balance simply refuses rather
/// than being treated as zero and quietly inventing money.
TransferOutcome applyTransfer(
  Map<String, dynamic> data, {
  required dynamic fromId,
  required dynamic toId,
  required dynamic amountText,
  required String today,
  required String Function() genId,
}) {
  final amount = transferAmount(amountText);
  if (!amount.isFinite || amount <= 0) {
    return const TransferOutcome.failed('Enter an amount greater than 0.');
  }
  if (fromId == null ||
      toId == null ||
      '$fromId'.isEmpty ||
      '$toId'.isEmpty ||
      fromId == toId) {
    return const TransferOutcome.failed('Pick two different accounts.');
  }
  final accounts = _accounts(data);
  final from = _find(accounts, fromId);
  final to = _find(accounts, toId);
  if (from == null || to == null) {
    return const TransferOutcome.failed('Pick two different accounts.');
  }
  final fromBal = ledger.amountOf(from['balance']);
  if (amount > fromBal) {
    return TransferOutcome.failed(
      '${from['name']} only has ${formatMoneyText(fromBal)}.',
    );
  }
  final nextAccounts = [
    for (final a in accounts)
      if (a['id'] == from['id'])
        {...a, 'balance': _round2(fromBal - amount)}
      else if (a['id'] == to['id'])
        {...a, 'balance': _round2(ledger.amountOf(to['balance']) + amount)}
      else
        a,
  ];
  final txs = data['transactions'];
  return TransferOutcome.applied({
    ...data,
    'accounts': nextAccounts,
    'transactions': [
      if (txs is List) ...txs,
      {
        'id': genId(),
        'type': 'transfer',
        'label': 'Transfer: ${from['name']} to ${to['name']}',
        'amount': amount,
        'date': today,
        'transferFromId': from['id'],
        'transferToId': to['id'],
      },
    ],
  });
}
