import 'package:flutter/material.dart';

import '../../core/money/bir_claims.dart';
import '../../core/money/debt_ratio.dart';
import '../../core/money/format.dart';
import '../../core/money/duplicate_balances.dart';
import '../../core/money/money.dart';
import '../../core/money/reports.dart';
import '../../design/tokens.dart';
import '../../design/type.dart';
import '../../features/info/info_dot.dart';
import '../../features/info/info_sheet.dart';
import '../../features/shared/sheet_scaffold.dart';
import '../../models/models.dart';
import '../../state/financial_state.dart';
import 'bir_claims_card.dart';
import 'category_bar.dart';
import 'reconciliation_view.dart';

/// Reports, the prototype's third tab, from archive/prototype-google-ai-studio/src/components/ReportsScreen.tsx.
///
/// Every figure comes out of core/money/reports.dart, which is locked to
/// vectors generated by running the prototype's own arithmetic. This file
/// decides what the screen LOOKS like and nothing about what it says.
///
/// SCOPE, named rather than implied. The prototype's Reports has a fourth
/// tab, Reconciliation, which is the only one that WRITES: it creates an
/// adjustment transaction to force the app's balance to match a real bank
/// balance, and it changes a transaction's status. A write path needs both
/// halves tested (the money, and a journey that taps to every screen which
/// should mention it afterwards), so it is its own batch rather than a fourth
/// tab bolted onto three read-only ones. The tab bar says so on screen rather
/// than leaving a gap somebody has to guess about.
///
/// Also not ported with it: CSV export (nothing in app/ can write a file yet)
/// and the comparison toggle (previous period, budget, forecast), which needs
/// period-over-period history the app does not keep.
class ReportsScreen extends StatefulWidget {
  const ReportsScreen({super.key, required this.state});

  final FinancialState state;

  @override
  State<ReportsScreen> createState() => _ReportsScreenState();
}

enum _ReportTab { position, performance, cashFlow, reconciliation }

/// Money with an explicit minus sign when it is negative.
///
/// [formatPeso] deliberately returns the ABSOLUTE value, because on most
/// screens the sign is carried by a label ("Money out") or an arrow. On this
/// screen it is not: net worth, net cash change and every "Net" row can land
/// on either side of zero, and without this a debt of 217,229.50 renders
/// character for character like savings of 217,229.50.
///
/// Colour alone cannot carry it. Roughly one man in twelve cannot reliably
/// separate the red from the green, and a screenshot, a printout or a
/// greyscale screen loses it for everybody.
/// Was a private copy of what is now formatPesoWithSign in format.dart. Pan
/// lacked the same line and reported a negative net worth as a positive
/// figure, so the two screens disagreed about a sign over one store.
String _signed(double v) => formatPesoWithSign(v);

/// "8 accounts" became a lie on 2026-10-05 and this is what replaced it.
///
/// The two totals it captions are no longer built from accounts alone: debts
/// entered on the Debt screen and instalment plans are in them too. A caption
/// that counts a different population from the figure above it is worse than
/// no caption, because somebody will divide one by the other and get an
/// average that is of nothing.
String _sources(int n) => n == 1 ? '1 entry' : '$n entries';

/// A ratio, or a dash when there is nothing to take a ratio OF.
///
/// Both published ratios return 0 when income is zero or negative
/// (`reports.dart:641` and `:643`). That is correct arithmetic and a terrible
/// reading: pick "This week" in the days before payday, which is exactly when
/// a worried person opens this tab, and the screen reports a savings rate of
/// 0.0% and debt servicing of 0.0% over a week that may hold thousands in loan
/// payments and no pay at all.
///
/// 0.0% is a measurement. The truth is that there is no measurement. A dash
/// says so and cannot be misread as a result.
///
/// The figure passed in is EARNED income, not "Money in", and the difference
/// is the whole point. Both ratios divide by what was earned, so a period
/// whose only inflow was a repayment has money in above zero and nothing to
/// divide by. Asking `totalIncome > 0` here let that case through and printed
/// the engine's "no measurement" zero as "0.0%", which is exactly what this
/// function exists to prevent.
String _ratioText(double ratio, double earnedIncome) =>
    earnedIncome > 0 ? '${ratio.toStringAsFixed(1)}%' : '-';

class _ReportsScreenState extends State<ReportsScreen> {
  _ReportTab _tab = _ReportTab.position;
  ReportPeriod _period = ReportPeriod.monthly;

  @override
  Widget build(BuildContext context) {
    final Palette p = Palette.of(widget.state.theme);

    // ONE call, so the three tabs cannot disagree about which entries they
    // were looking at. The profile comes from the shared store rather than a
    // local field, so switching entity on Activity and coming here does not
    // silently show a different scope.
    final ReportSet r = buildReports(
      transactions: widget.state.transactions,
      accounts: widget.state.accounts,
      period: _period,
      now: widget.state.now,
      profile: widget.state.activeProfile,
      // What a person entered on the Debt and Plans screens is money they
      // owe, and until 2026-10-05 the balance sheet could not see it. A
      // figure that changes depending on WHICH SCREEN a debt was typed into
      // is not a balance sheet.
      debts: widget.state.debts,
      plans: widget.state.installments,
    );

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        _Header(palette: p, profile: widget.state.activeProfile),
        _TabBar(
          palette: p,
          current: _tab,
          onSelect: (_ReportTab t) => setState(() => _tab = t),
        ),
        Expanded(
          child: ListView(
            padding: const EdgeInsets.fromLTRB(
              Spacing.lg,
              Spacing.md,
              Spacing.lg,
              Spacing.xl,
            ),
            children: <Widget>[
              // The period picker is hidden on Position, deliberately. A
              // balance sheet is what you own NOW; offering "this week" beside
              // it would imply the app can show last week's net worth, which
              // needs history it does not keep.
              if (_tab != _ReportTab.position &&
                  _tab != _ReportTab.reconciliation) ...<Widget>[
                _PeriodPicker(
                  palette: p,
                  current: _period,
                  onSelect: (ReportPeriod v) => setState(() => _period = v),
                ),
                const SizedBox(height: Spacing.md),
                _ScopeNote(palette: p, count: r.transactions.length),
                const SizedBox(height: Spacing.lg),
              ],
              switch (_tab) {
                _ReportTab.position => _PositionView(palette: p, report: r),
                _ReportTab.performance => _PerformanceView(
                  palette: p,
                  report: r,
                  period: _period,
                ),
                _ReportTab.cashFlow => _CashFlowView(palette: p, report: r),
                _ReportTab.reconciliation => ReconciliationView(
                  state: widget.state,
                ),
              },
              if (_tab != _ReportTab.reconciliation) ...<Widget>[
                const SizedBox(height: Spacing.lg),
                _ReconciliationNote(palette: p),
              ],
            ],
          ),
        ),
      ],
    );
  }
}

class _Header extends StatelessWidget {
  const _Header({required this.palette, required this.profile});

  final Palette palette;
  final ProfileEntity? profile;

  String get _scopeLabel => switch (profile) {
    null => 'All entities',
    ProfileEntity.personal => 'Personal',
    ProfileEntity.household => 'Household',
    ProfileEntity.business => 'Business',
    ProfileEntity.sideHustle => 'Side hustle',
  };

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(
        Spacing.lg,
        Spacing.md,
        Spacing.lg,
        Spacing.sm,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Text('Reports', style: AppType.title(palette)),
          const SizedBox(height: 2),
          // The scope, and nothing else. This line used to read "What you own,
          // what you earned, where it went" as well, which is a description of
          // the three tabs whose labels sit directly underneath it.
          Text(_scopeLabel, style: AppType.caption(palette)),
        ],
      ),
    );
  }
}

class _TabBar extends StatelessWidget {
  const _TabBar({
    required this.palette,
    required this.current,
    required this.onSelect,
  });

  final Palette palette;
  final _ReportTab current;
  final ValueChanged<_ReportTab> onSelect;

  static const Map<_ReportTab, String> _labels = <_ReportTab, String>{
    _ReportTab.position: 'Position',
    _ReportTab.performance: 'Performance',
    _ReportTab.cashFlow: 'Cash flow',
    _ReportTab.reconciliation: 'Check',
  };

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        border: Border(bottom: BorderSide(color: palette.border)),
      ),
      child: Row(
        children: <Widget>[
          for (final MapEntry<_ReportTab, String> e in _labels.entries)
            Expanded(
              child: Semantics(
                selected: current == e.key,
                button: true,
                child: InkWell(
                  onTap: () => onSelect(e.key),
                  child: Container(
                    // 44 logical pixels is the floor for anything tappable.
                    constraints: const BoxConstraints(minHeight: 44),
                    alignment: Alignment.center,
                    decoration: BoxDecoration(
                      border: Border(
                        bottom: BorderSide(
                          color: current == e.key
                              ? palette.accent
                              : Colors.transparent,
                          width: 2,
                        ),
                      ),
                    ),
                    // A CAP, and a small one, for the same reason the tab bar
                    // has one: four segments share the width of the phone and
                    // the longest of them is a single eleven letter word, so
                    // at 1.5x "Performance" was cut to "Performa...".
                    //
                    // Two lines was tried first and was worse. "Performance"
                    // has no space in it, so there is no line break
                    // opportunity inside it, and Flutter fell back to
                    // breaking between characters: the segment read
                    // "Performa" over "nce", which looks like a rendering
                    // fault rather than a label.
                    //
                    // 1.1 is measured, not chosen. "Performance" needs 85.9dp
                    // and a quarter of a 390dp phone gives it 97.5, so 1.13
                    // is the ceiling and 1.1 is the round number under it.
                    // That is barely any growth and it is said plainly rather
                    // than dressed up: the honest gain here is that the whole
                    // word survives at every font size, not that it gets
                    // bigger. Growing this properly means a scrolling
                    // segmented control or a shorter word, both of which
                    // change the product rather than fix a defect.
                    child: MediaQuery.withClampedTextScaling(
                      maxScaleFactor: 1.1,
                      child: Text(
                        e.value,
                        maxLines: 1,
                        textAlign: TextAlign.center,
                        overflow: TextOverflow.ellipsis,
                        style: AppType.button(
                          palette,
                          color: current == e.key
                              ? palette.accent
                              : palette.textMuted,
                        ),
                      ),
                    ),
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }
}

class _PeriodPicker extends StatelessWidget {
  const _PeriodPicker({
    required this.palette,
    required this.current,
    required this.onSelect,
  });

  final Palette palette;
  final ReportPeriod current;
  final ValueChanged<ReportPeriod> onSelect;

  @override
  Widget build(BuildContext context) {
    // Wrap rather than a Row: six labels do not fit one line on a 320dp phone,
    // and a horizontal scroller hides the options somebody is looking for.
    return Wrap(
      spacing: Spacing.xs,
      runSpacing: Spacing.xs,
      children: <Widget>[
        for (final ReportPeriod p in ReportPeriod.values)
          Semantics(
            selected: p == current,
            button: true,
            child: InkWell(
              onTap: () => onSelect(p),
              borderRadius: BorderRadius.circular(Radii.pill),
              // NO `alignment:` on this Container, and that is the whole
              // reason it is written this way. A Container given an alignment
              // and no width expands to its maximum constraint, so each pill
              // filled the row and the six of them stacked into a column that
              // ate a third of the screen. A Row with mainAxisSize.min sizes
              // to its content and still centres vertically, which is the
              // pattern the Log pill in the shell already uses.
              child: Container(
                constraints: const BoxConstraints(minHeight: 44),
                padding: const EdgeInsets.symmetric(horizontal: Spacing.md),
                decoration: BoxDecoration(
                  color: p == current ? palette.accent : palette.card,
                  borderRadius: BorderRadius.circular(Radii.pill),
                  border: Border.all(
                    color: p == current ? palette.accent : palette.border,
                  ),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    Text(
                      p.label,
                      style: AppType.button(
                        palette,
                        color: p == current
                            ? palette.onAccent
                            : palette.textSecondary,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
      ],
    );
  }
}

/// Says how many entries the figures below were computed from.
///
/// This is not decoration. Every total on this screen is a sum over a set the
/// person cannot see, and "0 entries" is the difference between "I earned
/// nothing this week" and "the filter is wrong".
class _ScopeNote extends StatelessWidget {
  const _ScopeNote({required this.palette, required this.count});

  final Palette palette;
  final int count;

  @override
  Widget build(BuildContext context) {
    final String entries = count == 1 ? '1 entry' : '$count entries';
    return Row(
      children: <Widget>[
        Expanded(
          child: Text(
            // The zero case keeps its reassurance, because an empty report is
            // the state most likely to be read as a broken one. The normal
            // case is now three words instead of a sentence about excluded
            // entries, which is in the explainer.
            count == 0
                ? 'No entries in this period, so nothing to report yet.'
                : 'From $entries',
            style: AppType.caption(palette),
          ),
        ),
        InfoDot(
          color: palette.textMuted,
          semanticLabel: 'What is being counted',
          onTap: () => InfoSheet.show(context, palette, InfoTopic.reportScope),
        ),
      ],
    );
  }
}

class _PositionView extends StatelessWidget {
  const _PositionView({required this.palette, required this.report});

  final Palette palette;
  final ReportSet report;

  @override
  Widget build(BuildContext context) {
    final FinancialPosition p = report.position;
    final bool underwater = p.netWorth.centavos < 0;
    final bool hasMortgage = p.liabilityAccounts.any(
      (Account a) => a.kind == AccountKind.mortgage,
    );
    // Whether the gap the sentence below describes is still a gap. It stopped
    // being one on 2026-10-05 for anybody who records the home itself.
    final bool hasProperty = p.assetAccounts.any(
      (Account a) => a.kind == AccountKind.property,
    );

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        // ABOVE THE FIGURE, NOT BESIDE IT, and the placement is the whole
        // design. A user panel found that a caveat sitting NEXT TO a headline
        // made one archetype distrust the headline itself. Above it, with the
        // reassurance in the same breath, says "read this first, then read
        // the number" instead of "this number is suspect".
        //
        // Nothing renders at all when the books are clean. No green tick, no
        // "all balanced" badge: a permanent reassurance nobody asked for
        // teaches people to read this whole area as decoration, which is
        // exactly what the 2026-09-18 rule rules out.
        if (report.duplicateBalances.isNotEmpty) ...<Widget>[
          _DoubleCountCard(palette: palette, flags: report.duplicateBalances),
          const SizedBox(height: Spacing.md),
        ],
        _SectionCard(
          palette: palette,
          // NOT "Net worth" WHEN IT IS NEGATIVE, on founder decision of
          // 2026-10-05. The arithmetic is unchanged and the figure is the
          // same figure; only the name moves.
          //
          // "Net worth: minus 217,229" is a verdict on a person. "Still to
          // pay off: 217,229" is a job with a finish line, and it is the
          // identical number read from the other end. For the audience this
          // app is for, a deeply negative figure is normal: it is usually one
          // mortgage, taken out deliberately, on a 25 year instrument
          // designed to be largest at the start. A headline that reads as a
          // judgement on a decision somebody already made, and cannot revisit
          // this fortnight, is a number they learn to stop opening.
          //
          // The word "net worth" is not hidden. It is the first line behind
          // the dot, because somebody who meets it at a bank or on a loan
          // form should recognise it.
          title: underwater ? 'Still to pay off' : 'What is really yours',
          topic: InfoTopic.netWorth,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              FittedBox(
                fit: BoxFit.scaleDown,
                alignment: Alignment.centerLeft,
                child: Text(
                  // UNSIGNED when underwater, because the minus sign is doing
                  // the work the old title did. "Still to pay off, minus
                  // 217,229" would read as a negative amount of debt.
                  underwater
                      ? formatPeso(p.netWorth.abs.pesos)
                      : _signed(p.netWorth.pesos),
                  style: AppType.hero(palette).copyWith(
                    color: underwater ? palette.negative : palette.positive,
                  ),
                ),
              ),
              // A = L + E, in the only words that need no glossary, and on
              // the screen rather than behind the dot because it is two
              // figures rather than a lesson. It is also what makes the
              // headline checkable: a person can see where it came from
              // without being told what an identity is.
              const SizedBox(height: 2),
              Text(
                'You own ${formatPeso(p.totalAssets.pesos)} and owe '
                '${formatPeso(p.totalLiabilities.pesos)}.',
                style: AppType.caption(palette),
              ),
              // THE WRONG CONCLUSION STOPPER, and it is now specific rather
              // than reassuring. It used to read "A housing loan alone can do
              // this", which excuses the figure without explaining it.
              //
              // The real reason was a modelling gap: `AccountKind` had no kind
              // for a thing you own outright, so a mortgage entered the ledger
              // with no house on the other side and the figure was not merely
              // unflattering, it was incomplete.
              //
              // THAT GAP IS CLOSEABLE NOW, which is why the sentence is gated
              // on more than a mortgage. Somebody who has recorded the home
              // itself IS having it counted, and telling them otherwise would
              // be the app printing a false statement to the one person who
              // did the thing it asked for. The condition reads "a mortgage
              // and no property", not "a mortgage".
              //
              // The other branch covers somebody underwater on cards alone,
              // who would otherwise be told about a home they do not have.
              if (underwater) ...<Widget>[
                const SizedBox(height: 2),
                Text(
                  hasMortgage && !hasProperty
                      ? 'Your home is not counted here, only the loan on it. '
                            'Add it under Accounts and this balances out.'
                      : 'This counts what you owe in full, including debts '
                            'you are paying down.',
                  style: AppType.caption(palette),
                ),
              ],
            ],
          ),
        ),
        const SizedBox(height: Spacing.md),
        StatPair(
          left: StatCard(
            palette: palette,
            label: 'Assets',
            value: formatPeso(p.totalAssets.pesos),
            caption: _sources(p.assetSourceCount),
            valueColor: palette.positive,
          ),
          right: StatCard(
            palette: palette,
            label: 'Liabilities',
            value: formatPeso(p.totalLiabilities.pesos),
            caption: _sources(p.liabilitySourceCount),
            valueColor: palette.negative,
          ),
        ),
        const SizedBox(height: Spacing.md),
        _SectionCard(
          palette: palette,
          title: 'What you own',
          child: Column(
            children: <Widget>[
              BreakdownRow(
                palette: palette,
                label: 'Cash and e-wallets',
                value: formatPeso(p.cashEquivalents.pesos),
              ),
              BreakdownRow(
                palette: palette,
                label: 'Investments',
                value: formatPeso(p.investments.pesos),
              ),
              BreakdownRow(
                palette: palette,
                label: 'Owed to you',
                value: formatPeso(p.receivables.pesos),
              ),
              Divider(color: palette.border, height: Spacing.lg),
              BreakdownRow(
                palette: palette,
                label: 'Total assets',
                value: formatPeso(p.totalAssets.pesos),
                emphasis: true,
                valueColor: palette.positive,
              ),
            ],
          ),
        ),
        const SizedBox(height: Spacing.md),
        _SectionCard(
          palette: palette,
          title: 'What you owe',
          child: Column(
            children: <Widget>[
              BreakdownRow(
                palette: palette,
                label: 'Credit cards',
                value: formatPeso(p.creditCards.pesos),
              ),
              BreakdownRow(
                palette: palette,
                label: 'Loans and mortgage',
                value: formatPeso(p.loans.pesos),
              ),
              Divider(color: palette.border, height: Spacing.lg),
              BreakdownRow(
                palette: palette,
                label: 'Total liabilities',
                value: formatPeso(p.totalLiabilities.pesos),
                emphasis: true,
                valueColor: palette.negative,
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class _PerformanceView extends StatefulWidget {
  const _PerformanceView({
    required this.palette,
    required this.report,
    required this.period,
  });

  final Palette palette;
  final ReportSet report;
  final ReportPeriod period;

  @override
  State<_PerformanceView> createState() => _PerformanceViewState();
}

class _PerformanceViewState extends State<_PerformanceView> {
  /// Whether the breakdown below is narrowed to claimable receipts.
  ///
  /// Off every time the tab is built, deliberately. A filter that survives
  /// out of sight is how somebody comes back tomorrow, reads "Where it went"
  /// as their whole month, and is short by everything that was not a
  /// business expense. The heading changes with it for the same reason.
  bool _claimableOnly = false;

  @override
  Widget build(BuildContext context) {
    final Palette palette = widget.palette;
    final ReportSet report = widget.report;
    final ReportPeriod period = widget.period;
    final FinancialPerformance f = report.performance;
    final bool positive = f.netSurplus >= 0;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        StatPair(
          left: StatCard(
            palette: palette,
            label: 'Money in',
            value: formatPeso(f.totalIncome),
            valueColor: palette.positive,
          ),
          right: StatCard(
            palette: palette,
            label: 'Money out',
            value: formatPeso(f.totalExpenses),
            valueColor: palette.negative,
          ),
        ),
        // MONEY THAT CAME BACK IS NOT MONEY EARNED, said once, under the
        // figure it qualifies.
        //
        // A repayment collected from somebody who owed you arrives as income
        // in the ledger, so "Money in" counts it, correctly: it really did
        // arrive. It is not earnings though, it is an asset turning back into
        // cash, and the balance sheet already treats it that way. Both
        // published ratios now divide by what was EARNED, so without this
        // line the two figures would silently disagree about one peso.
        if (f.repaymentInflows > 0) ...<Widget>[
          const SizedBox(height: Spacing.xs),
          Text(
            '${formatPeso(f.repaymentInflows)} of this is money coming back '
            'to you, not new money. The rates below leave it out.',
            style: AppType.caption(palette),
          ),
        ],
        const SizedBox(height: Spacing.md),
        _SectionCard(
          palette: palette,
          title: positive ? 'You kept' : 'You overspent by',
          // InfoTopic.performance WAS DEFINED AND UNREACHABLE. No screen
          // opened it, so three explanations (what counts as money in, what
          // counts as money out, and why an excluded entry reaches neither)
          // existed and could not be read by anybody.
          //
          // This card is where they belong rather than a tidy place to park
          // them: the topic's own formula is "Kept = money in - money out",
          // which is this card's hero figure. Hanging it off the Money in and
          // Money out pair instead would have meant inventing a title for the
          // one block on the tab that does not need one.
          //
          // Content nobody can reach cannot be reviewed, and quietly rots.
          // That is how the explainer behind the ratios card came to teach a
          // pass mark the screen had already removed.
          topic: InfoTopic.performance,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              FittedBox(
                fit: BoxFit.scaleDown,
                alignment: Alignment.centerLeft,
                child: Text(
                  formatPeso(f.netSurplus.abs()),
                  style: AppType.hero(palette).copyWith(
                    color: positive ? palette.positive : palette.negative,
                  ),
                ),
              ),
              const SizedBox(height: Spacing.xs),
              Text(
                // `keptRate`, not `savingsRate`. This card is about the cash
                // left over, and the savings rate now counts money moved into
                // an investment as saved, so the two are different numbers
                // and using the wrong one here would make the card contradict
                // its own hero figure.
                positive
                    ? 'That is ${f.keptRate.toStringAsFixed(1)}% of what '
                          'came in.'
                    : 'More went out than came in over this period.',
                style: AppType.caption(palette),
              ),
              // WHERE THE REST WENT, when some of it went somewhere rather
              // than simply out. A figure, not a lesson, so it belongs on the
              // screen: without it a person who put money into MP2 reads a
              // small "kept" figure and concludes they saved nothing.
              if (f.investedOutflows > 0) ...<Widget>[
                const SizedBox(height: Spacing.xs),
                Text(
                  '${formatPeso(f.investedOutflows)} of what went out went '
                  'into investments.',
                  style: AppType.caption(palette),
                ),
              ],
            ],
          ),
        ),
        const SizedBox(height: Spacing.md),
        _SectionCard(
          palette: palette,
          title: 'Two ratios worth watching',
          topic: InfoTopic.ratios,
          child: Column(
            children: <Widget>[
              // NO PASS MARK ON THE SAVINGS RATE, and removing it is a fix
              // rather than a softening.
              //
              // This row used to paint anything under 20 percent in the
              // warning colour. It had no source, and health_check.dart:534
              // REFUSES the same idea in
              // writing: "On an 18,000 to 25,000 Metro Manila salary a twenty
              // percent savings rate after rent is frequently arithmetically
              // impossible, so an absolute target turns the indicator into a
              // monthly notice that somebody doing their best is failing."
              //
              // So one screen declined to judge and the other judged anyway,
              // in orange, over the same ledger. For the public audience D19
              // names, the person most likely to see the warning is the one it
              // helps least.
              //
              // The figure stays. Only the verdict goes.
              //
              // AND THE 20 SURVIVED ANYWAY, for a day, because this comment
              // originally claimed the number "appeared nowhere else in lib/"
              // and nobody checked. It was in info_sheet.dart, on the sheet
              // THIS CARD'S OWN DOT OPENS, still teaching 20 percent as the
              // target. Removing a verdict from a screen does not remove it
              // from the explainer one tap behind the screen, and a claim in
              // a comment is not a search. Both are fixed now.

              // THE DENOMINATOR, shown only when it differs from "Money in".
              //
              // Both rows below divide by what was EARNED, and until this
              // line the only income figure anywhere on the screen was
              // "Money in", which includes money repaid to you. So in any
              // period where somebody paid you back, a reader who divided the
              // visible "Debt payments" by the visible "Money in" got a
              // different percentage from the one printed two rows down.
              //
              // The card already shows the numerator for exactly this reason,
              // and the comment below says why: a percentage whose numerator
              // is invisible cannot be checked. The denominator is the other
              // half of that sentence. A figure that cannot be reconciled
              // reads as a wrong figure, and wrong figures are how an app
              // like this loses somebody.
              //
              // Hidden when there is no repayment, because then it equals
              // "Money in" exactly and a row restating a figure already on
              // screen is the clutter the house rule is about.
              if (f.repaymentInflows > 0)
                BreakdownRow(
                  palette: palette,
                  label: 'Earned',
                  value: formatPeso(f.earnedIncome),
                ),
              BreakdownRow(
                palette: palette,
                label: 'Savings rate',
                value: _ratioText(f.savingsRate, f.earnedIncome),
              ),
              BreakdownRow(
                palette: palette,
                label: 'Debt servicing',
                value: _ratioText(f.debtServiceRatio, f.earnedIncome),
                // THE CANONICAL CONSTANTS, not a number typed here.
                //
                // This compared against a bare 35, under a comment saying
                // lenders commonly use about a third. debt_ratio.dart exists
                // to end exactly that: founder decision F8 sets
                // debtShareComfortable 30 and debtShareStretched 40, and
                // health_check.dart and loan.dart both use them.
                //
                // The 35 made Salapify disagree with itself. At 33 percent
                // this screen stayed quiet while the Health Check called the
                // same ledger stretched. It also sourced itself to lenders,
                // which is a claim this repository refuses to make elsewhere.
                // EARNED income, matching the dash gate above. On totalIncome
                // this read a ratio the engine had set to zero for want of a
                // denominator, and judged it against the bands as though it
                // were measured. It happened to land on textPrimary, so it
                // showed nothing wrong while being wrong.
                valueColor: f.earnedIncome <= 0
                    ? palette.textPrimary
                    : f.debtServiceRatio > debtShareStretched
                    ? palette.negative
                    : f.debtServiceRatio > debtShareComfortable
                    ? palette.warning
                    : palette.textPrimary,
              ),
              // The BAND, as a figure rather than a lesson. Without it the
              // colour is the only hint that a line exists at all, and a
              // colour cannot say where the line is.
              BreakdownRow(
                palette: palette,
                label: 'Comfortable up to',
                value: '$debtShareComfortable%',
              ),
              // THE PESOS BEHIND THE PERCENTAGE. f.debtServicingExpenses was
              // computed and rendered nowhere.
              //
              // The comment that used to sit here said a sentence naming both
              // figures was removed because "both figures were already on the
              // screen". That was true of income and false of this one: the
              // debt payments total appeared on no screen at all. A percentage
              // whose numerator is invisible cannot be checked by the person
              // it describes.
              if (f.debtServicingExpenses > 0)
                BreakdownRow(
                  palette: palette,
                  label: 'Debt payments',
                  value: formatPeso(f.debtServicingExpenses),
                ),
            ],
          ),
        ),
        if (f.businessRevenue > 0 || f.businessExpenses > 0) ...<Widget>[
          const SizedBox(height: Spacing.md),
          _SectionCard(
            palette: palette,
            title: 'Business only',
            child: Column(
              children: <Widget>[
                BreakdownRow(
                  palette: palette,
                  label: 'Revenue',
                  value: formatPeso(f.businessRevenue),
                  valueColor: palette.positive,
                ),
                BreakdownRow(
                  palette: palette,
                  label: 'Expenses',
                  value: formatPeso(f.businessExpenses),
                  valueColor: palette.negative,
                ),
                Divider(color: palette.border, height: Spacing.lg),
                BreakdownRow(
                  palette: palette,
                  label: 'Net profit',
                  value: _signed(f.businessNetProfit),
                  emphasis: true,
                  valueColor: f.businessNetProfit >= 0
                      ? palette.positive
                      : palette.negative,
                ),
              ],
            ),
          ),
        ],
        // The run rate divides by the day of the MONTH whatever period is
        // selected, which is the prototype's behaviour. Showing it on "this
        // year" would project a year onto a month and print a confident
        // nonsense figure, so it appears on the monthly view only.
        if (period == ReportPeriod.monthly) ...<Widget>[
          const SizedBox(height: Spacing.md),
          _SectionCard(
            palette: palette,
            title: 'If the rest of the month looks like this',
            topic: InfoTopic.runRate,
            child: Column(
              children: <Widget>[
                BreakdownRow(
                  palette: palette,
                  label: 'Income by month end',
                  value: formatPeso(f.projectedIncome),
                ),
                BreakdownRow(
                  palette: palette,
                  label: 'Spending by month end',
                  value: formatPeso(f.projectedExpenses),
                ),
                Divider(color: palette.border, height: Spacing.lg),
                BreakdownRow(
                  palette: palette,
                  label: 'Left over',
                  value: _signed(f.projectedSurplus),
                  emphasis: true,
                  valueColor: f.projectedSurplus >= 0
                      ? palette.positive
                      : palette.negative,
                ),
              ],
            ),
          ),
        ],
        const SizedBox(height: Spacing.md),
        BirClaimsCard(
          palette: palette,
          transactions: report.transactions,
          filterOn: _claimableOnly,
          onFilterChanged: (bool v) => setState(() => _claimableOnly = v),
        ),
        const SizedBox(height: Spacing.md),
        _BreakdownSection(
          palette: palette,
          // The title CHANGES with the filter, rather than the rows quietly
          // shrinking under a heading that still says "Where it went". A
          // filtered total under an unfiltered title is a figure somebody
          // reads as their whole month.
          title: _claimableOnly
              ? 'Where it went, claimable only'
              : 'Where it went',
          emptyNote: _claimableOnly
              ? 'Nothing marked as claimable in this period.'
              : 'Nothing spent in this period.',
          rows: _claimableOnly
              ? computeCategoryBreakdown(
                  report.transactions.where(isClaimable).toList(),
                  TransactionType.expense,
                )
              : report.expenseByCategory,
          barColor: palette.negative,
        ),
        const SizedBox(height: Spacing.md),
        _BreakdownSection(
          palette: palette,
          title: 'Where it came from',
          emptyNote: 'Nothing received in this period.',
          rows: report.incomeByCategory,
          barColor: palette.positive,
        ),
      ],
    );
  }
}

class _CashFlowView extends StatelessWidget {
  const _CashFlowView({required this.palette, required this.report});

  final Palette palette;
  final ReportSet report;

  @override
  Widget build(BuildContext context) {
    final CashFlow c = report.cashFlow;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        _SectionCard(
          palette: palette,
          title: 'Net change in cash',
          topic: InfoTopic.cashFlow,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              FittedBox(
                fit: BoxFit.scaleDown,
                alignment: Alignment.centerLeft,
                child: Text(
                  _signed(c.netCashChange),
                  style: AppType.hero(palette).copyWith(
                    color: c.netCashChange >= 0
                        ? palette.positive
                        : palette.negative,
                  ),
                ),
              ),
              const SizedBox(height: 2),
              Text(
                'Operating + investing + financing',
                style: AppType.caption(palette),
              ),
              // A GOOD MONTH LOOKED EXACTLY LIKE A BAD ONE HERE, and this is
              // the sentence that stops it.
              //
              // Put money into MP2 and overpay a loan, which is precisely
              // what this app teaches people to do, and the hero above turns
              // red at hero size. The sections below say why, but nobody
              // reads downward past a red headline about their own money.
              //
              // This clears the one exception to "a figure and the line
              // needed to read it": it is not a lesson, it is a sentence
              // without which the screen punishes the right behaviour.
              //
              // "or" rather than "and", because either one alone can do it
              // and the sections below name which.
              if (c.netCashChange < 0 && c.netOperating > 0) ...<Widget>[
                const SizedBox(height: Spacing.xs),
                Text(
                  'Day to day you came out ahead by '
                  '${formatPeso(c.netOperating)}. The total is below zero '
                  'because money moved into investments or into paying down '
                  'debt, not because you overspent.',
                  style: AppType.caption(palette),
                ),
              ],
            ],
          ),
        ),
        const SizedBox(height: Spacing.md),
        // The three sections carry a two or three word gloss instead of the
        // sentence each used to have. The sentences are in the cash flow
        // explainer, which the card above this one opens: three of them
        // stacked here turned a statement of cash flows into a reading
        // exercise.
        _FlowSection(
          palette: palette,
          title: 'Operating',
          note: 'Everyday living',
          inflows: c.operatingInflows,
          outflows: c.operatingOutflows,
          net: c.netOperating,
        ),
        const SizedBox(height: Spacing.md),
        _FlowSection(
          palette: palette,
          title: 'Investing',
          note: 'Things meant to grow',
          inflows: c.investingInflows,
          outflows: c.investingOutflows,
          net: c.netInvesting,
        ),
        const SizedBox(height: Spacing.md),
        _FlowSection(
          palette: palette,
          title: 'Financing',
          note: 'Loan and card repayments',
          inflows: c.financingInflows,
          outflows: c.financingOutflows,
          net: c.netFinancing,
        ),
        const SizedBox(height: Spacing.md),
        _SectionCard(
          palette: palette,
          title: 'Your own transfers',
          topic: InfoTopic.transfers,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              BreakdownRow(
                palette: palette,
                label: c.transfersCount == 1
                    ? '1 transfer'
                    : '${c.transfersCount} transfers',
                value: formatPeso(c.transfersVolume),
              ),
              const SizedBox(height: 2),
              Text(
                // The short version stays. Somebody who moved 5,000 and sees
                // no total move needs to know that is intended, not that the
                // report lost it, and that is a wrong conclusion rather than
                // a missed lesson. The reasoning is behind the dot.
                'Not counted above, on purpose.',
                style: AppType.caption(palette),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class _FlowSection extends StatelessWidget {
  const _FlowSection({
    required this.palette,
    required this.title,
    required this.note,
    required this.inflows,
    required this.outflows,
    required this.net,
  });

  final Palette palette;
  final String title;
  final String note;
  final double inflows;
  final double outflows;
  final double net;

  @override
  Widget build(BuildContext context) {
    final bool empty = inflows == 0 && outflows == 0;

    // Zero is neither good nor bad. Painting ₱0.00 green reads as a small
    // win and orange reads as a small loss, and it is neither: it means
    // nothing of this kind happened.
    Color colourFor(double v, Color whenNonZero) =>
        v == 0 ? palette.textMuted : whenNonZero;

    return _SectionCard(
      palette: palette,
      title: title,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          BreakdownRow(
            palette: palette,
            label: 'In',
            value: formatPeso(inflows),
            valueColor: colourFor(inflows, palette.positive),
          ),
          BreakdownRow(
            palette: palette,
            label: 'Out',
            value: formatPeso(outflows),
            valueColor: colourFor(outflows, palette.negative),
          ),
          Divider(color: palette.border, height: Spacing.lg),
          BreakdownRow(
            palette: palette,
            label: 'Net',
            value: _signed(net),
            emphasis: true,
            valueColor: colourFor(
              net,
              net >= 0 ? palette.positive : palette.negative,
            ),
          ),
          const SizedBox(height: 2),
          Text(
            // Three zeros with no comment invite the reading that the section
            // is broken, so the empty case still says so. It is four words
            // rather than a sentence.
            empty ? '$note. None this period.' : note,
            style: AppType.caption(palette),
          ),
        ],
      ),
    );
  }
}

class _BreakdownSection extends StatelessWidget {
  const _BreakdownSection({
    required this.palette,
    required this.title,
    required this.emptyNote,
    required this.rows,
    required this.barColor,
  });

  final Palette palette;
  final String title;
  final String emptyNote;
  final List<CategoryBreakdown> rows;
  final Color barColor;

  @override
  Widget build(BuildContext context) {
    return _SectionCard(
      palette: palette,
      title: title,
      child: rows.isEmpty
          ? Text(emptyNote, style: AppType.caption(palette))
          : Column(
              children: <Widget>[
                for (final CategoryBreakdown c in rows)
                  CategoryBar(palette: palette, row: c, barColor: barColor),
              ],
            ),
    );
  }
}

/// Says out loud that the fourth tab is not here, and why.
///
/// A missing tab with no explanation reads as a bug or an oversight. Naming it
/// costs one card and answers the question before it is asked.
class _ReconciliationNote extends StatelessWidget {
  const _ReconciliationNote({required this.palette});

  final Palette palette;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(Spacing.md),
      decoration: BoxDecoration(
        color: palette.surfaceAlt,
        borderRadius: BorderRadius.circular(Radii.control),
        border: Border.all(color: palette.border),
      ),
      // One line and a dot. This card used to be a four line paragraph at the
      // bottom of all three sub-tabs, which is three times the room for a
      // notice about something that does not exist yet.
      child: Row(
        children: <Widget>[
          Icon(Icons.rule, size: 16, color: palette.textMuted),
          const SizedBox(width: Spacing.xs),
          Expanded(
            child: Text(
              'Reconciliation comes next',
              style: AppType.label(palette),
            ),
          ),
          InfoDot(
            color: palette.textMuted,
            semanticLabel: 'What reconciliation will do',
            onTap: () =>
                InfoSheet.show(context, palette, InfoTopic.reconciliation),
          ),
        ],
      ),
    );
  }
}

class _SectionCard extends StatelessWidget {
  const _SectionCard({
    required this.palette,
    required this.title,
    required this.child,
    this.topic,
  });

  final Palette palette;
  final String title;
  final Widget child;

  /// The explainer this card's circled "i" opens, when it has one.
  ///
  /// A card with nothing to teach gets no dot. Putting one on every card
  /// trains people that it never says anything worth reading, and then the
  /// one card that genuinely needs explaining is ignored too.
  final InfoTopic? topic;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(Spacing.md),
      decoration: BoxDecoration(
        color: palette.surface,
        borderRadius: BorderRadius.circular(Radii.card),
        border: Border.all(color: palette.border),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          // The dot sits in the header row rather than below the figures, so
          // it costs no vertical space at all: the kicker line was already
          // there and the 44dp tap target fits inside its height.
          Row(
            children: <Widget>[
              Expanded(
                child: Text(
                  title.toUpperCase(),
                  style: AppType.kicker(palette),
                ),
              ),
              if (topic != null)
                InfoDot(
                  color: palette.textMuted,
                  semanticLabel: 'What $title means',
                  onTap: () => InfoSheet.show(context, palette, topic!),
                ),
            ],
          ),
          SizedBox(height: topic == null ? Spacing.sm : 0),
          child,
        ],
      ),
    );
  }
}

/// One obligation counted twice on the balance sheet, named rather than fixed.
///
/// IT NEVER SUBTRACTS ANYTHING. Every total on this screen stays whole, which
/// is the same policy the runway card uses for duplicated outflows and for
/// the same reason: removing a side would mean the app deciding which record
/// the person meant. An account is the right home for a loan you watch a
/// balance on; a debt row is the right home for one you make payments
/// against. Only they know which they intended.
///
/// OUTLINED, NOT FILLED. A filled warning panel the width of the screen above
/// a net worth figure is a klaxon, and nothing here is an emergency: the
/// money is fine and the bookkeeping has a duplicate in it.
class _DoubleCountCard extends StatelessWidget {
  const _DoubleCountCard({required this.palette, required this.flags});

  final Palette palette;
  final List<SuspectedDuplicateBalance> flags;

  @override
  Widget build(BuildContext context) {
    Money total = Money.zero;
    for (final SuspectedDuplicateBalance f in flags) {
      total += f.amount;
    }

    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(Spacing.md),
      decoration: BoxDecoration(
        color: palette.surface,
        borderRadius: BorderRadius.circular(Radii.card),
        border: Border.all(color: palette.warning),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Row(
            children: <Widget>[
              Icon(
                Icons.content_copy_outlined,
                size: 16,
                color: palette.warning,
              ),
              const SizedBox(width: Spacing.xs),
              Expanded(
                child: Text(
                  'COUNTED TWICE',
                  style: AppType.kicker(
                    palette,
                  ).copyWith(color: palette.warning),
                ),
              ),
            ],
          ),
          const SizedBox(height: Spacing.xs),
          // THE FIGURE, so the person can tell whether this matters at all.
          // 200 pesos recorded twice is a shrug; 16,250 is the difference
          // between two different pictures of somebody's finances.
          Text(formatPeso(total.pesos), style: AppType.amount(palette)),
          const SizedBox(height: 2),
          // WHICH SIDE, when both are affected, and this is a
          // wrong-conclusion stopper rather than detail. The two sides pull
          // net worth in OPPOSITE directions: on the sample ledger 10,000 of
          // what you owe and 6,250 of what you are owed are each counted
          // twice, so the headline figure is out by the difference, 3,750,
          // and not by the 16,250 printed above. Somebody who reads one
          // figure and subtracts it from the other gets a worse answer than
          // if the card had said nothing.
          Text(() {
            Money owed = Money.zero;
            Money owedToYou = Money.zero;
            for (final SuspectedDuplicateBalance f in flags) {
              if (f.isLiability) {
                owed += f.amount;
              } else {
                owedToYou += f.amount;
              }
            }
            if (owed.isPositive && owedToYou.isPositive) {
              return 'is on this page twice: ${formatPeso(owed.pesos)} of '
                  'what you owe, and ${formatPeso(owedToYou.pesos)} of what '
                  'you are owed. They pull in opposite directions, so the '
                  'figure below is out by the difference, not by the total.';
            }
            return flags.length == 1
                ? 'is on this page twice.'
                : 'is on this page twice, across ${flags.length} entries.';
          }(), style: AppType.caption(palette)),
          const SizedBox(height: Spacing.sm),
          // NAMED, every one. A figure with no name sends somebody hunting
          // through two screens for it, and the whole value of this card is
          // that they can go and look.
          for (final SuspectedDuplicateBalance f in flags)
            Padding(
              padding: const EdgeInsets.only(bottom: 2),
              child: Text(
                '${f.accountName} is also recorded as '
                '${f.debtNames.length == 1 ? f.debtNames.first : "${f.debtNames.length} debts"}.',
                style: AppType.caption(palette),
              ),
            ),
          const SizedBox(height: Spacing.xs),
          // THE WRONG CONCLUSION THIS STOPS, and it is the reason the card
          // says anything at all rather than quietly netting the figures off.
          // Somebody who sees a total they did not expect concludes the app
          // is broken. The honest sentence is that the app counted exactly
          // what it was given, twice, because it was given it twice.
          Text(
            'Nothing is wrong with your money. The same amount was entered '
            'in two places, so both totals above include it. Delete whichever '
            'one you do not use and the figures settle.',
            style: AppType.caption(palette),
          ),
        ],
      ),
    );
  }
}
