import 'package:flutter/material.dart';

import '../../core/money/format.dart';
import '../../core/money/reports.dart';
import '../../design/tokens.dart';
import '../../design/type.dart';
import '../../features/info/info_dot.dart';
import '../../features/info/info_sheet.dart';
import '../../features/shared/sheet_scaffold.dart';
import '../../models/models.dart';
import '../../state/financial_state.dart';
import 'category_bar.dart';
import 'reconciliation_view.dart';

/// Reports, the prototype's third tab, from src/components/ReportsScreen.tsx.
///
/// Every figure comes out of core/money/reports.dart, which is locked to
/// vectors generated by running the prototype's own arithmetic. This file
/// decides what the screen LOOKS like and nothing about what it says.
///
/// SCOPE, named rather than implied. The prototype's Reports has a fourth
/// tab, Reconciliation, which is the only one that WRITES: it creates an
/// adjustment transaction to force the app's balance to match a real bank
/// balance, and it changes a transaction's status. A write path needs both
/// halves tested (the money, and a journey that taps to every screen which
/// should mention it afterwards), so it is its own batch rather than a fourth
/// tab bolted onto three read-only ones. The tab bar says so on screen rather
/// than leaving a gap somebody has to guess about.
///
/// Also not ported with it: CSV export (nothing in app/ can write a file yet)
/// and the comparison toggle (previous period, budget, forecast), which needs
/// period-over-period history the app does not keep.
class ReportsScreen extends StatefulWidget {
  const ReportsScreen({super.key, required this.state});

  final FinancialState state;

  @override
  State<ReportsScreen> createState() => _ReportsScreenState();
}

enum _ReportTab { position, performance, cashFlow, reconciliation }

/// Money with an explicit minus sign when it is negative.
///
/// [formatPeso] deliberately returns the ABSOLUTE value, because on most
/// screens the sign is carried by a label ("Money out") or an arrow. On this
/// screen it is not: net worth, net cash change and every "Net" row can land
/// on either side of zero, and without this a debt of 217,229.50 renders
/// character for character like savings of 217,229.50.
///
/// Colour alone cannot carry it. Roughly one man in twelve cannot reliably
/// separate the red from the green, and a screenshot, a printout or a
/// greyscale screen loses it for everybody.
String _signed(double v) => v < 0 ? '-${formatPeso(v)}' : formatPeso(v);

class _ReportsScreenState extends State<ReportsScreen> {
  _ReportTab _tab = _ReportTab.position;
  ReportPeriod _period = ReportPeriod.monthly;

  @override
  Widget build(BuildContext context) {
    final Palette p = Palette.of(widget.state.theme);

    // ONE call, so the three tabs cannot disagree about which entries they
    // were looking at. The profile comes from the shared store rather than a
    // local field, so switching entity on Activity and coming here does not
    // silently show a different scope.
    final ReportSet r = buildReports(
      transactions: widget.state.transactions,
      accounts: widget.state.accounts,
      period: _period,
      now: widget.state.now,
      profile: widget.state.activeProfile,
    );

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        _Header(palette: p, profile: widget.state.activeProfile),
        _TabBar(
          palette: p,
          current: _tab,
          onSelect: (_ReportTab t) => setState(() => _tab = t),
        ),
        Expanded(
          child: ListView(
            padding: const EdgeInsets.fromLTRB(
              Spacing.lg,
              Spacing.md,
              Spacing.lg,
              Spacing.xl,
            ),
            children: <Widget>[
              // The period picker is hidden on Position, deliberately. A
              // balance sheet is what you own NOW; offering "this week" beside
              // it would imply the app can show last week's net worth, which
              // needs history it does not keep.
              if (_tab != _ReportTab.position &&
                  _tab != _ReportTab.reconciliation) ...<Widget>[
                _PeriodPicker(
                  palette: p,
                  current: _period,
                  onSelect: (ReportPeriod v) => setState(() => _period = v),
                ),
                const SizedBox(height: Spacing.md),
                _ScopeNote(palette: p, count: r.transactions.length),
                const SizedBox(height: Spacing.lg),
              ],
              switch (_tab) {
                _ReportTab.position => _PositionView(palette: p, report: r),
                _ReportTab.performance => _PerformanceView(
                  palette: p,
                  report: r,
                  period: _period,
                ),
                _ReportTab.cashFlow => _CashFlowView(palette: p, report: r),
                _ReportTab.reconciliation => ReconciliationView(
                  state: widget.state,
                ),
              },
              if (_tab != _ReportTab.reconciliation) ...<Widget>[
                const SizedBox(height: Spacing.lg),
                _ReconciliationNote(palette: p),
              ],
            ],
          ),
        ),
      ],
    );
  }
}

class _Header extends StatelessWidget {
  const _Header({required this.palette, required this.profile});

  final Palette palette;
  final ProfileEntity? profile;

  String get _scopeLabel => switch (profile) {
    null => 'All entities',
    ProfileEntity.personal => 'Personal',
    ProfileEntity.household => 'Household',
    ProfileEntity.business => 'Business',
    ProfileEntity.sideHustle => 'Side hustle',
  };

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(
        Spacing.lg,
        Spacing.md,
        Spacing.lg,
        Spacing.sm,
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Text('Reports', style: AppType.title(palette)),
          const SizedBox(height: 2),
          // The scope, and nothing else. This line used to read "What you own,
          // what you earned, where it went" as well, which is a description of
          // the three tabs whose labels sit directly underneath it.
          Text(_scopeLabel, style: AppType.caption(palette)),
        ],
      ),
    );
  }
}

class _TabBar extends StatelessWidget {
  const _TabBar({
    required this.palette,
    required this.current,
    required this.onSelect,
  });

  final Palette palette;
  final _ReportTab current;
  final ValueChanged<_ReportTab> onSelect;

  static const Map<_ReportTab, String> _labels = <_ReportTab, String>{
    _ReportTab.position: 'Position',
    _ReportTab.performance: 'Performance',
    _ReportTab.cashFlow: 'Cash flow',
    _ReportTab.reconciliation: 'Check',
  };

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        border: Border(bottom: BorderSide(color: palette.border)),
      ),
      child: Row(
        children: <Widget>[
          for (final MapEntry<_ReportTab, String> e in _labels.entries)
            Expanded(
              child: Semantics(
                selected: current == e.key,
                button: true,
                child: InkWell(
                  onTap: () => onSelect(e.key),
                  child: Container(
                    // 44 logical pixels is the floor for anything tappable.
                    constraints: const BoxConstraints(minHeight: 44),
                    alignment: Alignment.center,
                    decoration: BoxDecoration(
                      border: Border(
                        bottom: BorderSide(
                          color: current == e.key
                              ? palette.accent
                              : Colors.transparent,
                          width: 2,
                        ),
                      ),
                    ),
                    child: Text(
                      e.value,
                      maxLines: 1,
                      overflow: TextOverflow.ellipsis,
                      style: AppType.button(
                        palette,
                        color: current == e.key
                            ? palette.accent
                            : palette.textMuted,
                      ),
                    ),
                  ),
                ),
              ),
            ),
        ],
      ),
    );
  }
}

class _PeriodPicker extends StatelessWidget {
  const _PeriodPicker({
    required this.palette,
    required this.current,
    required this.onSelect,
  });

  final Palette palette;
  final ReportPeriod current;
  final ValueChanged<ReportPeriod> onSelect;

  @override
  Widget build(BuildContext context) {
    // Wrap rather than a Row: six labels do not fit one line on a 320dp phone,
    // and a horizontal scroller hides the options somebody is looking for.
    return Wrap(
      spacing: Spacing.xs,
      runSpacing: Spacing.xs,
      children: <Widget>[
        for (final ReportPeriod p in ReportPeriod.values)
          Semantics(
            selected: p == current,
            button: true,
            child: InkWell(
              onTap: () => onSelect(p),
              borderRadius: BorderRadius.circular(Radii.pill),
              // NO `alignment:` on this Container, and that is the whole
              // reason it is written this way. A Container given an alignment
              // and no width expands to its maximum constraint, so each pill
              // filled the row and the six of them stacked into a column that
              // ate a third of the screen. A Row with mainAxisSize.min sizes
              // to its content and still centres vertically, which is the
              // pattern the Log pill in the shell already uses.
              child: Container(
                constraints: const BoxConstraints(minHeight: 44),
                padding: const EdgeInsets.symmetric(horizontal: Spacing.md),
                decoration: BoxDecoration(
                  color: p == current ? palette.accent : palette.card,
                  borderRadius: BorderRadius.circular(Radii.pill),
                  border: Border.all(
                    color: p == current ? palette.accent : palette.border,
                  ),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  children: <Widget>[
                    Text(
                      p.label,
                      style: AppType.button(
                        palette,
                        color: p == current
                            ? palette.onAccent
                            : palette.textSecondary,
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
      ],
    );
  }
}

/// Says how many entries the figures below were computed from.
///
/// This is not decoration. Every total on this screen is a sum over a set the
/// person cannot see, and "0 entries" is the difference between "I earned
/// nothing this week" and "the filter is wrong".
class _ScopeNote extends StatelessWidget {
  const _ScopeNote({required this.palette, required this.count});

  final Palette palette;
  final int count;

  @override
  Widget build(BuildContext context) {
    final String entries = count == 1 ? '1 entry' : '$count entries';
    return Row(
      children: <Widget>[
        Expanded(
          child: Text(
            // The zero case keeps its reassurance, because an empty report is
            // the state most likely to be read as a broken one. The normal
            // case is now three words instead of a sentence about excluded
            // entries, which is in the explainer.
            count == 0
                ? 'No entries in this period, so nothing to report yet.'
                : 'From $entries',
            style: AppType.caption(palette),
          ),
        ),
        InfoDot(
          color: palette.textMuted,
          semanticLabel: 'What is being counted',
          onTap: () => InfoSheet.show(context, palette, InfoTopic.reportScope),
        ),
      ],
    );
  }
}

class _PositionView extends StatelessWidget {
  const _PositionView({required this.palette, required this.report});

  final Palette palette;
  final ReportSet report;

  @override
  Widget build(BuildContext context) {
    final FinancialPosition p = report.position;
    final bool underwater = p.netWorth < 0;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        _SectionCard(
          palette: palette,
          title: 'Net worth',
          topic: InfoTopic.netWorth,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              FittedBox(
                fit: BoxFit.scaleDown,
                alignment: Alignment.centerLeft,
                child: Text(
                  _signed(p.netWorth),
                  style: AppType.hero(palette).copyWith(
                    color: underwater ? palette.negative : palette.positive,
                  ),
                ),
              ),
              // ONE short line when the figure is negative, and nothing at all
              // when it is not. The full explanation moved behind the dot.
              //
              // This line stays on the screen while the rest went, and the
              // distinction is the rule: seeing minus two hundred thousand is
              // alarming, and alarm is the worst moment to ask somebody to go
              // hunting for reassurance. Everything that TEACHES is one tap
              // away; the one clause that stops a wrong conclusion is not.
              if (underwater) ...<Widget>[
                const SizedBox(height: 2),
                Text(
                  'A housing loan alone can do this.',
                  style: AppType.caption(palette),
                ),
              ],
            ],
          ),
        ),
        const SizedBox(height: Spacing.md),
        StatPair(
          left: StatCard(
            palette: palette,
            label: 'Assets',
            value: formatPeso(p.totalAssets),
            caption: '${p.assetAccounts.length} accounts',
            valueColor: palette.positive,
          ),
          right: StatCard(
            palette: palette,
            label: 'Liabilities',
            value: formatPeso(p.totalLiabilities),
            caption: '${p.liabilityAccounts.length} accounts',
            valueColor: palette.negative,
          ),
        ),
        const SizedBox(height: Spacing.md),
        _SectionCard(
          palette: palette,
          title: 'What you own',
          child: Column(
            children: <Widget>[
              BreakdownRow(
                palette: palette,
                label: 'Cash and e-wallets',
                value: formatPeso(p.cashEquivalents),
              ),
              BreakdownRow(
                palette: palette,
                label: 'Investments',
                value: formatPeso(p.investments),
              ),
              BreakdownRow(
                palette: palette,
                label: 'Owed to you',
                value: formatPeso(p.receivables),
              ),
              Divider(color: palette.border, height: Spacing.lg),
              BreakdownRow(
                palette: palette,
                label: 'Total assets',
                value: formatPeso(p.totalAssets),
                emphasis: true,
                valueColor: palette.positive,
              ),
            ],
          ),
        ),
        const SizedBox(height: Spacing.md),
        _SectionCard(
          palette: palette,
          title: 'What you owe',
          child: Column(
            children: <Widget>[
              BreakdownRow(
                palette: palette,
                label: 'Credit cards',
                value: formatPeso(p.creditCards),
              ),
              BreakdownRow(
                palette: palette,
                label: 'Loans and mortgage',
                value: formatPeso(p.loans),
              ),
              Divider(color: palette.border, height: Spacing.lg),
              BreakdownRow(
                palette: palette,
                label: 'Total liabilities',
                value: formatPeso(p.totalLiabilities),
                emphasis: true,
                valueColor: palette.negative,
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class _PerformanceView extends StatelessWidget {
  const _PerformanceView({
    required this.palette,
    required this.report,
    required this.period,
  });

  final Palette palette;
  final ReportSet report;
  final ReportPeriod period;

  @override
  Widget build(BuildContext context) {
    final FinancialPerformance f = report.performance;
    final bool positive = f.netSurplus >= 0;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        StatPair(
          left: StatCard(
            palette: palette,
            label: 'Money in',
            value: formatPeso(f.totalIncome),
            valueColor: palette.positive,
          ),
          right: StatCard(
            palette: palette,
            label: 'Money out',
            value: formatPeso(f.totalExpenses),
            valueColor: palette.negative,
          ),
        ),
        const SizedBox(height: Spacing.md),
        _SectionCard(
          palette: palette,
          title: positive ? 'You kept' : 'You overspent by',
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              FittedBox(
                fit: BoxFit.scaleDown,
                alignment: Alignment.centerLeft,
                child: Text(
                  formatPeso(f.netSurplus.abs()),
                  style: AppType.hero(palette).copyWith(
                    color: positive ? palette.positive : palette.negative,
                  ),
                ),
              ),
              const SizedBox(height: Spacing.xs),
              Text(
                positive
                    ? 'That is ${f.savingsRate.toStringAsFixed(1)}% of what '
                          'came in.'
                    : 'More went out than came in over this period.',
                style: AppType.caption(palette),
              ),
            ],
          ),
        ),
        const SizedBox(height: Spacing.md),
        _SectionCard(
          palette: palette,
          title: 'Two ratios worth watching',
          topic: InfoTopic.ratios,
          child: Column(
            children: <Widget>[
              BreakdownRow(
                palette: palette,
                label: 'Savings rate',
                value: '${f.savingsRate.toStringAsFixed(1)}%',
                valueColor: f.savingsRate >= 20
                    ? palette.positive
                    : palette.warning,
              ),
              BreakdownRow(
                palette: palette,
                label: 'Debt servicing',
                value: '${f.debtServiceRatio.toStringAsFixed(1)}%',
                // Lenders in the Philippines commonly look for total debt
                // servicing under about a third of income. Over that and the
                // number is worth seeing in a warning colour rather than
                // sitting quietly in the same grey as everything else.
                valueColor: f.debtServiceRatio > 35
                    ? palette.negative
                    : palette.textPrimary,
              ),
              // The sentence that spelled out "4,950 of loan repayments
              // against 51,000 of income" is gone. Both figures were already
              // on the screen, one of them twice, so it explained the
              // arithmetic of a percentage rather than telling anybody
              // anything.
            ],
          ),
        ),
        if (f.businessRevenue > 0 || f.businessExpenses > 0) ...<Widget>[
          const SizedBox(height: Spacing.md),
          _SectionCard(
            palette: palette,
            title: 'Business only',
            child: Column(
              children: <Widget>[
                BreakdownRow(
                  palette: palette,
                  label: 'Revenue',
                  value: formatPeso(f.businessRevenue),
                  valueColor: palette.positive,
                ),
                BreakdownRow(
                  palette: palette,
                  label: 'Expenses',
                  value: formatPeso(f.businessExpenses),
                  valueColor: palette.negative,
                ),
                Divider(color: palette.border, height: Spacing.lg),
                BreakdownRow(
                  palette: palette,
                  label: 'Net profit',
                  value: _signed(f.businessNetProfit),
                  emphasis: true,
                  valueColor: f.businessNetProfit >= 0
                      ? palette.positive
                      : palette.negative,
                ),
              ],
            ),
          ),
        ],
        // The run rate divides by the day of the MONTH whatever period is
        // selected, which is the prototype's behaviour. Showing it on "this
        // year" would project a year onto a month and print a confident
        // nonsense figure, so it appears on the monthly view only.
        if (period == ReportPeriod.monthly) ...<Widget>[
          const SizedBox(height: Spacing.md),
          _SectionCard(
            palette: palette,
            title: 'If the rest of the month looks like this',
            topic: InfoTopic.runRate,
            child: Column(
              children: <Widget>[
                BreakdownRow(
                  palette: palette,
                  label: 'Income by month end',
                  value: formatPeso(f.projectedIncome),
                ),
                BreakdownRow(
                  palette: palette,
                  label: 'Spending by month end',
                  value: formatPeso(f.projectedExpenses),
                ),
                Divider(color: palette.border, height: Spacing.lg),
                BreakdownRow(
                  palette: palette,
                  label: 'Left over',
                  value: _signed(f.projectedSurplus),
                  emphasis: true,
                  valueColor: f.projectedSurplus >= 0
                      ? palette.positive
                      : palette.negative,
                ),
              ],
            ),
          ),
        ],
        const SizedBox(height: Spacing.md),
        _BreakdownSection(
          palette: palette,
          title: 'Where it went',
          emptyNote: 'Nothing spent in this period.',
          rows: report.expenseByCategory,
          barColor: palette.negative,
        ),
        const SizedBox(height: Spacing.md),
        _BreakdownSection(
          palette: palette,
          title: 'Where it came from',
          emptyNote: 'Nothing received in this period.',
          rows: report.incomeByCategory,
          barColor: palette.positive,
        ),
      ],
    );
  }
}

class _CashFlowView extends StatelessWidget {
  const _CashFlowView({required this.palette, required this.report});

  final Palette palette;
  final ReportSet report;

  @override
  Widget build(BuildContext context) {
    final CashFlow c = report.cashFlow;

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: <Widget>[
        _SectionCard(
          palette: palette,
          title: 'Net change in cash',
          topic: InfoTopic.cashFlow,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              FittedBox(
                fit: BoxFit.scaleDown,
                alignment: Alignment.centerLeft,
                child: Text(
                  _signed(c.netCashChange),
                  style: AppType.hero(palette).copyWith(
                    color: c.netCashChange >= 0
                        ? palette.positive
                        : palette.negative,
                  ),
                ),
              ),
              const SizedBox(height: 2),
              Text(
                'Operating + investing + financing',
                style: AppType.caption(palette),
              ),
            ],
          ),
        ),
        const SizedBox(height: Spacing.md),
        // The three sections carry a two or three word gloss instead of the
        // sentence each used to have. The sentences are in the cash flow
        // explainer, which the card above this one opens: three of them
        // stacked here turned a statement of cash flows into a reading
        // exercise.
        _FlowSection(
          palette: palette,
          title: 'Operating',
          note: 'Everyday living',
          inflows: c.operatingInflows,
          outflows: c.operatingOutflows,
          net: c.netOperating,
        ),
        const SizedBox(height: Spacing.md),
        _FlowSection(
          palette: palette,
          title: 'Investing',
          note: 'Things meant to grow',
          inflows: c.investingInflows,
          outflows: c.investingOutflows,
          net: c.netInvesting,
        ),
        const SizedBox(height: Spacing.md),
        _FlowSection(
          palette: palette,
          title: 'Financing',
          note: 'Loan and card repayments',
          inflows: c.financingInflows,
          outflows: c.financingOutflows,
          net: c.netFinancing,
        ),
        const SizedBox(height: Spacing.md),
        _SectionCard(
          palette: palette,
          title: 'Your own transfers',
          topic: InfoTopic.transfers,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: <Widget>[
              BreakdownRow(
                palette: palette,
                label: c.transfersCount == 1
                    ? '1 transfer'
                    : '${c.transfersCount} transfers',
                value: formatPeso(c.transfersVolume),
              ),
              const SizedBox(height: 2),
              Text(
                // The short version stays. Somebody who moved 5,000 and sees
                // no total move needs to know that is intended, not that the
                // report lost it, and that is a wrong conclusion rather than
                // a missed lesson. The reasoning is behind the dot.
                'Not counted above, on purpose.',
                style: AppType.caption(palette),
              ),
            ],
          ),
        ),
      ],
    );
  }
}

class _FlowSection extends StatelessWidget {
  const _FlowSection({
    required this.palette,
    required this.title,
    required this.note,
    required this.inflows,
    required this.outflows,
    required this.net,
  });

  final Palette palette;
  final String title;
  final String note;
  final double inflows;
  final double outflows;
  final double net;

  @override
  Widget build(BuildContext context) {
    final bool empty = inflows == 0 && outflows == 0;

    // Zero is neither good nor bad. Painting ₱0.00 green reads as a small
    // win and orange reads as a small loss, and it is neither: it means
    // nothing of this kind happened.
    Color colourFor(double v, Color whenNonZero) =>
        v == 0 ? palette.textMuted : whenNonZero;

    return _SectionCard(
      palette: palette,
      title: title,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          BreakdownRow(
            palette: palette,
            label: 'In',
            value: formatPeso(inflows),
            valueColor: colourFor(inflows, palette.positive),
          ),
          BreakdownRow(
            palette: palette,
            label: 'Out',
            value: formatPeso(outflows),
            valueColor: colourFor(outflows, palette.negative),
          ),
          Divider(color: palette.border, height: Spacing.lg),
          BreakdownRow(
            palette: palette,
            label: 'Net',
            value: _signed(net),
            emphasis: true,
            valueColor: colourFor(
              net,
              net >= 0 ? palette.positive : palette.negative,
            ),
          ),
          const SizedBox(height: 2),
          Text(
            // Three zeros with no comment invite the reading that the section
            // is broken, so the empty case still says so. It is four words
            // rather than a sentence.
            empty ? '$note. None this period.' : note,
            style: AppType.caption(palette),
          ),
        ],
      ),
    );
  }
}

class _BreakdownSection extends StatelessWidget {
  const _BreakdownSection({
    required this.palette,
    required this.title,
    required this.emptyNote,
    required this.rows,
    required this.barColor,
  });

  final Palette palette;
  final String title;
  final String emptyNote;
  final List<CategoryBreakdown> rows;
  final Color barColor;

  @override
  Widget build(BuildContext context) {
    return _SectionCard(
      palette: palette,
      title: title,
      child: rows.isEmpty
          ? Text(emptyNote, style: AppType.caption(palette))
          : Column(
              children: <Widget>[
                for (final CategoryBreakdown c in rows)
                  CategoryBar(palette: palette, row: c, barColor: barColor),
              ],
            ),
    );
  }
}

/// Says out loud that the fourth tab is not here, and why.
///
/// A missing tab with no explanation reads as a bug or an oversight. Naming it
/// costs one card and answers the question before it is asked.
class _ReconciliationNote extends StatelessWidget {
  const _ReconciliationNote({required this.palette});

  final Palette palette;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(Spacing.md),
      decoration: BoxDecoration(
        color: palette.surfaceAlt,
        borderRadius: BorderRadius.circular(Radii.control),
        border: Border.all(color: palette.border),
      ),
      // One line and a dot. This card used to be a four line paragraph at the
      // bottom of all three sub-tabs, which is three times the room for a
      // notice about something that does not exist yet.
      child: Row(
        children: <Widget>[
          Icon(Icons.rule, size: 16, color: palette.textMuted),
          const SizedBox(width: Spacing.xs),
          Expanded(
            child: Text(
              'Reconciliation comes next',
              style: AppType.label(palette),
            ),
          ),
          InfoDot(
            color: palette.textMuted,
            semanticLabel: 'What reconciliation will do',
            onTap: () =>
                InfoSheet.show(context, palette, InfoTopic.reconciliation),
          ),
        ],
      ),
    );
  }
}

class _SectionCard extends StatelessWidget {
  const _SectionCard({
    required this.palette,
    required this.title,
    required this.child,
    this.topic,
  });

  final Palette palette;
  final String title;
  final Widget child;

  /// The explainer this card's circled "i" opens, when it has one.
  ///
  /// A card with nothing to teach gets no dot. Putting one on every card
  /// trains people that it never says anything worth reading, and then the
  /// one card that genuinely needs explaining is ignored too.
  final InfoTopic? topic;

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.all(Spacing.md),
      decoration: BoxDecoration(
        color: palette.surface,
        borderRadius: BorderRadius.circular(Radii.card),
        border: Border.all(color: palette.border),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          // The dot sits in the header row rather than below the figures, so
          // it costs no vertical space at all: the kicker line was already
          // there and the 44dp tap target fits inside its height.
          Row(
            children: <Widget>[
              Expanded(
                child: Text(
                  title.toUpperCase(),
                  style: AppType.kicker(palette),
                ),
              ),
              if (topic != null)
                InfoDot(
                  color: palette.textMuted,
                  semanticLabel: 'What $title means',
                  onTap: () => InfoSheet.show(context, palette, topic!),
                ),
            ],
          ),
          SizedBox(height: topic == null ? Spacing.sm : 0),
          child,
        ],
      ),
    );
  }
}
