import 'package:flutter/material.dart';

import '../../core/money/format.dart';
import '../../core/money/split_bill.dart';
import '../../design/tokens.dart';
import '../../design/type.dart';
import '../../models/models.dart';
import '../../state/financial_state.dart';
import '../shared/sheet_scaffold.dart';
import 'package:salapify/core/money/money.dart';

/// Splitting a bill, and turning the result into debts.
///
/// Ported from `archive/prototype-google-ai-studio/src/components/SplitBillModal.tsx` on founder direction,
/// 2026-10-01 ("do the Split Bill"). The arithmetic lives in
/// `core/money/split_bill.dart` behind twenty six golden vectors generated by
/// running the prototype's own engine; nothing on this screen computes a peso.
///
/// ## Two founder decisions, both differing from the prototype
///
/// 1. Debts are created at the EXACT share, including centavos. The prototype
///    wraps every share in Math.round before creating the debt, so a 1,000
///    bill split three ways creates two debts of 333 against shares of
///    333.33, and 67 centavos disappear from the ledger with nothing said.
///    Founder chose the exact figure.
/// 2. The expense is logged with a tick box, and the person picks the account
///    AND the category. The prototype hardcodes the category to Food & Dining
///    unless the split is a business one, which is the same defect this
///    repository already refused to port from the quick-log parser.
///
/// ## What is NOT ported
///
/// `createExpenseSplit`, the prototype's collaboration record. Collaboration
/// is not being built: the prototype's hub makes no network call and its own
/// types describe the member switcher as a local persona simulation, so a
/// stored "shared expense" would tell somebody a friend can see this when
/// nobody can. The debts carry the whole meaning on their own.
///
/// The prototype's default participant is named "Carla" and its default
/// description is "Barkada Lunch". Both are placeholder data that would ship
/// as a stranger's name pre-filled into a money form, so neither is ported.
/// What one tap on Record it actually wrote.
///
/// The sheet used to hand back a bare `true`, and Home threw even that away,
/// so a split saved with no confirmation and no way back: real money left an
/// account and the only screen that could have said so said nothing. This
/// carries the records themselves rather than their ids, because the undo
/// that reads it must be unable to ask for the removal of something it has
/// not got in front of it.
///
/// [accountName] is resolved HERE rather than by the caller. The sheet knows
/// for certain which account it spent from; a caller looking the id up again
/// afterwards is one deleted account away from throwing while trying to
/// display a reassurance.
class SplitBillResult {
  const SplitBillResult({
    required this.transaction,
    required this.debts,
    required this.accountName,
  });

  /// The expense, or null when the person unticked the box or had no account
  /// to spend from. A split with no expense is perfectly ordinary: somebody
  /// else paid and all that happened is that you now owe them.
  final Transaction? transaction;

  /// Every debt the split created, in the order it created them.
  final List<Debt> debts;

  /// The account the expense came out of, for the confirmation sentence.
  /// Null exactly when [transaction] is.
  final String? accountName;
}

class SplitBillSheet extends StatefulWidget {
  const SplitBillSheet({super.key, required this.palette, required this.state});

  final Palette palette;
  final FinancialState state;

  static Future<SplitBillResult?> show(
    BuildContext context, {
    required Palette palette,
    required FinancialState state,
  }) {
    return SheetScaffold.show<SplitBillResult>(
      context: context,
      palette: palette,
      builder: (BuildContext context) =>
          SplitBillSheet(palette: palette, state: state),
    );
  }

  @override
  State<SplitBillSheet> createState() => _SplitBillSheetState();
}

/// One row of the participant list.
///
/// The input controller is per person and per METHOD, because a percentage
/// and a fixed amount are different numbers about the same person and
/// swapping method should not carry one into the other.
class _Person {
  _Person(this.name, {this.isMe = false});

  final String name;
  final bool isMe;
  final TextEditingController percent = TextEditingController();
  final TextEditingController fixed = TextEditingController();
  final TextEditingController shares = TextEditingController();

  void dispose() {
    percent.dispose();
    fixed.dispose();
    shares.dispose();
  }
}

/// One debt Record it is going to create, before it has an id or a date.
///
/// Deliberately not a [Debt]. A Debt is a stored record and building one to
/// describe a hypothetical invites somebody to save it by accident; this
/// carries only what the sentence above the button and the save both need.
class _PlannedDebt {
  const _PlannedDebt({
    required this.person,
    required this.amount,
    required this.direction,
  });

  final String person;
  final double amount;
  final DebtDirection direction;
}

class _SplitBillSheetState extends State<SplitBillSheet> {
  final TextEditingController _total = TextEditingController();
  final TextEditingController _what = TextEditingController();
  final TextEditingController _newName = TextEditingController();

  SplitMethod _method = SplitMethod.equal;

  /// "You" is always first and cannot be removed. Everybody else is somebody
  /// the person typed in; there is no address book to draw from and inventing
  /// a name is what the prototype did.
  final List<_Person> _people = <_Person>[_Person('You', isMe: true)];

  /// Who actually paid. Defaults to you, which is the common case.
  String _payer = 'You';

  bool _logExpense = true;
  String? _accountId;
  String _category = 'Food & Dining';

  @override
  void initState() {
    super.initState();
    final List<Account> accounts = widget.state.accounts;
    if (accounts.isNotEmpty) _accountId = accounts.first.id;
  }

  @override
  void dispose() {
    _total.dispose();
    _what.dispose();
    _newName.dispose();
    for (final _Person p in _people) {
      p.dispose();
    }
    super.dispose();
  }

  double get _bill => double.tryParse(_total.text.trim()) ?? 0;

  Map<String, double> get _inputs {
    final Map<String, double> out = <String, double>{};
    for (final _Person p in _people) {
      final TextEditingController c = switch (_method) {
        SplitMethod.percentage => p.percent,
        SplitMethod.fixed => p.fixed,
        SplitMethod.shares => p.shares,
        SplitMethod.equal => p.percent,
      };
      final double? v = double.tryParse(c.text.trim());
      if (v != null) out[p.name] = v;
    }
    return out;
  }

  List<SplitShare> get _shares => calculateSplitShares(
    total: _bill,
    method: _method,
    names: _people.map((_Person p) => p.name).toList(growable: false),
    inputs: _inputs,
  );

  void _addPerson() {
    final String name = _newName.text.trim();
    if (name.isEmpty) return;
    // Case-insensitive, because two debts against "Carla" and "carla" are two
    // people as far as every screen that groups by name is concerned.
    if (_people.any(
      (_Person p) => p.name.toLowerCase() == name.toLowerCase(),
    )) {
      return;
    }
    setState(() {
      _people.add(_Person(name));
      _newName.clear();
    });
  }

  void _removePerson(_Person person) {
    if (person.isMe) return;
    setState(() {
      _people.remove(person);
      person.dispose();
      // The payer cannot be somebody who is no longer on the list.
      if (_payer == person.name) _payer = 'You';
    });
  }

  bool get _canSave => _bill > 0 && _people.length >= 2 && _shares.isNotEmpty;

  /// Exactly what Record it would write, worked out in ONE place.
  ///
  /// The sentence above the button and [_save] both read this, and that is
  /// the whole reason it exists. The first draft had the caption counting
  /// the debts for itself, which is the shape of defect this feature has
  /// already produced four times over: a rule applied at one entry point and
  /// not the others, so the sentence promises three debts while the save
  /// writes two, and the person is told something untrue about their money
  /// one tap before it happens.
  ///
  /// It decides nothing on its own. Every branch below is lifted from what
  /// [_save] already did; moving them here is a refactor, not a rule change.
  ({List<_PlannedDebt> debts, double leaving}) get _plan {
    final List<SplitShare> shares = _shares;
    final bool iPaid = _payer == 'You';
    final double myShare = shares
        .firstWhere(
          (SplitShare s) => s.name == 'You',
          orElse: () => const SplitShare(name: 'You', amount: 0, percentage: 0),
        )
        .amount;

    final List<_PlannedDebt> debts = <_PlannedDebt>[
      for (final SplitShare s in shares)
        if (s.name != 'You')
          if (iPaid && s.amount > 0)
            _PlannedDebt(
              person: s.name,
              amount: s.amount,
              direction: DebtDirection.owedToMe,
            )
          else if (s.name == _payer && myShare > 0)
            _PlannedDebt(
              person: _payer,
              amount: myShare,
              direction: DebtDirection.iOwe,
            ),
    ];

    // The FULL bill if you paid it, your share if somebody else did. That is
    // the prototype's rule and it is right: money left your account for the
    // whole bill, and the debts are what brings it back.
    double leaving = 0;
    if (_logExpense && _accountId != null) {
      final double amount = iPaid ? _bill : myShare;
      if (amount > 0) leaving = amount;
    }

    return (debts: debts, leaving: leaving);
  }

  /// The sentence under Record it, which says what the tap is about to do.
  ///
  /// It used to read "This creates a debt for each person, and nothing is
  /// sent anywhere." True, and it left out the only part that cannot be
  /// taken back: that money leaves a real account. Worse, the account is
  /// never chosen. [initState] picks whichever one sorts first and the
  /// expense box starts ticked, so the ordinary path spends the whole bill
  /// from an account the person was never shown. Naming it here is what
  /// makes that default visible, and it is cheaper than forcing a choice
  /// somebody would make identically nine times out of ten.
  ///
  /// Three clauses, and each one stops a different wrong conclusion, which
  /// is the only reason a caption is allowed to run this long:
  ///
  /// 1. the figure and the account, so nobody discovers afterwards which
  ///    account paid;
  /// 2. nothing is sent, so nobody believes their friends were just messaged
  ///    a payment request, which is what every app that looks like this does;
  /// 3. the undo exists, which is the difference between hesitating over a
  ///    button and tapping it.
  String get _whatTheTapWillDo {
    if (_people.length < 2) return 'Add at least one other person.';

    final ({List<_PlannedDebt> debts, double leaving}) plan = _plan;
    final int n = plan.debts.length;
    final String debts = n == 1 ? '1 debt' : '$n debts';
    final String account = _accountName ?? 'your account';

    if (plan.leaving <= 0) {
      return n == 0
          ? 'This moves no money and creates no debts yet.'
          : 'This creates $debts and moves no money. Nothing is sent to '
                'anyone.';
    }

    final String spend =
        'Recording this takes ${formatPeso(plan.leaving)} out of $account';
    return n == 0
        ? '$spend. Nothing is sent to anyone. You can undo it for a few '
              'seconds afterwards.'
        : '$spend and creates $debts. Nothing is sent to anyone. You can '
              'undo it for a few seconds afterwards.';
  }

  void _save() {
    if (!_canSave) return;

    final ({List<_PlannedDebt> debts, double leaving}) plan = _plan;
    final String what = _what.text.trim().isEmpty
        ? 'Split bill'
        : _what.text.trim();
    final bool iPaid = _payer == 'You';

    final String stamp = DateTime.now().microsecondsSinceEpoch.toString();
    int seq = 0;

    // COLLECTED AS THEY ARE WRITTEN, not looked up again afterwards. The ids
    // share [stamp], so a later cold-start undo could find them by prefix,
    // but an undo offered in the same breath as the write does not need to
    // go looking: it already holds exactly what it would be searching for.
    final List<Debt> created = <Debt>[];

    for (final _PlannedDebt pd in plan.debts) {
      // EXACT, not rounded. Founder decision, 2026-10-01, and a deliberate
      // divergence from the prototype: it wraps this in Math.round, so a
      // 333.33 share becomes a 333 debt and the centavos leave the ledger
      // with nothing said.
      final Debt d = Debt(
        id: 'debt_split_${stamp}_${seq++}',
        person: pd.person,
        direction: pd.direction,
        totalAmount: Money.fromDouble(pd.amount),
        paidAmount: Money.pesos(0),
        isSettled: false,
        notes: 'Split: $what',
      );
      widget.state.addDebt(d);
      created.add(d);
    }

    Transaction? logged;
    String? spentFrom;

    if (plan.leaving > 0) {
      final DateTime now = widget.state.now;
      logged = Transaction(
        id: 'tx_split_$stamp',
        type: TransactionType.expense,
        amount: Money.fromDouble(plan.leaving),
        category: _category,
        accountId: _accountId!,
        date:
            '${now.year}-${now.month.toString().padLeft(2, '0')}-'
            '${now.day.toString().padLeft(2, '0')}',
        createdAt: DateTime.now().millisecondsSinceEpoch,
        merchant: what,
        note: iPaid
            ? 'Paid the whole bill, split with '
                  '${_people.where((_Person p) => !p.isMe).map((_Person p) => p.name).join(', ')}'
            : 'My share, $_payer paid',
      );
      widget.state.logTransaction(logged);
      spentFrom = _accountName;
    }

    Navigator.of(context).pop(
      SplitBillResult(
        transaction: logged,
        debts: created,
        accountName: spentFrom,
      ),
    );
  }

  /// The chosen account's name, or null when there is no account to spend
  /// from.
  ///
  /// A plain loop rather than `firstWhere`, because `firstWhere` with no
  /// match throws, and a sentence written to reassure somebody about their
  /// money is the worst place in the app for an exception.
  String? get _accountName {
    if (_accountId == null) return null;
    for (final Account a in widget.state.accounts) {
      if (a.id == _accountId) return a.name;
    }
    return null;
  }

  @override
  Widget build(BuildContext context) {
    final Palette p = widget.palette;
    final List<SplitShare> shares = _shares;
    final bool balanced = sharesReconcile(_bill, shares);

    return SheetScaffold(
      palette: p,
      icon: Icons.groups_outlined,
      title: 'Split a bill',
      subtitle: 'Work out who owes what, and record it',
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.stretch,
        children: <Widget>[
          SheetField(
            palette: p,
            label: 'Total bill',
            controller: _total,
            // Every other money field in the app prefixes '₱ ', with the
            // space. This one said 'PHP' and rendered as "PHP2400", which is
            // the sort of thing only a render shows.
            prefix: '₱ ',
            hint: '0.00',
            onChanged: (_) => setState(() {}),
          ),
          const SizedBox(height: Spacing.md),
          SheetField(
            palette: p,
            label: 'What was it',
            controller: _what,
            hint: 'Lunch, groceries, the GrabCar',
            keyboardType: TextInputType.text,
          ),
          const SizedBox(height: Spacing.lg),

          Text('How to split it', style: AppType.label(p)),
          const SizedBox(height: Spacing.xs),
          SegmentedChoice<SplitMethod>(
            palette: p,
            selected: _method,
            onSelect: (SplitMethod m) => setState(() => _method = m),
            options: const <(SplitMethod, String)>[
              (SplitMethod.equal, 'Equal'),
              (SplitMethod.percentage, 'Percent'),
              (SplitMethod.fixed, 'Amounts'),
              (SplitMethod.shares, 'Shares'),
            ],
          ),
          const SizedBox(height: Spacing.lg),

          Text('Who is in on it', style: AppType.label(p)),
          const SizedBox(height: Spacing.xs),
          for (final _Person person in _people) ...<Widget>[
            _PersonRow(
              palette: p,
              person: person,
              method: _method,
              share: shares
                  .where((SplitShare s) => s.name == person.name)
                  .firstOrNull,
              isPayer: _payer == person.name,
              onPayer: () => setState(() => _payer = person.name),
              onChanged: () => setState(() {}),
              onRemove: person.isMe ? null : () => _removePerson(person),
            ),
            const SizedBox(height: Spacing.sm),
          ],

          Row(
            children: <Widget>[
              Expanded(
                child: SheetField(
                  palette: p,
                  label: 'Add somebody',
                  controller: _newName,
                  hint: 'Their name',
                  keyboardType: TextInputType.text,
                  onChanged: (_) => setState(() {}),
                ),
              ),
              const SizedBox(width: Spacing.sm),
              Padding(
                padding: const EdgeInsets.only(top: Spacing.lg),
                child: Semantics(
                  button: true,
                  label: 'Add this person to the split',
                  child: InkWell(
                    onTap: _addPerson,
                    borderRadius: BorderRadius.circular(Radii.control),
                    child: Container(
                      constraints: const BoxConstraints(
                        minWidth: 44,
                        minHeight: 44,
                      ),
                      alignment: Alignment.center,
                      decoration: BoxDecoration(
                        color: p.accentSoft,
                        borderRadius: BorderRadius.circular(Radii.control),
                        border: Border.all(color: p.border),
                      ),
                      child: Icon(Icons.add, color: p.accent, size: 20),
                    ),
                  ),
                ),
              ),
            ],
          ),

          if (shares.isNotEmpty) ...<Widget>[
            const SizedBox(height: Spacing.lg),
            _Summary(
              palette: p,
              bill: _bill,
              shares: shares,
              balanced: balanced,
              method: _method,
            ),
          ],

          const SizedBox(height: Spacing.lg),
          _LogExpense(
            palette: p,
            on: _logExpense,
            accounts: widget.state.accounts,
            accountId: _accountId,
            category: _category,
            categories: <String>[
              for (final CategoryInfo c in widget.state.categories)
                if (c.kind == CategoryKind.expense) c.name,
            ],
            iPaid: _payer == 'You',
            onToggle: (bool v) => setState(() => _logExpense = v),
            onAccount: (String id) => setState(() => _accountId = id),
            onCategory: (String c) => setState(() => _category = c),
          ),

          const SizedBox(height: Spacing.lg),
          PrimaryButton(
            palette: p,
            label: 'Record it',
            icon: Icons.check,
            onTap: _canSave ? _save : null,
          ),
          const SizedBox(height: Spacing.sm),
          Text(_whatTheTapWillDo, style: AppType.caption(p)),
        ],
      ),
    );
  }
}

class _PersonRow extends StatelessWidget {
  const _PersonRow({
    required this.palette,
    required this.person,
    required this.method,
    required this.share,
    required this.isPayer,
    required this.onPayer,
    required this.onChanged,
    required this.onRemove,
  });

  final Palette palette;
  final _Person person;
  final SplitMethod method;
  final SplitShare? share;
  final bool isPayer;
  final VoidCallback onPayer;
  final VoidCallback onChanged;
  final VoidCallback? onRemove;

  @override
  Widget build(BuildContext context) {
    final TextEditingController? input = switch (method) {
      SplitMethod.equal => null,
      SplitMethod.percentage => person.percent,
      SplitMethod.fixed => person.fixed,
      SplitMethod.shares => person.shares,
    };

    return Container(
      padding: const EdgeInsets.all(Spacing.md),
      decoration: BoxDecoration(
        color: palette.surfaceAlt,
        borderRadius: BorderRadius.circular(Radii.control),
        border: Border.all(color: isPayer ? palette.accent : palette.border),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Row(
            children: <Widget>[
              Expanded(
                child: Text(person.name, style: AppType.rowTitle(palette)),
              ),
              if (onRemove != null)
                Semantics(
                  button: true,
                  label: 'Remove ${person.name} from the split',
                  child: IconButton(
                    constraints: const BoxConstraints(
                      minWidth: 44,
                      minHeight: 44,
                    ),
                    icon: Icon(Icons.close, size: 18, color: palette.textMuted),
                    onPressed: onRemove,
                  ),
                ),
            ],
          ),
          Row(
            children: <Widget>[
              // WHO PAID is a choice on the person's own row rather than a
              // separate picker, because it is a fact about them and because
              // a second list of the same names is a second thing to keep in
              // step.
              Expanded(
                child: Semantics(
                  inMutuallyExclusiveGroup: true,
                  selected: isPayer,
                  button: true,
                  child: InkWell(
                    onTap: onPayer,
                    borderRadius: BorderRadius.circular(Radii.pill),
                    child: Container(
                      constraints: const BoxConstraints(minHeight: 44),
                      alignment: Alignment.centerLeft,
                      child: Row(
                        children: <Widget>[
                          Icon(
                            isPayer
                                ? Icons.radio_button_checked
                                : Icons.radio_button_unchecked,
                            size: 16,
                            color: isPayer ? palette.accent : palette.textMuted,
                          ),
                          const SizedBox(width: Spacing.xs),
                          Flexible(
                            child: Text(
                              'Paid the bill',
                              style: AppType.caption(palette).copyWith(
                                color: isPayer
                                    ? palette.textPrimary
                                    : palette.textMuted,
                              ),
                            ),
                          ),
                        ],
                      ),
                    ),
                  ),
                ),
              ),
              if (input != null)
                SizedBox(
                  width: 92,
                  child: TextField(
                    controller: input,
                    onChanged: (_) => onChanged(),
                    keyboardType: const TextInputType.numberWithOptions(
                      decimal: true,
                    ),
                    style: AppType.body(palette),
                    decoration: InputDecoration(
                      isDense: true,
                      hintText: switch (method) {
                        SplitMethod.percentage => '%',
                        SplitMethod.fixed => '0.00',
                        SplitMethod.shares => '1',
                        SplitMethod.equal => '',
                      },
                      hintStyle: AppType.caption(palette),
                      border: OutlineInputBorder(
                        borderRadius: BorderRadius.circular(Radii.tile),
                      ),
                    ),
                  ),
                ),
            ],
          ),
          if (share != null) ...<Widget>[
            const SizedBox(height: Spacing.xs),
            // THE AMOUNT, never the percentage, and that is the defence
            // against the engine's odd thing 2. When percentages do not add
            // to 100 the last person's amount is adjusted and their stated
            // percentage is not, so two people at 80% each pay 800 and 200
            // while both rows claim 80. The amount is always true.
            Text(
              'Their share: ${formatPeso(share!.amount)}',
              style: AppType.rowMeta(palette).copyWith(
                color: palette.textPrimary,
                fontWeight: FontWeight.w700,
              ),
            ),
          ],
        ],
      ),
    );
  }
}

/// What the split comes to, and whether it adds up.
class _Summary extends StatelessWidget {
  const _Summary({
    required this.palette,
    required this.bill,
    required this.shares,
    required this.balanced,
    required this.method,
  });

  final Palette palette;
  final double bill;
  final List<SplitShare> shares;
  final bool balanced;
  final SplitMethod method;

  @override
  Widget build(BuildContext context) {
    final double sum = sharesTotal(shares);
    final double gap = sum - bill;

    return Container(
      padding: const EdgeInsets.all(Spacing.md),
      decoration: BoxDecoration(
        color: balanced ? palette.surface : palette.warningSoft,
        borderRadius: BorderRadius.circular(Radii.control),
        border: Border.all(color: balanced ? palette.border : palette.warning),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Row(
            children: <Widget>[
              Expanded(
                child: Text(
                  'The shares come to',
                  style: AppType.caption(palette).copyWith(
                    color: balanced ? palette.textMuted : palette.textPrimary,
                  ),
                ),
              ),
              Text(
                formatPeso(sum),
                style: AppType.amountSmall(palette).copyWith(
                  color: balanced ? palette.textPrimary : palette.warning,
                ),
              ),
            ],
          ),
          if (!balanced) ...<Widget>[
            const SizedBox(height: Spacing.xs),
            // ON THE SCREEN, because silence here misleads. Fixed amounts are
            // never reconciled against the bill by the engine, so somebody
            // can be looking at a column of figures that does not come to
            // what they are paying, and the debts created from it would be
            // wrong in exactly that amount.
            Text(
              gap > 0
                  ? 'That is ${formatPeso(gap)} MORE than the bill. Check the '
                        'amounts before recording it.'
                  : 'That is ${formatPeso(-gap)} LESS than the bill. '
                        '${formatPeso(-gap)} is not assigned to anybody.',
              style: AppType.caption(
                palette,
              ).copyWith(color: palette.textPrimary),
            ),
          ],
        ],
      ),
    );
  }
}

class _LogExpense extends StatelessWidget {
  const _LogExpense({
    required this.palette,
    required this.on,
    required this.accounts,
    required this.accountId,
    required this.category,
    required this.categories,
    required this.iPaid,
    required this.onToggle,
    required this.onAccount,
    required this.onCategory,
  });

  final Palette palette;
  final bool on;
  final List<Account> accounts;
  final String? accountId;
  final String category;
  final List<String> categories;
  final bool iPaid;
  final ValueChanged<bool> onToggle;
  final ValueChanged<String> onAccount;
  final ValueChanged<String> onCategory;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(Spacing.md),
      decoration: BoxDecoration(
        color: palette.surface,
        borderRadius: BorderRadius.circular(Radii.control),
        border: Border.all(color: palette.border),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: <Widget>[
          Semantics(
            checked: on,
            button: true,
            child: InkWell(
              onTap: () => onToggle(!on),
              borderRadius: BorderRadius.circular(Radii.tile),
              child: Container(
                constraints: const BoxConstraints(minHeight: 44),
                child: Row(
                  children: <Widget>[
                    ExcludeSemantics(
                      child: Icon(
                        on
                            ? Icons.check_box_outlined
                            : Icons.check_box_outline_blank,
                        size: 20,
                        color: on ? palette.accent : palette.textMuted,
                      ),
                    ),
                    const SizedBox(width: Spacing.sm),
                    Expanded(
                      child: Text(
                        iPaid
                            ? 'Also log the whole bill as an expense'
                            : 'Also log my share as an expense',
                        style: AppType.body(palette).copyWith(fontSize: 13),
                      ),
                    ),
                  ],
                ),
              ),
            ),
          ),
          if (on) ...<Widget>[
            const SizedBox(height: Spacing.sm),
            if (accounts.isEmpty)
              Text(
                'No accounts yet, so there is nowhere to log it. The debts '
                'will still be recorded.',
                style: AppType.caption(palette),
              )
            else ...<Widget>[
              DropdownButtonFormField<String>(
                initialValue: accountId,
                isExpanded: true,
                decoration: InputDecoration(
                  labelText: 'From which account',
                  labelStyle: AppType.label(palette),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(Radii.control),
                  ),
                ),
                items: <DropdownMenuItem<String>>[
                  for (final Account a in accounts)
                    DropdownMenuItem<String>(
                      value: a.id,
                      child: Text(a.name, style: AppType.body(palette)),
                    ),
                ],
                onChanged: (String? v) {
                  if (v != null) onAccount(v);
                },
              ),
              const SizedBox(height: Spacing.sm),
              // A PICKER, not a hardcoded category. The prototype files every
              // split under Food & Dining unless it is a business one, which
              // is the same defect this repository already refused to port
              // from the quick-log parser: a wrong category is money sitting
              // perfectly in the ledger and missing from every summary that
              // reads it.
              DropdownButtonFormField<String>(
                initialValue: categories.contains(category)
                    ? category
                    : (categories.isNotEmpty ? categories.first : null),
                isExpanded: true,
                decoration: InputDecoration(
                  labelText: 'Category',
                  labelStyle: AppType.label(palette),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(Radii.control),
                  ),
                ),
                items: <DropdownMenuItem<String>>[
                  for (final String c in categories)
                    DropdownMenuItem<String>(
                      value: c,
                      child: Text(c, style: AppType.body(palette)),
                    ),
                ],
                onChanged: (String? v) {
                  if (v != null) onCategory(v);
                },
              ),
            ],
          ],
        ],
      ),
    );
  }
}
