// Backup, restore, and the sanitize choke point, ported 1:1 from
// mobile/lib/backup.js (plus normalizeCategoryTree from lib/categories.js).
// Every blob the Flutter app will ever load, import, or restore passes
// through sanitizeData, exactly like the RN app. Golden-verified against
// outputs generated by executing the real RN module, including the
// newer-version refusal, so the two apps can never disagree about a byte of
// stored data.
//
// JS semantics preserved on purpose:
// - unknown fields always survive (spread first, then coerce)
// - keys the RN code sets to undefined or deletes are OMITTED here
// - migrations are pure and forward only; a NEWER blob is refused loudly

import 'dart:convert' show JsonEncoder;

const int schemaVersion = 12;

const List<Map<String, dynamic>> defaultCategories = [
  {'id': 'cat_food', 'name': 'Food', 'icon': '🍜', 'monthlyCap': 0},
  {'id': 'cat_transport', 'name': 'Transport', 'icon': '🚌', 'monthlyCap': 0},
  {'id': 'cat_load', 'name': 'Load', 'icon': '📱', 'monthlyCap': 0},
  {'id': 'cat_bills', 'name': 'Bills', 'icon': '💡', 'monthlyCap': 0},
  {'id': 'cat_groceries', 'name': 'Groceries', 'icon': '🛒', 'monthlyCap': 0},
  {'id': 'cat_fun', 'name': 'Fun', 'icon': '🎉', 'monthlyCap': 0},
  {'id': 'cat_padala', 'name': 'Padala', 'icon': '💸', 'monthlyCap': 0},
  {'id': 'cat_health', 'name': 'Health', 'icon': '💊', 'monthlyCap': 0},
];

class NewerBackupException implements Exception {
  final String message;
  NewerBackupException(this.message);
  @override
  String toString() => message;
}

class NotABackupException implements Exception {
  final String message;
  NotABackupException(this.message);
  @override
  String toString() => message;
}

double _num(dynamic x) {
  if (x == null || x == false) return 0;
  if (x == true) return 1;
  if (x is num) return x.isFinite ? x.toDouble() : 0;
  if (x is String) {
    if (x.trim().isEmpty) return 0;
    final p = double.tryParse(x.trim());
    return (p == null || !p.isFinite) ? 0 : p;
  }
  return 0;
}

String _str(dynamic x, [String fallback = '']) => x is String ? x : fallback;

bool _truthy(dynamic v) =>
    v == true ||
    (v is num && v != 0 && !v.isNaN) ||
    (v is String && v.isNotEmpty);

Map<String, dynamic>? _asObj(dynamic x) =>
    (x is Map && x is! List) ? x.cast<String, dynamic>() : null;

List<Map<String, dynamic>> _cleanList(dynamic x) => (x is List)
    ? x.whereType<Map>().map((e) => e.cast<String, dynamic>()).toList()
    : [];

String _todayISO(DateTime d) {
  final m = d.month.toString().padLeft(2, '0');
  final day = d.day.toString().padLeft(2, '0');
  return '${d.year}-$m-$day';
}

/// Undated history stamps onto the first day of LAST month, never today.
String _legacyDate(DateTime now) =>
    _todayISO(DateTime(now.year, now.month - 1, 1));

final _isoDateTime = RegExp(r'^\d{4}-\d{2}-\d{2}T');
final _isoDatePrefix = RegExp(r'^\d{4}-\d{2}-\d{2}');
final _isoDateFull = RegExp(r'^\d{4}-\d{2}-\d{2}$');
final _receiptShape = RegExp(r'^receipts/receipt_[a-z0-9]+\.[A-Za-z0-9]+$');
final _personM3 = RegExp(r'^person_m3_(\d+)$');

// ---- normalizeCategoryTree (from mobile/lib/categories.js) ----
// Keep the tree at most two levels: self parents, orphans, third levels, and
// cycles all drop to top level by removing parentId.
List<Map<String, dynamic>> normalizeCategoryTree(
  List<Map<String, dynamic>> categories,
) {
  final byId = <dynamic, Map<String, dynamic>>{
    for (final c in categories)
      if (_truthy(c['id'])) c['id']: c,
  };
  Map<String, dynamic> strip(Map<String, dynamic> c) {
    final out = {...c};
    out.remove('parentId');
    return out;
  }

  return categories.map((c) {
    final pRaw = c['parentId'];
    final p = (pRaw is String && pRaw.isNotEmpty) ? pRaw : null;
    if (p == null || p == c['id']) return strip(c);
    final parent = byId[p];
    if (parent == null) return strip(c);
    final gp = parent['parentId'];
    final parentHasRealParent =
        gp is String &&
        gp.isNotEmpty &&
        gp != parent['id'] &&
        byId.containsKey(gp);
    if (parentHasRealParent) return strip(c);
    return {...c, 'parentId': p};
  }).toList();
}

// ---- Migrations (forward only, pure) ----

Map<String, dynamic> _migration3(Map<String, dynamic> d) {
  final receivables = (d['receivables'] is List)
      ? (d['receivables'] as List)
      : const [];
  var people = (d['people'] is List)
      ? List<dynamic>.from(d['people'] as List)
      : <dynamic>[];
  String keyOf(dynamic name) =>
      (name == null ? '' : name.toString()).trim().toLowerCase();
  final byKey = <String, Map<String, dynamic>>{};
  for (final p in people) {
    if (p is Map) byKey[keyOf(p['name'])] = p.cast<String, dynamic>();
  }
  var n = 0;
  for (final p in people) {
    if (p is Map) {
      final m = _personM3.firstMatch(_str(p['id']));
      if (m != null) {
        final v = int.parse(m.group(1)!) + 1;
        if (v > n) n = v;
      }
    }
  }
  final migrated = receivables.map((raw) {
    if (raw is! Map) return raw;
    final r = raw.cast<String, dynamic>();
    final pid = r['personId'];
    if (pid is String && pid.isNotEmpty) return {'payments': [], ...r};
    final key = keyOf(r['person']);
    if (key.isEmpty) return {'payments': [], ...r};
    var person = byKey[key];
    if (person == null) {
      person = {
        'id': 'person_m3_${n++}',
        'name': r['person'].toString().trim(),
        'phone': _str(r['phone']),
        'note': '',
      };
      people.add(person);
      byKey[key] = person;
    } else if (!_truthy(person['phone']) &&
        r['phone'] is String &&
        (r['phone'] as String).isNotEmpty) {
      final updated = {...person, 'phone': r['phone']};
      final prev = person;
      people = people.map((p) => identical(p, prev) ? updated : p).toList();
      byKey[key] = updated;
      person = updated;
    }
    return {'payments': [], ...r, 'personId': person['id']};
  }).toList();
  return {...d, 'people': people, 'receivables': migrated};
}

Map<String, dynamic> _migration4(Map<String, dynamic> d) {
  if (_cleanList(d['categories']).isNotEmpty) return {...d};
  return {
    ...d,
    'categories': defaultCategories.map((c) => {...c}).toList(),
  };
}

Map<String, dynamic> _migrate(Map<String, dynamic> raw) {
  var d = raw;
  var v = _num(raw['schemaVersion']).truncate();
  if (v < 1) v = 2;
  // JS clamps non-finite to 2 as well; _num already coerced those to 0.
  if (v > schemaVersion) {
    throw NewerBackupException(
      'This data comes from a newer version of Salapify. Update the app first, then try again. Nothing was changed.',
    );
  }
  while (v < schemaVersion) {
    v += 1;
    if (v == 3) d = _migration3(d);
    if (v == 4) d = _migration4(d);
    d = {...d, 'schemaVersion': v};
  }
  return d;
}

// ---- sanitizeData ----

Map<String, dynamic> sanitizeData(
  dynamic raw, {
  bool keepAppLock = false,
  DateTime? now,
}) {
  final src = _migrate(_asObj(raw) ?? {});
  final stampDate = _legacyDate(now ?? DateTime.now());

  List<Map<String, dynamic>> dated(dynamic list) => _cleanList(list).map((it) {
    var date = (it['date'] is String && (it['date'] as String).isNotEmpty)
        ? it['date'] as String
        : stampDate;
    if (_isoDateTime.hasMatch(date)) date = date.substring(0, 10);
    return {...it, 'date': date};
  }).toList();

  final settings = _asObj(src['settings']) ?? {};

  return {
    'schemaVersion': schemaVersion,
    'accounts': _cleanList(src['accounts']).map((a) {
      return {
        ...a,
        'name': _str(a['name'], 'Account'),
        'brand': _str(a['brand']),
        'icon': _str(a['icon']),
        'kind':
            const ['cash', 'savings', 'checking', 'ewallet'].contains(a['kind'])
            ? a['kind']
            : 'cash',
        'balance': _num(a['balance']),
        'target': _num(a['target']),
      };
    }).toList(),
    'assets': _cleanList(
      src['assets'],
    ).map((a) => {...a, 'value': _num(a['value'])}).toList(),
    'debts': _cleanList(src['debts']).map((d) {
      final out = {
        ...d,
        'name': _str(d['name'], 'Debt'),
        'type': _str(d['type'], 'other'),
        'remaining': _num(d['remaining']),
        'monthlyRate': _num(d['monthlyRate']),
        'minPayment': _num(d['minPayment']),
        'dueDay': _num(d['dueDay']),
        'statementDay': _num(d['statementDay']),
        'graceDays': _num(d['graceDays']),
        'creditLimit': _num(d['creditLimit']),
      };
      final iso = d['interestThroughISO'];
      if (iso is String && _isoDatePrefix.hasMatch(iso)) {
        out['interestThroughISO'] = iso;
      } else {
        out.remove('interestThroughISO');
      }
      return out;
    }).toList(),
    'payments': (() {
      var i = 0;
      return dated(src['payments']).map((p) {
        final out = {...p};
        final id = _str(p['id']);
        out['id'] = id.isNotEmpty ? id : 'pay_restored_$i';
        final amt = _num(p['amount']);
        out['amount'] = amt < 0 ? 0.0 : amt;
        if (p['interest'] != null) {
          final v = _num(p['interest']);
          out['interest'] = v < 0 ? 0.0 : v;
        } else {
          out.remove('interest');
        }
        if (p['principal'] != null) {
          final v = _num(p['principal']);
          out['principal'] = v < 0 ? 0.0 : v;
        } else {
          out.remove('principal');
        }
        i++;
        return out;
      }).toList();
    })(),
    'transactions': dated(src['transactions']).map((t) {
      final amt = _num(t['amount']);
      final out = {
        ...t,
        'amount': amt < 0 ? 0.0 : amt,
        'type':
            const [
              'income',
              'transfer',
              'debt',
              'adjustment',
            ].contains(t['type'])
            ? t['type']
            : 'expense',
        'label': (t['label'] is String && (t['label'] as String).isNotEmpty)
            ? t['label']
            : 'Entry',
      };
      final uri = t['receiptUri'];
      if (uri is String && _receiptShape.hasMatch(uri)) {
        out['receiptUri'] = uri;
      } else {
        out.remove('receiptUri');
      }
      final cat = t['categoryId'];
      if (cat is String && cat.isNotEmpty) {
        out['categoryId'] = cat;
      } else {
        out.remove('categoryId');
      }
      final oc = t['origCurrency'];
      if (oc is String && oc.isNotEmpty && _num(t['origAmount']) > 0) {
        out['origCurrency'] = oc;
        out['origAmount'] = _num(t['origAmount']);
      } else {
        out.remove('origCurrency');
        out.remove('origAmount');
      }
      final type = out['type'];
      final flow = t['flow'];
      if ((type == 'transfer' || type == 'adjustment') &&
          (flow == 'in' || flow == 'out')) {
        out['flow'] = flow;
      } else {
        out.remove('flow');
      }
      final srcField = t['source'];
      if (srcField is String && srcField.isNotEmpty) {
        out['source'] = srcField;
      } else {
        out.remove('source');
      }
      if ((type == 'transfer' || type == 'debt') && out['flow'] == null) {
        out.remove('accountId');
      }
      if (type == 'adjustment' && out['flow'] == null) {
        out.remove('accountId');
      }
      return out;
    }).toList(),
    'goals': _cleanList(src['goals'])
        .map(
          (g) => {
            ...g,
            'name': _str(g['name'], 'Goal'),
            'targetDate': _str(g['targetDate']),
            'target': _num(g['target']),
            'saved': _num(g['saved']),
          },
        )
        .toList(),
    'wins': _cleanList(src['wins']),
    'notes': _cleanList(src['notes']),
    'recurring': (() {
      var i = 0;
      final seen = <String>{};
      return _cleanList(src['recurring']).map((r) {
        var id = (r['id'] is String && (r['id'] as String).isNotEmpty)
            ? r['id'] as String
            : 'recurring_restored_$i';
        // A hand-edited backup can carry two items with the same id; edit and
        // delete match by id, so de-dup here the way categories do.
        while (seen.contains(id)) {
          id = '${id}_dup';
        }
        seen.add(id);
        final amt = _num(r['amount']);
        var day = _num(r['dayOfMonth']).round();
        if (day == 0) day = 1;
        if (day < 1) day = 1;
        if (day > 31) day = 31;
        final out = {
          ...r,
          'id': id,
          'type': r['type'] == 'income' ? 'income' : 'expense',
          'label': _str(r['label'], 'Recurring'),
          'amount': amt < 0 ? 0.0 : amt,
          'dayOfMonth': day,
          'accountId': _str(r['accountId']),
          'lastPosted': _str(r['lastPosted']),
        };
        i++;
        return out;
      }).toList();
    })(),
    'categories': (() {
      final seen = <String>{};
      var i = 0;
      final cleaned = _cleanList(src['categories']).map((c) {
        var id = (c['id'] is String && (c['id'] as String).isNotEmpty)
            ? c['id'] as String
            : 'cat_restored_$i';
        while (seen.contains(id)) {
          id = '${id}_dup';
        }
        seen.add(id);
        final cap = _num(c['monthlyCap']);
        final out = {
          ...c,
          'id': id,
          'name': _str(c['name'], 'Category'),
          'icon': _str(c['icon'], '🏷️'),
          'monthlyCap': cap < 0 ? 0.0 : cap,
        };
        final pid = c['parentId'];
        if (pid is String && pid.isNotEmpty) {
          out['parentId'] = pid;
        } else {
          out.remove('parentId');
        }
        i++;
        return out;
      }).toList();
      return normalizeCategoryTree(cleaned);
    })(),
    'people': _cleanList(src['people'])
        .map(
          (p) => {
            ...p,
            'name': _str(p['name'], 'Someone'),
            'phone': _str(p['phone']),
            'note': _str(p['note']),
          },
        )
        .toList(),
    'receivables': _utangList(src['receivables'], 'rpay_restored_', stampDate),
    'payables': _utangList(src['payables'], 'ppay_restored_', stampDate),
    'settings': (() {
      final s = <String, dynamic>{
        ...settings,
        'monthlyLimit': _num(settings['monthlyLimit']),
        'quickAdds': _cleanList(settings['quickAdds']),
        'appLock': keepAppLock ? settings['appLock'] == true : false,
        'pro': settings['pro'] == true,
        'budgetCarryOver': settings['budgetCarryOver'] == true,
        'notifications': _asObj(settings['notifications']) ?? {},
        'treats': (() {
          var i = 0;
          return _cleanList(settings['treats']).map((t) {
            final id = _str(t['id']);
            var target = _num(t['target']).round();
            if (target == 0) target = 3;
            if (target < 1) target = 1;
            if (target > 14) target = 14;
            var windowDays = _num(t['windowDays']).round();
            if (windowDays == 0) windowDays = 7;
            if (windowDays < 1) windowDays = 1;
            if (windowDays > 31) windowDays = 31;
            final lifetime = _num(t['lifetime']).round();
            final checkIns = <String>[];
            if (t['checkIns'] is List) {
              for (final dt in t['checkIns'] as List) {
                if (dt is String &&
                    _isoDateFull.hasMatch(dt) &&
                    !checkIns.contains(dt)) {
                  checkIns.add(dt);
                }
              }
            }
            final created = _str(t['createdAt']);
            final out = {
              ...t,
              'id': id.isNotEmpty ? id : 'treat_restored_$i',
              'treat': _str(t['treat'], 'My treat'),
              'action': _str(t['action'], 'My healthy action'),
              'emoji': _str(t['emoji'], '☕'),
              'target': target,
              'windowDays': windowDays,
              'checkIns': checkIns,
              'lifetime': lifetime < 0 ? 0 : lifetime,
              'createdAt': created.isNotEmpty ? created : stampDate,
            };
            i++;
            return out;
          }).toList();
        })(),
      };
      // Paluwagan is a Flutter-era collection with no RN counterpart, so it
      // lives under settings like treats and quickAdds. It is a CONDITIONAL
      // key: emitted only when the stored blob actually carries a list, and
      // removed otherwise. That keeps the golden key-set contract intact,
      // because the RN-generated fixtures never carry paluwagans and so must
      // not gain the key here either.
      final pal = settings['paluwagans'];
      if (pal is List) {
        s['paluwagans'] = _paluwaganList(pal);
      } else {
        s.remove('paluwagans');
      }
      // Steady Pay (the accepted weekly draw) is Flutter-era too, and the
      // same CONDITIONAL-key rule applies: present only when a valid
      // accepted amount exists, absent otherwise, so RN-generated fixtures
      // never gain the key and the golden key-set contract holds. Founder
      // approved 2026-07-24.
      final sp = settings['steadyPay'];
      final spAmt = sp is Map ? _num(sp['amount']) : 0.0;
      if (sp is Map && spAmt > 0 && spAmt.isFinite) {
        s['steadyPay'] = {
          'amount': spAmt,
          'acceptedAt': _str(sp['acceptedAt']),
        };
      } else {
        s.remove('steadyPay');
      }
      final cur = s['currency'];
      if (cur is! String || cur.isEmpty) s.remove('currency');
      if (s['currencyCode'] is! String) s.remove('currencyCode');
      return s;
    })(),
  };
}

/// Valid paluwagan cadence keys, kept in step with money/paluwagan.dart.
const List<String> _paluwaganCadenceKeys = ['weekly', 'kinsenas', 'monthly'];

/// Normalize a stored paluwagan list to the safe shape the engine expects:
/// members and turn clamped to a real group, a known cadence, a non-negative
/// amount, and a stable id. The engine also guards junk at read time, so this
/// is defense in depth plus a clean, comparable backup, mirroring _utangList.
List<Map<String, dynamic>> _paluwaganList(dynamic list) {
  var i = 0;
  return _cleanList(list).map((r) {
    final id = _str(r['id']);
    final members = _num(r['members']).round().clamp(2, 60);
    final amt = _num(r['amount']);
    final rawNote = r['note'];
    final note = rawNote is String
        ? (rawNote.length > 200 ? rawNote.substring(0, 200) : rawNote)
        : '';
    final out = {
      ...r,
      'id': id.isNotEmpty ? id : 'paluwagan_restored_$i',
      'name': _str(r['name'], 'Paluwagan'),
      'amount': amt < 0 ? 0.0 : amt,
      'members': members,
      'cadence': _paluwaganCadenceKeys.contains(r['cadence'])
          ? r['cadence']
          : 'monthly',
      'startDate': _str(r['startDate']),
      'myTurn': _num(r['myTurn']).round().clamp(1, members),
      'paidCycles': _num(r['paidCycles']).round().clamp(0, members),
      'note': note,
    };
    i++;
    return out;
  }).toList();
}

List<Map<String, dynamic>> _utangList(
  dynamic list,
  String payPrefix,
  String stampDate,
) {
  return _cleanList(list).map((r) {
    var i = 0;
    return {
      ...r,
      'person': (r['person'] is String && (r['person'] as String).isNotEmpty)
          ? r['person']
          : 'Someone',
      'personId': _str(r['personId']),
      'dueDate': _str(r['dueDate']),
      'phone': _str(r['phone']),
      'note': _str(r['note']),
      'amount': _num(r['amount']),
      'paid': _truthy(r['paid']),
      'cashLeg': _truthy(r['cashLeg']),
      'payments': _cleanList(r['payments']).map((p) {
        final id = _str(p['id']);
        final amt = _num(p['amount']);
        final out = {
          ...p,
          'id': id.isNotEmpty ? id : '$payPrefix$i',
          'amount': amt < 0 ? 0.0 : amt,
          'date': (p['date'] is String && (p['date'] as String).isNotEmpty)
              ? p['date']
              : stampDate,
          'settled': _truthy(p['settled']),
        };
        i++;
        return out;
      }).toList(),
    };
  }).toList();
}

/// Build the backup text, the same wrapper the RN buildBackup writes
/// (mobile/lib/backup.js:472-478): app, version 2, exportedAt, then the
/// whole data map, pretty printed with two spaces. The RN app's parseBackup
/// reads it back with JSON.parse plus sanitizeData, so any JSON-equal text
/// round-trips; number spelling differences (250 vs 250.0) vanish at parse.
String buildBackupText(
  Map<String, dynamic> data, {
  required String exportedAt,
}) {
  return const JsonEncoder.withIndent('  ').convert({
    'app': 'salapify',
    'version': 2,
    'exportedAt': exportedAt,
    'data': data,
  });
}

/// Parse a Salapify v2 backup JSON object (already decoded) back into clean
/// app data. Throws NotABackupException when it does not look like ours.
Map<String, dynamic> parseBackupObject(dynamic obj, {DateTime? now}) {
  // JS: obj && obj.data ? obj.data : obj. Any object or non-empty primitive
  // counts as truthy there; maps and lists are always truthy.
  final dataField = (obj is Map) ? obj['data'] : null;
  final dataTruthy =
      dataField is Map || dataField is List || _truthy(dataField);
  final data = (obj is Map && dataTruthy) ? dataField : obj;
  final asMap = _asObj(data);
  if (asMap == null || asMap['accounts'] is! List) {
    throw NotABackupException('That does not look like a Salapify backup.');
  }
  return sanitizeData(asMap, now: now);
}
