// Regenerates the three goldens that embed user-facing COPY (coach, pan,
// lessons) by replaying their stored fixtures through the FLUTTER engines,
// exactly mirroring what each golden test replays. Run from flutter/ with:
//
//   dart run tool/regen_copy_goldens.dart
//
// Why this exists: these goldens were originally generated by executing the
// frozen React Native app, locking Flutter's copy word for word to RN. On
// 2026-07-23 the founder directed the app's copy to be English first for the
// global launch, which deliberately breaks the WORDING half of that lock. The
// fixtures and reference dates in each file are kept byte identical, so every
// NUMBER still derives from the same RN-generated inputs; only the outputs are
// recomputed from the Flutter engines, which are now the owners of the copy.
// Run this after any deliberate copy change, then eyeball the diff: numbers
// and structure should not move, only words.

import 'dart:convert';
import 'dart:io';

import 'package:salapify/content/lessons.dart';
import 'package:salapify/money/coach.dart';
import 'package:salapify/money/debtmath.dart' show formatMoneyText;
import 'package:salapify/money/pan/ask.dart';
import 'package:salapify/money/pan/intents.dart' show detectIntent;
import 'package:salapify/money/pan/normalize.dart';
import 'package:salapify/money/recap.dart';
import 'package:salapify/money/schedule.dart'
    show daysUntilPayday, scheduleLabel;

const _enc = JsonEncoder.withIndent('  ');

Map<String, dynamic> _load(String path) =>
    (jsonDecode(File(path).readAsStringSync()) as Map).cast<String, dynamic>();

void _save(String path, Map<String, dynamic> data) =>
    File(path).writeAsStringSync('${_enc.convert(data)}\n');

/// Drop null-valued keys, matching the golden test's tidyReply.
Map<String, dynamic> _tidy(Map<String, dynamic> reply) {
  final out = <String, dynamic>{};
  reply.forEach((k, v) {
    if (v != null) out[k] = v;
  });
  return out;
}

void regenCoach() {
  const path = 'test/goldens/coach_goldens.json';
  final raw = _load(path);
  final ref = DateTime(2026, 7, 16, 12);
  final nov = DateTime(2026, 11, 16, 12);
  raw['weekKey'] = weekKey(ref);
  final scenarios = (raw['scenarios'] as Map).cast<String, dynamic>();
  for (final entry in scenarios.entries) {
    final s = (entry.value as Map).cast<String, dynamic>();
    final data = (s['data'] as Map).cast<String, dynamic>();
    final r = entry.key == 'kitchenSinkNov' ? nov : ref;
    s['candidates'] = decisionCandidates(data, r);
    s['checkIn'] = weeklyCheckIn(data, r);
    s['win'] = pickWin(data, r);
  }
  _save(path, raw);
  stdout.writeln('coach_goldens.json regenerated');
}

void regenPan() {
  const path = 'test/goldens/pan_goldens.json';
  final raw = _load(path);
  final now = DateTime.parse(raw['nowISO'] as String);
  final fixtures = (raw['fixtures'] as Map).cast<String, dynamic>();

  for (final c in (raw['cases'] as List).cast<Map<String, dynamic>>()) {
    final message = c['message'] as String;
    final norm = normalize(message);
    c['norm'] = norm;
    c['amount'] = extractAmount(message);
    final det = detectIntent(norm);
    c['detect'] = {
      'id': det['id'],
      'score': det['score'],
      'alternatives': det['alternatives'],
    };
    final data = (fixtures[c['fixture']] as Map).cast<String, dynamic>();
    c['reply'] = _tidy(ask(data, message, now: now));
  }

  raw['help'] = _tidy(helpReply());
  raw['helpAlt'] = _tidy(helpReply(['balances', 'payday']));
  raw['chips'] = suggestions(6);

  final main = (fixtures['main'] as Map).cast<String, dynamic>();
  final mainRecap = monthRecap(main, now);
  raw['recaps'] = {
    'main': mainRecap,
    'empty': monthRecap(const {}, now),
    'overspent': monthRecap({
      'transactions': [
        {
          'type': 'income',
          'label': 'Sweldo',
          'amount': 1000,
          'date': '2026-07-02',
        },
        {
          'type': 'expense',
          'label': 'Food',
          'amount': 3000,
          'date': '2026-07-03',
        },
      ],
    }, now),
    'texts': {
      'main': recapText(mainRecap, formatMoneyText),
      'mainHidden': recapText(mainRecap, formatMoneyText, true),
      'empty': recapText(monthRecap(const {}, now), formatMoneyText),
    },
  };

  for (final s in (raw['schedules'] as List).cast<Map<String, dynamic>>()) {
    s['days'] = daysUntilPayday(now, s['schedule']);
    s['label'] = scheduleLabel(s['schedule']);
  }
  _save(path, raw);
  stdout.writeln('pan_goldens.json regenerated');
}

void regenLessons() {
  const path = 'test/goldens/lessons_goldens.json';
  final raw = _load(path);
  raw['lessons'] = lessons;
  for (final c in (raw['ofDay'] as List).cast<Map<String, dynamic>>()) {
    final p = (c['date'] as String).split('-').map(int.parse).toList();
    c['id'] = lessonOfTheDay(DateTime(p[0], p[1], p[2], 12))['id'];
  }
  _save(path, raw);
  stdout.writeln('lessons_goldens.json regenerated');
}

void main() {
  regenCoach();
  regenPan();
  regenLessons();
}
