#!/usr/bin/env python3
"""Turns the extracted Academy JSON into Dart.

    bun app/tool/extract_academy.ts > academy.json
    python3 app/tool/gen_academy_dart.py academy.json > app/lib/data/academy_data.dart

Generated rather than written, for the same reason the fast-log keyword map
was: 32 courses with 96 lesson sections is a list with a typo in it if a
person copies it by hand.

The lucide icon names become Salapify icon NAMES. Content declares the
meaning and one file decides how it is drawn, so restyling every icon is one
edit and the user's own emoji are never touched.
"""
import json
import sys

# lucide name -> the meaning Salapify's resolver understands. Mapped once,
# here, so a course file never names a Material glyph directly.
ICONS = {
    'AlertTriangle': 'warning',
    'ArrowLeftRight': 'transfer',
    'Award': 'award',
    'BrainCircuit': 'mind',
    'Building2': 'building',
    'CalendarClock': 'calendar',
    'CreditCard': 'card',
    'FileText': 'document',
    'HandHeart': 'handshake',
    'HeartPulse': 'health',
    'Landmark': 'bank',
    'Laptop': 'laptop',
    'LineChart': 'chart',
    'Package': 'package',
    'Palmtree': 'palm',
    'PiggyBank': 'savings',
    'Send': 'send',
    'Share2': 'share',
    'ShieldAlert': 'shieldAlert',
    'ShieldCheck': 'shield',
    'ShoppingBag': 'shopping',
    'Sliders': 'sliders',
    'Smartphone': 'phone',
    'Sparkles': 'sparkle',
    'Target': 'target',
    'TrendingDown': 'trendingDown',
    'Users': 'people',
    'Zap': 'bolt',
}


def dart_string(s):
    """A Dart single-quoted string literal.

    The prototype's prose uses apostrophes and the odd double hyphen, so the
    escaping is done rather than assumed. Newlines are escaped rather than
    left raw, because a raw newline inside a single-quoted Dart string does
    not compile.
    """
    s = s.replace('\\', '\\\\')
    s = s.replace("'", "\\'")
    s = s.replace('$', '\\$')
    s = s.replace('\n', '\\n')
    s = s.replace('\r', '')
    return "'" + s + "'"


def emit_list(items, indent):
    pad = ' ' * indent
    if not items:
        return '<String>[]'
    out = ['<String>[']
    for i in items:
        out.append(f'{pad}  {dart_string(i)},')
    out.append(pad + ']')
    return '\n'.join(out)


def main():
    courses = json.load(open(sys.argv[1]))

    print('// GENERATED by app/tool/gen_academy_dart.py from')
    print('// src/data/academyData.ts. Do not edit by hand: regenerate.')
    print('//')
    print('//   bun app/tool/extract_academy.ts > academy.json')
    print('//   python3 app/tool/gen_academy_dart.py academy.json \\')
    print('//     > app/lib/data/academy_data.dart')
    print('//')
    print('// The curriculum is the prototype\'s, word for word. It was')
    print('// extracted rather than retyped because 32 courses with 96 lesson')
    print('// sections is a list with a typo in it if a person copies it.')
    print()
    print("import '../models/academy.dart';")
    print()
    print('/// The Salapify Academy curriculum: '
          f'{len(courses)} courses, '
          f'{sum(len(c["sections"]) for c in courses)} lesson sections.')
    print('const List<CourseModule> academyCourses = <CourseModule>[')

    for c in courses:
        print('  CourseModule(')
        print(f'    id: {dart_string(c["id"])},')
        print(f'    title: {dart_string(c["title"])},')
        print(f'    category: {dart_string(c["category"])},')
        icon = ICONS.get(c['iconName'])
        if icon is None:
            sys.exit(f'unmapped icon: {c["iconName"]}')
        print(f"    icon: '{icon}',")
        print(f'    description: {dart_string(c["description"])},')
        print(f'    durationMinutes: {c["durationMinutes"]},')
        print(f'    objectives: {emit_list(c.get("objectives", []), 4)},')

        print('    sections: <LessonSection>[')
        for s in c['sections']:
            print('      LessonSection(')
            print(f'        id: {dart_string(s["id"])},')
            print(f'        title: {dart_string(s["title"])},')
            print(f'        content: {dart_string(s["content"])},')
            print('      ),')
        print('    ],')

        kc = c.get('knowledgeCheck')
        if kc:
            print('    knowledgeCheck: KnowledgeCheck(')
            print(f'      question: {dart_string(kc["question"])},')
            print(f'      options: {emit_list(kc["options"], 6)},')
            print(f'      correctAnswerIndex: {kc["correctAnswerIndex"]},')
            print(f'      explanation: {dart_string(kc["explanation"])},')
            print('    ),')

        rp = c.get('reflectionPrompt')
        if rp:
            print(f'    reflectionPrompt: {dart_string(rp)},')

        print(f'    keyTakeaways: {emit_list(c.get("keyTakeaways", []), 4)},')
        print('  ),')

    print('];')


if __name__ == '__main__':
    main()
